### ISSUE TITLE
Underline still showing for footnote links, even with underline link options turned off

### ISSUE THREAD

**Issue by blackace72** [kepano/obsidian-minimal#100]
Apologies if this has been posted somewhere before.

I am still seeing an underline for links in footnotes even though I have both options "Underline internal links" and "Underline external links" turned OFF (using Style Settings plugin). Here is the example.
![image](https://user-images.githubusercontent.com/93956043/148339038-b1e40ade-7259-430e-a6d0-2d085e0e9a21.png)

Underlying markdown text: 
![image](https://user-images.githubusercontent.com/93956043/148339207-7b47e2fd-7042-4b12-961e-498084ff45f4.png)

If I am missing something/not understanding something, please let me know. Thank you.

**Comment by blackace72** [comment]
Update: It seems that the lines have disappeared after restarting Obsidian. If I figure out a way to reproduce it I'll let either you or the other (dev, plugin dev, etc.) know.

**Comment by kepano** [comment]
Ok reopen if you learn anything new.
