### ISSUE TITLE
Left/Right Pane width User selection option?

### ISSUE THREAD

**Issue by davebhc71** [kepano/obsidian-minimal#101]
I have failed to find a UI feature in the Theme (or accompanying plugins) to select/change the width of **pinned** side Panes (including the Left Pane) when using an iPad. There is so little screen real estate available when all three are active that I would like to recommend a UI FR to accomplish smaller ‘side’ Panes. Thanks for your consideration in advance. (p.s, using CSS snippets, etc., is above by pay grade, that’s why the request)

Also, I’m very aware (and sympathetic to feature bloat) from the point of view of this Community Forum thread - https://forum.obsidian.md/t/css-magicians-theme-creators-standardisation-of-theming-practices/29937?u=daveb08

**Comment by kepano** [comment]
This is now available in the latest update under Style Settings > Minimal Advanced Settings

**Comment by davebhc71** [comment]
FYI……….AMAZING……just what I needed and expected. Adds more functionality to Mobile. Much appreciated.
