### ISSUE TITLE
4.4 Cards layout - multiple columns and gray box

### ISSUE THREAD

**Issue by javiavid** [kepano/obsidian-minimal#102]
I'm trying to get the same layout as in the youtube demo of version 4.4.
The problem is that I can't get several columns and the grey background text box (card?) like in the video.

(Although they have the same image, they are 4 duplicate notes changing the name for testing purposes)

![image](https://user-images.githubusercontent.com/7627504/148518387-00be6d51-3016-40f8-b703-addf169451f9.png)

![image](https://user-images.githubusercontent.com/7627504/148518553-26d81086-3218-41ee-9cce-0f70dd5e1343.png)

**Comment by kepano** [comment]
You can change backgrounds and borders in Style Settings. Make sure you are using the latest version of the snippet.
