### ISSUE TITLE
4.4 Cards layout - Poster link for local stored Pictures

### ISSUE THREAD

**Issue by rolikeusch** [kepano/obsidian-minimal#104]
is there are reason that i can only use external links for poster pictures? or do i something wrong?

this cover link show a picture in dataview:
```
Poster:: ![poster](https://www.galaxus.ch/im/Files/1/7/8/8/2/4/2/2/Lagavulin-Whisky-16Y-07l-H-002.xxl3.jpg)
```

if i use this link from a local stored picture, no picture is shown in dataview:
```
Poster:: ![poster](Whiskey-Lagavulin.jpeg)
```

**Comment by kepano** [comment]
This is a known Dataview issue:
https://github.com/blacksmithgu/obsidian-dataview/issues/58
https://github.com/blacksmithgu/obsidian-dataview/issues/517

**Comment by rolikeusch** [comment]
oh i see, thanks for the info.

btw. cards are just great!!

**Comment by CreepyBasti** [comment]
I see this is already closed but as I already commented on https://github.com/blacksmithgu/obsidian-dataview/issues/58 , Ive found a simple solution to this. Just put:
```
---
Cover: "![[YourImageName.png]]"
---
```
and table for Cover in DataView
