### ISSUE TITLE
Other dataview card types?

### ISSUE THREAD

**Issue by blackpeasy** [kepano/obsidian-minimal#106]
Dear Kepano, love your theme!

Now that you have introduced the dataview cards feature, would you consider adding different types of cards?

I have been wanting to do something like [this](https://github.com/kaelri/obsidian-test-vault) for a while, but having no programming skills, the knowledge needed to set it up is beyond me. 

It would be awesome to be able to choose 'project-type' cards with a simple CSS style.

**Comment by kepano** [comment]
The repo you linked to has a detailed guide on how to achieve what you are trying to accomplish:

https://publish.obsidian.md/hub/03+-+Showcases+%26+Templates/Templates/Plugin-specific+templates/Dataview+templates/Project+Cards

**Comment by blackpeasy** [comment]
Indeed. It is a bit daunting for the casual user though. 
Consider it a general feature request, as I see a lot of value in functional dataview styles.

**Comment by kepano** [comment]
The way cards are set up in Minimal is very flexible, you can put anything that Dataview can display inside of a card. It's designed to be a container for any kind of content.

From the guide you linked above, the main difference I see is being able to only show 1 full-width card at a time. Would that address your need?

**Comment by blackpeasy** [comment]
Yes, that would definitely help.

**Comment by kepano** [comment]
If you download the latest update you can use the `cards-cols-1` helper class to do this

**Comment by blackpeasy** [comment]
Great, thanks for helping out!
