### ISSUE TITLE
Mermaid Diagram: Arrows don't show in Reader-Mode

### ISSUE THREAD

**Issue by SamAdams51** [kepano/obsidian-minimal#107]
Hi @kepano,

I just recognised, that the arrows of connection lines in my mermaid diagram are not displayed in reader mode, in live preview mode everything is fine. Here is my mermaid code block:

![Bildschirmfoto 2022-01-10 um 15 08 20](https://user-images.githubusercontent.com/42751459/148779402-3f891ab7-626f-4f5c-887b-437bd2bf426f.png)

And a screenshot showing the diagram both in **live preview mode:**

![Bildschirmfoto 2022-01-10 um 15 04 27](https://user-images.githubusercontent.com/42751459/148778865-88a010d6-2ee6-44fc-9afd-1052106bf554.png)

and in **reader mode:**

![Bildschirmfoto 2022-01-10 um 15 05 56](https://user-images.githubusercontent.com/42751459/148779055-df5295c4-17a9-4ddf-a0f5-19988e08bd89.png)

**Comment by SamAdams51** [comment]
Hi Stephan,
I'll check it out tomorrow. At the moment I have just access to my iPad, not to my desktop computer. On iPad (Obsidian Mobile Vers. 1.05) everything is ok.

**Comment by kepano** [comment]
Minimal doesn't have any styles that affect Mermaid diagram so I believe this is an Obsidian issue. You'll need to ask in the forum or Discord for help from the Obsidian team.

Reopen if you discover anything related to Minimal. Thanks!
