### ISSUE TITLE
Mobile Version 1.05 on iPad: Hamburger menu missing in local graph pane.

### ISSUE THREAD

**Issue by SamAdams51** [kepano/obsidian-minimal#109]
If I open the local graph of a note in a new pane via the hamburger menu of the note, the local graph pane has no hamburger menu making it impossible to close the local graph pane. The default theme and all other themes I tried show the hamburger menu in the local graph pane.

Screenshot of Minimal Theme:

![Bildschirmfoto 2022-01-10 um 22 46 00](https://user-images.githubusercontent.com/42751459/148844934-bd975c36-a98e-4209-a6c2-1335eaa17b13.png)

Screenshot Default Theme:

![Default Theme](https://user-images.githubusercontent.com/42751459/148845140-dcfca928-1402-4d0d-8eac-1baff0ead997.png)

**Comment by kepano** [comment]
This is now fixed as of the latest commit. Update the theme to get the latest. Thanks!

**Comment by SamAdams51** [comment]
Thanks for the quick fix.
