### ISSUE TITLE
img-grid not working

### ISSUE THREAD

**Issue by edmondlau** [kepano/obsidian-minimal#110]
I'm having trouble getting the img-grid layout working to show my images side-by-side. I'm on the live preview editor, have contextual typography installed, toggled the ing-grid option, even added the css classes to the top of the file, but my images are not rendering in a gallery. Ideas?

```
---
cssClasses: img-grid
---

![[pawel-czerwinski-vYnjAMo8DY8-unsplash.jpg]]
![[photo-1641810780723-8bc471f87245.jpeg]]

```
<img width="737" alt="image" src="https://user-images.githubusercontent.com/107530/148847019-7ab4f68c-aa82-47f0-b710-9f7e6d123d85.png">
<img width="728" alt="image" src="https://user-images.githubusercontent.com/107530/148846908-0cd8b93b-581f-48af-adfb-ec638ce42ac1.png">
<img width="734" alt="image" src="https://user-images.githubusercontent.com/107530/148846954-1dade917-a423-41b3-989b-31f323a67d9f.png">

**Comment by kepano** [comment]
Live Preview does not support CSS classes yet. This is a known Obsidian issue:

https://forum.obsidian.md/t/apply-yaml-cssclass-to-edit-mode/10234/6

**Comment by edmondlau** [comment]
@kepano Thanks, that makes sense. Is it expected behavior that if I have LP enabled, but I switch to reading / view mode, that the image grid still wouldn't work?

**Comment by edmondlau** [comment]
Hmm... There's still something not working then. Because my images just render in a single column, even in reading view.

<img width="681" alt="image" src="https://user-images.githubusercontent.com/107530/149402883-cee1b222-3d43-4186-8656-98d31d6f4d80.png">

<img width="743" alt="image" src="https://user-images.githubusercontent.com/107530/149402922-1ed5d89d-ec1f-461f-90eb-e3876a38453f.png">

<img width="727" alt="image" src="https://user-images.githubusercontent.com/107530/149402959-99e62ea2-2659-4a55-8d29-5cfbf1679fa3.png">

<img width="725" alt="image" src="https://user-images.githubusercontent.com/107530/149402992-ba685f32-fa7b-4400-95eb-5900e41a7042.png">

<img width="741" alt="image" src="https://user-images.githubusercontent.com/107530/149403020-9e87bac7-f5ba-49e4-ab06-81106b88f280.png">

**Comment by kepano** [comment]
I am not able to reproduce this.  Can you try quitting and restarting Obsidian?

The correct syntax is as follows, make sure there is no extra line break between images
```
![[image1.png]]
![[image2.png]]
```

If you are still having trouble try in a new test vault with just Minimal Theme + Minimal Theme Settings + Contextual Typography. You may have some other conflict with a plugin or snippet.

**Comment by edmondlau** [comment]
Possibly the issue was that I wasn't on the newest version of the theme. After I hit update on the theme, the img-grid works now.

Thanks for all the help — it would be helpful actually if the plugin could detect if I'm using an out-of-date theme version and show me a prompt to update it.
