### ISSUE TITLE
Inline math blocks are cut off in Live Preview

### ISSUE THREAD

**Issue by astutecat** [kepano/obsidian-minimal#112]
Hi,

First let me say thank you for this theme, it's great :)

I've noticed that in Live Preview mode inline math blocks (e.g. `$O(\log n)$` seem to be getting cut off:

LP:
![grafik](https://user-images.githubusercontent.com/2563682/148910736-97d7276f-6362-411a-b755-1cd314bf6498.png)

Read View:
![grafik](https://user-images.githubusercontent.com/2563682/148910838-0256f6f0-0505-4a36-b376-b691f888fdeb.png)

Obsidian v0.13.19
Theme version 4.4.0

Any ideas on what could be causing this?

**Comment by kepano** [comment]
I am not able to reproduce this. Are you using any other plugins or snippets?

**Comment by astutecat** [comment]
hmm, I did notice that it was most obvious when you use `\large` or `\LARGE`, e.g:

`$\LARGE O(\log n)$ bla bla bla`

**Comment by kepano** [comment]
I am trying it out with your syntax but not seeing the issue, even when `\large` is used.

**Comment by astutecat** [comment]
Well, this is embarrasing ... not sure what caused it but it seems to not be happening now. Sorry for bothering you!

**Comment by kepano** [comment]
No worries!

**Comment by astutecat** [comment]
Just a quick note - it appears that the `contextual typography` plugin was the culprit. Disabling that caused the issue to disappear :)

**Comment by kepano** [comment]
I am running Contextual Typography and not seeing this issue
