### ISSUE TITLE
First three icons in mobile toolbar are unresponsive

### ISSUE THREAD

**Issue by chrisberry-io** [kepano/obsidian-minimal#113]
For example, in the screen below, "add internal link", "toggle heading", and "toggle bold" don't respond to taps. If any of the options are moved into the fourth position (where "indent list item" is) it will function properly.

The device this has been tested on is a OnePlus 7 pro running Android 11. Obsidian, theme, and minimal theme settings plugin are up-to-date.

![Screenshot_20220111-093514.jpg](https://user-images.githubusercontent.com/1624489/148962741-16a980b9-78e5-431b-a7c2-7afb7168bd74.jpg)

**Comment by kepano** [comment]
I am not able to reproduce this on iOS. I don't have an Android phone unfortunately. 

Is this happening with the default theme?

**Comment by lishid** [comment]
I just tested on Obsidian Android v1.1.0 (With Android 11) and it works fine under the latest theme. Perhaps it's related to the mobile update that's currently under insider testing. It should be released for public use soon.

**Comment by chrisberry-io** [comment]
My mistake. It looks like I might have been on an old insiders build. Uninstalling and reinstalling the Play Store version seems to have resolved the issue.

Thank you for looking into this.
