### ISSUE TITLE
UI request for customizable side panel in iPad mobile 

### ISSUE THREAD

**Issue by davebhc71** [kepano/obsidian-minimal#115]
Because screen real estate is at a premium in Obsidian Mobile, could there be a setting(s) to shrink the size of the two (left & right) side panes.
![IMG_0502](https://user-images.githubusercontent.com/80698092/149056070-6ae21dca-2975-4de0-9e86-0d442115e1f8.jpeg)

**Comment by kepano** [comment]
This is a duplicate of #101 — will investigate
