### ISSUE TITLE
More options to make view header (note title) visible when in focus mode

### ISSUE THREAD

**Issue by frankreporting** [kepano/obsidian-minimal#117]
**Is your feature request related to a problem? Please describe.**
Currently while in focus mode, you have to hover specifically over the view header area to see the note title, even if it's focused. For example, if you use the command to edit the note title, the cursor may actually be in the note title area ready for editing, but you can't see it unless you move your mouse to reveal it or else leave focus mode.

**Describe the solution you'd like**
Would it be possible to add a couple other triggers to temporarily make the view header visible without leaving focus mode?
- When note title has focus, whether you clicked it or used the Obsidian command
- When scrolling up with trackpad or mouse. This would be similar to how an app like Safari works on iOS — when you scroll down, it goes full screen, and when you scroll up, the address bar reappears.

**Comment by kepano** [comment]
Have you considered binding the focus mode toggle to a hotkey in Minimal Theme Settings?

**Comment by frankreporting** [comment]
Good point. I guess I was going for a solution with fewest key strokes/no context switching. But that's just me being super picky. I can totally live with that :)

**Comment by kepano** [comment]
You can now do this with Embedded Note Title plugin

**Comment by frankreporting** [comment]
Fwiw I noticed in a recent update it started working! Not sure if you did this or if it was a change in Obsidian, but when you hit the keyboard shortcut to edit the note title, now even if the title is hidden because you're in focus mode, it reappears and takes focus immediately. Works like a charm!
