### ISSUE TITLE
Timeline CSS class with Dataview

### ISSUE THREAD

**Issue by blackpeasy** [kepano/obsidian-minimal#118]
I know this is a biggie, so feel free to dismiss it outright if you want to.

The current timeline plugins are very cumbersome to work with, they don't scale very well and they require a lot of manual work to set up.
As you have already made the cards CSS class for Dataview, I want to suggest a feature: Timeline CSS class.

Presenting data from a dataview query in a simple (horizontal or vertical) timeline with proper scaling between values.
That would be worth quite a few cups of coffee...

**Comment by kepano** [comment]
Can you share any screenshots of what the output might look like? (Doesn’t have to be from Obsidian plugins)

**Comment by blackpeasy** [comment]
I can make a few mockups - will return in a day or two.

**Comment by blackpeasy** [comment]
Here's my idea for a mockup, re-using your dataview cards as timeline entries.

I guess the timeline would require a specific numeric field type. 
Perhaps the first field in the query will define the x-axis position on the timeline? 

```dataview
table without id
timeline, file.link as Mezcal, style as "Agave", mezcalero as Mezcalero, ratingRb as "Rating"
from #mezcal and #reviews
where !contains(file.name, "Template)
```

With inline queries like this: 
- In the "Felix Angeles..."-note ```timeline:: 2001```
- In the "Rey Campero..."-note ```timeline:: 2011```
- In the "El Mero..."-note ```timeline:: 2013```
- In the "Maguey Melate..."-note ```timeline::: 2021```

![Minimal timeline mockup](https://user-images.githubusercontent.com/92858268/149507333-2cb6b040-5d2e-4cb8-ad06-a29d9001dc96.jpg)

**Comment by blackpeasy** [comment]
I see. Thank you for considering it anyway.

**Comment by kepano** [comment]
Good luck! I hope someone picks it up as a plugin project. It would be a cool feature 😊

**Comment by blackpeasy** [comment]
Yeah, I think it's a tough sell though. Two timeline plugins already exist. 
However, one of them doesn't have scaling and the other is extremely cumbersome to work with.
