### ISSUE TITLE
Accent Color could be used in more places

### ISSUE THREAD

**Issue by rodrigo-rufino** [kepano/obsidian-minimal#119]
One small suggestion I have is to use the Accent Color in more components in Obsidian (like the side buttons hover, for example).

If not possible (or if it doesn't make sense for any reason) no problem... the theme is great how it is!

Example:
![Captura de Tela 2022-01-13 às 16 53 50](https://user-images.githubusercontent.com/18670446/149399825-85ae3829-e424-4dd8-91b8-aca91d7319d0.png)

**Comment by kepano** [comment]
This is now available using Style Settings
