### ISSUE TITLE
Console error 

### ISSUE THREAD

**Issue by mnvwvnm** [kepano/obsidian-minimal#12]
Hi,
I found this error on dev console:

<img width="501" alt="image" src="https://user-images.githubusercontent.com/22862501/122991622-26403380-d39d-11eb-80c2-b58a4f2c2f4b.png">

Any idea?

Thanks

**Comment by frankreporting** [comment]
I get this too. I'm on a 2019 16-inch Macbook Pro running Big Sur, if that helps.

**Comment by kepano** [comment]
This should be fixed as of 3.0
