### ISSUE TITLE
Place the body of the texts a little lower when toggling focus mode

### ISSUE THREAD

**Issue by u2003** [kepano/obsidian-minimal#120]
Dear developer, thank you for creating such great theme! I love the focus mode and the immersing experience when toggling it. Yet there is a little problem sometimes, when I try to click on the first line of the texts, this will bring the page header to the front more often. Also, when I zoom in a bullet list, it's really difficult to click on the navigation bar on the top, every time this action will toggle the page header instead. So I wonder if you could please consider placing the body of the contents a little lower to avoid contradiction. It would be so great if you could take my advice into account~
![CleanShot 2022-01-14 at 12 40 54](https://user-images.githubusercontent.com/84957135/149452717-7f2dfa02-06c0-4504-bd8f-87d8dc751665.gif)
![CleanShot 2022-01-14 at 12 41 34](https://user-images.githubusercontent.com/84957135/149452721-f287e9e8-e970-414a-87e7-f922b271c6d6.gif)

**Comment by kepano** [comment]
This should be fixed now
