### ISSUE TITLE
Table size in Reading mode

### ISSUE THREAD

**Issue by davebhc71** [kepano/obsidian-minimal#121]
I’m not sure this is a bug, but I can not get the table I’ve created to appear in Minimal in the same proportion as the normal Obsidian Theme. I’ve tried making changes to the settings UI for tables.

![IMG_0507](https://user-images.githubusercontent.com/80698092/149601964-96a655b8-8245-4ac4-9aa9-b0c51a53c24a.jpeg)

![IMG_0506](https://user-images.githubusercontent.com/80698092/149601975-5aa03630-6598-489f-ada3-d678858f9006.jpeg)

**Comment by kepano** [comment]
This is the default styling for tables in Minimal, they always appear full width

i can look into adding a CSS class to override

**Comment by davebhc71** [comment]
One more Toggle 😉

**Comment by tmllull** [comment]
Hi. I'm not sure if this is exactly the same question, but it's related to the "Table size in Reading mode". I've a doubt about width  on "standard" tables (compared to dataview tables). On edit mode (with live preview), both use the entire "text space", as You see below (first table is dataview, second is default table).

![image](https://user-images.githubusercontent.com/5560652/179916148-4031d591-02d8-4f23-bd0f-954cfc22f1d1.png)

But when You switch to preview mode, default tables not use this space:

![image](https://user-images.githubusercontent.com/5560652/179916323-3db542a6-6cbb-44f1-80ac-bcc5bd302390.png)

I checked the tables options, but changing the default width only apply to edit mode, and the width is too large ("overflow" the text)

![image](https://user-images.githubusercontent.com/5560652/179916967-8b71c13e-1e29-490f-b1b2-92ab849f723e.png)

Is there any option to force that default tables works as dataview tables and full the entire "text space"?

Thanks a lot for your works and congratulations for the theme!

Best regards.

**Comment by kepano** [comment]
This was fixed in 6.0 you can use Style Settings > Table > Maximize table width
