### ISSUE TITLE
Uniform font size for plugins using right side Pane?

### ISSUE THREAD

**Issue by davebhc71** [kepano/obsidian-minimal#122]
**Describe the solution you'd like**-

On my iPad, I have four plugins that can occupy the Right Side Pane when Pined (obviously one at a time😉). Three (3) of them honor the UI size I have chosen in Minimal’s Settings. The 4th does not! Is there a way that Minimal can control this ‘outlaw’. It would seem more advantageous to me as the ‘end’ user, if Obsidian, CodeMirror or whatever would give the Theme developer jurisdiction over these things and NOT the plugin Dev.

**Comment by kepano** [comment]
Which plugin? Likely the plugin is adding its own styles that are overriding Obsidian’s default font size.

**Comment by davebhc71** [comment]
Obsidian TODO-
https://github.com/larslockefeer/obsidian-plugin-todo
