### ISSUE TITLE
Relationship lines do not show in Editor Mode

### ISSUE THREAD

**Issue by austingovella** [kepano/obsidian-minimal#123]
### Before you open a bug report

- [x] Disable plugins and snippets that could be causing a conflict. Update to the latest versions of the following, and restart Obsidian
- [x] Minimal Theme
- [x] Minimal Theme Settings plugin (or Style Settings plugin, but not both)
- [x] Contextual Typography plugin

### Describe the bug

Relationship lines do not appear in edit mode (Live Preview or Source Mode).

(They showed in the past. I turned them off for a while. Not sure when they stopped showing for me. I installed Minimal and  Minimal Theme Settings on the Help Vault and got the same behavior.)

### To reproduce

1. In Minimal Theme Settings
2. Turn on Relationship Lines in Editor
3. View list
4. See no relationship lines

### Screenshots

Editor mode doesn't show relationship lines
<img width="377" alt="image" src="https://user-images.githubusercontent.com/539473/149688380-6bf24e9c-6044-48a9-b8ba-1d5e6a9bdd70.png">

Preview mode does show
<img width="267" alt="image" src="https://user-images.githubusercontent.com/539473/149688401-1ffba0a4-2d0c-4f47-9267-0cf5090740be.png">

### Debug info (please complete the following information):

SYSTEM INFO:
	Obsidian version: v0.13.19
	Installer version: v0.12.19
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 12
	Plugins enabled: 8
		1: Sliding Panes (Andy's Mode)
		2: Periodic Notes
		3: Calendar
		4: Readwise Official
		5: Tasks
		6: Minimal Theme Settings
		7: QuickAdd
		8: Hider

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please try to make the issue happen in the help vault or disable community plugins.

**Comment by kepano** [comment]
Relationship lines are being removed from Minimal starting in 4.4.1

Please use Indentation Guides plugin instead.

https://github.com/kepano/obsidian-minimal/releases/tag/4.4.1

**Comment by davebhc71** [comment]
Indentation Guides plugin doesn’t work for Mobile.
