### ISSUE TITLE
No selection highlight for inline code block

### ISSUE THREAD

**Issue by Sinled** [kepano/obsidian-minimal#124]
**Describe the bug**
Selection is not visible inside inline code blocks in edit mode

**To reproduce**
1. Create inline code block with single `
2. Try to select text inside

**Expected behavior**
Selection should be visible

As i understand the problem is here
https://github.com/kepano/obsidian-minimal/tree/master/src/scss/obsidian/editor.scss#L103
i could make a pr, but i am not sure why this code is there

**Comment by kepano** [comment]
This is fixed in the latest commit
