### ISSUE TITLE
Add a little ‘padding’ to bottom of left Sidebar on Mobile

### ISSUE THREAD

**Issue by davebhc71** [kepano/obsidian-minimal#125]
**Is your feature request related to a problem? Please describe.**
As the title says, on iPad Mobile, the Sidebar lower Settings icon is difficult to access when cursor is in Note pane. 

**Describe the solution you'd like**
Can the Theme contain a little more space ‘padding’ between the gif and the Mobile bar. (see png)
![IMG_0513](https://user-images.githubusercontent.com/80698092/149839248-d91c0681-fe04-4067-b6fa-1f08de080b24.jpeg)

**Comment by kepano** [comment]
I am not able to reproduce this scenario on my iPad. 

Somehow it looks like the toolbar is clipping the sidebar. I am pushing a change in 4.4.6 that will change the z-index of the sidebar but I am not sure if that will fix this for you.

**Comment by davebhc71** [comment]
Seeing the same issue with v4.4.7

**Comment by kepano** [comment]
I am not able to reproduce the issue :/

I wonder if it is due to a plugin? Have you tried in a new vault?

**Comment by davebhc71** [comment]
With v5, item is NOT an issue when Sidebar is pinned. I’m satisfied. Thanks (especially if it was because of the updates 😉).

**Comment by kepano** [comment]
Nothing changed in the Minimal code. Please reopen if you discover something else. Cheers!
