### ISSUE TITLE
Not working link at 4.3.0 release description

### ISSUE THREAD

**Issue by slvt** [kepano/obsidian-minimal#128]
Not working link at 4.3.0 release description
https://github.com/kepano/obsidian-minimal/blob/master/snippets/nav-labels.css

**Comment by kepano** [comment]
Fixed, thanks

**Comment by slvt** [comment]
Sorry, but the link still doesn't work

> The label text can be edited using [this snippet](https://github.com/kepano/obsidian-minimal/blob/master/snippets/nav-labels.css) for other languages/preferences

**Comment by kepano** [comment]
Got it, I missed that one. Fixed, thanks.

It points to the /translations folder

https://github.com/kepano/obsidian-minimal/blob/master/translations/nav-labels.css
