### ISSUE TITLE
Distorted Emoji in Minimal Theme

### ISSUE THREAD

**Issue by skeskali** [kepano/obsidian-minimal#13]
This is something that recently popped up after I added the Advanced Appearance plugin. I have since removed this plugin, but this behaviour persists. 

Whenever I use emoji in Obsidian with the Minimal theme, my emoji are distorted. 
![CleanShot 2021-06-24 at 22 55 27](https://user-images.githubusercontent.com/2754684/123380470-56760680-d544-11eb-8899-da9bd402a70c.jpeg)

**Comment by kepano** [comment]
I believe this has already been reported as an issue with the emoji plugin — I am assuming that's what you're using?

**Comment by skeskali** [comment]
> I believe this has already been reported as an issue with the emoji plugin — I am assuming that's what you're using?

Nope, I wasn't using the emoji plugin, but I tried it again with the plugin, and I'm having the same problem.

**Comment by cashew90** [comment]
I can confirm that it happens with and without the emoji plugin, albeit differently. If the plugin is activated, emojis are distorted like shown in the first post. If it is deactivated, emojis get humungously large.

**Comment by kepano** [comment]
I am not able to reproduce this bug on Mac or iOS. 

Can you try adding this CSS snippet?
```
.markdown-preview-view .image-embed img:not([width]) {
  width:auto;
}
```
I am wondering if emoji are treated as image embeds for some reason.

**Comment by cashew90** [comment]
Somehow, it's not happening anymore. So whatever caused this is fixed.

**Comment by serpro69** [comment]
Hi @kepano ,
Is it OK to reopen this? I have exactly same issue.

Edit mode:
![image](https://user-images.githubusercontent.com/22973227/147691113-b459eef3-0c2a-41e1-99b7-224d49cec147.png)

Preview mode:
![image](https://user-images.githubusercontent.com/22973227/147691126-2a2718fd-0cb8-4cf5-8d71-2f5749f42675.png)

I tried adding the snippet you pasted above, but that doesn't help.

Anyone been able to find a fix for this?
