### ISSUE TITLE
Wrong Icons when using a language other than English

### ISSUE THREAD

**Issue by DasCapschen** [kepano/obsidian-minimal#130]
**Describe the bug**
When using a language other than English, some Icons are not correctly displayed, because the CSS selectors select on label names, which change with language. This might affect things other than icons, too.

**To reproduce**
1. Activate Minimal Theme
2. Observe the File Explorer icon being a House
3. Change language to German (or some other language)
4. Observe the File Explorer icon being a Folder

**Expected behavior**
Icons shouldn't change with language.

**Screenshots**
![css_1](https://user-images.githubusercontent.com/3923406/150114981-01591ebd-8b98-47c2-8ea8-04dc23b0fdcd.png)
![css_2](https://user-images.githubusercontent.com/3923406/150114994-6a859a2f-95a2-4b4a-9498-9724ee587938.png)

**Comment by kepano** [comment]
Unfortunately there is no cross-language way to target some of the icons. I would recommend opening an issue in the Obsidian forums.

You can read more about contributing a translation here:
https://github.com/kepano/obsidian-minimal/releases/tag/4.3.0

**Comment by DasCapschen** [comment]
Has this been fixed?
I just noticed I now have the correct icons show up, and they don't change with language anymore (0.13.22) 🙂 

![grafik](https://user-images.githubusercontent.com/3923406/151456790-a1121092-8945-4bb3-84b3-3745d9c9d9e9.png)

**Comment by kepano** [comment]
Yes this is fixed as of Obsidian 0.13.22 😊
