### ISSUE TITLE
Force helper class ```cards-cols-value``` to reduce card size

### ISSUE THREAD

**Issue by blackpeasy** [kepano/obsidian-minimal#131]
When I use the css helper class ```cards-cols-1``` it works as expected, reducing the number of columns to 1.

However, when entering a value larger than the number of cards in the table, it does nothing.
In tables with 2-6 cards the cards are huge. 

I would love to be able to use e.g. ```cards-cols-8``` in a table with 3 cards to reduce the size of the cards.
I don't mind that they won't fill the whole page-width. They could just be left-aligned.

**Comment by kepano** [comment]
Can you share screenshots?

Have you tried changing the card width in Style Settings?

**Comment by kepano** [comment]
The variables can be found here:
https://github.com/kepano/obsidian-minimal/blob/master/src/scss/features/cards.scss#L5-L13

You should be able to accomplish what you're trying to do just by using the `cards` class alone and setting the `--cards-min-width`

**Comment by blackpeasy** [comment]
With `--cards-min-width:40px;`
It seems like everything above `cards-cols-3` gives me as many columns as can fit within the frame.

`cards-cols-3`
![image](https://user-images.githubusercontent.com/92858268/150382942-c3598875-0677-4636-9c08-5b49da4a57e4.png)

`cards-cols-4`
![image](https://user-images.githubusercontent.com/92858268/150383435-03e0e96a-0ceb-4ce6-b716-c4bceef16246.png)

`cards-cols-5`
![image](https://user-images.githubusercontent.com/92858268/150383731-c0ae3f60-ccf8-41a2-b5b1-163813a940b0.png)

etc...

**Comment by kepano** [comment]
In the latest commit you can also define the max-width of cards globally by using this snippet

```
body {
  --cards-max-width:200px;
}
```

**Comment by blackpeasy** [comment]
Awesome, thanks! Looks much cleaner now :)
