### ISSUE TITLE
Ability to choose dark mode style per device

### ISSUE THREAD

**Issue by owenfiscus** [kepano/obsidian-minimal#132]
I'm not sure if it's possible but I would love the ability to choose a dark mode style based on the device. For example, the _true black_ style would be great to use on my iPhone but I would prefer to use the _default_ style on my MacBook.

**Comment by kepano** [comment]
Yes it's possible, but depends on the sync solution you use. This is not really a Minimal-related thing, though.

If you use Obsidian Sync you can simply turn off syncing plugin settings. If you use another sync solution there are other options for defining preferences in mobile vs desktop that you can find the Obsidian forums.

**Comment by owenfiscus** [comment]
Thanks for the guidance, I'll look into it some more.
