### ISSUE TITLE
fail to click on the top bar of some plugins when toggling Focus Mode

### ISSUE THREAD

**Issue by u2003** [kepano/obsidian-minimal#133]
I reported an issue likewise last time, in which I advised to put the body of the texts lower. After upgrading, I find that it's ok with texts now, yet the page header in focus mode still contradicts the top bar of some other plugins, such as Zoom, Breadcrumbs, etc. 

https://user-images.githubusercontent.com/84957135/150499751-5a73cb69-c6d5-4241-b445-a58cde97b065.mp4

https://user-images.githubusercontent.com/84957135/150500298-bfa0ab20-2804-407a-951f-679a67fe7afb.mp4

**Comment by kepano** [comment]
How do you imagine that this should work? Here are the options I can think of:

1. Breadcrumbs should move down so they do not conflict on hover
2. Titlebar should be hidden if breadcrumb is present
3. Do not show the titlebar on hover (would require toggling it into view via Command Palette or hotkey)

Is there some other way you imagine dealing with this conflict?

**Comment by u2003** [comment]
Personally, I would prefer the second one, as I suppose most people don't need to edit the title that frequently. For me I love the title bar hidden because I feel it provides a purer and more immersing editing experience, and that's why I always turn on focus mode. The second option may work better to maintain visual consistency. Also, I think the third one can be put into consideration. Some people may not want everything to be hidden, and it's never wrong to provide more customization options to suit different people's appetite.

**Comment by u2003** [comment]
The trouble with the second option may be, there can be quite a few plugins adding a bar on the top, such as zoom, breadcrumbs, and perhaps other plugins I don't know. It may take some work to find out all of them and keep supporting them in future upgrades.

**Comment by kepano** [comment]
Can you try 4.4.6 and see if this fixes it for you?

**Comment by u2003** [comment]
Thank you so much. I tried it and the contradiction has been fixed. Yet another problem coms up. You can see in the ohoto, the banner was cut off on the right top.

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/84957135/150659457-ca102591-d724-4bed-b9db-94a675194823.png">

**Comment by u2003** [comment]
I find the banner icon is also shaded now, but I'm not sure this is caused by Minimal.

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/84957135/150660859-7c2cd6ca-b9d9-46ed-889a-56b5ccecdf98.png">

**Comment by kepano** [comment]
Ok this should be fixed in the latest commit, thanks!
