### ISSUE TITLE
[BUG] Uneven margin missalignments between Reading Mode and the others

### ISSUE THREAD

**Issue by veradrawer** [kepano/obsidian-minimal#135]
**Describe the bug**
Hi, loving Minimal so far. I've discovered a bug while using the Embedded Note Titles Plugin.
Normally I would go post in their repo, but I noticed that the misalignment emerges from spacing within the theme, as shown in a screenshot below using outlining in the divs.

**To reproduce**
1. Install the [Embedded Note Titles Plugin](https://github.com/mgmeyers/obsidian-embedded-note-titles) 

**Expected behavior**
Equal Spacing in every previsualization mode

**Screenshots**
![1](https://user-images.githubusercontent.com/75331117/150523631-9b03b1ba-e5ea-4915-82a8-84b9a83c01a5.png)
A Preview of how Headings are displayed in the three existing preview modes.

![2](https://user-images.githubusercontent.com/75331117/150523752-e5149554-0f0a-4e2a-be5d-7b699a70fb8a.png)
Using outlining, we can see that the problem seems to be uneven spacing between preview modes.

Hope this helps!

**Comment by kepano** [comment]
This is closed in 4.4.7

**Comment by veradrawer** [comment]
I can confirm that as Minimal 4.4.8, this has not been fixed.

![imagen](https://user-images.githubusercontent.com/75331117/150678883-45c5f8d7-d401-49ad-b281-dc109446b469.png)

Sorry for all the trouble.

**Comment by kepano** [comment]
This should now be fixed
