### ISSUE TITLE
Controls are offset when deleting files/folders, in some languages through a long name (inscription).

### ISSUE THREAD

**Issue by ivanmood0** [kepano/obsidian-minimal#137]
Controls are offset when deleting files/folders, in some languages through a long name (inscription).
![2022-01-21_14-09](https://user-images.githubusercontent.com/79835684/150526342-52b0d937-7532-42bb-8f16-77cee554a0b6.png)

**Comment by kepano** [comment]
I made some various small fixes in 4.4.4 that should help with this
