### ISSUE TITLE
Color themes for Minimal

### ISSUE THREAD

**Issue by vi-cat** [kepano/obsidian-minimal#138]
I really like Obsidian Minimal, especially the heavy lifting UI changes. However, I would really like to be able to change the colors of the theme. In particular, the editor/preview colors. I'm a big fan of the Dracula color scheme: https://draculatheme.com/. They have an Obsidian theme, but compared to Minimal, it very flimsy.

Would it be possible to add color profiles to Minimal's settings?

**Comment by kepano** [comment]
This is on my near-term roadmap.

In the meantime you can find custom color schemes for Minimal [on the forum](https://forum.obsidian.md/t/share-your-minimal-theme-screenshots-configuration/8983), or ask in the #minimal channel on Obsidian Discord. I believe someone has made a Dracula color scheme for Minimal already that you can install as snippet.

**Comment by kepano** [comment]
This is available as of Minimal 5.0
