### ISSUE TITLE
Very hard to grab onto the scrollbar because it's small

### ISSUE THREAD

**Issue by ivanmood0** [kepano/obsidian-minimal#140]
It's very hard to grab onto the scrollbar because it's small, probably needs some zoom effect or something.

https://user-images.githubusercontent.com/79835684/150650313-19c3426e-273e-4d52-a6a9-6a17a1dea57a.mp4

**Comment by kepano** [comment]
You might want to try the Native Scrollbars plugin. Or using the following snippet

```
::-webkit-scrollbar {
  width:20px;
}
```

**Comment by ivanmood0** [comment]
> You might want to try the Native Scrollbars plugin. Or using the following snippet
> 
> ```
> ::-webkit-scrollbar {
>   width:20px;
> }
> ```

The Native Scrollbars plugin, at least in my case, looks awful, but thanks for the reply.
