### ISSUE TITLE
[BUG] Potential typeface injection

### ISSUE THREAD

**Issue by veradrawer** [kepano/obsidian-minimal#142]
I'm using Obsidian on both Desktop and App with the Minimal theme, and set "Inter" my preferred typeface.
I was surprised when I found that in the App the typeface was also synced. But then I striked on those things that ruin the experience.
With the Minimal theme (tested with Default and California Coast) Inter has some kind of conflicts with its italic version. The text rendered looks like a 700 instead of the preffered value. There are no css snippets enabled for this test.

Tweaking with the css does not work, so I ended up concluding that the theme was fetching Inter from somewhere and overriding my installed copy or something even weirder. I can confirm this happens in both Source Mode and Live Edit.

![imagen](https://user-images.githubusercontent.com/75331117/150654955-8b094240-b330-4af9-8a87-dfd93f7c9a53.png)
Here we can see a paragraph with fat italics in Reading Mode.

![imagen](https://user-images.githubusercontent.com/75331117/150655028-9fdb575e-cffc-428e-8d7f-8d48b5793b61.png)
The text is dealing with the same issue in Source Mode.

![imagen](https://user-images.githubusercontent.com/75331117/150655103-b883c7b5-667d-41e0-ba8c-9cf8aee9a115.png)
I confirm with the Developer Tools if somehow this is set to 700 or so. Nope.

![imagen](https://user-images.githubusercontent.com/75331117/150655122-0bd6bee8-2a6f-4491-885b-7bca739b6853.png)
Ironically, manually changing the value to 700 affects the rest of the body. Same thing with 900.

![imagen](https://user-images.githubusercontent.com/75331117/150655164-dad58b14-a356-4386-b44a-91ed7caff814.png)
Something interesting. When I set the weight value to the absolute minimum (100), the italics are showing what seems to be an additional weight. They appear like 400 now!

![imagen](https://user-images.githubusercontent.com/75331117/150655241-bc8e608f-5fa4-4f9b-b808-c05b76a90056.png)
Yup, body weight italics are fine.

![imagen](https://user-images.githubusercontent.com/75331117/150655273-cdb09669-70c6-43fd-b891-545ee7f615bb.png)
There isn't any weight change with 500. This is where I start thinking something is overriding my installed fonts. I confirm I can use Inter 500 on any other app without issue.

![imagen](https://user-images.githubusercontent.com/75331117/150655427-ef887ea4-322a-4163-9b1f-17747f61855b.png)
With California Coast.

![imagen](https://user-images.githubusercontent.com/75331117/150655452-93a8d037-de89-4697-b46a-d95e53be2c07.png)
And finally with the Obsidian Default theme.

![imagen](https://user-images.githubusercontent.com/75331117/150655658-5257c047-c0b7-4cb2-850d-23e5dc6b5259.png)
So, Okay, I have no idea what is going on. At this point I enable Safe mode and start checking. This changes the font to Segoe as the Style Settings plugin was disabled. I manually change the font to Inter again, just to check. And there is. Still.
NOTE: Segoe UI Bold Italic is not afected, just the text set in Inter is. I can use whatever typography I see fit but Inter. Obsidian won't let me use all installed weights of this typeface.

Help, please.

**To reproduce**
1. Install the Minimal Theme
2. Install Inter from Google Fonts
3. Install Style Settings Plugin in Obsidian
4. Set "Inter" as default font

**Expected behavior**
Bold Italics are the same weight as bold.

**Comment by veradrawer** [comment]
![imagen|236x500](upload://i1xGiSv3gybhddwmKDegIK9Tzde.jpeg)
This is a screenshot from my phone, as you can see, this happens across devices.
I have not installed Inter in my phone.

**Comment by veradrawer** [comment]
This issue is now also posted on the [Obsidian Forum](https://forum.obsidian.md/t/bug-inconsistent-font-weight-across-themes-that-could-imply-residual-code/31110)

**Comment by kepano** [comment]
This is not a Minimal theme issue because it also happens with the default theme.

The issue seems to be that the version of Inter that ships with Obsidian doesn't contain the 600 weight italic variation.

The default bold weight in Obsidian is 700, whereas the default bold weight in Minimal is 600. That's why there is a discrepancy. 

If you use a snippet to set `--bold-weight:700` the fonts will be consistent in bold vs. bold italic
