### ISSUE TITLE
Border and Font Size Options for Code Blocks

### ISSUE THREAD

**Issue by dvdmtw98** [kepano/obsidian-minimal#143]
Option to add border to code blocks and the ability to change the font size of code blocks
The current font size of code blocks is a bit to small having the ability to customize the size would be great

**Comment by alicangok** [comment]
+1

This is probably not the most healthy way to make this change, but I was able to change the font size of code blocks by modifying the "0.85" number in the following passage within the extremely long line 39 of `my_vault_directory/.obsidian/themes/minimal.css`

`.HyperMD-codeblock,.cm-s-obsidian span.cm-inline-code,.markdown-preview-view code,.markdown-preview-view pre,.markdown-source-view.mod-cm6 .cm-preview-code-block pre.dataview-error{color:var(--text-code);font-size:0.85em}`

For example, modifying 0.85em to 1.0em makes them the same size as the regular body font.

**Comment by dvdmtw98** [comment]
Thanks for your suggestion @alicangok
Will you this for the time being and hope that @kepano adds this as a customizable option

**Comment by alicangok** [comment]
> Will you this

Will I what? :) If you mean forking or something, I'm not really an expert, so I would rather stay away from it. I just opened the mentioned .css file in my PC using a simple text editor and made the change there. I'm sure my local change will be gone when the plugin is updated on my Obsidian client.

**Comment by kepano** [comment]
Added in Minimal 5.0
