### ISSUE TITLE
Name of vault in the desktop version

### ISSUE THREAD

**Issue by ivanmood0** [kepano/obsidian-minimal#144]
It would be great to see the name of vault in the desktop version, as it is implemented in the mobile. Sometimes you just need to look to see if you're making a note in the right vault.

![2022-01-23_11-46](https://user-images.githubusercontent.com/79835684/150673183-9a51657c-101f-49df-a148-9ce5fe7ea0b4.png)

**Comment by kepano** [comment]
This is available as of 5.1.5
