### ISSUE TITLE
[Mobile] The delete (close) icon goes beyond the search field

### ISSUE THREAD

**Issue by ivanmood0** [kepano/obsidian-minimal#145]
The delete (close) icon goes beyond the search field, probably because it has a background. Spotted while searching for plugins. In other search scenarios, I did not check.

![2022-01-23_11-32](https://user-images.githubusercontent.com/79835684/150673397-e8af1272-5231-4795-a1c3-193653cb4cae.png)

**Comment by kepano** [comment]
This is fixed in the latest version
