### ISSUE TITLE
Support plugin "Tasks"

### ISSUE THREAD

**Issue by ivanmood0** [kepano/obsidian-minimal#146]
If not very difficult, please add support for the "Tasks" plugin. Сurrently, for example, completed tasks are not crossed out.
Here is a link to the plugin (by the way, this is a very popular plugin), so its support, I think, will be useful to many. 

https://github.com/schemar/obsidian-tasks

**Comment by ivanmood0** [comment]
Here's an example of what a completed task looks like when using a "minimal" and "original" theme.

![tsk](https://user-images.githubusercontent.com/79835684/150694738-d0aa0d71-8b97-4a62-8ce6-f78e5b5524b9.png)

**Comment by kepano** [comment]
Have you tried using the option in Style Settings to turn on “strike completed tasks”?

**Comment by ivanmood0** [comment]
> Have you tried using the option in Style Settings to turn on “strike completed tasks”?

No, I haven't tried. Where can I find it?
