### ISSUE TITLE
Support plugin "Reminder"

### ISSUE THREAD

**Issue by ivanmood0** [kepano/obsidian-minimal#147]
Please add support for the "Reminder" plugin. From what I noticed, the defer notification button is slightly shifted. The screenshot is attached below. Thanks.

![2022-01-23_17-18](https://user-images.githubusercontent.com/79835684/150685782-2d0febad-8fdd-4818-8b62-f27a3e5900d5.png)

Plugin link:

https://github.com/uphy/obsidian-reminder

**Comment by kepano** [comment]
Added in 5.2.7
