### ISSUE TITLE
Banner icon cut off by banner

### ISSUE THREAD

**Issue by u2003** [kepano/obsidian-minimal#148]
as you can see in the photo, the banner icon is cut off
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/84957135/150718854-2f5470d5-47ae-46bc-a4b9-18a1ae90caf8.png">

**Comment by kepano** [comment]
Can you please fill in the bug report template? There is not enough detail to work with here.

**Comment by u2003** [comment]
Do you mean the debug info? I put it below now. And after testing all my plugins, I think it's contradicted by Contexual Typography. When I turn off this plugin, it'll be ok.

SYSTEM INFO:
	Obsidian version: v0.13.19
	Installer version: v0.13.19
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 3
	Safe mode: off
	Plugins installed: 103
	Plugins enabled: 89
		1: Homepage
		2: Gallery
		3: Typewriter Scroll
		4: Easy Typing
		5: Auto pair chinese symbol
		6: MarginNote Companion
		7: Recent Files
		8: Fullscreen mode plugin
		9: Zoom
		10: Word Splitting for Simplified Chinese in Edit Mode
		11: LanguageTool Integration
		12: Calendar
		13: Advanced Tables
		14: DEVONlink
		15: Quick Switcher++
		16: Table of Contents
		17: Convert url to preview (iframe)
		18: Citations
		19: Hotkey Helper
		20: Media Extended
		21: Note Refactor
		22: Paste URL into selection
		23: Tag Wrangler
		24: Better footnote
		25: Footlinks
		26: Natural Language Dates
		27: Footnote Shortcut
		28: Icons
		29: Tidy Footnotes
		30: QuickAdd
		31: Hider
		32: Activity History
		33: Command Alias
		34: Mind Map
		35: Copy Block Link
		36: Banners
		37: Dataview
		38: Icon Folder
		39: Sliding Panes (Andy's Mode)
		40: MetaEdit
		41: Hotkeys for templates
		42: Media Extended BiliBili Plugin
		43: Smart Random Note
		44: Customizable Sidebar
		45: Kanban
		46: Cycle through Panes
		47: Open with
		48: Number Headings
		49: Table Extended
		50: Flashcards
		51: Force note view mode
		52: Graph Analysis
		53: Journey
		54: Customizable Menu
		55: Emoji Toolbar
		56: Markdown prettifier
		57: Get Info
		58: Smart Typography
		59: Advanced URI
		60: Custom window title
		61: Auto Link Title
		62: Customizable Page Header
		63: Global Hotkeys
		64: Charts View
		65: Contextual Typography
		66: System Dark Mode
		67: Plugin Changelogs
		68: Pandoc Plugin
		69: Obsidian42 - BRAT
		70: Frontmatter Tag Suggest
		71: Obsidian Charts
		72: Spaced Repetition
		73: Vantage - Advanced search builder
		74: Image auto upload Plugin
		75: Style Settings
		76: Breadcrumbs
		77: obsidian markmind
		78: floating-toc Plugin
		79: Dynamic Table of Contents
		80: Regex Find/Replace
		81: Advanced Mobile Toolbar
		82: Periodic Notes
		83: Admonition
		84: Obsidian Memos
		85: Excalidraw
		86: Outliner
		87: Juggl
		88: Sortable
		89: Indentation Guides

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please try to make the issue happen in the help vault or disable community plugins.

**Comment by kepano** [comment]
This is fixed
