### ISSUE TITLE
[Mobile] The mobile version does not display a button (frame) around the text when deleting

### ISSUE THREAD

**Issue by ivanmood0** [kepano/obsidian-minimal#149]
The mobile version does not display a button (frame) around the text when deleting, I don't know, maybe this is the author's idea, and it has always been so, but before I did not pay attention to it.

![butt](https://user-images.githubusercontent.com/79835684/150782251-50efc49d-4a20-4ab6-8efd-0153b5af0714.png)

**Comment by kepano** [comment]
This is intentional as of the latest release to reduce accidental input

**Comment by ivanmood0** [comment]
> This is intentional as of the latest release to reduce accidental input

Well, it looks a bit strange, well, or just unusual, but for that matter, I suggest you transfer this style to the desktop version, I think it would be appropriate, so that both versions correspond to the general style.

**Comment by kepano** [comment]
The desktop screenshot you shared is not the latest version. You can see more about the discussion on this topic in the Obsidian Discord

**Comment by ivanmood0** [comment]
> The desktop screenshot you shared is not the latest version. You can see more about the discussion on this topic in the Obsidian Discord

Well..., the latest version of the program is 0.13.19 (excluding insider build), the version of the theme is 4.4.8, doesn't matter, the main thing is that you are aware 😁
