### ISSUE TITLE
In settings, the last line is cropped

### ISSUE THREAD

**Issue by autonomygaps** [kepano/obsidian-minimal#15]
I've been using Minimal for a long time now, and even with the new version, I have the following bug:  in settings, I can see the last line of the window. For example, if I try to see all of my community plug-ins, I scroll to the bottom, and the last one (Workbench) doesn't entirely show.  Do you have any idea what might be causing this?

<img width="1090" alt="Screen Shot 2021-07-18 at 12 27 38" src="https://user-images.githubusercontent.com/48016853/126063862-671d12c7-7df7-4f1b-a2c4-a904bd13c1aa.png">

**Comment by kepano** [comment]
Can you download the latest version (3.0.6) and try again?

**Comment by autonomygaps** [comment]
This solves the problem, thanks!  I also noticed that the margin spacing was more normal, with "Settings > Editor > Readable line length" toggled off.  I just tried toggling it ON again, however, and it generated a new line length of 1 character.  Might be a new bug generated by the fix you just made?
Interestingly, I get the same behavior in California Coast (partly based on Minimal, I think), but not on other Community Themes (or with the default theme).
Not an urgent problem for me, because I don't use "Readable line length," but I thought I'd like you know.

Below are sceenshots of the output, and of the the developer Console.

<img width="1154" alt="Screen Shot 2021-07-19 at 07 39 28" src="https://user-images.githubusercontent.com/48016853/126112257-b12734c8-219e-4b28-8848-4786dda65e87.png">

<img width="1112" alt="Screen Shot 2021-07-19 at 08 25 27" src="https://user-images.githubusercontent.com/48016853/126112656-6e24bd3d-a1ea-451c-858c-d8ab20241ca8.png">

**Comment by autonomygaps** [comment]
Not sure what all's going on…. This problem seems to have resolved itself on the Mac, but on the iPad – running iOS 14, public beta 3.  I'm also getting a fade-out with the titles.

![IMG_D1671D1C743F-1 2](https://user-images.githubusercontent.com/48016853/126225930-1fe42861-6fb8-4a7c-96ef-f00311709866.jpeg)

**Comment by kepano** [comment]
Can you try restarting the app? I think your line width settings in Minimal Theme have not synced properly. I am guessing it is set to a really small number on your iPad

**Comment by autonomygaps** [comment]
It's working again, but I'm still regularly having situations in which the title bar (of the note) is not visible.  Then I reinstall the Minimal Style Settings, and it works again.

**Comment by kepano** [comment]
It sounds like it is related to your sync preferences.

**Comment by autonomygaps** [comment]
Thanks.  I'll keep an eye on it.  I'm running Obsidian betas on beta iPadOS, so who know where is starts.
