### ISSUE TITLE
Progress bar CSS snippet broken with Minimal 4.4.8

### ISSUE THREAD

**Issue by blackpeasy** [kepano/obsidian-minimal#150]
I have a custom CSS snippet for progress bars enabled.

However, with the new Minimal it seems like the theme's style is prioritized higher than my snippet.

How do I make my snippet work?

**Comment by kepano** [comment]
You will need to add more specificity, e.g. adding `body` at the beginning of the CSS rules

Please use #minimal channel on Discord for support questions
