### ISSUE TITLE
Dataview tables word-breaks in live preview

### ISSUE THREAD

**Issue by blackpeasy** [kepano/obsidian-minimal#156]
Behavior in reading mode (Preferred): Keeps words intact and adds a horizontal scrollbar at the bottom.
<img width="300" alt="image" src="https://user-images.githubusercontent.com/92858268/151200539-39631f8e-8a15-422e-ac86-8bee554d24c1.png">

Behavior in preview mode: Tries to fit everything in. Breaks words, creating an unreadable and very long list
<img width="300" alt="image" src="https://user-images.githubusercontent.com/92858268/151200637-f028c098-fe56-45fd-ac16-46ad0df8e96b.png">

**Comment by kepano** [comment]
Changing this to a feature request. What you see in LP is the default Obsidian behavior for both LP and Reading view. Minimal has special table handling in Preview as of 4.2.0 to address this issue but it hasn’t been added to LP yet.

**Comment by blackpeasy** [comment]
Thanks!
