### ISSUE TITLE
Tag settings conflict with JSX/TSX syntax highlighting

### ISSUE THREAD

**Issue by nianiam** [kepano/obsidian-minimal#16]
As title says, the `.tag` class is also used within code blocks for certain syntax's - such as JSX and TSX.

As far as I can tell, simply changing:

```css
.frontmatter-container .tag, .tag { ... }
```

to 

```css
.frontmatter-container .tag { ... }
```

Fixes the problem. However, I haven't tested throughly the larger effects of removing this selector.

**Comment by kepano** [comment]
This is fixed in 3.0.7
