### ISSUE TITLE
cards with images only show one item

### ISSUE THREAD

**Issue by xinyirenxinyi** [kepano/obsidian-minimal#160]
Hi I'm playing with the new cards beta function (love the demo) and am having trouble 

Everything works fine without adding images, query:
`dataview
table aliases
from #Ref/Book 
where cover
`

result (looks good so far)
![image](https://user-images.githubusercontent.com/68445000/151679912-6a562014-4a07-413b-9c2a-0509e5276307.png)

but once I add images to the query then only one entry shows up
`dataview
table ("![](" + cover + ")") as Cover
from #Ref/Book 
where cover
`

result
![image](https://user-images.githubusercontent.com/68445000/151679942-d24d8497-812b-4fad-8724-7706220e4c59.png)

Thanks for your amazing work

**Comment by kepano** [comment]
This seems related to your query not the theme. First make sure your query works without adding the cards class.

You can get help with Dataview in the #dataview channel on Obsidian Discord
