### ISSUE TITLE
[MOBILE] Popup info boxes are unreadable

### ISSUE THREAD

**Issue by aventuraviper** [kepano/obsidian-minimal#162]
**Describe the bug**
Obsidian info popups are unreadable. They appear black with no text (assume text colour is same as popup fill)

**To reproduce**
1. Go to any file in Obsidian iOS
2. Open command palette
3. Choose a command that results in a popup, such as "copy file path"

**Expected behavior**
Popup with informative text should appear and the text should be readable. Note, choosing a colur theme changes the colour on the popup on desktop. This doesn't appear to be the case on mobile.

**Screenshots**
![IMG_5320](https://user-images.githubusercontent.com/55485055/151798885-b5c7ca8d-9b65-4209-bba2-b01e74b45b80.png)

**Debug info (please complete the following information):**
Minimal 5.0.0, Obsidian 1.0.5 on iOS 15

**Comment by ArttuLai** [comment]
The font used to be white, but is now black, and so is the popup background on mobile. Wonder what's the CSS for the font so I could fix it while at it.

**Comment by kepano** [comment]
This should be fixed if you update Minimal theme

**Comment by aventuraviper** [comment]
> This should be fixed if you update Minimal theme

It is! Thank you for the swift fix.
