### ISSUE TITLE
Legible CSS Root

### ISSUE THREAD

**Issue by realbearsmith** [kepano/obsidian-minimal#164]
Would it be possible to break the root line out into readable code?

I prefer to make edits at the root CSS in order to ensure the theme is consistent with my publish site (style plugin doesn't apply to publish). I would prefer to use the Minimal theme but I've been unable to effectively do so. This is because every time an update comes out, I have to go through the CSS file and add line breaks and indentations throughout the root code. This takes far too long to be worth it.

This is the only Obsidian theme I've seen that does this.

Is there a reason the root line is this way? Is there a way I can more easily edit the root CSS?

**Comment by kepano** [comment]
I am not sure I understand what you mean by “root” in this context. Take a look at the readme section for developers. The build script creates a copy of the theme that is unminified in the main project directory. 

That being said Minimal is not designed for use with Publish. At least 99% of the code is irrelevant to Publish and therefore is not optimal for your visitors.
