### ISSUE TITLE
Reset button doesn't revert to transparent swatch in the Minimal Theme settings area in Style Settings plugin when resetting color

### ISSUE THREAD

**Issue by janpeeters70** [kepano/obsidian-minimal#165]
**Describe the bug**
When I try to reset any color in the Minimal Theme settings of Style Settings to default, the old color remains in the color sample circle instead of showing the transparent swatch. 
The color does reset though to the default one in the background.

**To reproduce**
1. Go to 'Style Settings' in prefs
2. Click on 'Minimal Custom Color Scheme'
3. Go to 'Interface'
4. Change 'Sidebar Background' color to something else.
5. Exit window. 
6. Come back to the setting and try to reset color.

**Expected behavior**
When I hit the reset button the color sample reverts to the transparent swatch.

**Added info**
@HEmile suggested in the Style Settings repo that this might be caused because there appears to be no default color value set, only '#'. So it might not know where to revert to. But on the other hand if there would be a default color set, I guess this would interfere with the color scheme that is chosen in Minimal Theme Settings. Maybe it's just a matter of replacing the set color swatch with the transparent swatch.

**Screenshots**
https://cln.sh/3ZowSeVJJT01aT67K5lR

**Debug info):**
SYSTEM INFO:
	Obsidian version: v0.13.23
	Installer version: v0.12.19
	Operating system: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 21.3.0
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 79
	Plugins enabled: 4
		1: Style Settings
		2: Minimal Theme Settings
		3: Contextual Typography
		4: Hider

**Comment by kepano** [comment]
This is intentional because of the way color schemes work. When you reset to default it will use the default color from the color scheme that you are using which is stored in the CSS not in the Style Settings. Style Settings doesn’t have the ability to have multiple defaults per color scheme.

**Comment by janpeeters70** [comment]
_I wasn't clear enough:_
If you look again at the video, you'll see that clicking the reset button doesn't change anything to the swatch of the custom color that I've set. That is confusing because it's not the active color anymore.

Expected behavior would be that if you reset the color, it replaces the custom color swatch in the UI with the (default) checkerboard pattern again.

**Comment by kepano** [comment]
I believe this is a Style Settings issue. If you close and reopen the pane it returns to the checkerboard pattern.

**Comment by janpeeters70** [comment]
Thanks, I'll report it back again at the style settings repo.
