### ISSUE TITLE
Accent color not rendered correctly in the UI

### ISSUE THREAD

**Issue by icebruce** [kepano/obsidian-minimal#168]
**Steps to reproduce**

1. Set the Accent color from the Style settings (#2168AB)
2. Navigate Obsidian menu or create a link on a page
3. The accent color does not have the same shade (shows darker color)

![image](https://user-images.githubusercontent.com/66655064/152087164-fa620711-1918-4028-93a7-9b97d48bdf83.png)
![image](https://user-images.githubusercontent.com/66655064/152087174-69f068b3-645a-4ddf-8f8f-fffead1d563e.png)

Expected behaviour
Accent color set by the Style Settings should be rendered as is.
**Notes:**
    Latest version of Minimal, Minimal Style settings and Style settings installed
    Tried each style setting separately. Issue persists only when Style setting is enabled with an Accent color

**Comment by icebruce** [comment]
Does not look like its an issues with the Style settings (see https://github.com/mgmeyers/obsidian-style-settings/issues/55#issue-1121350705). Issue is resolved when testing with another theme.

**Comment by kepano** [comment]
This is intentional because the accent picker is used to generate multiple sub-colors. If you want to exactly define the checkbox color you can do so in the settings below (as mentioned in the description for that setting)
