### ISSUE TITLE
Link in heading is not bold in live preview

### ISSUE THREAD

**Issue by sestei** [kepano/obsidian-minimal#170]
Consider two headings, one of which is also a link. This is how it looks like in source editing mode:
![image](https://user-images.githubusercontent.com/10315681/152336950-f1ab600e-68db-426f-91d1-8e57eeca86c7.png)

In Live Preview, this is what one gets (cursor on second line):
![image](https://user-images.githubusercontent.com/10315681/152337070-b9cce94a-5f09-4062-9f13-508f46c41d75.png)
... or, moving cursor away:
![image](https://user-images.githubusercontent.com/10315681/152337115-f29e0033-d54b-478d-ae6d-ff0556c977a8.png)

In reading mode, however, both lines are (correctly, I assume) formatted in bold:
![image](https://user-images.githubusercontent.com/10315681/152337212-0590b469-a7b5-4a6e-978f-5ad30c45dbd9.png)
(related note: there's also more vertical space in reading mode, compared to editing mode).

**Comment by kepano** [comment]
This should be fixed in the latest
