### ISSUE TITLE
Query - How do I make the left menu look like the screenshots?

### ISSUE THREAD

**Issue by chrissainty** [kepano/obsidian-minimal#173]
I've just installed the theme but the left menu doesn't look the same as the screenshots in this repo. I'm not seeing the Notes, Search, Starred options at the top. Also my interface seems a bit more compressed than the screenshots, like it's missing a lot of padding and spacing. Any ideas?

**Comment by kepano** [comment]
You need to turn on the “Text labels for primary navigation” feature in Minimal Theme Settings.

Please use the Obsidian Discord for general questions as this is neither a bug nor a feature request. Thanks!

**Comment by chrissainty** [comment]
Thanks for the help and apologies for not using the right channel. I'll not make that mistake again. 

Thanks for your work on this great theme.
