### ISSUE TITLE
Block quote font colors are overriding other font colors (like Internal Links)

### ISSUE THREAD

**Issue by rodrigo-rufino** [kepano/obsidian-minimal#176]
**Describe the bug**
Font colors of other elements (like links, bold, italic) inside a block quote are being overridden by the block quote font color in Live Preview. 

**To reproduce**
1. Create a block quote.
2. Add a link inside it.
3. See that the link doesn't have the color used for links (works correctly on hover, though).

**Expected behavior**

**Screenshots**
Live Preview Mode:
![Captura de Tela 2022-02-07 às 09 58 53](https://user-images.githubusercontent.com/18670446/152792595-1efe4386-7833-4208-9882-4b09e5779c98.png)

Reading Mode:
![Captura de Tela 2022-02-07 às 10 04 38](https://user-images.githubusercontent.com/18670446/152793518-69d59060-08f2-4bb3-9f67-e51a1b4ce954.png)

**Comment by kepano** [comment]
I have fixed the unresolved link so that there is consistency.

However I think the issue with italics and bold is a matter of preference. It is not easy to allow the user to choose which color has precedence between the blockquote color and the text inside of the blockquote. Right now I am making the choice that the blockquote color precedes the color of the contents.

**Comment by totholz5d** [comment]
> However I think the issue with italics and bold is a matter of preference. It is not easy to allow the user to choose which color has precedence between the blockquote color and the text inside of the blockquote. Right now I am making the choice that the blockquote color precedes the color of the contents.

I also find that it would be more logical if the color of content would precede the blockquote color (like it does in the reading view).

I understand that a decision is necessary for this behavior but it would be really nice to have an option to choose the preferred behavior in the style settings.

I have been struggling, until now without success, to write an CSS snippet that would implement this behavior...
