### ISSUE TITLE
Portrait and landscape on mobile has different font sizes

### ISSUE THREAD

**Issue by EHBaozi** [kepano/obsidian-minimal#177]
On iPhone the font size is significantly larger when viewed in landscape. Is this designed behavior?

![image](https://user-images.githubusercontent.com/38034505/152858518-7859959b-925a-4950-96bd-a877915d2d4e.png)

![image](https://user-images.githubusercontent.com/38034505/152858574-1800be51-5b0c-4e04-8f9d-4f1fb5a5516f.png)

**Comment by EHBaozi** [comment]
I just realized it's hard to see from the screenshots but it's more obvious on device.

**Comment by EHBaozi** [comment]
This one should be clearer.

![image](https://user-images.githubusercontent.com/38034505/152859252-e8655b6b-74c6-472a-8f9c-b6a4c02926e7.png)

**Comment by kepano** [comment]
Yes this because Minimal uses adaptive font sizes depending on the width of your screen, see

https://github.com/kepano/obsidian-minimal/blob/master/src/scss/variables/adaptive-font-size.scss

**Comment by EHBaozi** [comment]
I see. Thanks!
