### ISSUE TITLE
Blockquotes text color not being applied.

### ISSUE THREAD

**Issue by mhinton** [kepano/obsidian-minimal#179]
**Describe the bug**
The font color of blockquotes doesn't change when changed in Style Settings. It seems to be using the muted text color.

**Expected behavior**
The font color of blockquotes should change when changed in the Style Settings.

**Screenshots**
![CleanShot 2022-02-07 at 15 00 15](https://user-images.githubusercontent.com/23145/152871412-88a6e489-0ccc-464b-9b3b-fe590a2262f3.png)

**Comment by kepano** [comment]
I am trying to reproduce the bug but I am not able to. I am using Dracula dark.

<img width="1159" alt="Screen Shot 2022-02-07 at 1 45 11 PM" src="https://user-images.githubusercontent.com/10565871/152877133-1c984401-bddb-4407-a2b8-f1395a0b159c.png">

**Comment by mhinton** [comment]
Weird, it must be on my end somehow. I disabled every Obsidian extension except Minimal Theme Settings and Style Settings and I still have the issue. The "Blockquotes font size" and "Blockquotes font style" both work just text color doesn't.

**Comment by kepano** [comment]
Can you export your Style Settings and paste them here? Click **Export** at the top of the Style Settings window.

You may also want to restart Obsidian to see if that helps.

**Comment by mhinton** [comment]
I have tried restarting after every change but that hasn't changed anything.

```
{
  "sanctum@@line-width": 50,
  "sanctum@@font-preview": "'Helvetica Neue', 'Inter', 'iA Writer Quattro S', 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  "sanctum@@font-editor": "'Helvetica Neue', 'Inter', 'iA Writer Quattro S', 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  "things-style@@font-monospace": "CascadiaCodePL-Regular,JetBrains Mono,Menlo,SFMono-Regular,Consolas,\"Roboto Mono\",monospace",
  "things-style@@macOS-translucent": false,
  "obsidian-california-coast-theme@@cc-lp-editor-heading-hash": false,
  "obsidian-california-coast-theme@@font-monospace": "CascadiaCodePL-Regular,Menlo, SFMono-Regular, Consolas, \"Roboto Mono\", monospace",
  "obsidian-california-coast-theme@@h1-color@@dark": "#4F93FF",
  "obsidian-california-coast-theme@@h2-color@@dark": "#4BA2C1",
  "obsidian-california-coast-theme@@h3-color@@dark": "#48BC93",
  "obsidian-california-coast-theme@@h4-color@@dark": "#96BC46",
  "obsidian-california-coast-theme@@h5-color@@dark": "#DAB74C",
  "obsidian-california-coast-theme@@cc-no-custom-icons": true,
  "obsidian-california-coast-theme@@cc-no-folder-icons": true,
  "buttons-styles@@button-background@@dark": "#434343",
  "sanctum@@heading-clr": true,
  "sanctum@@color-heading-1-l": "rgb(102, 142, 165)",
  "sanctum@@color-heading-2-l": "rgb(132, 132, 188)",
  "sanctum@@color-heading-3-l": "rgb(70, 153, 106)",
  "sanctum@@color-heading-4-l": "rgb(140, 141, 59)",
  "embedded-note-titles@@embedded-note-title-size": 22,
  "minimal-style@@blockquote-style": "normal",
  "minimal-style@@blockquote-size": "15px",
  "minimal-style@@ax3@@dark": "#BF95F9",
  "minimal-style@@tx1@@dark": "#E0E0D6",
  "minimal-advanced@@font-smallest": 12,
  "minimal-style@@h1": "1.75em",
  "minimal-style@@h2": "1.5em",
  "minimal-style@@h3": "1.4rem",
  "minimal-style@@h4": "1.25em",
  "minimal-style@@h6": "1em",
  "minimal-style@@h5": "1.1em",
  "minimal-style@@tx2@@dark": "#B7B7B3",
  "minimal-style@@text-blockquote@@dark": "#DD4BD5"
}

```

**Comment by kepano** [comment]
I am not sure... I have loaded your Style Settings preferences and it still works for me.

Can you try updating the theme to the latest version?

**Comment by mhinton** [comment]
I am running the latest version.

**Comment by kepano** [comment]
Unfortunately I am running out of ideas. If you are able to, I would look at the developer tools and see if you can inspect the CSS to figure out where things are being overridden

**Comment by mhinton** [comment]
Here's what dev tools shows.
![CleanShot 2022-02-08 at 09 05 17](https://user-images.githubusercontent.com/23145/153014600-1a6533fe-751f-4fdc-b36f-be23459bb7f0.png)

**Comment by kepano** [comment]
Hmm... something is wrong here. The CSS doesn't match the rules from the theme see screenshot below. I would recommend that you update the theme, update Obsidian and restart the app. 

<img width="1094" alt="Screen Shot 2022-02-08 at 9 40 14 AM" src="https://user-images.githubusercontent.com/10565871/153044460-7ddbaf36-6f58-4018-8e92-8caa6041809b.png">

**Comment by mhinton** [comment]
I uninstalled the theme restarted obsidian and then installed the theme again and now it works.
