### ISSUE TITLE
Search not working in Preview.

### ISSUE THREAD

**Issue by Cantolla** [kepano/obsidian-minimal#18]
I am on mobile.
Latest Minimal Theme version.
Obsidian 1.0.3.

Clicking on a search in preview mode won't take you to that part of the file. It will work in editor mode, only not in preview.

**Comment by kepano** [comment]
This is a known issue with Obsidian not the theme. Please report in the Obsidian forum. Thanks!

**Comment by Cantolla** [comment]
Will do, thank you for the quick reply!
