### ISSUE TITLE
Dragging Obsidian lags when translucent mode is enabled

### ISSUE THREAD

**Issue by davidjaggi** [kepano/obsidian-minimal#181]
**Before you open a bug report**
Disable plugins and snippets that could be causing a conflict. Update to the latest versions of the following, and restart Obsidian:
- Minimal Theme
- Minimal Theme Settings plugin (or Style Settings plugin, but not both)
- Contextual Typography plugin

**Describe the bug**
When the translucent mode is enabled dragging a window lags significantly.

**To reproduce**
1. Enable translucent mode
2. Click on border of obsidian
3. Dragging now lags extremely

**Expected behavior**
Should be snappy.

**Screenshots**

**Debug info (please complete the following information):**
SYSTEM INFO:
	Obsidian version: v0.13.24
	Installer version: v0.12.15
	Operating system: Windows 10 Pro 10.0.19044
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 19
	Plugins enabled: 19
		1: Minimal Theme Settings
		2: Kanban
		3: Advanced Tables
		4: Dataview
		5: Excalidraw
		6: Longform
		7: Mind Map
		8: Outliner
		9: Zoom
		10: Tag Wrangler
		11: Markdown prettifier
		12: Advanced Slides
		13: Readwise Official
		14: RSS Reader
		15: Admonition
		16: Editor Syntax Highlight
		17: Templater
		18: Pandoc Plugin
		19: Better Word Count

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Comment by kepano** [comment]
Have you tested without Minimal?

**Comment by davidjaggi** [comment]
It's an Obsidian issue and not related to the Minimal Theme.
Sorry for the inconvenience.
