### ISSUE TITLE
Add setting for full-width vs automatic width tables

### ISSUE THREAD

**Issue by zirawell** [kepano/obsidian-minimal#183]
**Describe the bug**
Minimal theme settings-Table-trim Dataview columns
I  have switched ‘trim Dataview columns’ off and on.
I find my table width abnormal in preview mode and normal in exported pdf.

**To reproduce**
1. Go to 'Minimal theme settings-Table-trim Dataview columns'
2. Switch off
3. Switch on

**Expected behavior**
table width in preview mode is the same as exported pdf.

**Screenshots**
source code as:
<img width="1138" alt="source_code" src="https://user-images.githubusercontent.com/26316343/153145929-8cee7e81-2025-436e-b845-b118b0c4aac1.png">

preview mode as:
<img width="1134" alt="preview_mode" src="https://user-images.githubusercontent.com/26316343/153145984-79227654-a645-42c2-b1b9-5f64b72c85d4.png">

export pdf as:
[export.pdf](https://github.com/kepano/obsidian-minimal/files/8030583/export.pdf)

**Comment by kepano** [comment]
This is not a bug, tables intentionally fill the normal line width. I will look into making this optional.

**Comment by trijste** [comment]
Thank you. This is the same for images and it should be optional too. I have images that look bad when scaled beyond their natural width.

**Comment by kepano** [comment]
This is already possible for images in Minimal Theme Settings. Turn off “maximize images”

**Comment by trijste** [comment]
> This is already possible for images in Minimal Theme Settings. Turn off “maximize images”
> […](#)

Thanks very much! I wasn't able to find that on my own.

**Comment by kepano** [comment]
Added in 6.0: Style Settings > Minimal > Tables
