### ISSUE TITLE
Title bar not well-aligned

### ISSUE THREAD

**Issue by CavalloneChen** [kepano/obsidian-minimal#186]
The newly introduced title align feature does not perfectly align the title with body text. Alignment method is set to text body in style settings.
Minimal: 5.1.2
Minimal settings: 5.1.2
Style settings: 0.4.9

<img width="1567" alt="image" src="https://user-images.githubusercontent.com/28266566/153328015-0212303b-06a3-4fdc-afa3-f8f8c8a004cd.png">

**Comment by kepano** [comment]
It looks like you have a mismatch between your folding offset settings.

You need to either enable folding in the Obsidian Editor settings, or disable the folding offset in the Minimal Theme Settings

**Comment by CavalloneChen** [comment]
> It looks like you have a mismatch between your folding offset settings.
> 
> You need to either enable folding in the Obsidian Editor settings, or disable the folding offset in the Minimal Theme Settings

Thanks a lot. Disabling the folding offset in the Minimal Theme Settings did the trick.
