### ISSUE TITLE
Window color changes when hovering clickable elements

### ISSUE THREAD

**Issue by gamedeviced** [kepano/obsidian-minimal#189]
**Describe the bug**
Window background color changes slightly when hovering clickable elements.

**To reproduce**
1. Open Obsidian
2. Hover over clickable element

**Expected behavior**
Window color shouldn't change / should stay the same.

**Screenshots**
https://user-images.githubusercontent.com/70090026/153703946-4f668846-b350-4bcf-b0fb-de44bd0b88f0.mov

_Edit:_ Added another screen recording >
https://user-images.githubusercontent.com/70090026/154429600-244fa877-c6ca-4031-9e10-61ce081cdb0b.mov

**Debug info (please complete the following information):**
```
SYSTEM INFO:
	Obsidian version: v0.13.23
	Installer version: v0.13.23
	Operating system: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 21.3.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 14
	Plugins enabled: 10
		1: Advanced Tables
		2: Calendar
		3: Dataview
		4: Templater
		5: Editor Syntax Highlight
		6: Paste URL into selection
		7: Kanban
		8: Natural Language Dates
		9: Minimal Theme Settings
		10: Style Settings

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.
```

**Comment by kepano** [comment]
This is not a bug. This designed to match the official interface guidelines for Mac and iOS.

If you want to disable this effect you can use Style Settings or CSS snippets to change the background color on active states.

**Comment by gamedeviced** [comment]
@kepano Sorry I was not precise enough. I don't mean the hover effect background the button. I mean the overall color change of the window background color. For example look how the top bar gets brighter. It only happens if I didn't hide tooltips.

**Comment by gamedeviced** [comment]
Behaviour stayed the same no matter whether I turned Translucend window in Appearance settings on or off. Same applies for Translucent sidebar in Minimal Theme Settings. The color change happens when an active element shows a tooltip.

**Comment by kepano** [comment]
I see what you mean in the video but I am unable to reproduce the issue on my side. Can you try in a new vault using just Minimal Theme + Minimal Theme Settings?

**Comment by gamedeviced** [comment]
Tried a new vault and the same happens. But: installed it on my MacBook from work using Big Sur, the problem does not occur. It happens only on my private MacBook using Monterey (not sure if thats the root cause). I will investigate further.

**Comment by gamedeviced** [comment]
Other themes don't show this behaviour.

**Comment by gamedeviced** [comment]
Created a new vault on my Monterey MacBook on the Guest Account. So everything is fresh. Same behaviour.

**Comment by gamedeviced** [comment]
I did some more testing: forget about that Big Sur / Monterey thing. The color change is only visible on the internal screen of my MacBook. Not on my external display. That's why I saw the difference between private and work MacBooks.

The color scheme doesn't matter.

Where are the background colors defined? Maybe MacOS does something strange with the hsl converstion or something? On the other hand that's not the case with other themes I tried that use `hsl()` or `hsla()`

**Comment by gamedeviced** [comment]
I checked the Minimal Theme Settings and the only difference I found was in dark mode background contrast:

- Color change happens on Default and Low contrast
- Doesn't happen on True black


All other settings (including Typography) changed nothing.

**Comment by marcjulianschwarz** [comment]
Just noticed the same issue. However, just like @gamedeviced mentioned it is only visible on the internal screen (MacBook Pro) and not on an external screen.

**Comment by kepano** [comment]
Are you able to use the dev tools to investigate? I am unable to reproduce the issue.

**Comment by marcjulianschwarz** [comment]
Looks like it has something to do with the tooltips. The colors only change when hovering over an element with a tooltip. Other hoverable elements without a tooltip don't affect the colors.

**Comment by marcjulianschwarz** [comment]
And if you change the dark mode color scheme in Minimals plugin different parts of the UI seem to change color.
For the macOS scheme the markdown view will change a lot and for the default dark mode color scheme the sidebar will change and the markdown view a bit less.

**Comment by kepano** [comment]
Can you update to the latest version of Minimal theme and try again? 

I am not able to reproduce the issue but I removed the blur effect that is used on tooltips. It may be causing a specific issue with the graphics processing.
