### ISSUE TITLE
Folding header buttons not showing

### ISSUE THREAD

**Issue by timrosenberg** [kepano/obsidian-minimal#19]
I have folding header offset turned on; but, I don't see the folding toggles.

**Comment by kepano** [comment]
You need to also have  "Fold heading" turned on in the Obsidian Settings > Editor

Minimal intentionally only shows the folding toggle when you hover over a heading, or when the heading is collapsed. If you want to show the toggles at all times, I would recommend using a CSS snippet to do so.
