### ISSUE TITLE
Support for outgoing intendation lines with Outliner plugin

### ISSUE THREAD

**Issue by danieltomasz** [kepano/obsidian-minimal#192]
**Is your feature request related to a problem? Please describe.**
Outliner is adding great value to Obsidian for outlining of ideas.
https://github.com/vslinko/obsidian-outliner Currently Outliner has around 108k downloads.
When using Outliner with Minimal the the settings  "Draw vertical indentation lines" to show indentation doesn't look great (screenshot below)
![image](https://user-images.githubusercontent.com/7980381/153882572-a8e1dc96-3a3d-4071-8c97-79faf47d0a07.png)
The way it should be looking
![image](https://user-images.githubusercontent.com/7980381/153882633-6dfff1ed-8bf3-472c-9a7e-73379ff8549e.png)

**Describe the solution you'd like**
Making changes  in the theme that allow CSS  indentation  from Outliner to work (it may be toggle-able) or creating support of this style vertical lines in minimal itself

**Comment by kepano** [comment]
This should be requested on the Outliner plugin as it appears this way with every theme.

You can use Indentation Guides plugin for correct relationship lines
