### ISSUE TITLE
Support quote styling inside bullet list

### ISSUE THREAD

**Issue by danieltomasz** [kepano/obsidian-minimal#193]
**Is your feature request related to a problem? Please describe.**

I often make my notes in the form of hierarchical, nested bullet list.
Currently Quote in the live preview inside the bullet isn't supported:
```
- A
   -  >B
  ```

0nly 
```
-A
>B
``` 

will render `B` as quote.
**Describe the solution you'd like**
In 
```
- A
   -  >B
  ```

an option should exist to render  `>B` as quote too

**Comment by kepano** [comment]
Are you able to do this when using the default theme?

**Comment by danieltomasz** [comment]
No, now I see that this is limitation of live preview and it is currently a feature request, I am closing this issue https://forum.obsidian.md/t/live-preview-support-quotes-in-list-items/29582
