### ISSUE TITLE
Colorful Headings issue?

### ISSUE THREAD

**Issue by karbassi** [kepano/obsidian-minimal#194]
**Describe the bug**
When theme is set to one of the presets and `colorful headings` is turned on, some themes override the colorful headings styles.

This may be by design, but I wanted to make sure.

For example, if I set my theme to `Things` and set `Colorful headings` to on, the `Things` theme overrides the `Colorful headings` CSS variables.

**To reproduce**

<details>
<summary>Screenshot of settings</summary>

![SCR-20220214-j5i](https://user-images.githubusercontent.com/17738/153935468-86659c80-0318-48a3-8816-f7e7889ea97f.png)

</details>

<details>
<summary>Example</summary>

![Screen Shot 2022-02-14 at 1 49 56 PM](https://user-images.githubusercontent.com/17738/153937447-c68abe4d-258d-4452-9c60-9b63f9a2c6c6.png)

</details>

<details>
<summary>Theme CSS specificity is higher than colorful headers specificity</summary>

![Screen Shot 2022-02-14 at 2 02 21 PM](https://user-images.githubusercontent.com/17738/153937716-0c37ff95-163e-4830-97af-0e81113c14ce.png)

![Screen Shot 2022-02-14 at 2 02 26 PM](https://user-images.githubusercontent.com/17738/153937723-4f950694-8308-4e0b-b74c-ac8bf976d671.png)

</details>

**Expected behavior**
Personally, I'd like the colorful headers to override the theme headers. However, this could be subjective.

**Screenshots**
See above.

**Debug info (please complete the following information):**

<details>
<summary>Debug Info</summary>

SYSTEM INFO:
	Obsidian version: v0.13.23
	Installer version: v0.13.23
	Operating system: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 21.3.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 4
	Safe mode: off
	Plugins installed: 48
	Plugins enabled: 32
		1: Outliner
		2: Editor Syntax Highlight
		3: Day Planner
		4: Paste URL into selection
		5: Zoom
		6: Calendar
		7: Focus Mode
		8: Typewriter Scroll
		9: Advanced Tables
		10: Auto Link Title
		11: Dataview
		12: Quick Switcher++
		13: Extract Highlights
		14: Hotkey Helper
		15: Format Hotkeys
		16: Minimal Theme Settings
		17: Sliding Panes (Andy's Mode)
		18: Templater
		19: Linter
		20: Local images
		21: Natural Language Dates
		22: Recent Files
		23: Reveal Active File Button
		24: Get Info
		25: Shell commands
		26: Activity History
		27: MySnippets
		28: Folder Note
		29: Contextual Typography
		30: Hider
		31: Obsidian Tabs
		32: Style Settings

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

</details>

--- 

Now, I may be wrong on this or it could be a design/development choice to have the theme override the colorful headers choice. Let me know either way.

**Comment by kepano** [comment]
This is changed as of the latest commit.

Note that the actual Things app doesn't specify many colors and blue is the color for headings. So now the Minimal Things color scheme will fall back on the default colorful heading which is red for H1s. I expect this will cause some annoyance for some users because this is less accurate to the Things look, however it does provide the ability to customize via Style Settings.
