### ISSUE TITLE
Space between paragraphs

### ISSUE THREAD

**Issue by almandin** [kepano/obsidian-minimal#196]
Hi there,
In the default configuration of the minimal theme, there is only little space between each blocks/paragraphs (there is actualy no space at all). It would be nice to be able to adjust this space through the minimal theme plugin, or if it could be bigger by default at least.
There is a space only *before* headings. This space should, in my opinion, also be present between paragraphs. The actual workaround is to put empty lines to delimit paragraphs.

**Comment by kepano** [comment]
duplicate #360 which provides a better description with screenshots
