### ISSUE TITLE
Hashtag Pill is cut 

### ISSUE THREAD

**Issue by tim-hilde** [kepano/obsidian-minimal#197]
Since the new version (from 14.02.) tag pills are cut:

![image](https://user-images.githubusercontent.com/44113468/154066033-49d09a56-b026-488f-b479-83f1c8e50c56.png)

**Comment by kepano** [comment]
I am not able to reproduce this, but just made a small change that may help. Can you try the latest commit?

If the issue persists I need more detail:

- Which modes does this happen in? Reading vs editing vs legacy editor
- What font and font size are you using?

**Comment by tim-hilde** [comment]
It's fixed now, thanks a lot!
