### ISSUE TITLE
Citation [@author] aren't styled and are same color as the rest of the text

### ISSUE THREAD

**Issue by danieltomasz** [kepano/obsidian-minimal#199]
**Before you open a bug report**
Citations `[@cite]` are not styled (they are the same colour as the rest of the text)>
Writing an academic article is really hard without it.

**To reproduce**

**Expected behavior**
Citations `[@cite]`  will be by default styling. Citations might be the same colour but a different shade.

**Screenshots**
Vanilla obsidian
![image](https://user-images.githubusercontent.com/7980381/154185008-9f421362-1399-4fd4-ba61-f186ca5b6805.png)

Minimal theme
![image](https://user-images.githubusercontent.com/7980381/154185057-da79dacd-ed39-4e65-9f05-22a3ba70360f.png)

**Debug info (please complete the following information):**
SYSTEM INFO:
	Obsidian version: v0.13.23
	Installer version: v0.12.19
	Operating system: Darwin Kernel Version 21.4.0: Sat Jan 29 03:25:23 PST 2022; root:xnu-8020.100.417.0.4~31/RELEASE_ARM64_T8101 21.4.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Minimal Theme Settings

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Comment by kepano** [comment]
See #333

**Comment by kepano** [comment]
[@cite] is not supported as a syntax in Obsidian to date, open feature request in Obsidian Forum

**Comment by danieltomasz** [comment]
Sorry for opening the issue twice, and this is indeed a feature for Obsidian forum, thanks!
