### ISSUE TITLE
Customize Background-colour of right sidebar

### ISSUE THREAD

**Issue by Philipp5483** [kepano/obsidian-minimal#201]
**Is your feature request related to a problem? Please describe.**
Hello there, 
I am trying to built a personal high-contrast theme which has the sidebar on the left as well as the right panel with a dark background and light text, while the main window has a light background. This appears to be not possible at the moment.
Also i am running into the problem that i need the muted colour to be light to be readable in the sidebar but then it obviously disappears or becomes unreadable in the panel on the right.
![grafik](https://user-images.githubusercontent.com/91229713/154687004-ea6c01d6-c092-4868-ad77-1a0b05aad1d4.png)

**Describe the solution you'd like**

- Addition to the high-contrast setting where i can set side-bar and the right panel to have high-contrast background

**Comment by kepano** [comment]
This is an advanced use case that I am not planning to support.

I would encourage you to achieve this with a CSS snippet. You can learn about creating your own CSS snippets in the Obsidian forum: https://forum.obsidian.md/t/getting-comfortable-with-obsidian-css/133

**Comment by Philipp5483** [comment]
okay, thanks for the fast reply!
