### ISSUE TITLE
Feature Request: Adding a separate color setting for inline code blocks

### ISSUE THREAD

**Issue by yigitozgumus** [kepano/obsidian-minimal#202]
**Is your feature request related to a problem? Please describe.**
The code blocks color setting both affects the actual code block and inline version of it. (maybe its name is different I'm not sure)

For example

```kotlin
fun main(){...}
````

`testSomething()`

I generally use  inline version to define something code related. In the default theme these blocks have a red text font. In Minimal theme, I can change the code block but then non colored parts in the first one gets updated as well. Separating the two types of code blocks (if possible) would make it easier to spot those.

**Describe the solution you'd like**
Separate color setting for both code block options

**Comment by kepano** [comment]
This is already available if you go to Style Settings > Code blocks > Code text color
