### ISSUE TITLE
Sharing color schemes

### ISSUE THREAD

**Issue by abogawat** [kepano/obsidian-minimal#203]
I love the fact that we have the ability to experiment with color schemes in the theme now, but I don't see a way to share custom color schemes or find ones from the community. It would be great to have a place to find, try and share more custom color schemes.

**Comment by kepano** [comment]
See official documentation on this topic:
https://minimal.guide/Plugins/Style+Settings

Style Settings offers the option to share color schemes by using the **Import** and **Export** buttons in the top right corner of the Style Settings pane. 

Note that when using the **Export** functionality, all of your saved Style Settings preferences across all themes you've modified will be exported. You may need to edit the output to only include the styles that you want to share.

You can find and share Minimal color schemes in the [Obsidian forum thread](https://forum.obsidian.md/t/share-your-minimal-theme-screenshots-configuration/8983) or in the the [Minimal channel](https://discord.com/channels/686053708261228577/931008597557649410) on the official [Obsidian Discord](https://discord.gg/veuWUTm).

**Comment by abogawat** [comment]
Got it. Thanks!
