### ISSUE TITLE
The scroll bar is hard to grab

### ISSUE THREAD

**Issue by rduwjjnh** [kepano/obsidian-minimal#205]
The area where you can grab the sidebar to resize it is too large, it overlaps the scroll bar and makes it very hard to grab.

![2022-02-21 22_48_41](https://user-images.githubusercontent.com/79216500/155018188-287a3359-ff30-4c32-bb08-b75479b91de5.png)

**Comment by alanalvarado** [comment]
This one is very urgent to fix.

I have a gazillion of notes per folder, and with the mouse wheel is very hard to navigate through those, to collapse the folder.

Also the _attachments folder is impossible to navigate
