### ISSUE TITLE
Feature Request: Bionic-Reading Support

### ISSUE THREAD

**Issue by Duhkha8** [kepano/obsidian-minimal#209]
Hi, I simply love Minimal. Thank you for all your hard work and the value you've created. I don't know if you're familiar with Bionic-Reading (BR). I currently use Reeder app as my RSS reader and it supports BR, so this was my introduction to it. BR has become invaluable to me.

Arguably, I have minor dyslexia. **But** don't limit BR's consideration to this context. I believe everyone can experience improved, faster reading and retention, reduced eye and brain fatigue, and more. Each developer, designer, lay person I've introduced this to has both comprehended and experienced its value. The ability to control fixation, opacity, saccade, size, width, line height, letter spacing and more is what differentiates this.

https://bionic-reading.com

Is it possible to implement or support this within Minimal so users have this as a choice? It's likely that this would be primarily used for Editor font and when actively working, creating, etc. Users will probably want another font for Preview and output. The potential enhanced ability to scan, read, process text while editing/making in Obsidian would be vital for me and, I imagine, others.

With gratitude,

-John

**Comment by kepano** [comment]
I think this would be a great feature but it's not within the scope of what Obsidian themes can do. It will require a plugin to achieve this — unless there is a special font out there that can replicate this effect.

I would recommend opening a "request for plugin" on the Obsidian Forum and Obsidian Discord. You will be much more likely to attract developers if there is a bounty as well.

**Comment by Duhkha8** [comment]
Stephan,

I appreciate your response. I will submit a request. Regardless, I do hope you had a chance to explore and learn more about BR. 

Blessings,

-John

**Comment by alanalvarado** [comment]
Doesn't seems that hard, you select words, depending on the length you divide between 2, math.round or math.ceil and apply a bold style.
