### ISSUE TITLE
No ghost copy of files & folders when dragging them inside the navigation panel

### ISSUE THREAD

**Issue by alanalvarado** [kepano/obsidian-minimal#211]
**Describe the bug**
When dragging a file inside the navigation panel to move it to another folder, NO shadow element appears, so no idea where our file is being moved, anyway the class `.is-being-dragged` is applied correctly to the element we are trying to move, but if I disable Minimal, then it works correctly and obsidian creates the shadow element `div.drag-ghost`

**To reproduce**
Click over a file inside the navigation panel and keep the mouse pressed and try to drag and move a file to another folder inside obsidian.

**Expected behavior**
A shadow element to appear, so you know where you will drop your file, similar to when you drag an IMG.

**Comment by rivrwind** [comment]
I am also having this issue

**Comment by kepano** [comment]
This is now fixed as of the latest commit
