### ISSUE TITLE
Highlight color should be different from search color

### ISSUE THREAD

**Issue by kangruixiang** [kepano/obsidian-minimal#213]
Right now the highlight color of the text is the same as the search color, making it difficult to see when searching. It would be nice to have another shade/tint for differentiation. 

<img width="722" alt="image" src="https://user-images.githubusercontent.com/17035138/156202714-1b18d13c-a345-41d8-b539-8435235bcb1d.png">

**Comment by kepano** [comment]
This is fixed if you update to the latest. Note that this was only an issue in Live Preview. The latest update makes the search matches outlined, like they are in Reading view. Note that in Live Preview search works differently than in Reading view, as it doesn't offer the concept of which is the "active" search result.

See screenshot below for differences between highlight, text selection and search result

<img width="523" alt="Screen Shot 2022-03-01 at 9 04 19 AM" src="https://user-images.githubusercontent.com/10565871/156214801-302f920c-1366-4d0c-8665-e55890383418.png">

**Comment by emisjerry** [comment]
After searching, the matched text in codeblock cannot be seen.
![image](https://user-images.githubusercontent.com/131511/158016223-efa87cc0-adc3-4c64-9466-05d2b7878ce9.png)
