### ISSUE TITLE
Image grids not working on Debian

### ISSUE THREAD

**Issue by laurastephsmith** [kepano/obsidian-minimal#214]
I can't seem to make image grid work. I'm on Debian. How would I go about debugging this? Thanks!

**Describe the bug**
Images appear as usual, one under each other. This is the same in live preview and reading view.

**To reproduce**
1. Enable "Image grids" in plugin settings.
2. Create blank note.
3. Enter the following:
```
![[1200px-Cervus_elaphus_Luc_Viatour_6.jpg]]
![[Red_deer_(Cervus_elaphus)_hind.jpg]]
```

**Expected behavior**
Images appear side by side.

**Debug info**
SYSTEM INFO:
	Obsidian version: v0.13.23
	Installer version: v0.13.23
	Operating system: #1 SMP Debian 5.15.15-1 (2022-01-18) 5.15.0-3-amd64
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: none
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 14
	Plugins enabled: 2
		1: Minimal Theme Settings
		2: Contextual Typography

**Comment by kepano** [comment]
I am not able to reproduce this issue. Note that image grids do not work in Live Preview because of limitations in how Obsidian works.

Have you tried using the YAML method and do you get the same result?

```
---
cssClasses: img-grid
---
```

Can you also try restarting the app? Contextual Typography doesn't trigger on an already open note if you just installed the plugin for the first time.

**Comment by laurastephsmith** [comment]
Thanks for trying to reproduce it. I've tried restarting, and I've just tried using that YAML, but still not working. That's a shame that it can't work in Live Preview. I have been trying in reading view with this though.

I'm happy to continue debugging with you if you have any suggestions, but don't worry about it on my account, since I don't use reading view much.

**Comment by zhl111** [comment]
![image](https://user-images.githubusercontent.com/29135984/157154759-f50fe04c-2d4c-49e1-9e19-5642ac36506b.png)
Can the image arrangement only be so small? How do I make them bigger?
