### ISSUE TITLE
Possibility to have  note name as label  in the primary navigation

### ISSUE THREAD

**Issue by danieltomasz** [kepano/obsidian-minimal#216]
**Is your feature request related to a problem? Please describe.**
I would like to add some meta-notes to primary navigation.
Currently when note is added is displayed as note, not by its title
![image](https://user-images.githubusercontent.com/7980381/156981923-8dd3c45b-52cc-4259-9f3d-5f1b6676babb.png)

Note title only is visible when hoovering over titlebar of the note.

**Describe the solution you'd like**

I dont't know If this possible with current Obsidian API.
I would prefer option to display note title instead of generic "note"

**Comment by kepano** [comment]
This would have to be done as a plugin because themes cannot access the API.
