### ISSUE TITLE
Display not normal in reading mode,

### ISSUE THREAD

**Issue by zhl111** [kepano/obsidian-minimal#219]
**Before you open a bug report**
Disable plugins and snippets that could be causing a conflict. Update to the latest versions of the following, and restart Obsidian:
- Minimal Theme
- Minimal Theme Settings plugin (or Style Settings plugin, but not both)
- Contextual Typography plugin

**Describe the bug**
Display not normal in reading mode, normal in live preview。

**To reproduce**
1. I think it's the mix of graphics and text
2. Adding a blank line makes the display different, if there is a place where no blank line is added, the problem still exists
3. ![image](https://user-images.githubusercontent.com/29135984/157157419-13b3bc8b-9650-42d8-88a5-27128ad5cc8d.png)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/29135984/157156229-9656fb18-135d-4c81-8db7-ac86725e988a.png)
![image](https://user-images.githubusercontent.com/29135984/157156215-c5f85616-1b16-4b10-bb80-febdbcf11d9c.png)

**Debug info (please complete the following information):**
SYSTEM INFO:
	Obsidian version: v0.13.30
	Installer version: v0.12.3
	Operating system: Windows 10 Home China 10.0.19043
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 18
	Safe mode: off
	Plugins installed: 81
	Plugins enabled: 65
		1: Buttons
		2: Citations
		3: Clear Unused Images
		4: Convert url to preview (iframe)
		5: Dataview
		6: Diagrams
		7: Workspaces Plus
		8: Workbench
		9: Word Splitting for Simplified Chinese in Edit Mode
		10: Text expand
		11: Templater
		12: Tag Wrangler
		13: Remember cursor position
		14: Recent Files
		15: QuickAdd
		16: Reset Font Size
		17: Icon Shortcodes
		18: Hotkeys++
		19: Better footnote
		20: Obsidian Leaflet
		21: YouHaveBeenStaring
		22: Vault Statistics
		23: Admonition
		24: Advanced URI
		25: Annotator
		26: Bartender
		27: Block Reference Counter
		28: Calendar
		29: Completr
		30: Customizable Sidebar
		31: Easy Typing
		32: Editor Syntax Highlight
		33: Excalidraw
		34: Extract url content
		35: Find unlinked files and unresolved links
		36: Folder Note
		37: Fullscreen mode plugin
		38: Global Hotkeys
		39: Homepage
		40: Hotkey Helper
		41: Image Toolkit
		42: Journey
		43: Juggl
		44: Kanban
		45: Map of Content
		46: Map View
		47: Media Extended
		48: MetaEdit
		49: Metatable
		50: Mind Map
		51: Obsidian Memos
		52: Obsidian42 - BRAT
		53: Obsidian42 - Text Transporter
		54: Search on Internet
		55: Shell commands
		56: Table Extended
		57: Various Complements
		58: Auto Note Mover
		59: ZH增强编辑
		60: BookNote
		61: Dynamic Highlights
		62: Style Settings
		63: Contextual Typography
		64: Minimal Theme Settings
		65: Highlightr

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Comment by kepano** [comment]
You currently have 65 plugins enabled. Are you able to reproduce this issue in a new vault? If not can you try again by disabling plugins, or in a new vault so you can identify which plugin is causing the issue?

**Comment by zhl111** [comment]
![image](https://user-images.githubusercontent.com/29135984/157157780-bcb39e7f-f3d5-400a-a46c-f0df8fda3b7d.png)
I see, that's why.close it is ok
