### ISSUE TITLE
Editor text is invisible on mobile

### ISSUE THREAD

**Issue by ryanjamurphy** [kepano/obsidian-minimal#22]
On iPhone (iOS 14.7) and iPad (iPadOS 15 Public Beta), Obsidian Mobile 1.0.4, the editor is completely blank when using Minimal. 

I can reproduce this by creating a brand new vault and installing the minimal theme new from the in-app gallery. I'm sure it's something I'm doing, but I can't fathom what that might be!

**Comment by kepano** [comment]
Ooops. Can you grab the latest version and let me know if this is fixed?

**Comment by ryanjamurphy** [comment]
Fixed! Thanks! Mostly I'm just glad I'm not imagining things...
