### ISSUE TITLE
Question: Use of ->

### ISSUE THREAD

**Issue by MosheSteinberg** [kepano/obsidian-minimal#220]
On other themes (including Obsidian's default theme), the characters -> are brought together into a single joined arrow. This doesn't seem to happen with the minimal theme (Obsidian 0.13.30, Minimal 5.1, on Windows). Is there a reason for this? Is there a way I can make this happen?

Happy to add pictures if the description isn't clear

**Comment by kepano** [comment]
The default Obsidian theme uses the Inter font which has a ligature that displays `->` as an arrow (but only for display purposes). You can change the font in Minimal to Inter by using Minimal Theme Settings.

Alternatively you can use the Smart Typography plugin to actually convert `->` to the proper `→` arrow character
