### ISSUE TITLE
Clicking on a specific area causes the workspace to be abnormal

### ISSUE THREAD

**Issue by Johnson0907** [kepano/obsidian-minimal#222]
**Describe the bug**
Clicking on a specific area causes the workspace to be abnormal.

**To reproduce**
1. Open Obsidian Mobile
2. Click on a specific area
3. See error

**Additional information**
Obsidian Mobile: latest version
Minimal Theme: latest version
Safe Mode: On

**Screenshots**
![bug](https://user-images.githubusercontent.com/64899466/157419553-75c34a9a-5295-415b-9a54-81480eddd16d.png)

https://user-images.githubusercontent.com/64899466/157461053-0ae0171a-b9df-4e0e-a96b-d774d08fc47c.mp4

**Comment by Johnson0907** [comment]
In the default theme, there is a pin button in this location.
I guess the bug came from here.

![bug](https://user-images.githubusercontent.com/64899466/157706580-dfa77b23-716d-4f77-838d-470c34d7ab47.png)

**Comment by kepano** [comment]
This is fixed in 5.1.8
