### ISSUE TITLE
Savings and Idea alternate checkboxes not working

### ISSUE THREAD

**Issue by olivia530** [kepano/obsidian-minimal#226]
**Before you open a bug report**
Disable plugins and snippets that could be causing a conflict. Update to the latest versions of the following, and restart Obsidian:
- Minimal Theme
- Minimal Theme Settings plugin (or Style Settings plugin, but not both)
- Contextual Typography plugin

**Describe the bug**
Support for alternate checkboxes was added in the most recent Minimal update. These checkboxes include `- [S]`, for savings, and `- [I]`, for idea. However, I have found that these checkboxes do not render correctly if any text comes after them on the same line. If any text is after `- [S]`, it will render as a regular checked checkbox. If any text is after `- [I]`, it will render as an information checkbox (the same as typing `- [i]`, with a lowercase `i`). Both types of checkboxes do render as expected if no text follows them.

**To reproduce**
1. On a new line , type `- [I]` or `- [S]`
2. Add any text after this checkbox
3. Change from Editing to Reading mode (I am using the legacy editor)

**Expected behavior**
`- [S]` and `- [I]` rendering as a savings checkbox (dollar icon) and an idea checkbox (lightbulb icon), respectively.

**Comment by ScottKillen** [comment]
![2022-03-11_23-59-08](https://user-images.githubusercontent.com/1509989/158004488-907ff577-cc85-4020-bd5f-d357e0fc069d.gif)

**Comment by olivia530** [comment]
https://user-images.githubusercontent.com/90682443/158005493-ff8bf87e-5350-4695-af9c-09c6409bac35.mov

Here's a video showing the behavior described above.

**Comment by kepano** [comment]
I assume that this somehow related to a case-sensitivity issue but I cannot reproduce this on my end

**Comment by cansar** [comment]
I have this issue on iOS (it works fine on desktop), but I was able to reproduce it slightly differently. Live Preview shows the correct icons but Reader mode doesn’t. Does that help with reproducing?
