### ISSUE TITLE
change size of header font 

### ISSUE THREAD

**Issue by zzong2006** [kepano/obsidian-minimal#227]
I want to increase the size of header # 1, ## 2, ### 3 .. etc.

They are too small to see them.
<img width="101" alt="image" src="https://user-images.githubusercontent.com/12367773/158012798-ef932f7d-e420-4989-adef-7eac56592141.png">

**Comment by zzong2006** [comment]
Oh I'vs just found that I can change the size of them from css file. Never mind. 

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/12367773/158012918-9f3688c3-0896-4d1b-a6ff-26d77668e55d.png">

**Comment by kepano** [comment]
Please review the documentation. You can do this with style settings plugin.
