### ISSUE TITLE
After searching, the matched text in codeblock cannot be seen.

### ISSUE THREAD

**Issue by emisjerry** [kepano/obsidian-minimal#229]
After searching, the matched text in codeblock cannot be seen.

Steps:
1. Ctrl+F, enter the search term
2. In codeblock, the matched text cannot be read well

![image](https://user-images.githubusercontent.com/131511/158016266-1f0cf0db-2577-4171-9297-d8c18f371adc.png)

**Comment by zjph90** [comment]
I get this also
