### ISSUE TITLE
The custom check boxes are not styled in "Read" mode

### ISSUE THREAD

**Issue by ScottKillen** [kepano/obsidian-minimal#230]
**Before you open a bug report**
Disable plugins and snippets that could be causing a conflict. Update to the latest versions of the following, and restart Obsidian:
- Minimal Theme
- Minimal Theme Settings plugin (or Style Settings plugin, but not both)
- Contextual Typography plugin

**Describe the bug**
The new custom checkboxes are not styled in "Read" mode

**To reproduce**
1. Type a custom check box.
2. Click on "Read" mode
4. See the custom checkboxes lose their styling

**Expected behavior**
The custom checkboxes should maintain their styles in Read mode

**Screenshots**
![2022-03-11_23-59-08](https://user-images.githubusercontent.com/1509989/158004488-907ff577-cc85-4020-bd5f-d357e0fc069d.gif)

**Debug info (please complete the following information):**
SYSTEM INFO:
	Obsidian version: v0.13.33
	Installer version: v0.13.31
	Operating system: Windows 10 Pro 10.0.22000
	Login status: logged in
	Catalyst license: vip
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 7
	Safe mode: off
	Plugins installed: 50
	Plugins enabled: 49
		1: Admonition
		2: Advanced Tables
		3: Auto Class
		4: Bartender
		5: Better footnote
		6: Better PDF Plugin
		7: Calendar
		8: Collapse All
		9: Contextual Typography
		10: Customizable Sidebar
		11: Dataview
		12: Diagrams
		13: Dictionary
		14: Extra Markdown Commands
		15: Excalidraw
		16: Folder Note
		17: Footnote Shortcut
		18: Get Info
		19: Hider
		20: Hover External Link Plugin
		21: Hotkey Helper
		22: Icon Shortcodes
		23: Linter
		24: Natural Language Dates
		25: Note Folder Autorename
		26: Obsidian Git
		27: Obsidian42 - BRAT
		28: Open vault in VSCode
		29: Open with
		30: Pane Relief
		31: Prominent Starred Files
		32: Quick Explorer
		33: Reading Time
		34: Readwise Official
		35: Recent Files
		36: Sliding Panes (Andy's Mode)
		37: Smart Typography
		38: Style Settings
		39: Tag Wrangler
		40: Tasks
		41: Templater
		42: Wikipedia
		43: Icon Folder
		44: Minimal Theme Settings
		45: Icons
		46: Plugin Changelogs
		47: Excel to Markdown Table
		48: Codeblock Completer
		49: Obsidian Charts

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Comment by kepano** [comment]
There is probably a conflict with one of your plugins. Can you follow the steps in the bug report template? Try in a new vault without any additional plugins — or else retry by disabling plugins and re-enabling them.

**Comment by kepano** [comment]
Actually I see the issue — you have a line break between your list blocks. You should remove that as it causes issues with Markdown parsing.

**Comment by ScottKillen** [comment]
Who knew? (Obviously you. 😀 ) Thank you!

**Comment by kepano** [comment]
If you update to the latest version your example should be supported now. I am learning that this is called a "loose list" in the Markdown spec:

**Comment by ScottKillen** [comment]
Markdown is an interesting beast.
