### ISSUE TITLE
[FR] Light High Contrast on the two sidebar

### ISSUE THREAD

**Issue by Mara-Li** [kepano/obsidian-minimal#233]
I think it will be better to have the two sidebar “darker” than the left one.

![image](https://user-images.githubusercontent.com/30244939/158122209-b2e77bcb-94fc-4e0e-ae4b-ce850ca8b6d8.png)

I do this with a snippet, manually putting the color, so it's not better (the color will be killed if a change my color) than a real implementation. Maybe adding an option?
I love the high contrast option.

**Comment by kepano** [comment]
I don’t plan to add this capability. For now it is best to achieve this using snippets.
