### ISSUE TITLE
Allow a different typeface family for headings

### ISSUE THREAD

**Issue by Palingenae** [kepano/obsidian-minimal#237]
**Is your feature request related to a problem? Please describe.**
I'd like to have a different font family for my headings, in general.

**Describe the solution you'd like**
It seems that you are passing the body's font-family in the global context, with some differences, like for the UI and Code blocks.

I wish that for headings (h1..h6), you'd allow to set a different font family. 

You could implement that your prefered way.

**Comment by kepano** [comment]
This is available as of 5.2
