### ISSUE TITLE
Broken style setting

### ISSUE THREAD

**Issue by Mara-Li** [kepano/obsidian-minimal#24]
My other snippet doesn't show up in style settings. There is just Minimal. I think there is a problem with the formatting but I can't check the error for the moment.

Anyone can help me?

**Comment by Mara-Li** [comment]
Okay, I found the culprit ! It's because of the last `-` for style settings : https://github.com/kepano/obsidian-minimal/blob/c4999a75c5ab6b97466b2af18a0ecfe455f35487/obsidian.css#L4829

**Comment by kepano** [comment]
This is fixed as of 3.3.2
