### ISSUE TITLE
Task Collector misplaced checkboxes

### ISSUE THREAD

**Issue by Nemoos-0** [kepano/obsidian-minimal#240]
Using the [Task Collector](https://github.com/ebullient/obsidian-task-collector) plugin, the checkboxes are misplaced. 

I'd like to center them, but found no solution. Can you fix it?

![image](https://user-images.githubusercontent.com/52749992/159126148-9290b14e-1353-4eaf-b934-db63047b9d9d.png)

Thanks in advance.

**Comment by kepano** [comment]
This appears to be a bug with the task collector plugin as it is present in the default theme also. Please open a bug here: https://github.com/ebullient/obsidian-task-collector

**Comment by Nemoos-0** [comment]
Sorry, I wasn't clear.
I didn't mean that they are not vertically centered, but that the checkbox icon are outside the outer square.

![image](https://user-images.githubusercontent.com/52749992/159153906-57e6cc88-6c77-407c-87a3-cde787fc1622.png)

I would like the checkbox to be in the outer square.
