### ISSUE TITLE
img-grid for webp images

### ISSUE THREAD

**Issue by mordv** [kepano/obsidian-minimal#241]
I can inline `.webp` images just like any other image format. However, I wasn't able to make an `img-grid` of them. Is there some limitations so the format not supported or is the problem on my side?

**Comment by kepano** [comment]
It sounds related to this issue:

https://github.com/mgmeyers/obsidian-contextual-typography/issues/10

**Comment by mordv** [comment]
Don't see relations, it's `.webp` in my case.

**Comment by mordv** [comment]
It's exactly `.webp` in my case, no case variations.

**Comment by kepano** [comment]
It’s related in the sense that it is due to Contextual Typography not detecting the image type
