### ISSUE TITLE
(Suggestion) MacOS Big Sur like translucent titlebar support

### ISSUE THREAD

**Issue by HideOnFluff** [kepano/obsidian-minimal#244]
Hey! would it be possible to have a MacOS Big Sur like translucent titlebar option for Style Settings? for example:
![image](https://user-images.githubusercontent.com/83287502/159214008-5ab2d072-29f7-472b-923c-6e8ca33686dc.png)
![image](https://user-images.githubusercontent.com/83287502/159214182-d24c0628-cc70-4964-9ce7-af3545a245f9.png)
(themes used for examples: [Yin and Yang](https://github.com/chetachiezikeuzor/Yin-and-Yang-Theme), [California Coast](https://github.com/mgmeyers/obsidian-california-coast-theme))

**Comment by HideOnFluff** [comment]
Nevermind I found there's an option for this with it's extension lol

**Comment by kepano** [comment]
This is already supported, see documentation
