### ISSUE TITLE
Alternate checkboxes create indent on next line

### ISSUE THREAD

**Issue by rivrwind** [kepano/obsidian-minimal#245]
![](https://user-images.githubusercontent.com/48160993/159334783-35cf4b25-9805-4df6-b832-893919c9c2b2.png)
### Seeing an issue with Live Preview & the new alternate checkboxes: the line below the bulleted item has an indent.

![](https://user-images.githubusercontent.com/48160993/159335254-891e14a0-b3ac-49ae-991d-d147b3ef216c.png)
**Styled Checkbox**   
  
![](https://user-images.githubusercontent.com/48160993/159335346-1f67ba8d-93a9-4070-92df-63be431938a7.png)
**Normal Checkbox**

## EDIT
Hitting "SHIFT+TAB" then "TAB" fixes this. Or the reverse, TAB then SHIFT+TAB

**Comment by kepano** [comment]
I am not able to reproduce this issue. Please follow the instructions in the bug report template, you may have a plugin or snippet interfering.
