### ISSUE TITLE
(Suggestion) For Horizontal line above Headings

### ISSUE THREAD

**Issue by looneyapache** [kepano/obsidian-minimal#246]
Is there any possibility that we could add a horizontal line _above_ heading 

When I start a new headings, they appear to be part of previous heading 

(Also, I have been using Given theme from day one and its awesome theme, Thank you!)

![image](https://user-images.githubusercontent.com/10562851/159455538-68a0311c-94fa-4bd0-9f61-7795a4e85f6d.png)

**Comment by kepano** [comment]
This should be achieved via snippets
