### ISSUE TITLE
Search result not opened at the correct positions

### ISSUE THREAD

**Issue by tim-hilde** [kepano/obsidian-minimal#247]
When you want to open a search result within a rather long file, you don't jump to the correct place in the document. Only after several clicks it works. Disabling the theme solves this issue.

https://user-images.githubusercontent.com/44113468/159497337-2b396c14-4842-4884-9836-a2fea1c2d37e.mov

**Comment by kepano** [comment]
I don't think this is related to Minimal. I am able to reproduce the issue in the default theme.
