### ISSUE TITLE
Bullets with not aligned in Live Preview when using larger line height

### ISSUE THREAD

**Issue by sahammer** [kepano/obsidian-minimal#249]
**Describe the bug**
When in live preview editor, the bullets are not aligned - but in preview mode.. they are. This is on MacOS (debug pasted below) and I followed [your guide](https://minimal.guide/Features/macOS+configuration) to setup. I didn't make major changes using style settings - other than changing heading styles & some fonts.

Prior to opening this I saw #92 - but it doesn't seem to apply here.

**Expected behavior**
I'd expect the bullets to be aligned :)

**Screenshots**
Live Editor:
![image](https://user-images.githubusercontent.com/873622/159812630-4119b503-1e73-44f7-a350-8b48015a7c0a.png)

Preview:
![image](https://user-images.githubusercontent.com/873622/159812654-3c011be4-d95b-461c-92a2-8a19031c7927.png)

**Debug info (please complete the following information):**
SYSTEM INFO:
	Obsidian version: v0.13.33
	Installer version: v0.13.31
	Operating system: Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000 21.4.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 7
	Plugins enabled: 7
		1: Electron Window Tweaker
		2: Hider
		3: Minimal Theme Settings
		4: Paste URL into selection
		5: Style Settings
		6: Calendar
		7: Readwise Official

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Comment by kepano** [comment]
Can you provide more detail about what font and font size you are using?

**Comment by sahammer** [comment]
Sure! Currently using [Karla](https://fonts.google.com/specimen/Karla) - here's a screen of my settings:

![CleanShot 2022-03-29 at 09 45 38](https://user-images.githubusercontent.com/873622/160663566-134e3ffa-7bf9-4930-a097-ceaad4342364.png)

**Comment by sahammer** [comment]
Actually after looking at that screenshot.. I moved line height to 1.5. I don't recall changning it but I guess I did at some point. this has largely fixed the issue:

Editor view:
![CleanShot 2022-03-29 at 09 48 13](https://user-images.githubusercontent.com/873622/160664150-d85516cb-b63a-4511-9875-3863aee79e3a.png)

So... looks like I may have fixed it! One of those classic cases of calling for help, and then it fixes itself! 🤣

You should be able to close this out, unless you have any more questions 🙂

**Comment by kepano** [comment]
Got it, I am going to keep this open so that I can fix the issue for larger line height
