### ISSUE TITLE
Unable to Zoom with Ctrl + Scroll wheel

### ISSUE THREAD

**Issue by canmetan** [kepano/obsidian-minimal#25]
First of all thank you for making this amazing theme! :1st_place_medal: :+1: 

When using this theme and enabling Settings -> Appearance -> Quick font size adjustment

Using Ctrl + scroll wheel does not zoom in ( in both edit mode or preview mode ). I can use this in almost every other theme including default theme. I'm not sure if this was intended or a bug.

This is the only reason I'm not using this theme now. Would love to use it if we can change the font size with Ctrl + scroll up/down.

Edit: let me know if I can help/

**Comment by kepano** [comment]
Font sizes in Minimal can be controlled via the Minimal Theme Settings plugin. You should also be able to use the `CTRL +` and `CTRL -` hotkeys to change font sizes.

**Comment by kjentech** [comment]
Necroing this. I can't tell by your answer if you don't **want** to add this feature, but I hope you will consider adding this feature, as it would be extremely useful.

I write my notes on a 4k display. Sometimes I want to be able to "zoom out" and see the structure of my note. Sometimes, I also just like writing at different zoom levels. I do this all the time in the Default theme, and it's something that's making me reconsider Minimal as my theme of choice. Having support for ctrl-scroll would mean that I don't have those qualms any longer, and that I can use Minimal as my daily driver.

The issue with ctrl+ and ctrl- is that the entire interface is zoomed, along with interface elements, sidebars etc. It makes Obsidian an eyesore to look at, with either UI elements that are way too big or way too small.

Strangely, ctrl-scroll "works" with Minimal and the "Quick font size adjustment" option enabled under Appearance, but it's only visible after a restart of Obsidian.

Again, I hope you'll reconsider adding this option. Thanks in advance.

**Comment by kepano** [comment]
All of the ways to resize fonts work in Minimal:

- Via CMD+scroll
- Via zoom
- Via the Minimal Theme Settings hotkeys for font size

**Comment by kjentech** [comment]
Ctrl/CMD-scroll does work, but it requires a restart of Obsidian (or a CSS refresh).
Tested with and without plugins enabled.

**Comment by kepano** [comment]
Sorry I don't understand or cannot reproduce the problem. I am able to CMD+scroll to resize fonts without restarting Obsidian.
