### ISSUE TITLE
Hamburger Menu disappears on mobile after opening note

### ISSUE THREAD

**Issue by tonydiep** [kepano/obsidian-minimal#251]
**Describe the bug**
On mobile, side panel disappears after editing a note, making UI un-useable.

**To reproduce**
1. Go to any note on a mobile phone
2. Edit note
3. Close Note by tapping close current pane
4. Screen does not show hamburger menu

**Expected behavior**
Note closes. 
Hamburger menu visible to allow user to do other things.

**Screenshots**

Only three options are visible

Create new file <-- works
Go to file <-- doesn't do anything
See recent files <-- doesn't do anything

**Workaround**

Manually delete .obsidian/workspace

**Comment by kepano** [comment]
This is a feature not a bug :)

You can drag from the left side to open the menu, or use the command palette.

**Comment by tonydiep** [comment]
Dragging from the left doesn't work. I'm using Android 11 / OnePlus UI where where dragging from the left is mapped to "Go back"

There is no hamburger menu so I can't get to the command palette.

**Comment by kepano** [comment]
What you're describing sounds like an Obsidian bug. There is a 2 finger gesture to go back, 1 finger to open menu.

Obsidian mobile settings allows you to map command palette to the drag down gesture.

**Comment by tonydiep** [comment]
Ah... I see ...  how to make it work with Android swipe gestures.

If I drag from the left side of the phone I go back per regular Android swipe gestures
If I start dragging on the screen, starting some place already on the screen, but not from the left of the phone, then the side panel will appear.

If I drag from the top of the phone, I get android notifications per Android swipe gestures.
If I start dragging on the screen, starting some place already on the screen, but not from the top of the phone, then the command pallette appears.

Ok. I get it.

Love your theme. Thanks for making it.

Is there an option to make the hamburger menu always visible on mobile?

**Comment by BernardoGO** [comment]
Android 11+ gestures make it impossible to use without the hamburger menu.
Is there any way to get it back?
