### ISSUE TITLE
Inconsistent indentation on bullets with more than one line. 

### ISSUE THREAD

**Issue by Robertgreene123** [kepano/obsidian-minimal#252]
Inconsistent indentation on bullets with more than one line. 
I have tested this on a vault with only the minimal theme and no other plugins.

**Screenshots**
![Screenshot 2022-03-27 090410](https://user-images.githubusercontent.com/68683404/160268951-9c69f3ff-e179-4a0a-8152-c9eb09331fdd.png)

**Debug info (please complete the following information):**
SYSTEM INFO:
	Obsidian version: v0.14.2
	Installer version: v0.13.31
	Operating system: Windows 10 Pro 10.0.19044
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 0
	Safe mode: on

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.

**Comment by kepano** [comment]
Are you able to reproduce this with the default theme? Is this screenshot from live preview or reader mode?

**Comment by Robertgreene123** [comment]
No, the default theme works properly and that is the live preview.

**Comment by kepano** [comment]
Can you copy paste the exact source text in a code block? I am not able to reproduce

**Comment by Robertgreene123** [comment]
I am sorry I am not sure how to do that.

I also have to add that when I open another file and then return to the one with inconsistent indentation, i find that it corrects itself.

**Comment by kepano** [comment]
What you are describing sounds like a known bug with Obsidian, take a look at the forums, I believe it has been reported there

**Comment by Robertgreene123** [comment]
Oh I see in the forum it hasn't yet been fixed. Thanks for your help.
