### ISSUE TITLE
Misaligned Indentation Guides

### ISSUE THREAD

**Issue by zcysxy** [kepano/obsidian-minimal#256]
- Minimal Theme

The core Indentation Guides (relationship lines) are shifted right a little bit in the Live Preview.

<img width="786" alt="image" src="https://user-images.githubusercontent.com/48207708/161192354-1e0f1b48-a921-410b-bdde-41ff72543a6a.png">

**Comment by kepano** [comment]
I would recommend raising this issue with the Obsidian developers as this comes up with different themes, and Obsidian hasn't provided a way to adjust this yet.

**Comment by kepano** [comment]
Can you try again in 5.2 and let me know if this is improved?

**Comment by zcysxy** [comment]
In the Sandbox vault.

- Default settings: slightly to the right

<img width="720" alt="image" src="https://user-images.githubusercontent.com/48207708/167280511-03b13dd0-aea8-4220-85b9-28b6a6a82f03.png">

- Use Minimal Theme Settings and set `Body font size` to 18: perfectly aligned

<img width="720" alt="image" src="https://user-images.githubusercontent.com/48207708/167280546-d22d1d2a-3f4d-44c8-8b99-d7833d5ad315.png">

**Comment by kepano** [comment]
As of 5.2.3 there is now a Style Settings option to adjust the horizontal positioning of Indentation Guides
