### ISSUE TITLE
Minimal Theme Settings: Ability to choose accent colour in a more direct way

### ISSUE THREAD

**Issue by ernest67** [kepano/obsidian-minimal#257]
Currently, the only way to change the accent colour is to adjust the slider:
![Screenshot 2022-04-02 at 12 53 21](https://user-images.githubusercontent.com/95947701/161366886-dd75c34c-dfac-4a0c-81ea-9f4a0e80d89f.png)

It would be much better if you can add a feature to allow us to pick the colour we want in a colour wheel:
![Screenshot 2022-04-02 at 12 54 13](https://user-images.githubusercontent.com/95947701/161366908-21b8d74a-fecc-482e-936e-f705e60f65fe.png)

This is because it is hard to choose the colour you want without seeing all the colours at once.

Once again, thank you for create this amazing theme and I hope more and more people will use this theme!

**Comment by kepano** [comment]
You can do this by using the Style Settings plugin
