### ISSUE TITLE
Title Bar Icon Color Not Being set Correctly When Using the Hover Editor

### ISSUE THREAD

**Issue by briskmap4926** [kepano/obsidian-minimal#259]
**Before you open a bug report**
Disable plugins and snippets that could be causing a conflict. Update to the latest versions of the following, and restart Obsidian:

- Minimal Theme
- Minimal Theme Settings plugin
- Contextual Typography plugin

**Confirm that the bug is not present when Minimal theme is off**

**Describe the bug**
As I understand it, minimal now includes support for the Hover Editor plugin. When using the minimal theme, the hover plugin, and style settings plugin, if a "Titlebar active icon color" is set it is not used. Instead a different icon color is used. However the "Titlebar active foreground color" is applied correctly to the text in the titlebar. This used to work correctly so it seems to be an issue with a recent update. 

**To reproduce**
In the Style Settings plugin, under Hover Editor, Title Bar Icons, set the "titlebar active icon color" to a specific color. 

**Expected behavior**
The icons in the titlebar of the Hover Editor should be the color that is set using the Style Settings plugin.

**Screenshots**
For example, see this screenshot: the icons are not the color set in style settings:
<img width="494" alt="Screen Shot 2022-04-02 at 10 41 41 AM" src="https://user-images.githubusercontent.com/102869285/161390607-7a6f6e34-0fae-4315-9047-c0683d4f2196.png">

<img width="746" alt="Screen Shot 2022-04-02 at 10 42 42 AM" src="https://user-images.githubusercontent.com/102869285/161390614-28d30efd-dfe3-4511-9395-65b7ede993bd.png">

**Debug info (required):**
SYSTEM INFO:
	Obsidian version: v0.14.5
	Installer version: v0.13.31
	Operating system: Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000 21.4.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 7
	Safe mode: off
	Plugins installed: 19
	Plugins enabled: 12
		1: Minimal Theme Settings
		2: Style Settings
		3: Hider
		4: Electron Window Tweaker
		5: Icon Swapper
		6: Footnote Shortcut
		7: Dataview
		8: Pandoc Plugin
		9: Remember cursor position
		10: Icon Folder
		11: Hover Editor
		12: Quick Explorer

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Comment by kepano** [comment]
I am not sure I understand what I am looking at in your screenshot. Why is the background of the titlebar blue?

The icons themselves are intended to use the same style as the pane's titlebar action icons. However I did notice an issue with the pin icon on panes that I just fixed.

**Comment by briskmap4926** [comment]
I changed the active titlebar to blue and the active title bar text to white using style settings / Hover Editor / Title Bar Background / Foreground. That is working correctly. However when I make the color change for the icons, they do not change. It looks like they are being overriden by another icon style.

**Comment by kepano** [comment]
Hmm I am not able reproduce this issue. The icons do seem to respond to Style Settings for me. You need to use the "Icon color" setting, it seems like you are trying to use the "Icon color (active)" which is not used in this context

**Comment by briskmap4926** [comment]
Yes, I am using the "Icon color (active)" setting under the Hover Editor title bar. I don't want to change the "icon color" for everything, just for the title bar of the hover editor. 

Hmm. If the setting for the active icon color for the titlebar of the hover editor is not used in the title bar of an active hover editor, then what context is this setting for? Or why don't they simply follow the titlebar foreground color? Or is this a bug with the Hover Editor?

What's really interesting is that in another one of my Obsidian Vaults, the icons are colored correctly and it's coming from the color assigned to the titlebar:

<img width="479" alt="Screen Shot 2022-04-02 at 12 16 28 PM" src="https://user-images.githubusercontent.com/102869285/161393936-2c254e1a-1f47-4243-91db-5703491b11b3.png">
<img width="321" alt="Screen Shot 2022-04-02 at 12 16 50 PM" src="https://user-images.githubusercontent.com/102869285/161393938-2a3de32b-aae9-4c9b-b3db-70bde39a18bd.png">

**Comment by kepano** [comment]
The "active" color is used for active states such as the currently active sidebar tab. The style of the hover popover in Minimal is meant to mimic the normal pane style.

Based on the level of customization you are looking to do you should consider creating your own CSS snippet to modify these variables.

**Comment by briskmap4926** [comment]
So the titlebar active icon colors are ignored by Minimal intentionally?

**Comment by kepano** [comment]
The active icon color variable represent the active state of the button to which the icon belongs, not the active state of a pane/window. In the context of panes/popovers, the buttons don't remain active after you use them, so the active state is not used.

**Comment by briskmap4926** [comment]
I think I partially understand, but it would probably be helpful to retitle those settings so it's more clear. And I don't know if it's possible but it might reduce confusion to hide the settings for title bar icons when Minimal is the active theme because it doesn't appear to be used at all from what I can tell.

What is strange is that in one of my vaults, per the screenshot here https://github.com/kepano/obsidian-minimal/issues/259#issuecomment-1086681983 the icons do follow the titlebar color.
