### ISSUE TITLE
misalignment in outline pane

### ISSUE THREAD

**Issue by sky31even** [kepano/obsidian-minimal#260]
**Describe the bug**

Headings with sub-headings are not aligned to those w/o .... (check the screenshot below)

**Screenshots**
<img width="178" alt="image" src="https://user-images.githubusercontent.com/49628447/161406721-99a1c665-9b7f-4611-a285-8afcfdeb8ffb.png">

**To reproduce**

just copy this document in:

```
# test 0

# test 1

## test 1-1

## test 1-2
````

**Debug info (required):**

SYSTEM INFO:
	Obsidian version: v0.14.2
	Installer version: v0.14.2
	Operating system: Windows 10 Pro 10.0.22000
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 28
	Plugins enabled: 28
		1: Tag Wrangler
		2: Advanced Tables
		3: Note Refactor
		4: Smart Random Note
		5: Quick Switcher++
		6: Minimal Theme Settings
		7: 盘古
		8: Citations
		9: Footnote Shortcut
		10: Cycle through Panes
		11: Dataview
		12: Metatable
		13: File Explorer Note Count
		14: MetaEdit
		15: Quick Explorer
		16: Periodic Notes
		17: Link Archive
		18: Word Splitting for Simplified Chinese in Edit Mode
		19: Editor Syntax Highlight
		20: Better Word Count
		21: Hypothes.is
		22: Icon Folder
		23: Excalidraw
		24: Recent Files
		25: Obsidian Git
		26: Media Extended
		27: Media Extended BiliBili Plugin
		28: Contextual Typography

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Comment by kepano** [comment]
This should be fixed in the latest commit
