### ISSUE TITLE
A gap appears at the top published in obsidian publish.

### ISSUE THREAD

**Issue by ndoii** [kepano/obsidian-minimal#261]
There were no bugs until Minimal 3.3.3.
Now the latest version, 5.1.8, shows gaps.

Firefox and Safari on Mac and Safari on iPhone also show the gap.

After inspecting the CSS, the gap no longer appears after removing the following statement

body:not(.hider-frameless):not(.is-fullscreen):not(.is-mobile) {
  --titlebar-height: 28px;
  padding-top: var(--titlebar-height)!important
}

Is this a bug? I don't see any practical problem, but it bothers me, so if it is possible to fix it, I would like to have it addressed.

Translated with www.DeepL.com/Translator (free version)

**Comment by kepano** [comment]
Minimal does not support Publish yet and is not licensed for that usage. A version of Minimal for Publish will be available soon
