### ISSUE TITLE
Bullets and Indention Guides are Not Aligned

### ISSUE THREAD

**Issue by icheft** [kepano/obsidian-minimal#265]
### **Describe the bug**
The alignment of ordered and unordered lists is a bit off both in reading mode and editing mode. 

In editing mode, unordered lists (bullets) are slightly shifted to the right; in reading mode, the relationship lines (indention guides) are shifted to the right. 

### **Expected behavior** and **Screenshots**

|mode|default theme|minimal theme|
|---|---|---|
|editing mode|![image](https://user-images.githubusercontent.com/40349202/161704540-eaf80120-df34-403b-8116-3d8cb2b4281b.png)|![image](https://user-images.githubusercontent.com/40349202/161704592-e1ebf21f-746d-4c96-bb46-27568c98ed7b.png)|
|reading mode|![image](https://user-images.githubusercontent.com/40349202/161704329-66d4a2e8-5f48-45e3-a927-cc830273c354.png)|![image](https://user-images.githubusercontent.com/40349202/161704412-db7d3889-7f9d-4937-a1b4-689e3507de66.png)|

\* Please ignore the red underlines

### **Debug info (required):**
```
SYSTEM INFO:
	Obsidian version: v0.14.2
	Installer version: v0.14.2
	Operating system: Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 21.4.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 1
	Safe mode: off
	Plugins installed: 15
	Plugins enabled: 14
		1: Dynamic Table of Contents
		2: Advanced Tables
		3: Style Settings
		4: Code Editor Shortcuts
		5: Tag Wrangler
		6: Ozan's Image in Editor Plugin
		7: LanguageTool Integration
		8: Linter
		9: Typewriter Scroll
		10: Paste URL into selection
		11: Folder Note
		12: Advanced Cursors
		13: Excalidraw
		14: Minimal Theme Settings

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.
```

**Comment by kepano** [comment]
Have you reviewed any reports of this in the Obsidian Forum? Now that this feature has been brought into the core it seems that there are issues across fonts with keeping this consistent in all modes. It seems like a functionality that Obsidian will need to advise on.

**Comment by icheft** [comment]
I've been experimenting the usage with other themes, it seems like some themes (e.g. [California Coast](https://github.com/mgmeyers/obsidian-california-coast-theme)) aren't affected by this.

**Comment by icheft** [comment]
Also, I wonder if the followings are intent designs:

+ When adding a list item, the spacing between the item and the left border is quite noticeable.
+ When adding a block quote within a list item, the alignments for other sub-items are way off

|Function|Minimal| Atom | Default|
|---|---|---|---|
|List editing|![image](https://user-images.githubusercontent.com/40349202/162607050-6d67be57-22c2-4fdb-9057-eefad069fe28.png)|![image](https://user-images.githubusercontent.com/40349202/162607216-c5e8767b-1945-4bc1-9b69-7afb7cabed8c.png)| ![image](https://user-images.githubusercontent.com/40349202/162607227-3313b381-01fc-452d-9995-d69452acf09d.png)|
|Blockquote within list item|![image](https://user-images.githubusercontent.com/40349202/162607349-60798630-537b-4a2a-9a4c-b0ece31696c6.png)|![image](https://user-images.githubusercontent.com/40349202/162607379-942711df-7497-46d6-9398-05b0d0739152.png)|![image](https://user-images.githubusercontent.com/40349202/162607386-4ab23a7d-dc34-43d5-ab30-3cca09ba0459.png)|

Thanks for the theme anyway! Besides the little things mentioned, the design is still my go-to.
