### ISSUE TITLE
Allow adjustment of paragraph spacing

### ISSUE THREAD

**Issue by theThought** [kepano/obsidian-minimal#266]
I use Obsidian, amongst other things for writing documents.  Today I have to double return to create paragraph spacing.  This causes an issue when publishing either to the web or to Word where paragraph spacing is a formatting setting not a physical blank paragraph.

Could you implement an option to control paragraph spacing (effectively padding-bottom) after text and headings

**Comment by kepano** [comment]
Do you mean in live preview or reading view, or both?

**Comment by theThought** [comment]
Both, although preview is more important.

**Comment by kepano** [comment]
So I just made a little snippet for you that you can install and will automatically give you a new option to do this in Style Settings
https://gist.github.com/kepano/7b1011cfd730512edaad0849498cadcc

However this is likely going to lead to unexpected bugs. The problem with adding padding this way, is that it can mess with the way that Obsidian calculates your position on the page, e.g. when switching between editing/reading, when scrolling down to a search result, etc.

Overall I would say this isn't a Minimal-specific thing. You can get help from other community members on the Obsidian Forum or Discord
