### ISSUE TITLE
[Mobile] Duplicate name of vault in the mobile version

### ISSUE THREAD

**Issue by ivanmood0** [kepano/obsidian-minimal#267]
Duplicate name of vault in the mobile version, and also the style of writing differs (in the desktop version capital letters are used unlike mobile).

![obss](https://user-images.githubusercontent.com/79835684/162285077-2e1a6c31-ffb6-46b0-b7ba-1546ae7c6e1d.png)

**Comment by kepano** [comment]
This is fixed now
