### ISSUE TITLE
Specific tables on a page as cards

### ISSUE THREAD

**Issue by gmakstutis** [kepano/obsidian-minimal#269]
At present, as far as I can see, we can only apply Card formatting to all the tables on a page.

Could there be a way to have only specific tables get formatted as Cards? This would be ideal for things like 'dashboards' where you might be displaying multiple types of content through different dataviews (some as 'tables' others as 'cards').

If there is a way to already do this, I've not been able to determine it.

Thanks

**Comment by kepano** [comment]
This is a limitation of Dataview, not Minimal. See https://github.com/blacksmithgu/obsidian-dataview/issues/675
