### ISSUE TITLE
Bug: File name invisible when renaming note with colorful active states enabled

### ISSUE THREAD

**Issue by lguenth** [kepano/obsidian-minimal#271]
**Describe the bug**
When "Colorful active states" is enabled in the Minimal Settings plugin, renaming a note through the file explorer is not possible. The text becomes indistinguishible from the background color, effectively making the name invisible while editing.

I temporarily fixed it with this snippet:
```css
.nav-file-title-content.is-being-renamed, .nav-folder-title-content.is-being-renamed {
    color: var(--text-normal);
}
```

**To reproduce**
1. Enable "colorful active states" in Minimal Settings plugin
2. Try to rename note in file explorer

**Expected behavior**
Text should be visible, i.e. different from the background color

**Screenshots**
*Light mode (my own screenshots)*

![220415_163100_screenshot](https://user-images.githubusercontent.com/69049131/163584053-46126731-2aa8-4052-b44b-a0ac6fe34431.png)
![220415_163052_screenshot](https://user-images.githubusercontent.com/69049131/163584148-58b03937-6422-4746-93b4-926d4021142f.png)

*Dark mode (taken from [Discord](https://discord.com/channels/686053708261228577/931008597557649410/964445553364701225))*

![](https://cdn.discordapp.com/attachments/931008597557649410/964445552836243486/CleanShot_2022-04-15_at_15.34.562x.jpg)
![](https://cdn.discordapp.com/attachments/931008597557649410/964445631894650910/CleanShot_2022-04-15_at_15.42.272x.jpg)
![](https://cdn.discordapp.com/attachments/931008597557649410/964445729475158047/CleanShot_2022-04-15_at_15.42.452x.jpg)

**Debug info (required):**
```
SYSTEM INFO:
	Obsidian version: v0.14.6
	Installer version: v0.14.2
	Operating system: #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022 5.13.0-39-generic
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 5
	Safe mode: off
	Plugins installed: 50
	Plugins enabled: 24
		1: Divide & Conquer
		2: Admonition
		3: Auto Link Title
		4: Completr
		5: Dataview
		6: Dynamic Highlights
		7: Footnote Shortcut
		8: Hover Editor
		9: Linter
		10: Minimal Theme Settings
		11: Sliding Panes (Andy's Mode)
		12: Obsidian Git
		13: Supercharged Links
		14: Breadcrumbs
		15: Creases
		16: Kanban
		17: Obsidian42 - BRAT
		18: QuickAdd
		19: Reveal Active File Button
		20: Rollover Daily Todos
		21: Style Settings
		22: Smarter Markdown Hotkeys
		23: Tag Wrangler
		24: Templater

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.
```

**Comment by kepano** [comment]
This is fixed as of the latest commit

**Comment by lguenth** [comment]
Brilliant, thank you!
