### ISSUE TITLE
No differentiation between backlinks(obsidian) and external links

### ISSUE THREAD

**Issue by Paramstr** [kepano/obsidian-minimal#273]
So currently when editing the style settings, the "Link-Colour" changes the colour for both backlinks and external links. 

**Describe the solution you'd like**

Seeing as they are pretty distinct from each other, would be good if we could have seperate style options for each.

**Comment by kepano** [comment]
Closed in [Minimal 6.1.0](https://github.com/kepano/obsidian-minimal/releases/tag/6.1.0)
