### ISSUE TITLE
Tags are not aligned with regular text

### ISSUE THREAD

**Issue by ppasquet** [kepano/obsidian-minimal#275]
**Before you open a bug report**
Disable plugins and snippets that could be causing a conflict. Update to the latest versions of the following, and restart Obsidian:

- Minimal Theme
- Minimal Theme Settings plugin
- Contextual Typography plugin

**Confirm that the bug is not present when Minimal theme is off**

<img width="92" alt="Screen Shot 2022-04-21 at 11 03 16 AM" src="https://user-images.githubusercontent.com/80340281/164487881-41ec7794-7b7e-4813-96ec-9c52806f7469.png">

**Describe the bug**
Tags are not aligned with regular text
<img width="116" alt="Screen Shot 2022-04-21 at 11 03 33 AM" src="https://user-images.githubusercontent.com/80340281/164488040-f772433b-1627-4425-85f2-2765703a11d0.png">

**To reproduce**
Insert a tag (prefexing `#`) within a regular text line

**Expected behavior**
Tag and texts should be aligned

**Screenshots**
Attached above

**Comment by kepano** [comment]
Try the new plain tag option in 5.2
