### ISSUE TITLE
Graph links are barely visible in dark mode

### ISSUE THREAD

**Issue by memeplex** [kepano/obsidian-minimal#279]
**Before you open a bug report**
Disable plugins and snippets that could be causing a conflict. Update to the latest versions of the following, and restart Obsidian:

- Minimal Theme
- Minimal Theme Settings plugin
- Contextual Typography plugin

**Confirm that the bug is not present when Minimal theme is off**

**Describe the bug**

There is almost no contrast between links and background in dark mode:

<img width="403" alt="image" src="https://user-images.githubusercontent.com/2845433/166582325-76baeb60-8520-47fd-8568-da1b855dc2fa.png">

**To reproduce**
Provide steps to reproduce the behavior

**Expected behavior**

I'm able to see links at normal brightness (not 100%!).

**Screenshots**
If applicable, add screenshots to help explain your problem

**Debug info (required):**
Paste your debug info below, which can be accessed in Obsidian with Ctrl/Cmd-P, enter "Show debug info", and click "Copy to clipboard"

SYSTEM INFO:
	Obsidian version: v0.14.6
	Installer version: v0.14.6
	Operating system: Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 20.6.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 5
	Plugins enabled: 5
		1: Calendar
		2: Outliner
		3: Obsidian Git
		4: Minimal Theme Settings
		5: Spaced Repetition

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Comment by DitchComfort** [comment]
You can very easily fix this with a custom CSS.

**Comment by memeplex** [comment]
I'm aware but I still don't think this lack of contrast is desirable OOTB.

**Comment by kepano** [comment]
I am making a change to slightly increase contrast in the next version of Minimal, however I think one of the issues is that you have the line thickness set to very thin in the Graph > Display preferences.

**Comment by kepano** [comment]
Fixed in 5.2
