### ISSUE TITLE
Grabber icon

### ISSUE THREAD

**Issue by mnvwvnm** [kepano/obsidian-minimal#280]
**Minimal 5.1**
**Obsidian 0.14.6**

Style Settings > Minimal > Title bar > option **Always show grabber icon** on

In the case presented in the image below, with **Title alignment** option in _Left_ we have this:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/22862501/166592786-a0b7dd45-9477-4f36-8c70-0b1cacaee640.png">

With **Title alignment** option in _Text body_ we have this (grabber icon behind the title in the first pane):

<img width="600" alt="image" src="https://user-images.githubusercontent.com/22862501/166595061-a9ab5ec4-6894-41d7-afb3-a3d02f3da48f.png">

We found the same behavior in the title bar inside a new pane of the _Hover Editor_:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/22862501/166599000-4e6ddd20-5f89-417b-b517-dbd40588146b.png">

Actually, grabber icon seems to be unnecessary in hover editor (or a separated option to remove it).

Thanks

**Comment by kepano** [comment]
This should be fixed in 5.2, can you check? I think the grabber icon is still relevant for the hover editor because it can be used to drag the popup into a pane

**Comment by mnvwvnm** [comment]
Hi @kepano.
After a fast check, I think the issue is solved.
And you're right about the grabber in hover editor. I'm a newbie in this plugin and I didn't know that we could use the drag to place the "window" in the pane. :)
Thank you.
