### ISSUE TITLE
Support for Obsidian Reminder Plugin 

### ISSUE THREAD

**Issue by DitchComfort** [kepano/obsidian-minimal#282]
Is it possible to support/make a better experience when using Minimal and the Reminder plugin? I’m mostly talking about styling etc. It doesn’t really fit the rest of the beautiful theme, IMO.

![957E260D-39E1-4254-A2F4-F25AEB4DD9B4](https://user-images.githubusercontent.com/77794110/166662290-aec7b044-f240-45c9-9de3-74d74b254a17.jpeg)

**Comment by ronrdev** [comment]
I also use the reminder plugin. This is a duplicate posting. See #127 
https://github.com/kepano/obsidian-minimal/issues/127
Also #147 https://github.com/kepano/obsidian-minimal/issues/147

**Comment by kepano** [comment]
Added in 5.2.7

**Comment by kepano** [comment]
Added in 5.2.7
