### ISSUE TITLE
table-wide, table-max, table-100 not work with dataviewjs.

### ISSUE THREAD

**Issue by may3rd** [kepano/obsidian-minimal#284]
**Is your feature request related to a problem? Please describe.**
I have tried table-wide, table-100, and table-100 but not working with table generated by dataviewjs.
It works on dataview TABLE but not dataviewjs dv.table().

Could you please make it works or guide me how to.

**Comment by kepano** [comment]
Fixed in 5.2.8
https://github.com/kepano/obsidian-minimal/releases/tag/5.2.8
