### ISSUE TITLE
Enhancement: Display multi-line long text for dataview table

### ISSUE THREAD

**Issue by MugenLee** [kepano/obsidian-minimal#285]
hello kepano
mini is an awesome theme, I've been using it for a long time

Recently I've improved my note-taking method and will often use dataview to capture long text

I found that the mini theme simplifies the styles in the dataview table:
1. Remove unordered list
2. Remove the forced line break

I can understand the simplification of the mini, but it can be very confusing for the presentation of long texts
like this: 
![image](https://user-images.githubusercontent.com/91043731/167233442-b19a96b9-a953-4be1-b97e-a7ccd4aeb95a.png)

![image](https://user-images.githubusercontent.com/91043731/167233433-152e479e-c880-486e-b09a-e5eec489f109.png)

There are two solutions I can think of (only just for someone,)
1. Can I use css snippet to open the unordered list of the dataview table and force line breaks?
like this:
![image](https://user-images.githubusercontent.com/91043731/167233637-d5006468-bc32-4be4-abf0-c945d6dafe63.png)

2. Can the width of the DataViewtable be pulled to the widest in real-time preview mode, and can the unordered list style be added at the same time?
like this:
![image](https://user-images.githubusercontent.com/91043731/167233737-0764f245-e932-436b-b916-96049638d8c1.png)

This could affect my entire workflow

Looking forward to your reply
@kepano 
good luck

**Comment by kepano** [comment]
You can turn off trimming Dataview columns in Minimal Theme Settings

**Comment by MugenLee** [comment]
> You can turn off trimming Dataview columns in Minimal Theme Settings

Yes, I opened it, and I just replaced the new v5.2 with the mini to support the Live preview mode "table-max", this problem has been solved.

thank you very much~

Another small question is, if I want to display the Unordered Lists style in the dataview-table, what should I do? Can you give me a hint?
