### ISSUE TITLE
Configuring Minimal theme's bold formatting to 'look like' the default Obsidian bold formatting.

### ISSUE THREAD

**Issue by JacobOllivier** [kepano/obsidian-minimal#286]
**Is your feature request related to a problem? Please describe.**
I'm loving the Minimal theme and how easily customized it is, but I've noticed it's almost impossible for me to see bold formatting in the theme. Googling online I haven't found anyone else mentioning this, but the differences between Minimal and vanilla obsidian seem stark:

![image](https://user-images.githubusercontent.com/64910635/167236577-67715c3d-5d73-4882-8991-dfa99a3f3c8f.png)
![image](https://user-images.githubusercontent.com/64910635/167236620-d01c5034-f778-498a-b0bf-d3f75f1a4138.png)

There may also be a way to do this that I haven't found. I tried messing with bold-text-weighting but that didn't really do anything to get it closer to the vanilla look.

**Comment by kepano** [comment]
You can change the bold weight by going to Style Settings > Minimal > Text

Try larger numbers like 700 or 800. It will also depend on the font you are using. Obsidian default font is Inter
