### ISSUE TITLE
The edge of the callout is out of bounds

### ISSUE THREAD

**Issue by Quorafind** [kepano/obsidian-minimal#288]
**Before you open a bug report**
Disable plugins and snippets that could be causing a conflict. Update to the latest versions of the following, and restart Obsidian:

- Minimal Theme
- Minimal Theme Settings plugin
- Contextual Typography plugin

**Confirm that the bug is not present when Minimal theme is off**

**Describe the bug**

After 0.5.2 of minimal theme, callout's edge is out of bounds

**To reproduce**

1. Insert Callout; 
2. Use LP mode.

**Expected behavior**
The edge is inbound.

**Screenshots**
![image](https://user-images.githubusercontent.com/13215013/167279604-c7088286-a488-4e95-8922-ae37df4094a7.png)

And in the default theme:

![image](https://user-images.githubusercontent.com/13215013/167279780-a316dc1f-7412-4397-a53d-b5140756efa7.png)

![image](https://user-images.githubusercontent.com/13215013/167279844-fbe31606-73e0-4557-86d9-726f33400c80.png)

**Debug info (required):**

```
SYSTEM INFO:
	Obsidian version: v0.14.9
	Installer version: v0.14.6
	Operating system: Windows 10 Pro for Workstations 10.0.19043
	Login status: logged in
	Catalyst license: vip
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: none
	Snippets enabled: 2
	Safe mode: off
	Plugins installed: 45
	Plugins enabled: 9
		1: Natural Language Dates
		2: Dataview
		3: Hover Editor
		4: Obsidian42 - BRAT
		5: Theme Design Utilities
		6: Omnisearch
		7: Corkboard
		8: Obsidian Memos
		9: Periodic Notes

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.
```

**Comment by aidenlx** [comment]
related: when editor width is smaller than `var(--line-width)`, the callout will be trimmed: 

### editor

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/31102694/167280232-b63d9364-adb8-4a71-9ef8-b506231f02b4.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/31102694/167280263-4f0cf79a-20e9-408e-b2be-ac276cda4de3.png">

### preview
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/31102694/167280250-6910f53c-7a6b-4f8e-9d8a-ba74b499b0b1.png">

**Comment by aidenlx** [comment]
the following css snippet can fix the issues above: 
```css
.is-live-preview.is-readable-line-width .cm-embed-block.cm-callout > div {
  width: auto !important;
  padding-left: 0;
}
.is-live-preview.is-readable-line-width .cm-embed-block.cm-callout {
  max-width: var(--max-width);
  margin: 0 auto !important;
}
```

**Comment by kepano** [comment]
This is fixed in the latest

**Comment by Quorafind** [comment]
![image](https://user-images.githubusercontent.com/13215013/167281751-d9cec090-0ea4-4366-8d38-ff65be670fcb.png)

Seems like gutter things is influenced now, like the number of line

**Comment by kepano** [comment]
I am not sure I understand what you mean. If you mean that the line numbers have moved to the left, yes that is intentional. See release notes for 5.2. If you mean that line numbers are skipped, that is a behavior of Obsidian present in the default theme.
