### ISSUE TITLE
Rendered code blocks dedented in live preview mode

### ISSUE THREAD

**Issue by Triquetra** [kepano/obsidian-minimal#289]
**Before you open a bug report**
Disable plugins and snippets that could be causing a conflict. Update to the latest versions of the following, and restart Obsidian:

- Minimal Theme
- Minimal Theme Settings plugin
- Contextual Typography plugin

**Confirm that the bug is not present when Minimal theme is off**

**Describe the bug**
With minimal theme active, rendered code blocks (including DataView, Tasks, and in-built queries) are dedented in live preview mode. If unrendered (e.g. Tasks block while Tasks plugin is not enabled), code block is no longer dedented in live preview mode. 

Rendered code blocks are properly aligned in reading mode.

Other themes, including the default theme, render properly in all modes.

This behavior was not happening prior to Minimal 5.2.0

**To reproduce**
Update to Minimal 5.2. Enable Minimal theme. Open document with valid code block in live preview mode.

**Expected behavior**
Rendered code block properly aligned with other content

**Screenshots**
Live Preview Mode:
![Minimal 5 2 0 LP mode](https://user-images.githubusercontent.com/195027/167285920-afa353d8-0a80-4b6c-9d46-617e17c297d6.png)

Reading Mode:
![Minimial 5 2 0 Reading Mode](https://user-images.githubusercontent.com/195027/167285929-8c9d1d0b-9c4f-456f-a640-a2e9b212e107.png)

**Debug info (required):**
SYSTEM INFO:
	Obsidian version: v0.14.6
	Installer version: v0.14.6
	Operating system: Windows 10 Pro 10.0.22000
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 2
	Safe mode: off
	Plugins installed: 32
	Plugins enabled: 27
		1: Minimal Theme Settings
		2: Contextual Typography
		3: Dynamic Table of Contents
		4: Advanced Cursors
		5: Advanced Tables
		6: Calendar
		7: Style Settings
		8: Dataview
		9: Emoji Toolbar
		10: File Tree Alternative Plugin
		11: Full Calendar
		12: Linter
		13: Local REST API
		14: Natural Language Dates
		15: Outliner
		16: Periodic Notes
		17: QuickAdd
		18: Remember cursor position
		19: Smart Typography
		20: Smarter Markdown Hotkeys
		21: Sortable
		22: Sliding Panes (Andy's Mode)
		23: Tag Wrangler
		24: Tasks
		25: Templater
		26: Vale
		27: Workspaces Plus

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Comment by dancemonkey** [comment]
This issue also happens in Live Preview on mobile (iOS in my case). Code blocks are not conforming to line width settings in live preview mode. They are also running off the edge of the window in mobile LP.

**Comment by kepano** [comment]
Can you test 5.2.2 and let me know if this is improved?

**Comment by laawn** [comment]
@kepano Still not working for me on desktop or mobile for 5.2.2

**Comment by kepano** [comment]
This should now be fixed in 5.2.3

**Comment by chodorowicz** [comment]
For me tables are still _dedented_ on 5.2.3

![image-2022-05-09-vsx3RIhg](https://user-images.githubusercontent.com/119451/167318076-cf66b29e-8be5-4ae9-b09b-3c61debe7de1.jpg)

![image-2022-05-09-EDWPfUUS](https://user-images.githubusercontent.com/119451/167318083-b4e76493-5987-4f07-9dcb-1335ef618b7e.jpg)

**Comment by kepano** [comment]
@chodorowicz please open a new issue with more detail about your configuration

- Is Readable line length on?
- Is Minimal Theme Settings on?
- Is Contextual typography on?

**Comment by Triquetra** [comment]
Thank you kepano for the awesome theme and quick fix! 5.2.3 seems to have fixed my issues. Code blocks are properly aligned in LP. Incidentally, tables are also properly aligned for me in 5.2.3, but I may have another extension that affects table alignment...
