### ISSUE TITLE
Left sidebar not accessible in Android

### ISSUE THREAD

**Issue by Chriswaterguy** [kepano/obsidian-minimal#29]
The top left hamburger menu is completely missing in Android. 

The only way I could open the left sidebar was indirectly, via the command palette. 

Device: Nokia 5.3 (Android One) running Android 11.

**Comment by kepano** [comment]
This is intentional to give more space to the title bar. You can swipe from the left side to access the sidebar.

**Comment by Chriswaterguy** [comment]
Yes, thanks – I just worked this out then saw your reply. Makes good sense.

If there's a way of giving this suggestion when someone first tries it in Android, it might be helpful.

**Comment by hsiktas** [comment]
> This is intentional to give more space to the title bar. You can swipe from the left side to access the sidebar.
> […](#)
> On Sep 20, 2021, at 00:08, Chriswaterguy ***@***.***> wrote: ﻿ The to left hamburger menu is completely missing in Android. The only way I could open the left sidebar was indirectly, via the command palette. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Is it possible to add an option for this? Swiping from the side of a screen might be troublesome with some bulkier phone cases.

**Comment by kepano** [comment]
> > This is intentional to give more space to the title bar. You can swipe from the left side to access the sidebar.
> 
> Is it possible to add an option for this? Swiping from the side of a screen might be troublesome with some bulkier phone cases.

You can swipe anywhere on screen as long as you drag from left to right. The current set up is much more accessible for right handed users than reaching in the top left corner.

**Comment by hsiktas** [comment]
> You can swipe anywhere on screen as long as you drag from left to right. Unless I'm missing something, it seems like the current set up is much more accessible for right handed users than reaching in the top left corner?

You are right! I didn't even notice this. 😀
