### ISSUE TITLE
5.2. issues

### ISSUE THREAD

**Issue by tim-hilde** [kepano/obsidian-minimal#290]
After updating to 5.2 I noticed a few changes which seem to be bugs, but I'm not quite sure. First, the gutter is too much on the left resulting in a big distance between lapels and headings. Second, the edit buttons of code blocks are also in the gutter now. Is this expected behavior? And last, the backlinks section in the document is max width – I'm not sure if this is desired, but personally, I think it looks off.

I'm on insider 0.14.19 and newest minimal theme, as well as the corresponding plugins

![SCR-20220508-d24](https://user-images.githubusercontent.com/44113468/167286402-e2f305a6-86a9-4bf9-b2c4-5c980029da64.png)

**Debug info (required):**
SYSTEM INFO:
	Obsidian version: v0.14.9
	Installer version: v0.14.6
	Operating system: Darwin Kernel Version 21.4.0: Fri Mar 18 00:47:26 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T8101 21.4.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 27
	Safe mode: off
	Plugins installed: 57
	Plugins enabled: 57
		1: Divide & Conquer
		2: Advanced Mobile Toolbar
		3: Better footnote
		4: BibNotes Formatter
		5: Calendar
		6: Citation Style Translation
		7: Typewriter Scroll
		8: Code block from selection
		9: Convert url to preview (iframe)
		10: Creases
		11: Quick Switcher++
		12: Dataview
		13: Garble Text
		14: Hotkey Helper
		15: Hotkeys++
		16: Lapel
		17: Metadata Extractor
		18: Natural Language Dates
		19: Advanced Slides
		20: Advanced URI
		21: Apply Patterns
		22: Contextual Typography
		23: Copy Block Link
		24: Dictionary
		25: Dynamic Highlights
		26: Dynamic Table of Contents
		27: Electron Window Tweaker
		28: Focus Mode
		29: Obsidian Git
		30: Hider
		31: Hotkeys for templates
		32: Hover Editor
		33: Obsidian Link Converter
		34: Minimal Theme Settings
		35: Pandoc Plugin
		36: Quiet Outline
		37: Regex Find/Replace
		38: Smart Typography
		39: Sortable
		40: Style Settings
		41: System Dark Mode
		42: Tabout
		43: Obsidian Tabs
		44: Version History Diff
		45: Zotero Desktop Connector
		46: Obsidian42 - BRAT
		47: Omnisearch
		48: Pane Relief
		49: Periodic Notes
		50: Plugin Changelogs
		51: Advanced Tables
		52: Templater
		53: Workspaces Plus
		54: Block Reference Counter
		55: Pandoc Reference List
		56: Admonition
		57: Markdown Table Editor

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Comment by kepano** [comment]
Backlinks pane should be fixed now. The gutter is now left aligned intentionally, [see release notes](https://github.com/kepano/obsidian-minimal/releases/tag/5.2.0).
