### ISSUE TITLE
Default UI font no longer loads on Obsidian for iPadOS

### ISSUE THREAD

**Issue by jonathan2384** [kepano/obsidian-minimal#292]
<details>
**Before you open a bug report**
Disable plugins and snippets that could be causing a conflict. Update to the latest versions of the following, and restart Obsidian:

- Minimal Theme (Done)
- Minimal Theme Settings plugin (Not Installed)
- Contextual Typography plugin (Not Installed)

**Confirm that the bug is not present when Minimal theme is off**
Fonts for all other themes work, including the built-in one and “Things”.
</details>

**Describe the bug**
On Obsidian for iPadOS, the default font used for Minimal no longer loads. Instead, a placeholder font (likely Times New Roman) is used for the UI font. However, the text font (what the user types) appears to be untouched.

Other themes do not appear to exhibit this behavior.

**To reproduce**
Update to the latest version of Obsidian for iOS/iPadOS and install the Minimal Theme from the Community Theme Manager.

The font should show as Times New Roman - I recall that on previous versions of Minimal, a non-TimesNewRoman font was used. This seems to be a bug caused in the latest version. I’m also using Obsidian on a brand-new install, with no other settings modified or plugins installed.

**Expected behavior**
I expected the Minimal default font to be displayed, instead of Times New Roman.

**Screenshots**

![IMG_0027](https://user-images.githubusercontent.com/93066841/167308606-8f5e4eb5-c664-4dde-bbed-4bc63f08b8a4.png)
*On Minimal, the font appears to be Times New Roman.*

![IMG_0028](https://user-images.githubusercontent.com/93066841/167308563-919dd8ff-1bc3-467f-a1d3-35f23d5b3488.png)
*The default Obsidian theme does not exhibit the font issue.*

![IMG_0029](https://user-images.githubusercontent.com/93066841/167308565-38e635e9-d53f-49b3-8008-b6e0917bdde6.png)
*Nor does another theme, Things.*

**Debug info (required):**
Paste your debug info below, which can be accessed in Obsidian with Ctrl/Cmd-P, enter "Show debug info", and click "Copy to clipboard"

```
SYSTEM INFO:
	Operating system: ios 15.4.1 (Apple iPad)
	Login status: not logged in
	Live preview: on
	Legacy editor: on
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Safe mode: on

RECOMMENDATIONS:
	Update installer: installer version too low, please download from https://obsidian.md/download and reinstall.
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
```

**Comment by kepano** [comment]
Which version of the app are you using? You can see it in About > Settings

I believe this will be resolved if you update to the latest insider build, but I will issue a fix soon for reverse compatibility.

**Comment by jonathan2384** [comment]
> Which version of the app are you using? You can see it in About > Settings
> 
> I believe this will be resolved if you update to the latest insider build, but I will issue a fix soon for reverse compatibility.

Thanks for the fast reply - the About page indicates that I’m in 1.2.0, API 0.14.2.

**Comment by kepano** [comment]
Do you have the Minimal Theme Settings plugin turned on? If not does everything work correctly when you turn it on?

**Comment by kepano** [comment]
This is fixed if you update to the latest
