### ISSUE TITLE
Colorful active state does not respect accent color set in Style Settings

### ISSUE THREAD

**Issue by ScottKillen** [kepano/obsidian-minimal#293]
## Description

When the 'Colorful Active State' feature is active, the theme does not use the accent color set in the 'style settings' plugin to color the active state.

## Steps to reproduce

1. Configure Obsidian to use a dark mode theme.
2. In 'Minimal Theme Settings' select a dark mode color scheme.
3. In 'Minimal Them Settings' activate the 'Colorful active states' feature.
4. Set an accent color in the 'Style Settings' plugin.
5. Observe that Minimal uses the 'Style Settings' accent to color only links. Toggle backgrounds and active states are adorned with the *theme's* accent color.

## Expected behavior
The documentation says the 'Style Settings' colors override theme selections (and indeed this is the case for **every** other color) so the 'Colorful active state feature' should also respect the accent color set in style settings.

Ideally, Minimal Theme Settings and Style Settings would work together so that setting a theme in Minimal Style Settings would set all of the colors correctly in Style Settings, which could then be adjusted.

![image](https://user-images.githubusercontent.com/1509989/167310654-2253b705-aebb-4b66-8056-0841b46b510c.png)

## Debug Info

SYSTEM INFO:
	Obsidian version: v0.14.9
	Installer version: v0.14.6
	Operating system: Windows 10 Pro 10.0.22000
	Login status: logged in
	Catalyst license: vip
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 15
	Safe mode: off
	Plugins installed: 51
	Plugins enabled: 50
		1: Admonition
		2: Advanced Tables
		3: Auto Class
		4: Bartender
		5: Better footnote
		6: Better PDF Plugin
		7: Calendar
		8: Collapse All
		9: Contextual Typography
		10: Customizable Sidebar
		11: Dataview
		12: Diagrams
		13: Dictionary
		14: Extra Markdown Commands
		15: Excalidraw
		16: Folder Note
		17: Footnote Shortcut
		18: Get Info
		19: Hider
		20: Hotkey Helper
		21: Icon Shortcodes
		22: Linter
		23: Natural Language Dates
		24: Note Folder Autorename
		25: Obsidian Git
		26: Obsidian42 - BRAT
		27: Open vault in VSCode
		28: Open with
		29: Pane Relief
		30: Prominent Starred Files
		31: Quick Explorer
		32: Reading Time
		33: Readwise Official
		34: Recent Files
		35: Sliding Panes (Andy's Mode)
		36: Smart Typography
		37: Tag Wrangler
		38: Tasks
		39: Templater
		40: Wikipedia
		41: Icon Folder
		42: Minimal Theme Settings
		43: Icons
		44: Plugin Changelogs
		45: Excel to Markdown Table
		46: Obsidian Charts
		47: Hover Editor
		48: Frontmatter Tag Suggest
		49: Omnisearch
		50: Style Settings

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Comment by kepano** [comment]
I am not able to reproduce this issue. Are you sure that you have set a color in Style Settings for dark mode? Note that the dark mode and light mode accent colors are two different values in Style Settings.

**Comment by ScottKillen** [comment]
Yessir.

![image](https://user-images.githubusercontent.com/1509989/167311620-897dd604-606e-42a2-8b65-e2fabc58d0da.png)

I have attached my plugin data files also:
[minimal-settings-data.json](https://github.com/kepano/obsidian-minimal/files/8647623/minimal-settings-data.json.txt)
[style-settings-data.json](https://github.com/kepano/obsidian-minimal/files/8647624/style-settings-data.json.txt)

**Comment by kepano** [comment]
You have an override in your settings

`Style Settings > Minimal > Lists and checkboxes`

You have the color set to purple

**Comment by ScottKillen** [comment]
:facepalm

So sorry!
