### ISSUE TITLE
Update 5.2.4 Causes Display Issue in Live Preview.

### ISSUE THREAD

**Issue by ScribeCraft** [kepano/obsidian-minimal#295]
Update 5.2.4 seems to have altered Live Preview by moving some elements of the page to the far left. I also notice that images do not conform to the specified sizes required. For example, I have an image set at 200 pixels that displays at 200 pixels in Reading Mode. But in Live Preview, it displays at its full 800-pixel size. These display errors only seem to show up in Live Preview.

See, for example, this image.

![MinimalUpdateBug](https://user-images.githubusercontent.com/91273737/167351384-def9c600-dbab-4bdb-8f85-38df6a372b82.png)

Thanks.

SYSTEM INFO:
	Obsidian version: v0.14.9
	Installer version: v0.14.2
	Operating system: Windows 10 Enterprise 10.0.22000
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 1
	Safe mode: off
	Plugins installed: 8
	Plugins enabled: 8
		1: Advanced Tables
		2: Sliding Panes (Andy's Mode)
		3: Minimal Theme Settings
		4: Style Settings
		5: Editor Syntax Highlight
		6: Better Word Count
		7: Hider
		8: Contextual Typography

**Comment by kepano** [comment]
I think I have a fix for the first issue with the HTML block. Please update to the latest.

Regarding the image issue, can you share a screenshot and the associated markdown text?

**Comment by ScribeCraft** [comment]
Your quick fix seems to have resolved the first issue. Thank you. The image issue remains unresolved. Here are the screenshots you requested (Source View for the code, Reading View for proper display, and Live Preview) showing` how Live Preview is not responding to the size parameter. 

![SourceView](https://user-images.githubusercontent.com/91273737/167471653-e8cdc8d8-4a16-411b-835e-a841caebf9cd.png)
![ReadingView](https://user-images.githubusercontent.com/91273737/167471679-1b470ccf-37a1-4b3f-9f86-4553fb50878b.png)
![LivePreview](https://user-images.githubusercontent.com/91273737/167471694-27298a8b-5d5f-4b6f-b428-4e5220943f5f.png)

**Comment by kepano** [comment]
This should now be fixed in 5.2.5

**Comment by ScribeCraft** [comment]
This update fixed it. Thank you! I appreciate it, Mr. Wizard.
