### ISSUE TITLE
Half of first lane of kanban pages cut off in vertical split view   

### ISSUE THREAD

**Issue by liammrharris** [kepano/obsidian-minimal#30]
In version 3.2.2, given both the Minimal theme and Kanban plugin are installed and enabled, when a Kanban board is opened in vertical split view the horizontal scroll is limited so that at most half of the first Kanban lane is visible.

This can be immediately resolved by changing the theme from "Minimal" to "None" in Settings > Appearance > Themes > Theme

But, of course, I want to use Minimal Theme because it makes me happy.

Liam

**Comment by kepano** [comment]
Have you tested with the latest version of Minimal?

**Comment by liammrharris** [comment]
Currently got 3.2.2 installed.

**Comment by kepano** [comment]
Can you please update to the latest version (released last night). You can update via the Obsidian app itself.

**Comment by liammrharris** [comment]
Sorry, I should have been clearer: Minimal Theme Settings is version 3.2.2. No newer version of Minimal Theme Settings shows after clicking the button to check updates.

Just now, I went to Settings > Appearance > Theme > Themes > Browse

Then I searched and found Minimal Theme, clicked use and overwrote the old one. The same issue remains, however.

Am I now up to date?

**Comment by kepano** [comment]
I just pushed another version of the theme. Can you please repeat that last step again? Go to `Settings > Appearance > Theme > Themes > Browse` and update from there. Thanks!

**Comment by liammrharris** [comment]
Great stuff. Thank you for the swift fix.
