### ISSUE TITLE
Mathjax multline environments don't respect the readable line length setting

### ISSUE THREAD

**Issue by raineszm** [kepano/obsidian-minimal#302]
**Before you open a bug report**
Disable plugins and snippets that could be causing a conflict. Update to the latest versions of the following, and restart Obsidian:

- Minimal Theme
- Minimal Theme Settings plugin
- Contextual Typography plugin

**Confirm that the bug is not present when Minimal theme is off**

**Describe the bug**
Mathjax multline environments don't respect the readable line length.

**To reproduce**
1. Open Note
2. Create math display math
3. Insert multline environment4. 

**Expected behavior**
Left alignment of the math environment should match text

**Screenshots**
If applicable, add screenshots to help explain your problem

Here the issue is illustrated in the help vault

![Screen Shot 2022-05-10 at 12 21 58 PM](https://user-images.githubusercontent.com/15145/167676234-45bfaed4-0013-4267-ba7d-eee213b5b83a.png)

**Debug info (required):**
Paste your debug info below, which can be accessed in Obsidian with Ctrl/Cmd-P, enter "Show debug info", and click "Copy to clipboard"

SYSTEM INFO:
	Obsidian version: v0.14.9
	Installer version: v0.14.6
	Operating system: Darwin Kernel Version 21.4.0: Fri Mar 18 00:47:26 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T8101 21.4.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 3
	Plugins enabled: 3
		1: Minimal Theme Settings
		2: Style Settings
		3: Contextual Typography

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Comment by kepano** [comment]
This should be fixed now, thanks!
