### ISSUE TITLE
broken `--list-indent` variable

### ISSUE THREAD

**Issue by aidenlx** [kepano/obsidian-minimal#304]
**Describe the bug**

setting up list indent size in styles settings doesn't work on both reading mode and live preview mode

PS: seems like indent in live preview is hard-coded in `style` of `.HyperMD-list-line`, that might be a bit trick.

**Screenshots**

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/31102694/167758334-94d10b5c-8201-403e-b792-c2c2ddfc444f.png">

**Debug info (required):**
```
SYSTEM INFO:
	Obsidian version: v0.14.10
	Installer version: v0.14.6
	Operating system: Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 21.4.0
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 0
	Plugins enabled: 0

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
```

**Comment by kepano** [comment]
The indent is for the space between the deeper levels of the lists, not the first bullet

**Comment by kepano** [comment]
Updated the name in Style Settings to `Nested list indent`

**Comment by jeansordes** [comment]
@kepano I couldn't find in your documentation anything about changing the indent of the first bullet, have I missed something ?

For now I've added the following CSS code to my vault
```css
.HyperMD-list-line {
    transform: translateX(-15px);
}
```

Is there a better way ?
