### ISSUE TITLE
True Black Dark Mode Makes "Jump to Link" Plugin's Navigation Markers Unreadable

### ISSUE THREAD

**Issue by julroger2013** [kepano/obsidian-minimal#306]
**Before you open a bug report**

I have done so. 

**Confirm that the bug is not present when Minimal theme is off**

I have tried this with various themes, including various dark versions of the Minimal Theme. The issue appears if, and only if, Minimal Theme Settings are set to the "True Black" background contrast for Dark Mode. 

**Describe the bug**

The navigation markers created by the "Jump to Link" plugin become so dark as to be unreadable. Note, however, that I've been able to address this by adjusting the "Sidebar" color palette for Minimal Theme via the Style Settings plugin. However, this comes at the expense of making Hover Editor popups an unusual color. 

**To reproduce**

Install the Minimal Theme, set it to Dark Mode, and set the background contrast to "True Black." From there, install the "Jump to Link" plugin and then invoke that plugin's navigation features (typically by using Control + '). 

**Expected behavior**

The text on the navigation markers should be sufficiently distinct from the background of those markers to remain readable. 

**Screenshots**

I cannot take screenshots for this one because using the screenshot shortcut cancels out the navigation markers created by the "Jump to Link" plugin.

**Comment by kepano** [comment]
I have reviewed this however I don't think it is a bug with Minimal. This problem would occur on any theme with a dark background. The bug should be reported on the Jump to Link plugin repo.

The problem is that the author of the plugin is not using Obsidian's theme variables to style the content. My recommendation for the theme developer would be to use the `--text-normal` variable.

**Comment by julroger2013** [comment]
Bingo! I substituted that variable for the default font color designation within the plugin's style setting and the text immediately became properly visible! I'll add this as a suggestion for that plugin's repository as a fix.
