### ISSUE TITLE
Font Size slider is ignored

### ISSUE THREAD

**Issue by ngoetti** [kepano/obsidian-minimal#309]
**Before you open a bug report**
Disable plugins and snippets that could be causing a conflict. Update to the latest versions of the following, and restart Obsidian:

- Minimal Theme
- Minimal Theme Settings plugin
- Contextual Typography plugin

**Confirm that the bug is not present when Minimal theme is off**
Confirmed

**Describe the bug**
The font size does not change if I adjust the slider under Appearance -> Font size

**To reproduce**
Install obsidian. Install minimal design. Change font size.

**Expected behavior**
The font size changes with the slider.

**Screenshots**
Font Size minimal: ![image](https://user-images.githubusercontent.com/39217894/168424189-beaccafa-f3db-4f4b-94d4-09ae39685e56.png)
Font Size maximal: 
![image](https://user-images.githubusercontent.com/39217894/168424204-275fb214-fea2-4fba-8601-fc992c047285.png)

**Debug info (required):**
SYSTEM INFO:
	Obsidian version: v0.14.6
	Installer version: v0.14.2
	Operating system: Windows 10 Pro 10.0.22000
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Safe mode: on

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.

**Comment by ngoetti** [comment]
Does anyone know what the reverse Command is for: CTRL _
It decreased the font size with no way to increase it. This is how I noticed the slider bug.

**Comment by kepano** [comment]
Fonts are set via the plugin

Please see documentation:
https://minimal.guide/Plugins/Minimal+Theme+Settings

**Comment by kepano** [comment]
This is now fixed as of 5.2.6, so you can set font size without Minimal Theme Settings

It sounds like you also probably changed the overall zoom level of the app. You can change this with CTRL - and CTRL +
