### ISSUE TITLE
Cursor not working for lines / heardings above & below callouts

### ISSUE THREAD

**Issue by foenixp** [kepano/obsidian-minimal#311]
**Before you open a bug report**
Disable plugins and snippets that could be causing a conflict. Update to the latest versions of the following, and restart Obsidian:

- Minimal Theme
- Minimal Theme Settings plugin
- Contextual Typography plugin

**Confirm that the bug is not present when Minimal theme is off**
Confirmed

**Describe the bug**
I can't click on the lines (without or without headings) which have callouts below or above them. If I inserted an empty line between the headings and the callouts, sometimes I could click and the blinking cursor would appear, sometimes the cursor would jump the line above it (aka the end of the last line of the callout code block).
I made a brand new, empty vault to test, and noticed that this issue only appears when I turned off the readable line length option. 

**To reproduce**
1. Create a new vault
2. Install minimal theme
3. Turn off readable line length
4. Create several callouts (which contents either plain texts, embeded internal links, or dataview code blocks)
5. Try clicking on all lines

**Expected behavior**
The blinking cursor should appear on every line I clicked on.

**Screenshots**
Please see the attached video.

**Debug info (required):**
SYSTEM INFO:
	Obsidian version: v0.14.11
	Installer version: v0.11.13
	Operating system: Windows 10 Home 10.0.19044
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 5
	Plugins enabled: 5
		1: Minimal Theme Settings
		2: Style Settings
		3: Contextual Typography
		4: Dataview
		5: Banners

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

https://user-images.githubusercontent.com/102443314/168647358-e3ad38e6-80aa-40c9-bb7f-9587c73c969b.mp4

**Comment by kepano** [comment]
Can you update to the latest version of the theme and let me know if this is still an issue?

**Comment by foenixp** [comment]
I updated, and the issue seems to no longer exist. Thank you!
