### ISSUE TITLE
Can you increase the space distance above the title

### ISSUE THREAD

**Issue by zhl111** [kepano/obsidian-minimal#312]
The distance between the top of the title and the text paragraph, and the distance between the text paragraph below is the same, can some adjustments be made?
![CopyQ BGqRDH](https://user-images.githubusercontent.com/29135984/168958024-ec7a95b1-95bc-4789-9303-7592fd8c8136.png)

It would be nice if this was the case
![image](https://user-images.githubusercontent.com/29135984/168958094-897e713e-8cef-42ad-81eb-c35247ee347a.png)

**Comment by zhl111** [comment]
[obsidian-california-coast-theme](https://github.com/mgmeyers/obsidian-california-coast-theme)
![image](https://user-images.githubusercontent.com/29135984/170873970-3cdbb3f3-3881-4195-a099-d16ddec6f116.png)
I tried to take the paragraph spacing from this thread and used it, but it didn't work

**Comment by kepano** [comment]
Are you talking about reading mode or editing mode or both?

**Comment by zhl111** [comment]
It's  reading mide.editing mode can be achieved by separating them with spaces

**Comment by kepano** [comment]
In that case you can use Contextual Typography plugin:
https://github.com/mgmeyers/obsidian-contextual-typography

**Comment by zhl111** [comment]
① His plug-in is to narrow the distance between titles
②What I wanted to achieve was the spatial distance between paragraphs and headings, and his plugin didn't change that
![image](https://user-images.githubusercontent.com/29135984/171034748-91b10bfb-535f-455f-b3f7-0f3de8d0b743.png)

**Comment by kepano** [comment]
You should read the documentation for Contextual Typography as it allows you to define any margins you want between element types

**Comment by zhl111** [comment]
I'm very sorry, I can't find anything to adjust, which means I don't know how to do it. I would be very grateful if you could show me how to do it.

**Comment by ernest67** [comment]
I encounter the same problem and I was unable to find the documentation for Contextual Typography. @kepano @zhl111 if you are free can you kindly point out how to I use that plug-in to define the margin please? Thank you!

**Comment by kepano** [comment]
Fixed in 7.0
