### ISSUE TITLE
No Code Edit Button When Readable Line Length Toggle Off

### ISSUE THREAD

**Issue by Zhicheng2914** [kepano/obsidian-minimal#313]
Obsidian Version: v0.14.12 insider preview
Minimal Theme Version: v5.2.7
Platform: Windows 11

---

Description: As title descripted, please refer screenshot below, When close the Settings --> Editor --> Readable Line Length toggle this bug will appear.

![image](https://user-images.githubusercontent.com/17692778/168965938-514d4f6e-b829-4b46-b479-9daab19f7ef8.png)

**Comment by kepano** [comment]
This will be fixed in an upcoming update, you can access the beta in the `margin-offset` branch

**Comment by kepano** [comment]
Fixed in 5.2.8 https://github.com/kepano/obsidian-minimal/releases/tag/5.2.8
