### ISSUE TITLE
Minimal Theme doesn't work with Outliner-Plugin's Vertical indentation line click action: “Toggle Folding” 

### ISSUE THREAD

**Issue by brotbrot** [kepano/obsidian-minimal#314]
The “obsidian-outliner”-Plugin has the option: Vertical indentation line click action → “Toggle Folding”:
<img width="980" alt="CleanShot 2022-05-19 at 17 38 13@2x" src="https://user-images.githubusercontent.com/33879005/169338411-98dc8818-639b-4943-a368-18b6547471bb.png">

this should help to click a vertical line (1) of an outline (or list) to fold the chosen levels (2):
<img width="573" alt="CleanShot 2022-05-19 at 17 39 23@2x" src="https://user-images.githubusercontent.com/33879005/169338703-72d8f319-d4fa-429e-8b11-f89aa2407bef.png">
<img width="774" alt="CleanShot 2022-05-19 at 17 39 40@2x" src="https://user-images.githubusercontent.com/33879005/169338716-9eeda8de-1cb7-49b2-b006-0b16fb7e4571.png">

This works perfectly fine with the default theme. With the Minimal Theme activated, it stops working.
Do I Miss something?

**Comment by wirtzdan** [comment]
@kepano Is it not possible to implement this with Minimal? Coming from Logseq, this would be a great feature to enable with Minimal Theme.

**Comment by kepano** [comment]
@wirtzdan making indentation lines clickable is not a thing themes can control, it would be something that needs to be added to the core app

**Comment by wirtzdan** [comment]
I thought it might be the case. Thanks for elaborating.
