### ISSUE TITLE
Font Size don't change on Mobile (iOS)

### ISSUE THREAD

**Issue by chrimich1** [kepano/obsidian-minimal#315]
**Before you open a bug report**
Disable plugins and snippets that could be causing a conflict. Update to the latest versions of the following, and restart Obsidian:

- Minimal Theme
- Minimal Theme Settings plugin
- Contextual Typography plugin

**Confirm that the bug is not present when Minimal theme is off**
With other themes the font-size can be adjusted. 

**Describe the bug**
The Setting Font Size in the main menu "Appearance" has no impact on the font size in the minimal theme in the Mobil App on iOS. On Desktop it works fine. It worked also on the Mobile before the latest update of the minimal theme was installed. 

**To reproduce**
Go to setting Font Size in the Appearance menu and change the font size - no change in the editor view/editor mode. 

**Expected behavior**
Font Size in the Editor/View mode can be changed by the setting

**Screenshots**
n.a.

**Debug info (required):**
Mobile App

**Comment by kepano** [comment]
This is an Obsidian bug that is already fixed in the latest beta

**Comment by kepano** [comment]
FYI this should now be resolved as of the latest update to Minimal theme

**Comment by chrimich1** [comment]
Thank you very much, it works again
