### ISSUE TITLE
Inline html causes odd spacing in Live Preview

### ISSUE THREAD

**Issue by ScottKillen** [kepano/obsidian-minimal#318]
**Describe the bug**
Lice Preview hides inline HTML tags, but they still show as whitespace.

**To reproduce**
Surround text with an HTML tag like <span>. Move the cursor elsewhere.

**Expected behavior**
The hidden tag should not produce whitespace.

**Screenshots**
![2022-05-21_17-18-48](https://user-images.githubusercontent.com/1509989/169669453-93488013-bc97-4201-9665-18d05898deca.gif)

**Debug info (required):**
SYSTEM INFO:
	Obsidian version: v0.14.12
	Installer version: v0.14.6
	Operating system: Windows 10 Pro 10.0.22000
	Login status: logged in
	Catalyst license: vip
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 15
	Safe mode: off
	Plugins installed: 52
	Plugins enabled: 51
		1: Admonition
		2: Advanced Tables
		3: Auto Class
		4: Bartender
		5: Better footnote
		6: Better PDF Plugin
		7: Calendar
		8: Collapse All
		9: Contextual Typography
		10: Customizable Sidebar
		11: Dataview
		12: Diagrams
		13: Dictionary
		14: Extra Markdown Commands
		15: Excalidraw
		16: Folder Note
		17: Footnote Shortcut
		18: Get Info
		19: Hider
		20: Hotkey Helper
		21: Icon Shortcodes
		22: Linter
		23: Natural Language Dates
		24: Note Folder Autorename
		25: Obsidian Git
		26: Obsidian42 - BRAT
		27: Open vault in VSCode
		28: Open with
		29: Pane Relief
		30: Prominent Starred Files
		31: Quick Explorer
		32: Reading Time
		33: Readwise Official
		34: Recent Files
		35: Sliding Panes (Andy's Mode)
		36: Smart Typography
		37: Tag Wrangler
		38: Tasks
		39: Templater
		40: Wikipedia
		41: Icon Folder
		42: Minimal Theme Settings
		43: Icons
		44: Plugin Changelogs
		45: Excel to Markdown Table
		46: Obsidian Charts
		47: Hover Editor
		48: Frontmatter Tag Suggest
		49: Omnisearch
		50: Style Settings
		51: Semantic Line Breaker

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Comment by kepano** [comment]
Which version of Minimal are you using? Just pushed a small fix, lmk if that helps.

**Comment by ScottKillen** [comment]
@kepano I am using 5.2.8.

**Comment by kepano** [comment]
This is fixed if you update to the latest

**Comment by ScottKillen** [comment]
I can confirm the fix. Thank you!
