### ISSUE TITLE
Table and header alignement 

### ISSUE THREAD

**Issue by icebruce** [kepano/obsidian-minimal#319]
**Headers and text does not seem to be aligned with table**
Header and text seems to be slightly offset to the right, when compared to a table.

**To reproduce**
1. Enable readable line length in settings
2. Enter text/header and create a table

**Expected behavior**
Content to be aligned. Right now the table and the text/header are just slightly off in terms of alignment. This only happens if Readable line length is on. Does not happen with Obsidian default theme or other themes

**Screenshots**
![image](https://user-images.githubusercontent.com/66655064/169735924-7e8bc2e5-955c-4487-8992-179ab257ee3a.png)

**Debug info (required):**
SYSTEM INFO:
	Obsidian version: v0.14.12
	Installer version: v0.14.5
	Operating system: Windows 10 Pro 10.0.19043
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal

**Comment by kepano** [comment]
Which version of Minimal are you using? Can you confirm this happens with the latest version?

**Comment by icebruce** [comment]
Yup, can confirm its happening with 5.2.8. I updated yesterday so can't remember if it was happening with the previous one as well.

![image](https://user-images.githubusercontent.com/66655064/169891582-a8bc5074-068d-4ac6-ab41-13bc072ffd06.png)

**Comment by kepano** [comment]
It's strange, I am not able to reproduce this issue

**Comment by icebruce** [comment]
Interesting. Its not a big issue I guess.
I will do some digging on my end see if there is something I can use to put this in place. In the meantime did some more testing. 

Disabled all snippets and plugins. With readable line length on the left side seem to be kinda ok
![image](https://user-images.githubusercontent.com/66655064/170169326-44107a28-b475-44f7-a1da-f9223647df6a.png)

While the same with readable line length looks pretty off altogether
![image](https://user-images.githubusercontent.com/66655064/170169540-2b26f68c-259a-41b8-8d2f-7eb1ea0d4883.png)

**Comment by kepano** [comment]
I am trying to reproduce, but I haven't been able to

<img width="789" alt="Screen Shot 2022-05-24 at 8 36 45 PM" src="https://user-images.githubusercontent.com/10565871/170174519-d3a5fe87-9b40-48a5-9fe6-cc5e8043512f.png">

**Comment by icebruce** [comment]
Very strange. I have now tried with a brand new vault, after re-installing Obsidian and am getting similar results. Looks like its not theme specific after all. Maybe its specific to live preview as in reading mode it seems good. Anyways ill look further into this on my end. Thanks!
