### ISSUE TITLE
"Readable line length" option not working with minimal theme

### ISSUE THREAD

**Issue by jakevossen5** [kepano/obsidian-minimal#32]
I am unable to turn off the "Readable line length" option in editor settings, but only while using this theme.

**Comment by kepano** [comment]
I am not sure I understand. Are you saying that the toggle in the Obsidian settings doesn't switch on and off, or that when you turn it off that has no effect?

Do you have Minimal Theme Settings plugin? If so you may want to adjust the values for Normal line width and Maximum line width.

**Comment by jakevossen5** [comment]
Sorry, realize it was worded poorly. Yes, I can change the toggl, but it has no effect on line length. Didn't realize Minimal Theme Settings plugin existed - that is a good workaround for me!

**Comment by kepano** [comment]
Got it. Please make sure you are also running the latest version of Minimal theme. I am unable to reproduce the bug you described.
