### ISSUE TITLE
Something strange with the Todoist Sync plugin

### ISSUE THREAD

**Issue by DitchComfort** [kepano/obsidian-minimal#322]
Every task is on a new/separate line, or I don't know how to actually explain it. Strange things are happening.

<img width="286" alt="Screenshot 2022-05-25 at 20 33 02" src="https://user-images.githubusercontent.com/77794110/170341319-20c780c5-14d0-4e2a-be3f-b7c7cc9be2d3.png">

<img width="625" alt="Screenshot 2022-05-25 at 20 24 28" src="https://user-images.githubusercontent.com/77794110/170341468-3ce77838-eaf9-4ec6-8dcf-afc341702e7a.png">

This is normal behavior, or what I expect:

<img width="290" alt="Screenshot 2022-05-24 at 18 00 24" src="https://user-images.githubusercontent.com/77794110/170340769-b772f8ea-f466-4cbb-8af3-95db3ce27575.png">

**Comment by kepano** [comment]
Is this related to any snippets? I am not able to reproduce
