### ISSUE TITLE
Catppuccin color scheme

### ISSUE THREAD

**Issue by CaptainSou** [kepano/obsidian-minimal#323]
First and foremost I'd like to say thank you for making such an amazing theme for Obsidian which I've been rolling basically ever since I've started working with Obsidian.

I've noticed that you've added Everforest colour scheme lately, and couldn't help but wonder if there are any plans to add Catppuccin in the near future?

**Comment by kepano** [comment]
I'd like to see more demand from the community first. There are thousands of color schemes out there, so I want to stay relatively conservative an add only the most popular ones.

For the long tail of color schemes there are two additional options for [creating your own](https://minimal.guide/Features/Color+schemes):

1. Style Settings allows you to fully reproduce a color scheme, and share it via import/export functionality
2. [CSS styles](https://github.com/kepano/obsidian-minimal/tree/master/src/scss/color-schemes) for the existing preset color schemes are easy to duplicate as a template for a snippet

**Comment by kepano** [comment]
Added in Minimal 6.1
