### ISSUE TITLE
Move ribbon and menu items up in frameless mode (currently stay in same spot when titlebar is removed, leaving blank gap)

### ISSUE THREAD

**Issue by afland** [kepano/obsidian-minimal#324]
When using Hider to enable frameless mode, the ribbon items stay in the same spot, leaving a blank space at the top, as shown in the below screenshot.

![Screenshot_20220527_204908](https://user-images.githubusercontent.com/67392684/170808715-17af9f55-dbb4-441f-9d6a-6d59281bd75a.png)

It would be great if those could be moved to the top in frameless mode as in e.g. the discord theme:

![Screenshot_20220527_204409](https://user-images.githubusercontent.com/67392684/170808574-45285682-3a53-41ef-bf4d-a142f586e28e.png)

Additionally, the spacing would hopefully make those 2 border lines align:
![Screenshot_20220527_205000](https://user-images.githubusercontent.com/67392684/170808738-d2c06808-b43a-41a9-a0e2-bca4a076e44a.png)

**Comment by kepano** [comment]
Which operating system are you using?

**Comment by kepano** [comment]
This is fixed in 5.2.9

**Comment by afland** [comment]
> This is fixed in 5.2.9

Thanks for the quick fix! Sorry to pester you again, but I was wondering if it would be possible to move the ribbon items up as well: 
![Screenshot_20220528_113942](https://user-images.githubusercontent.com/67392684/170838721-7ccb0e98-30f1-40b0-b62b-4b3ef7cdf9e0.png)

And this might be a little less realistic, but maybe also an option in the plugin to move the go forward + go back buttons to the navigation row with the file explorer / search buttons e.g. to the right of them
![Screenshot_20220528_113942](https://user-images.githubusercontent.com/67392684/170838786-85c76e7e-819d-4d40-8f41-4770524cd713.png)

**Comment by kepano** [comment]
The ribbon issue is resolved.

The forward back buttons is a different problem that is not in scope for me right now
