### ISSUE TITLE
Tags Font Size Does Not Change With Settings

### ISSUE THREAD

**Issue by Zhicheng2914** [kepano/obsidian-minimal#326]
Obsidian Version: v0.14.15 insider preview
Minimal Theme Version: v5.2.9
Platform: Windows 11

---

## Description: 
As title descripted, please refer screenshot below. Tags font size does not change if I change the obsidian editor font size.

## Which Tag not response font size change?
1. Tags displayed in Dateview
2. Normal Tags
3. All Tags in read mode

## Which Tag response font size change?
1. Tags in title and only response on live preview mode

![Universe - Obsidian v0 14 15 2022-06-01 11-45-38_](https://user-images.githubusercontent.com/17692778/171323911-e87e058c-48aa-4c92-9763-a49fc290b34e.gif)
![Universe - Obsidian v0 14 15 2022-06-01 11-46-27_](https://user-images.githubusercontent.com/17692778/171323925-7d763b8f-8544-4d44-ba76-6b4b739f734c.gif)

**Comment by kepano** [comment]
Tag font size uses the small (sidebar) size defined in Minimal Theme Settings
