### ISSUE TITLE
Tasks in embed are cut off in preview

### ISSUE THREAD

**Issue by necopinus** [kepano/obsidian-minimal#33]
Tasks in an embedded note are cut off on the left-hand side when the note is previewed.

![03FC60C4-C456-4740-9EB2-3E12FE718637](https://user-images.githubusercontent.com/134362/135530612-f5709f90-dfd7-4683-89d2-a4ef86427b19.png)

Tested on iOS/iPadOS with the latest version of the Minimal theme and with all CSS snippets disabled.

**Comment by necopinus** [comment]
Superficially looks similar to [the problem that Kanban boards had](https://github.com/kepano/obsidian-minimal/pull/28).

**Comment by kepano** [comment]
Fixed in 4.0
