### ISSUE TITLE
Weird behaviour with focus mode enabled in 5.2.10 (partially visible pane bar)

### ISSUE THREAD

**Issue by danieltomasz** [kepano/obsidian-minimal#330]
When i have left sidebar open I while focus is enabled I see this
![image](https://user-images.githubusercontent.com/7980381/171957643-a42080e5-e091-4864-b0e3-7b4519e41cdf.png)
When sideber is not visible the corner is "focused"

Is this intended behaviour? I suppose it should be completely hidden and visible only on click

**Comment by kepano** [comment]
Oops, this should be fixed now
