### ISSUE TITLE
Adding blockquote background

### ISSUE THREAD

**Issue by Mela-Mela** [kepano/obsidian-minimal#331]
The blockquote is a bit too similar to the rest of the notes. It'd be good if I can tell which is my own writing and which is quotes from readings just by a glance. 

Adding the option of blockquote background (colour) will be very helpful.

**Comment by kepano** [comment]
Blockquotes can be customized via Style Settings plugin, you can learn more here:
https://minimal.guide/Plugins/Style+Settings#Blockquotes

**Comment by Mela-Mela** [comment]
Thanks for your reply. I see that Blockquotes are customizable in terms of text colour, font size, and font style. I just wonder if blockquote background colour can also be customized.

**Comment by kepano** [comment]
You can definitely do this via snippets. I don’t have immediate plans to add background color

**Comment by axelson** [comment]
I'm not sure if this is the best way, but here's what I have done to add a blockquote background color as a CSS snippet:
```css
.HyperMD-quote {
  background-color: #171717 !important;
}
```

And here's how it looks with my (somewhat customized) obsidian minimal theme:
![image](https://user-images.githubusercontent.com/9973/196002650-d4af7056-ebb9-485c-8d3f-7711c106e2ac.png)

**Comment by kepano** [comment]
Closed in 6.0.13 
https://github.com/kepano/obsidian-minimal/releases/tag/6.0.13

**Comment by axelson** [comment]
Thanks for adding it! Although it appears that it is not working in the live preview editor for me because of CSS specificity:

![Screenshot 2022-10-17 19-06-42](https://user-images.githubusercontent.com/9973/196340435-feae97f6-8fb4-4bf8-a757-d7f4b00cb885.png)
