### ISSUE TITLE
Dataview Query Not Working After Following Movie Database Creation Guide

### ISSUE THREAD

**Issue by fmksr2007** [kepano/obsidian-minimal#332]
**Bug Description**
I followed the guide on creating the movie database at https://minimal.guide/Guides/Create+a+movie+database. Still, the dataview query does not provide posters or movie information and instead keeps showing "Dataview: No results to show for table query."

**To reproduce**
Follow the steps given at: https://minimal.guide/Guides/Create+a+movie+database

**Expected behaviour**
The end result photograph shown at: https://minimal.guide/Guides/Create+a+movie+database

**Screenshots**
![Screenshot 1](https://user-images.githubusercontent.com/106901917/172039202-543674b0-0520-4abd-8878-ed385a98b5e0.png)
![Screenshot 2](https://user-images.githubusercontent.com/106901917/172039204-70919e9b-4f99-4d64-ac12-a0c932b4cd95.png)

**Debug info (required):**
SYSTEM INFO:
	Obsidian version: v0.14.6
	Installer version: v0.14.6
	Operating system: Windows 10 Pro 10.0.22621
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 15
	Plugins enabled: 12
		1: Advanced Tables
		2: Calendar
		3: Sliding Panes (Andy's Mode)
		4: Natural Language Dates
		5: Hotkeys++
		6: Enhancing Mindmap
		7: Citations
		8: Pandoc Plugin
		9: Minimal Theme Settings
		10: Dataview
		11: QuickAdd
		12: Sortable

**Comment by kepano** [comment]
Please get assistance via Discord Dataview channel. Issues here are for the theme itself.
