### ISSUE TITLE
Pandoc [@cite]  coloring not supported

### ISSUE THREAD

**Issue by danieltomasz** [kepano/obsidian-minimal#333]
Within vanilla obsidian `[@cite]` is highlighted 

![image](https://user-images.githubusercontent.com/7980381/172123259-3fb5a7d3-6832-449a-807a-0b20b9b83bfa.png)

Minimal doesn't support it 
![image](https://user-images.githubusercontent.com/7980381/172123521-ba7ad708-fa02-48a0-83eb-f48a11671795.png)

**Comment by kepano** [comment]
Minimal and Obsidian now behave the same way. However the fact that it uses the accent color is a bug with Obsidian, it's not intended to be accented afaik because the Pandoc notation is not supported yet. Should be an Obsidian forum feature request.
