### ISSUE TITLE
No cursor in obsidian editor (after update from 0.14.6 to 0.14.15) with minimal thime plugin installed

### ISSUE THREAD

**Issue by swl181** [kepano/obsidian-minimal#338]
**Before you open a bug report**
using latest version minimal theme settings plugin
obsidian 0.14.15

**Confirm that the bug is not present when Minimal theme is off**

Bug is not present when Minimal theme is **off** in obsidian v0.14.15

Bug is not present when Minimal theme is **on** in obsidian v0.14.6

**Describe the bug**
No cursor in obsidian editor (after update from 0.14.6 to 0.14.15) with minimal thime plugin installed

I've found similar situation here https://forum.obsidian.md/t/no-cursor-in-the-obsidian-editor/36924/2
but reinstalling minimal theme settings plugin does not resolve issue

**To reproduce**
Turn on minimal theme settings plugin in obsidian v0.14.15 and goto obsidian editor mode - no cursor

**Expected behavior**
Cursor is visible

**Screenshots**
If applicable, add screenshots to help explain your problem

**Debug info (required):**
SYSTEM INFO:
	Obsidian version: v0.14.15
	Installer version: v0.14.15
	Operating system: Windows 10 Pro 10.0.19044
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 24
	Plugins enabled: 24
		1: Calendar
		2: Checklist
		3: Templater
		4: Natural Language Dates
		5: Dataview
		6: Buttons
		7: Clear Unused Images
		8: Citations
		9: PlantUML
		10: Linter
		11: Customizable Page Header and Title Bar
		12: Homepage
		13: Spaced Repetition
		14: Customizable Menu
		15: Customizable Sidebar
		16: Emoji Toolbar
		17: Excalidraw
		18: Kanban
		19: Outliner
		20: Sliding Panes (Andy's Mode)
		21: Hider
		22: Pandoc Plugin
		23: Advanced Tables
		24: Minimal Theme Settings

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Comment by davidkopp** [comment]
Updating Minimal Theme to 5.2.10 solves the problem.

**Comment by swl181** [comment]
thanks a lot!
