### ISSUE TITLE
Create `Primary` color scheme

### ISSUE THREAD

**Issue by ka1tzyu** [kepano/obsidian-minimal#339]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I think It would be cool to add `Primary` variant to color schemes with all styling such as font-styles (bold, italic), callouts, button, etc.

**Comment by kepano** [comment]
This is not something I plan to do since Primary already exists as an Obsidian theme. However there are two other ways to create your own color schemes for Minimal, via Style Settings or CSS snippets see: https://minimal.guide/Features/Color+schemes

**Comment by ka1tzyu** [comment]
> This is not something I plan to do since Primary already exists as an Obsidian theme. However there are two other ways to create your own color schemes for Minimal, via Style Settings or CSS snippets see: https://minimal.guide/Features/Color+schemes

Got it, thanks
