### ISSUE TITLE
Spacing between paragraphs is reduced in embeds when previewed

### ISSUE THREAD

**Issue by necopinus** [kepano/obsidian-minimal#34]
The spacing between paragraphs (and lists?) in an embedded note is reduced when the note is previewed. This makes the embedded note text much harder to read.

![7E5E50A4-7116-4573-848D-A478AAD8752A](https://user-images.githubusercontent.com/134362/135531077-f0b75886-d857-443e-bd29-a201cc431f72.png)

Tested on iOS/iPadOS with the latest version of the Minimal theme and with all CSS snippets disabled.

**Comment by kepano** [comment]
This will be fixed in Minimal 4.0
