### ISSUE TITLE
Option to revert elements to default look or change blockqoute style?

### ISSUE THREAD

**Issue by saucypilot** [kepano/obsidian-minimal#342]
I prefer the default way blockqoutes are displayed on Obsidian.
>This is because with the minimal theme, it looks like the relationship lines for bullet points.

### Possible options
1.I could manually change the Minimal theme CSS but if a new update for the theme comes out, it would disappear.
It's a hassle having to go edit a CSS file for every update.

2.Using CSS snippets, I don't know exactly how to make blockqoutes revert back to its original look. Maybe I can use CSS to make it look default, instead of actually reverting it?

Is this a feature thats possible? I've seen it done with tags. It's an option with the styles plugin.

**Comment by kepano** [comment]
This doesn't seem like an issue with the theme. Minimal is intentionally opinionated. I would recommend using a snippet if you want to customize the look, or using a different theme that better fits your preferences.
