### ISSUE TITLE
Edit this block icon '< >' is partly hoovering over first link in tasks query

### ISSUE THREAD

**Issue by jaroet** [kepano/obsidian-minimal#345]
When I use the minimal theme with tasks for every query I make an group by pagename the "Edit this block" icon showing '< >' is in part hoovering over a small part of the first pagename shown in the query. 

Like so ... 
<img width="201" alt="image" src="https://user-images.githubusercontent.com/28713432/174431949-588b52ee-b12f-47ff-96d9-058b541909df.png">

It should not. My personal preference would be to show left of the text or to the far right. But at least it should not partly cover the page link in the query. 

Thanks for this great theme. Using MacOS and 14.15 obsidian.

**Comment by kepano** [comment]
If you turn on readable line length this should work.
