### ISSUE TITLE
Codeblocks and someother things use full width when readable line length is enabled

### ISSUE THREAD

**Issue by isle9** [kepano/obsidian-minimal#346]
**Confirm that the bug is not present when Minimal theme is off**

 The bug does not appear in the default theme.

**Describe the bug**
Codeblock use full width while the readable line length is enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/74906541/174501446-894bc164-6777-4acb-8c45-e0342e81d52f.png)

**Comment by kepano** [comment]
I am not seeing how the screenshot relates to the issue you are describing. Can you please provide more detail and instructions to reproduce?

**Comment by isle9** [comment]
In the default theme, while the readable line length is enabled, various elements like codeblocks and the breadcrumb plugin in the screenshot, only use a certain percentage of the pane.

![image](https://user-images.githubusercontent.com/74906541/174546057-b024f805-ad6f-49f3-8621-f54ef6523a5c.png)

But when using the minimal theme, these various elements like codeblocks don't respect this rule and use the full width of the pane and I haven't been able to find an option in the setting to disable this.

![174501446-894bc164-6777-4acb-8c45-e0342e81d52f](https://user-images.githubusercontent.com/74906541/174546295-94ebb5c0-c059-4334-b8f3-53ce57ed3aa6.png)

**Comment by kepano** [comment]
Sorry but I am still confused. Can you share the raw markdown text from your note? In the screenshot you shared it looks like you are using a blockquote, is it also wrapped inside of a code block? Also in the screenshot it doesn't seem like the quote is taking up the whole width, am I missing something?

**Comment by isle9** [comment]
`.cm-contentContainer {
	max-width: 55% !important;
}`

The width of the cm-contentContainer was the problem. The minimal theme uses 100% while the default obsidian theme uses 700px.
This seems to mess with a couple of plugins. The quote block inside the codeblock is from the local quotes plugin, for instance.

**Comment by isle9** [comment]
Percentages break minimal on mobile so the right code is this:

`.cm-contentContainer { max-width: 700px !important; }`

It's just a revert to base Obsidian.
