### ISSUE TITLE
Question: Using the Cards function, only two cards are showing side by side?

### ISSUE THREAD

**Issue by ReaderGuy42** [kepano/obsidian-minimal#348]
I just followed this tutorial (https://minimal.guide/Guides/Create+a+movie+database) for a movie database and it all seems to be working fine, so thanks for that! 

But now it seems that only two movie posters show up side by side. Is there a way to set it so it fills up the width of the available screen?

Thanks!

**Comment by ReaderGuy42** [comment]
When I take out the "Where" thing from the dataview block I can have three posters side by side, is that intended?

**Comment by kepano** [comment]
Please review the Cards documentation and use the Discord for help

https://minimal.guide/Block+types/Cards
