### ISSUE TITLE
Custom plugin search box appears to be missing top margin

### ISSUE THREAD

**Issue by necopinus** [kepano/obsidian-minimal#35]
When using the Minimal theme, the custom plugin search box appears to be missing its top margin:

![51F61F71-40DA-431A-98F5-7A0DC686BE86](https://user-images.githubusercontent.com/134362/135531528-030bc36e-20f6-4920-9e6f-7282ae638f0c.png)

Tested on iOS/iPadOS with the latest version of the Minimal theme and with all CSS snippets disabled.

**Comment by kepano** [comment]
Fixed in 4.0
