### ISSUE TITLE
Option to change Marker colours of Lists

### ISSUE THREAD

**Issue by ManasMadrecha** [kepano/obsidian-minimal#352]
**Is your feature request related to a problem? Please describe.**
Currently, there is no option in Style Settings plugin to change the colour of the list markers.

**Describe the solution you'd like**
Kindly provide this option for both Light and Dark theme. 

**Alternative**
Currently, I have to use Custom CSS snippet to manage this. It would be nice if such option was present in the setting itself.

**Comment by kepano** [comment]
You can do this by changing the color under Styles Settings > Minimal > Text > Faint color

**Comment by ManasMadrecha** [comment]
Changed it to bright reddish-orange for Dark theme, and it changed the colours of collapsible folders' icon in File Explorer, the Headings hashtags, and also the List markers. It has made the theme much more clear and crisp. It's beautiful. Thanks 😄
