### ISSUE TITLE
Soft break inside a list broken

### ISSUE THREAD

**Issue by ironhak** [kepano/obsidian-minimal#354]
### Is the bug present when using the default Obsidian theme?

No

### Minimal theme version

last version

### Normal behaviour:
Live preview mode:
![Screenshot 2022-06-28 at 21 43 58](https://user-images.githubusercontent.com/62611612/176271483-a818912e-800b-495e-9fc0-5d5e52bec2fe.png)
Reading mode:
![Screenshot 2022-06-28 at 21 44 27](https://user-images.githubusercontent.com/62611612/176271549-46b14634-370c-409b-9fad-d9c20e7e17ae.png)
### Issue
If I create a soft break inside a list, I get this:
Live preview mode:
![Screenshot 2022-06-28 at 21 45 34](https://user-images.githubusercontent.com/62611612/176271733-a2ccb2c3-83dc-4025-a540-4372b87bdd26.png)
Reading mode:
![Screenshot 2022-06-28 at 21 46 08](https://user-images.githubusercontent.com/62611612/176271825-06588213-6eed-4d99-a81a-7bd2077c5caa.png)

I would expect reading mode to be equal to live preview mode. Also, if I follow markdown rule and I add the second line: 
Live preview mode:
![Screenshot 2022-06-28 at 21 47 04](https://user-images.githubusercontent.com/62611612/176272006-ef6bb63a-2302-4016-a142-8fe30919546b.png)
Reading mode:
![Screenshot 2022-06-28 at 21 47 16](https://user-images.githubusercontent.com/62611612/176272033-2d556095-6217-4d3d-86de-a9c48d52f8a6.png)

As you can see, everything gets screwed up. Hope you understand the issue and can resolve it. 

### Debug info

SYSTEM INFO:
	Obsidian version: v0.14.15
	Installer version: v0.14.15
	Operating system: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 21.5.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 1
	Safe mode: off
	Plugins installed: 14
	Plugins enabled: 14
		1: Style Settings
		2: File path to URI
		3: Image Toolkit
		4: Clear Unused Images
		5: Paste URL into selection
		6: Wikilinks to MDLinks
		7: Highlightr
		8: Hider
		9: Zoom
		10: Obsidian Tabs
		11: Cycle through Panes
		12: Typewriter Scroll
		13: Underline
		14: Minimal Theme Settings

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Comment by kepano** [comment]
Can you share the markdown file you are using?

**Comment by ironhak** [comment]
Hi, thank's for taking your time to checking into this, here's the file. 
[Untitled.md](https://github.com/kepano/obsidian-minimal/files/9008100/Untitled.md)

Also, thank's for creating this highly customizable theme.

**Comment by kepano** [comment]
I am testing your file, and the issues you are describing are also present in the default theme. Obsidian is wrapping a paragraph element around the last two list items. This might be related to the handling of Markdown loose lists. There are many forum threads about this e.g. https://forum.obsidian.md/t/incorrect-line-spacing-in-reading-view-for-bullet-lists/30977

**Comment by ironhak** [comment]
Hi... yes I see. Sorry I didn't noticed that this issue was present even on default theme. Let's hope obsidian team fix this, sorry for bothering you with issues not related to your work. 
Thank's for investigating into it btw, wish you a good day.
