### ISSUE TITLE
Simple Header Level Identification

### ISSUE THREAD

**Issue by MarcosDantasdeSantana** [kepano/obsidian-minimal#356]
**Is your feature request related to a problem? Please describe.**
In minimal theme is sometimes difficult to understand what headrer level is now.

**Describe the solution you'd like**
A simple indicator of the header level, with styles based in the theme.

One Exemple of What I have done:

- Header expecified in the **right**;
- If _hovered_ or is the _active line_ is **hidden**.

![Screenshot_20220629-090708~2](https://user-images.githubusercontent.com/82475903/176448281-1ae269a4-fe47-4f87-bdf0-dec00def07cf.png)

**Comment by kepano** [comment]
You can do this via the Lapel plugin or snippets
