### ISSUE TITLE
Another Quick Switcher icons cut

### ISSUE THREAD

**Issue by tim-hilde** [kepano/obsidian-minimal#357]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

5.3.0

### Describe the bug

When using minimal in conjunction with the plugin "Another Quick Switcher" the icons in the pop up are cut off:

![SCR-20220701-9nq](https://user-images.githubusercontent.com/44113468/176828978-b284ae08-d63a-4990-bdc2-bb1c24559325.png)

I've already created an issue in the plugin's repo: https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/issues/73#issue-1290922766 

### Debug info

SYSTEM INFO:
	Obsidian version: v0.15.3
	Installer version: v0.14.6
	Operating system: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 21.5.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 30
	Safe mode: off
	Plugins installed: 60
	Plugins enabled: 58
		1: Divide & Conquer
		2: Pandoc Plugin
		3: Quiet Outline
		4: Regex Find/Replace
		5: Smart Typography
		6: Sortable
		7: System Dark Mode
		8: Tabout
		9: Obsidian Tabs
		10: Version History Diff
		11: Zotero Integration
		12: Obsidian42 - BRAT
		13: Omnisearch
		14: Periodic Notes
		15: Plugin Changelogs
		16: Advanced Tables
		17: Templater
		18: Workspaces Plus
		19: Block Reference Counter
		20: Obsidian Enhancing Export
		21: Pandoc Reference List
		22: Advanced URI
		23: Dynamic Highlights
		24: Pane Relief
		25: Obsidian Git
		26: Better File Link
		27: Admonition
		28: Advanced Mobile Toolbar
		29: Apply Patterns
		30: Better footnote
		31: BibNotes Formatter
		32: Calendar
		33: Code block from selection
		34: Contextual Typography
		35: Convert url to preview (iframe)
		36: Copy Block Link
		37: Dataview
		38: Dictionary
		39: Citation Style Translation
		40: Typewriter Scroll
		41: Quick Switcher++
		42: Garble Text
		43: Hotkey Helper
		44: Hotkeys++
		45: Lapel
		46: Markdown Table Editor
		47: Metadata Extractor
		48: Natural Language Dates
		49: Dynamic Table of Contents
		50: Electron Window Tweaker
		51: Focus Mode
		52: Hider
		53: Hotkeys for templates
		54: Obsidian Link Converter
		55: Hover Editor
		56: Minimal Theme Settings
		57: Style Settings
		58: Another Quick Switcher

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
This issue is due to bugs introduced in Obsidian 0.15.3 — I will come back to it when 0.15.4 is released
