### ISSUE TITLE
Jumping to end of a line in split pane view

### ISSUE THREAD

**Issue by aaronjz** [kepano/obsidian-minimal#359]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

5.3.0

### Describe the bug

I use Cmd + Right arrow to jump to the end of a line in all my writing software. But when I try to do so in split pane view (when my paragraphs are adjusted into more lines) using the Minimal theme, it jumps to the end of that current paragraph instead of the end of the line I'm on. 

This video shows the expected behavior of the cursor using the Default Obsidian theme, then shows the bug behavior in the Minimal theme.

https://user-images.githubusercontent.com/104883320/176980883-b65b67c5-b57a-4022-8b48-f74beb1b5109.mov

### Debug info

SYSTEM INFO:
	Obsidian version: v0.14.15
	Installer version: v0.14.6
	Operating system: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 21.5.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 24
	Plugins enabled: 17
		1: Calendar
		2: Auto Note Mover
		3: Advanced Tables
		4: Underline
		5: Natural Language Dates
		6: Better Word Count
		7: Advanced URI
		8: Typewriter Scroll
		9: Pandoc Plugin
		10: Bible Linker
		11: Periodic Notes
		12: Excalidraw
		13: Recent Files
		14: Smart Random Note
		15: Contextual Typography
		16: Quiet Outline
		17: Hider

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Comment by kepano** [comment]
I am not able to reproduce this issue. Also I am fairly certain that there is nothing in Minimal theme itself that could be causing this issue. I would recommend trying in a new vault without plugins and seeing if there is a plugin that is causing a conflict. You might also want to check your hotkeys to make sure there isn't a hotkey conflicting with the system binding that you are trying to use.

**Comment by aaronjz** [comment]
Thanks for the response. I tried it out again in a test vault. The issue I was encountering had to do with the Hider plugin. Sorry about that! I hadn’t fully tested the bug with each plugin.

Aaron

**Comment by eikowagenknecht** [comment]
Just leaving it here if anyone else is wondering:

For me it was the Style Settings plugin with the "Style Settings -> Minimal -> Line numbers -> Highlight active line" setting that caused this behaviour. Disabling this setting fixed it for me.

![image](https://github.com/kepano/obsidian-minimal/assets/1475672/8c45a7b7-fe1f-4777-b840-71291ddf1325)

**Comment by eikowagenknecht** [comment]
@kepano After a bit more research, it seems like this setting is provided by the Minimal theme? Then it would be good to add a warning there or maybe it can even be fixed?

https://github.com/kepano/obsidian-minimal/blob/c82c834bfcadd1c2d7ed9848e91a8b76cffb82da/src/css/style-settings.css#L1187
