### ISSUE TITLE
Make reading and live preview mode consistent with padding

### ISSUE THREAD

**Issue by DeutscheGabanna** [kepano/obsidian-minimal#360]
This is how reading mode looks like on a paragraph of text:
![image](https://user-images.githubusercontent.com/59067099/177615886-15da37be-4f66-4f87-8490-341bea783c5c.png)

This is how live preview looks like on a paragraph of text:
![image](https://user-images.githubusercontent.com/59067099/177615921-16b7fe3e-5384-44c2-9b45-5938ab5f0ed7.png)

Can't we have consistent looks on both modes?

**Comment by kepano** [comment]
The challenge here is that reading and editing have different uses and limitations. What you are describing is not necessarily desirable for all users. 

In edit mode the height of the line is defined by the height of the text on the line. Extra vertical padding is limited to help visualize empty lines for editing purposes. In reading mode, empty lines are usually not rendered (depending on your Obsidian settings), and spacing between elements is optimized for the reading experience.

I will look into making the vertical spacing more customizable, however it will be challenging to make them a perfect match.

**Comment by kepano** [comment]
@adampetrovic What you are describing is unrelated to the OP's suggestion. It looks like you are using Markdown loose lists. [See Obsidian forum](https://forum.obsidian.md/t/bullet-list-weird-spacing-if-empty-line-in-between/23511)

**Comment by kepano** [comment]
This should be improved as of Obsidian 1.3.7+ and Minimal 7.0. You can adjust the spacing in Style Settings > Minimal > Text
