### ISSUE TITLE
Compatibility with Image positions

### ISSUE THREAD

**Issue by Warden20** [kepano/obsidian-minimal#361]
**Is your feature request related to a problem? Please describe.**
With the last update the compatibility with this snippet is broken in live preview https://github.com/SlRvb/Obsidian--ITS-Theme/blob/main/Guide/Image-Positions.md 
It would be awesome if minimal will make it work again. The snippet stil works in the default theme.
Obsidian default theme
![after](https://user-images.githubusercontent.com/64172827/177655628-5b39089f-92bb-4cd4-9a29-515b1ca1ac88.JPG)
Minimal theme
![now](https://user-images.githubusercontent.com/64172827/177655629-666caf91-c28c-436d-87bd-508364405168.JPG)

**Describe the solution you'd like**
I would like this feature implemented to simplify the process of editing my notes

**Comment by kepano** [comment]
Compatibility with snippets is not in the scope of Minimal, you can [read more here](https://minimal.guide/Help#Compatibility+with+community+CSS+snippets). You will need to ask the snippet author for help making it compatible with Minimal.
