### ISSUE TITLE
Helper Class Not Working

### ISSUE THREAD

**Issue by ernest67** [kepano/obsidian-minimal#363]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

5.3.0

### Describe the bug

Despite adding a helper class so that the table could use max line width (cssClass: table-max) in editing mode, the table in the reading mode does not use max line width.
Editing Mode:
![Screenshot 2022-07-08 at 16 34 39](https://user-images.githubusercontent.com/95947701/177952194-8a413a29-a026-4ba7-817d-0a86e728a25e.png)

Reading Mode:
![Screenshot 2022-07-08 at 16 35 04](https://user-images.githubusercontent.com/95947701/177952277-b95f81d6-b99b-4c83-9a10-0dfb127367ab.png)

 Appreciate your kind help and thank you again for making the best theme for obsidian!

### Debug info

SYSTEM INFO:
	Obsidian version: v0.15.4
	Installer version: v0.12.19
	Operating system: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 21.5.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 27
	Plugins enabled: 20
		1: Admonition
		2: Minimal Theme Settings
		3: Advanced Tables
		4: Better Word Count
		5: Calendar
		6: Checklist
		7: Dataview
		8: Hider
		9: Hotkeys++
		10: Icons
		11: Kanban
		12: Mind Map
		13: Outliner
		14: Paste URL into selection
		15: Style Settings
		16: Indentation Guides
		17: Hover Editor
		18: Recent Files
		19: Electron Window Tweaker
		20: Sortable

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Contextual Typography plugin is required for this feature. Please remember to review documentation before opening a bug. https://minimal.guide/Features/Block+width
