### ISSUE TITLE
Scrollbars are weird since latest insider release; also horizontal whitespace

### ISSUE THREAD

**Issue by ryadaj** [kepano/obsidian-minimal#366]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

5.3.0

### Describe the bug

1) Since latest update to Minimal and/or Insider release, the scroll bars are no longer as nice looking as they used to be. This is shown in the attached screenshots along with item (2). Another screenshot (the one with the weird Omnisearch bug) is attached showing how scroll bars used to look. Scroll bars are like this in both notes and in other windows such as settings menu, sidebars, and quick switcher.

2) Horizontal white space appears after callouts (also shown in screenshot taken of an empty test vault with only Minimal installed and no other modifications)

_**Note: Both issues tested with and without snippets and plugins enabled, but debug info copied with plugins enabled**_

<img width="1800" alt="Screen Shot 2022-07-10 at 17 05 32" src="https://user-images.githubusercontent.com/82765301/178162096-29a75954-c9e0-4bdd-b9d6-7dd6df63484d.png">

<img width="1800" alt="Screen Shot 2022-07-10 at 17 03 28" src="https://user-images.githubusercontent.com/82765301/178162022-917b0dde-a8ee-42cd-a2f8-e8d85d5bb824.png">

<img width="1800" alt="Screen Shot 2022-07-10 at 16 59 22" src="https://user-images.githubusercontent.com/82765301/178161953-775f95fa-879d-486e-a25c-5a45ea160823.png">

<img width="731" alt="Screen Shot 2022-07-05 at 10 21 12" src="https://user-images.githubusercontent.com/82765301/178161994-fb892b56-b26e-49f2-85c1-449282b20994.png">

### Debug info

SYSTEM INFO:
	Obsidian version: v0.15.5
	Installer version: v0.14.15
	Operating system: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 21.5.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 5
	Safe mode: off
	Plugins installed: 24
	Plugins enabled: 24
		1: Advanced Tables
		2: Another Quick Switcher
		3: Banners
		4: Booksidian
		5: Contextual Typography
		6: Customizable Sidebar
		7: Dataview
		8: Excalidraw
		9: File Explorer Note Count
		10: Hover Editor
		11: Icon Shortcodes
		12: Kanban
		13: Kobo Highlights Importer
		14: Mind Map
		15: Minimal Theme Settings
		16: Natural Language Dates
		17: Obsidian Columns
		18: Omnisearch
		19: Pandoc Plugin
		20: Shortcuts extender
		21: Smarter Markdown Hotkeys
		22: Style Settings
		23: Tag Wrangler
		24: Various Complements

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Please update the theme to 5.3.1

Both of these issues are related to changes in Obsidian not Minimal.

The first issue is that Obsidian switched to native scrollbars on macOS. It looks like you have scrollbars set to show `Always`. You can change this in macOS `System Preferences > General` and set to `When scrolling`. Alternatively I have added a new option in Style Settings under `Minimal Advanced Settings` to return to the styled scrollbars.

The second issue is present in the default theme, unrelated to Minimal. You will need to open an issue with the plugin creator and/or with Obsidian team.

**Comment by ryadaj** [comment]
Amazing thank you so much! Really appreciate your help.

Devs pointed me here so apologies for the clutter.
