### ISSUE TITLE
Sliding Panes plugin not working properly with Minimal Theme

### ISSUE THREAD

**Issue by johnm-melvin** [kepano/obsidian-minimal#368]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

5.3.1

### Describe the bug

First of all, I would like to thank the developers for this awesome obsidian theme. It really changed my workflow!
Well, I'm experiencing a weird bug when using the Minimal Theme with the Sliding Panes plugin... The movement of the panels suddenly stops and the panes disappear on the sides of the window. Also, the panes' width doesn't seem to adjust correctly when more than 3 windows are opened. I wonder if somebody else is experiencing this...
I appreciate any help from you guys.
Thank you!

### Debug info

SYSTEM INFO:
	Obsidian version: v0.15.6
	Installer version: v0.11.13
	Operating system: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 21.5.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 10
	Plugins enabled: 8
		1: Imgur Plugin
		2: Clear Unused Images
		3: Minimal Theme Settings
		4: Style Settings
		5: Contextual Typography
		6: Advanced Tables
		7: Cycle through Panes
		8: Sliding Panes (Andy's Mode)

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

<img width="1169" alt="Captura de Tela 2022-07-12 às 16 05 57" src="https://user-images.githubusercontent.com/109174137/178575208-b678e8ed-439c-4d44-b569-03eb83015937.png">
<img width="1169" alt="Captura de Tela 2022-07-12 às 16 07 17" src="https://user-images.githubusercontent.com/109174137/178575379-b0c37f63-0206-491a-a4bf-8514848353fc.png">
<img width="1169" alt="Captura de Tela 2022-07-12 às 16 08 10" src="https://user-images.githubusercontent.com/109174137/178575399-e0d75aee-4c40-4712-9f88-eebe3eb41bce.png">

**Comment by kepano** [comment]
Given that the issue is present with the default theme, it should be opened on the Sliding Panes repo or in the Obsidian forum

**Comment by kepano** [comment]
I am not sure why this is happening. Perhaps @nothingislost can provide some insight on what has changed in recent versions of Sliding Panes that could cause this issue.

**Comment by kepano** [comment]
I am not sure why this is happening. Perhaps @deathau can provide some insight on what has changed in recent versions of Sliding Panes that could cause this issue.
