### ISSUE TITLE
Contiguous relationship lines in Edit mode

### ISSUE THREAD

**Issue by rodrigo-rufino** [kepano/obsidian-minimal#37]
Is there a way to make the relationship lines in Edit Mode contiguous like the ones in the Preview Mode?

Mine looks like this:
![Screenshot from 2021-10-07 11-05-47](https://user-images.githubusercontent.com/18670446/136401005-4491237c-cb12-4fae-8a28-b2027c0acecc.png)

**Comment by rodrigo-rufino** [comment]
I just tested and apparently is a conflict with the Outliner plugin. I disabled it and worked perfectly.

**Comment by kepano** [comment]
From what I can see this is affecting all themes that have relationship lines. I would suggest seeing if the Outliner author is aware of this issue.
