### ISSUE TITLE
Callout scroll bars not styled correctly

### ISSUE THREAD

**Issue by tim-hilde** [kepano/obsidian-minimal#371]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

5.3.1

### Describe the bug

Inside a callout the horizontal scroll bars are not styled like the vertical ones

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/44113468/179020515-7f33ca24-ce41-4ec2-ba18-3d9751f73226.png">

### Debug info

SYSTEM INFO:
	Obsidian version: v0.15.6
	Installer version: v0.14.6
	Operating system: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 21.5.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 30
	Safe mode: off
	Plugins installed: 63
	Plugins enabled: 63
		1: Divide & Conquer
		2: Style Settings
		3: Advanced Mobile Toolbar
		4: Better footnote
		5: BibNotes Formatter
		6: Block Reference Counter
		7: Calendar
		8: Citation Style Translation
		9: Typewriter Scroll
		10: Code block from selection
		11: Convert url to preview (iframe)
		12: Quick Switcher++
		13: Dataview
		14: Garble Text
		15: Hotkey Helper
		16: Hotkeys++
		17: Lapel
		18: Markdown Table Editor
		19: Natural Language Dates
		20: Admonition
		21: Advanced URI
		22: Another Quick Switcher
		23: Apply Patterns
		24: Contextual Typography
		25: Copy Block Link
		26: Dictionary
		27: Dynamic Highlights
		28: Dynamic Table of Contents
		29: Electron Window Tweaker
		30: Obsidian Enhancing Export
		31: Better File Link
		32: Obsidian Git
		33: Hider
		34: Hotkeys for templates
		35: Obsidian Link Converter
		36: Minimal Theme Settings
		37: Pandoc Plugin
		38: Quiet Outline
		39: Regex Find/Replace
		40: Smart Typography
		41: Sortable
		42: System Dark Mode
		43: Tabout
		44: Obsidian Tabs
		45: Version History Diff
		46: Zotero Integration
		47: Obsidian42 - BRAT
		48: Omnisearch
		49: Pane Relief
		50: Periodic Notes
		51: Plugin Changelogs
		52: Advanced Tables
		53: Templater
		54: Workspaces Plus
		55: Macros
		56: Creases
		57: Tag Wrangler
		58: Excalidraw
		59: Query Control
		60: Daily Stats
		61: Hover Editor
		62: Pandoc Reference List
		63: Metadata Extractor

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
This is fixed if you update to the latest
