### ISSUE TITLE
Quick Switcher++ : Open in symbol mode doesn't indent headings

### ISSUE THREAD

**Issue by hungquoc1410** [kepano/obsidian-minimal#374]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

5.3.1

### Describe the bug

<img width="1440" alt="Screen Shot 2022-07-15 at 13 16 37" src="https://user-images.githubusercontent.com/87603881/179162897-7c1e3de4-f638-44c4-8848-d49d053a293e.png">
Open Quick Switcher++ in symbol mode doesn't indent the headings making it harder to navigate.

### Debug info

SYSTEM INFO:
	Obsidian version: v0.15.6
	Installer version: v0.14.6
	Operating system: Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64 21.4.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 29
	Plugins enabled: 29
		1: Templater
		2: Dataview
		3: Periodic Notes
		4: Outliner
		5: QuickAdd
		6: Hider
		7: Minimal Theme Settings
		8: Style Settings
		9: Smart Random Note
		10: Toggl Track
		11: Number Headings
		12: Linter
		13: Admonition
		14: cMenu
		15: File Explorer Note Count
		16: Find and replace in selection
		17: Obsidian Tabs
		18: Pluck
		19: Version History Diff
		20: Clear Unused Images
		21: Podcast Note
		22: Smart Typography
		23: Calendar
		24: Zoom
		25: Quick Switcher++
		26: Typewriter Scroll
		27: Tasks
		28: Tag Wrangler
		29: Advanced Tables

**Comment by kepano** [comment]
Can you show screenshots of the intended behavior?

**Comment by hungquoc1410** [comment]
![image](https://user-images.githubusercontent.com/87603881/179337414-798ec875-9df7-4acf-9b9b-5682d26257cd.png)
It supposes to look like this
