### ISSUE TITLE
Problem with "Focus mode" and Obsidian Tabs plugin

### ISSUE THREAD

**Issue by ironhak** [kepano/obsidian-minimal#375]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

5.3.1

### Describe the bug

First of all "Focus mode" is an amazing feature, but when used with [Obsidian tabs](https://github.com/gitobsidiantutorial/obsidian-tabs) plugin I can't no more know what tabs to look for because title is hidden. Here's an example:
- Focus mode off 
![image](https://user-images.githubusercontent.com/62611612/179751815-f8865f8f-6b30-4055-9dbd-d975c0943d0e.png)
- Focus mode on
![image](https://user-images.githubusercontent.com/62611612/179751880-5e76e26d-45c2-4c44-a8a6-45857babe9b9.png)

As you can see if I want to change tab it's impossible to know which one it's the one I'm looking for. It would be nice to have the option to apply focus mode to everything but notes title or to hide notes title only on current note if there are multiple notes open. 
Focus mode makes the use of obsidian much more pleasant and this is the only thing that's buggin me, hope I've explain the issue in a good way. 

Thank's for your time and your contribution on here. 

### Debug info

SYSTEM INFO:
	Obsidian version: v0.15.6
	Installer version: v0.14.15
	Operating system: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 21.5.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 1
	Safe mode: off
	Plugins installed: 23
	Plugins enabled: 23
		1: Style Settings
		2: File path to URI
		3: Image Toolkit
		4: Clear Unused Images
		5: Paste URL into selection
		6: Wikilinks to MDLinks
		7: Highlightr
		8: Hider
		9: Zoom
		10: Obsidian Tabs
		11: Typewriter Scroll
		12: Underline
		13: Minimal Theme Settings
		14: Natural Language Dates
		15: Media Extended
		16: Waypoint
		17: Advanced Tables
		18: Templater
		19: Kindle Highlights
		20: Dataview
		21: Calendar
		22: Cycle through Panes
		23: Hotkeys for starred files and searches

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
This will probably not get fixed because the next version of Obsidian will include tabs natively

**Comment by ironhak** [comment]
Well, good to know then!!! Thank's :)
