### ISSUE TITLE
Search result highlighting looks bad

### ISSUE THREAD

**Issue by memeplex** [kepano/obsidian-minimal#376]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

5.3.1

### Describe the bug

For example, after following a linked reference to A I see this:

<img width="263" alt="image" src="https://user-images.githubusercontent.com/2845433/179844617-790a7956-f8b5-4c52-932f-18a4488eada0.png">

### Debug info

SYSTEM INFO:
	Obsidian version: v0.15.6
	Installer version: v0.15.6
	Operating system: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 21.5.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 5
	Plugins enabled: 5
		1: Calendar
		2: Dataview
		3: Minimal Theme Settings
		4: Outliner
		5: Advanced Tables

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by memeplex** [comment]
It's not the case for a Cmd-f search:

<img width="47" alt="image" src="https://user-images.githubusercontent.com/2845433/179845028-679ee0d8-1fe0-45a3-a6b8-064a69bf82fb.png">

**Comment by memeplex** [comment]
This is for a linked mention of an image:

![image](https://user-images.githubusercontent.com/2845433/179846023-c2016fe9-1b8e-47d2-92b8-b2a3c4c49bdc.png)

It's like there is a separate box around delimited text fragments, with delimiters being [, ], |, etc. This level of detail doesn't look good and indeed obscures the match. It's not very noticeable when using the default theme because it just subtly highlights the background instead of boxing contents.

**Comment by kepano** [comment]
This is a bug with Obsidian not Minimal. It will be fixed in the next major version of Obsidian.

**Comment by memeplex** [comment]
Hi, thanks for the info, with "next major version" you mean 0.16.x, right?

**Comment by kepano** [comment]
Yes

**Comment by memeplex** [comment]
Probably the same issue, but just as a heads up, tags show a similar glitch:

<img width="59" alt="image" src="https://user-images.githubusercontent.com/2845433/183988964-1c02a5c5-4ac4-4e5f-8618-f4c6941dac65.png">
