### ISSUE TITLE
numbered lists and todos are in conflict

### ISSUE THREAD

**Issue by dpetrouk** [kepano/obsidian-minimal#377]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

5.3.0

### Describe the bug

A picture is worth a thousand words:
![num list and todo](https://user-images.githubusercontent.com/30505853/180066467-a18efb9f-777b-43d7-ba90-4cedeaae9602.PNG)

### Debug info

SYSTEM INFO:
	Obsidian version: v0.15.6
	Installer version: v0.13.23
	Operating system: Windows 10 Enterprise 2016 LTSB 10.0.14393
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Safe mode: on

**Comment by dsteinbock** [comment]
+1 to this bug

<img width="278" alt="Screen Shot 2022-10-20 at 12 46 40 PM" src="https://user-images.githubusercontent.com/4734875/197044106-417dbbea-f402-451e-ada9-f1e36899ba66.png">

**Comment by kepano** [comment]
Closed in [Minimal 6.1.0](https://github.com/kepano/obsidian-minimal/releases/tag/6.1.0)

**Comment by jonmseaman** [comment]
Thanks!
