### ISSUE TITLE
Block Reference Counter plugin displayed incorrectly in editing mode & live preview

### ISSUE THREAD

**Issue by Dirtyuri** [kepano/obsidian-minimal#378]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

5.3.1

### Describe the bug

The inline references are displayed at the max width of the pane, 

![1658541145188](https://user-images.githubusercontent.com/68465099/180585983-07be8f8d-192a-4f28-9d12-cca6d944d8f9.png)

which should have been as wide as the content.

![1658541188595](https://user-images.githubusercontent.com/68465099/180586037-a8eaa250-fcc5-4185-af36-cf270825a87f.png)

### Debug info

SYSTEM INFO:
	Obsidian version: v0.15.8
	Installer version: v0.15.6
	Operating system: Windows 10 Home China 10.0.22000
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: adapt to system
	Community theme: Minimal
	Snippets enabled: 1
	Safe mode: off
	Plugins installed: 26
	Plugins enabled: 26
		1: Sliding Panes (Andy's Mode)
		2: Calendar
		3: Dataview
		4: Excalidraw
		5: Hotkeys++
		6: Note Refactor
		7: Pane Relief
		8: Periodic Notes
		9: Style Settings
		10: Tag Wrangler
		11: Text Format
		12: Wikipedia
		13: Workspaces Plus
		14: Kanban
		15: Sortable
		16: Recent Files
		17: Advanced Tables
		18: Paste URL into selection
		19: Auto Link Title
		20: Better Word Count
		21: Convert url to preview (iframe)
		22: Hover Editor
		23: Buttons
		24: Natural Language Dates
		25: Collapse All
		26: Block Reference Counter

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by nicolasmarc1** [comment]
Hello, same issue for me, besides the max-width, there is also the fact that you can't click on the control buttons (it instead open the first result when you click them)
Thanks!

**Comment by kepano** [comment]
The Block Reference Counts plugin has been archived is no longer maintained
