### ISSUE TITLE
Uninstall button not clickable

### ISSUE THREAD

**Issue by DeutscheGabanna** [kepano/obsidian-minimal#380]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

5.3.0

### Describe the bug

![image](https://user-images.githubusercontent.com/59067099/180461391-a7718b73-5033-4613-9fac-382d8097e5c6.png)

### Debug info

app.js:1 Uncaught (in promise) Error: EPERM: operation not permitted, rmdir 'C:\Users\username\Google Drive\Repozytorium\Obsidian notes\Allegro\.obsidian\plugins\buttons'

when clicking the button for uninstalling plugin 'buttons'

**Comment by kepano** [comment]
This seems unrelated to Minimal.
