### ISSUE TITLE
Link font weight not work

### ISSUE THREAD

**Issue by aooaa** [kepano/obsidian-minimal#382]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

5.3.2

### Describe the bug

link font weight setting not responds when change the value. both not work on PC and Mobile.
setting location: Setting > Style setting > Links > Link font weight

### Debug info

SYSTEM INFO:
 Operating system: ios 15.5 (Apple iPhone)
 Obsidian version: 1.3.0 (63)
 API version: v0.15.6
 Login status: logged in
 Catalyst license: none
 Live preview: on
 Legacy editor: off
 Base theme: light
 Community theme: California Coast
 Snippets enabled: 0
 Safe mode: off
 Plugins installed: 2
 Plugins enabled: 2
  1: Style Settings
  2: Minimal Theme Settings

RECOMMENDATIONS:
 Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
 Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
I am not able to reproduce. Can you share and export of your Style Settings?

**Comment by aooaa** [comment]
Sorry, I just re-test the link font weight. It works well. but thanks for your help.
