### ISSUE TITLE
Dot not in middle when line height not 1.5

### ISSUE THREAD

**Issue by Zhicheng2914** [kepano/obsidian-minimal#384]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

5.3.2

### Describe the bug

Dot when line height set as 2 in minimal theme settings, not in center

![image](https://user-images.githubusercontent.com/17692778/181713296-38c0f4f9-5c31-4a3e-b518-7789c4db4f96.png)

This is 1.5 line height

![image](https://user-images.githubusercontent.com/17692778/181713671-f6fddc2b-40f6-43cc-9fca-840cb27ce9a2.png)

### Debug info

SYSTEM INFO:
	Obsidian version: v0.15.9
	Installer version: v0.14.15
	Operating system: Windows 10 Pro 10.0.22000
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 3
	Restricted mode: off
	Plugins installed: 45
	Plugins enabled: 34
		1: Calendar v1.5.10
		2: Advanced Tables v0.17.3
		3: Stille v1.2.1
		4: Recent Files v1.3.3
		5: Collapse All v1.5.2
		6: File path to URI v1.4.0
		7: Note Folder Autorename v0.1.2
		8: Folder Note v0.7.3
		9: Style Settings v0.4.10
		10: Minimal Theme Settings v5.3.2
		11: Dataview v0.5.41
		12: Templater v1.12.0
		13: Frontmatter Tag Suggest v0.4.1
		14: Better Word Count v0.8.1
		15: Obsidian Charts v3.6.2
		16: Tag Wrangler v0.5.3
		17: Admonition v9.0.3
		18: Customizable Sidebar v2.2.1
		19: Hotkeys for specific files v1.2.0
		20: Local images v0.14.2
		21: Kanban v1.3.11
		22: Excel to Markdown Table v0.4.0
		23: Dictionary v2.21.1
		24: Hider v1.1.1
		25: Sortable v0.2.5
		26: Contextual Typography v2.2.4
		27: Banners v1.3.3
		28: Tasks v1.11.0
		29: Advanced Slides v1.15.0
		30: QuickAdd v0.5.5
		31: Remember cursor position v1.0.7
		32: Excalidraw v1.7.8
		33: Flashcards v1.6.3
		34: LanguageTool Integration v0.3.0

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
This will be fixed in Minimal 6.0 which will be coincide with the next major version of Obsidian
