### ISSUE TITLE
Background of nested code blocks displayed improperly

### ISSUE THREAD

**Issue by Gadiguibou** [kepano/obsidian-minimal#385]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

5.3.2

### Describe the bug

In "Live Preview" or "Source Mode" create some bullet points and nested code blocks under them with Shift-Enter. Notice the improperly indented first line of each code block and how their overall indentation does not match the indentation level of the bullet point.

**In Live Preview with Minimal theme:**

<img width="670" alt="Screenshot 2022-08-01 at 13 13 36" src="https://user-images.githubusercontent.com/34945306/182205563-e01368f9-931c-41d9-8553-18e3205bb0d8.png">

**In Source Mode with Minimal theme:**

<img width="657" alt="Screenshot 2022-08-01 at 13 13 50" src="https://user-images.githubusercontent.com/34945306/182205630-0f376ab3-263e-4a66-abfb-04b65c8fafe2.png">

**In Reading with Minimal theme (_expected behavior_)**:

<img width="655" alt="Screenshot 2022-08-01 at 13 14 07" src="https://user-images.githubusercontent.com/34945306/182205709-73da525e-c64f-47d3-b942-a14a601a857b.png">

**In Live Preview with default theme:**

<img width="711" alt="Screenshot 2022-08-01 at 13 16 47" src="https://user-images.githubusercontent.com/34945306/182205867-360a00c5-fd3c-49a0-94ba-8f048191a3de.png">

**In Source Mode with default theme:**

<img width="735" alt="Screenshot 2022-08-01 at 13 18 36" src="https://user-images.githubusercontent.com/34945306/182206167-36cd3501-2a44-4aab-9a19-1db03f31410f.png">

### Debug info

SYSTEM INFO:
	Obsidian version: v0.15.9
	Installer version: v0.15.9
	Operating system: Darwin Kernel Version 22.0.0: Wed Jul 20 01:53:56 PDT 2022; root:xnu-8792.0.188.141.3~2/RELEASE_ARM64_T6000 22.0.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: adapt to system
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 0

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.

**Comment by tslaton** [comment]
I'm still seeing this issue in Obsidian v1.1.9 on macOS 13.1 (22C65)

**Comment by kepano** [comment]
I believe this should be fixed in 7.0 — or at least the behavior is now similar to default theme
