### ISSUE TITLE
[Feature Request] better support for the database folder plugin

### ISSUE THREAD

**Issue by afland** [kepano/obsidian-minimal#386]
I'm not certain how much minimal can do about these suggestions, but I'll attach some screenshots + descriptions anyway. 

When you scroll horizontally to the right, the top bar of the database ends and transitions with this weird shadow effect to the same color. 
![image](https://user-images.githubusercontent.com/67392684/183237645-875c5e92-c937-49c5-ae2a-4956843ebaa2.png)
There are also those awkward double lines at the bottom of the top bar. 

This is a little more petty, but I find the contrast of the template selector's outline to be excessive/distracting
![image](https://user-images.githubusercontent.com/67392684/183237667-f5cbb136-23f9-4c3b-af36-4b323fa32633.png)

Also more petty, but if you hover over/highlight any item in the top row (the ones that define the column names), this weird bar at the right appears. Looks like a scrollbar, but there's definitely no scrolling function there. 
![image](https://user-images.githubusercontent.com/67392684/183237761-fbb6e63b-e829-4ab7-87cb-e8ffe3ae72b8.png)

**Comment by kepano** [comment]
See #451 — I do not plan to support DB folder
