### ISSUE TITLE
Floating Edit/View Button

### ISSUE THREAD

**Issue by jandamm** [kepano/obsidian-minimal#390]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to switch to the edit/viewer mode on my phone and have to reach to the top bar.

**Describe the solution you'd like**
I would like to have this button placed in the bottom right corner so it's easy to press on mobile devices.
The popular things theme has such a feature.

**Comment by codey-badger** [comment]
@jandamm I share your frustration, did you find a solution? I would want to stay in minimal.

**Comment by jandamm** [comment]
I switched to the Things theme and finally stopped using Obsidian altogether.
