### ISSUE TITLE
a strange wireframe under unlinked mentions

### ISSUE THREAD

**Issue by biorz** [kepano/obsidian-minimal#391]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

5.3.2

### Describe the bug

![9741C6B9-69B2-420B-8877-3BC6FC95027B](https://user-images.githubusercontent.com/15077010/183837444-7bd53c95-361d-4d3f-978f-0cd8138ea531.png)

a strange wireframe under unlinked mentions

### Debug info

SYSTEM INFO:
	Obsidian version: v0.15.9
	Installer version: v0.14.6
	Operating system: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 21.5.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: on

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.

**Comment by kepano** [comment]
This is present in default theme
