### ISSUE TITLE
Headings format not show in Live Preview

### ISSUE THREAD

**Issue by edu-zam** [kepano/obsidian-minimal#393]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

5.3.2

### Describe the bug

When I turn the Live preview or Source mode, all of the headings lost this format. It's appears like standart text.
When I go to Reading Mode, the correct format appear

### Debug info

SYSTEM INFO:
	Obsidian version: v0.15.9
	Installer version: v0.15.9
	Operating system: Windows 10 Pro 10.0.22000
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 22
	Plugins enabled: 20
		1: Hotkeys++ v0.2.7
		2: Cycle through Panes v0.1.0
		3: Calendar v1.5.10
		4: Minimal Theme Settings v5.3.2
		5: Outliner v2.4.0
		6: Paste URL into selection v1.7.0
		7: LanguageTool Integration v0.3.0
		8: Local images v0.14.2
		9: Dataview v0.5.41
		10: Smart Random Note v0.2.1
		11: Clear Unused Images v1.0.6
		12: Privacy Glasses v0.5.2
		13: cMenu v1.1.2
		14: Recent Files v1.3.3
		15: Image Toolkit v1.3.1
		16: Emoji Toolbar v0.3.1
		17: Linter v1.4.3
		18: QuickAdd v0.5.5
		19: Templater v1.12.0
		20: Style Settings v0.4.10

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Can you share screenshots? I am now able to reproduce

**Comment by edu-zam** [comment]
![headings](https://user-images.githubusercontent.com/74326159/185406016-a45ee2a2-8175-4420-858f-68d19d291dd7.gif)
Thanks for the quick reply

**Comment by kepano** [comment]
Are you sure this is not happening in the default theme? This does not seem related to Minimal as far as I can tell.
