### ISSUE TITLE
Multiline quotes don't indent corectally in 

### ISSUE THREAD

**Issue by jbytes1027** [kepano/obsidian-minimal#395]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

5.3.1

### Describe the bug

Indentation is inconsistent in editing mode for multi-line quotes. The first and following lines do not match up. The indentations in the screenshots are with tabs. There is an issue with using spaces also but it is less pronounced.

![Screenshot 2022-08-21 173243](https://user-images.githubusercontent.com/50090107/185811865-d52275e4-3ba0-483f-9833-b3b87083e75a.png)
![Screenshot 2022-08-21 173221](https://user-images.githubusercontent.com/50090107/185811867-69c7dde1-4609-450b-987a-130bf374a3a7.png)
![Screenshot 2022-08-21 173302](https://user-images.githubusercontent.com/50090107/185811869-6efadd18-6c4c-4a5e-b6a4-8756370d7d07.png)

### Debug info

SYSTEM INFO:
	Obsidian version: v0.15.9
	Installer version: v0.15.9
	Operating system: Windows 10 Pro 10.0.22000
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 5
	Plugins enabled: 0

**Comment by kepano** [comment]
This is a known Obsidian bug, unrelated to Minimal
