### ISSUE TITLE
More code block highlight options?

### ISSUE THREAD

**Issue by I7T5** [kepano/obsidian-minimal#398]
User of the [OneDark Pro](https://github.com/Binaryify/OneDark-Pro) theme. Not to say the current highlighting colors are unpleasant. They're actually great too. 
Would be better if there were more code-block highlighting options which enables this.

**Comment by kepano** [comment]
Syntax highlighting has been added in Minimal 6.0.4 via Style Settings
https://github.com/kepano/obsidian-minimal/releases/tag/6.0.4
