### ISSUE TITLE
No horizontal scrollbars in side panels

### ISSUE THREAD

**Issue by toroworx** [kepano/obsidian-minimal#399]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

5.3.2

### Describe the bug

The sidepanels don't show horizontal scrollbars. This is annoying, especially with nested files, you can't decrease the sidebar width and still see the files.

The following CSS snippet fixes the navigation sidebar and the tags sidebar. The tags sidebar is not fully correctly fixed, but the horizontal scrollbar is included. There are likely more sidepanels which don't have a horizontal scrollbar.

    /* Adds horizontal scrollbars */
    
    /* Navigation sidebar */
    .nav-files-container
    {
        overflow: auto;
    }
    
    .nav-file-title
    {
        width: max-content;
    }
    
    /* Tags sidebar */
    .tree-item-inner, .search-result-file-title
    {
        overflow:visible;
    }

I really love this theme, IMO the best Obsidian theme. Thanks and keep up the good work!

### Debug info

-

**Comment by kepano** [comment]
This it's intentional. You can always turn off file name trimming in Minimal Theme Settings

**Comment by toroworx** [comment]
I turned off `Trim file names in sidebars`, restarted Obsidian and there are still no horizontal scrollbars.

I understand you prefer the theme as minimalistic as possible, but I think this works counterproductive. If you don't plan to include it, it's at least possible to work around it with the code mentioned above with a custom CSS snippet (Appearance > CSS snippet).

**Comment by kepano** [comment]
Thanks! I would recommend sharing snippets in the forum thread about Minimal customization, since it is more likely to be seen there:

https://forum.obsidian.md/t/share-your-minimal-theme-screenshots-configuration/8983
