### ISSUE TITLE
Making search results/backlinks slightly higher contrast/more prominent?

### ISSUE THREAD

**Issue by cansar** [kepano/obsidian-minimal#40]
Just a suggestion: This may totally be me but while I think Minimal is (by far!) the best Obsidian theme I recently noticed that I find the backlinks and search results a bit washed out and that I find those features harder to use than I previously realized.

**Comment by kepano** [comment]
I am certain that my eyesight will eventually agree with you, but for now the lower contrast is a deliberate choice that I've been happy with and don't plan to change. That said, you can simply create a CSS snippet that adjusts these variables:

```
.theme-light {
--text-muted: #000;
}
.theme-dark {
--text-muted: #FFF;
}
```
