### ISSUE TITLE
Window title bar background not consistent in high-contrast mode

### ISSUE THREAD

**Issue by wowo101** [kepano/obsidian-minimal#401]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.0.0

### Describe the bug

On macOS, since Obsidian 0.16 the window title bar background not consistent in high-contrast mode: There is a grey area in the top left corner. In other modes the area has the same colour as the rest of the bar.

<img width="386" alt="Screenshot 2022-09-02 at 09 49 03" src="https://user-images.githubusercontent.com/37489/188101989-9c1487eb-b0ea-4cc7-96c5-b6bf7cf5bb54.png">

### Debug info

SYSTEM INFO:
	Obsidian version: v0.16.1
	Installer version: v0.14.6
	Operating system: Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 21.6.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: off
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 28
	Plugins enabled: 25
		1: Text Format v1.8.1
		2: Calendar v1.5.10
		3: Charts View v1.1.9
		4: Contextual Typography v2.2.4
		5: DEVONlink v2.2.1
		6: Dictionary v2.21.1
		7: Focus Mode v1.9.0
		8: Hotkey Helper v0.3.15
		9: Minimal Theme Settings v6.0.0
		10: Note Refactor v1.7.1
		11: Smart Typography v1.0.18
		12: Sortable v0.2.6
		13: Style Settings v0.4.11
		14: Readwise Official v2.0.1
		15: Native Scrollbars v1.0.1
		16: File Explorer Note Count v1.2.0
		17: Obsidian Git v1.31.0
		18: Reading Time v1.1.1
		19: Better Word Count v0.8.1
		20: Dataview v0.5.43
		21: Pandoc Plugin v0.2.5
		22: Obsidian TODO | Text-based GTD v0.2.7
		23: Better footnote v1.0.1
		24: Pane Relief v0.3.0
		25: Sliding Panes (Andy's Mode) v3.4.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Fixed in 6.0.2
