### ISSUE TITLE
Line numbers not displaying after upgrade to Obsidian v.0.16.0/1

### ISSUE THREAD

**Issue by jamietr1** [kepano/obsidian-minimal#402]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.0.0

### Describe the bug

When the Editor > Show Line Number feature is enabled in Obsidian, the line numbers no longer show up in the gutter when the Minimal theme is active. If I use the default them, this is what I see:

![image](https://user-images.githubusercontent.com/3660885/188131815-ac111325-518c-4f5a-ae3a-42a3c40e2908.png)

With the Minimal theme enabled, I see the following. Note that the red arrows point to pixels at the very edge of the gutter which I think are the right edges of the line numbers, but they are offset to far that you can't see them, and no matter how I move panes around or resize, they always look like this:

![image](https://user-images.githubusercontent.com/3660885/188132027-1c71ff4f-2db0-4284-89fc-5000a440e876.png)

This has been happening ever since I upgraded to Obsidian v.0.16.0 (and 0.16.1)

### Debug info

SYSTEM INFO:
	Obsidian version: v0.16.1
	Installer version: v0.15.9
	Operating system: Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:35 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T8101 21.6.0
	Login status: logged in
	Catalyst license: vip
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 14
	Plugins enabled: 14
		1: Sliding Panes (Andy's Mode) v3.3.0
		2: Vimrc Support v0.7.2
		3: Advanced Tables v0.17.3
		4: Auto Link Title v1.2.5
		5: Calendar v1.5.10
		6: Contextual Typography v2.2.4
		7: Dataview v0.5.43
		8: Dice Roller v8.6.4
		9: Minimal Theme Settings v6.0.0
		10: Natural Language Dates v0.6.1
		11: QuickAdd v0.5.5
		12: Style Settings v0.4.10
		13: Templater v1.12.0
		14: TTRPG Statblocks v2.17.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Have you tried updating the theme? This was fixed a couple days ago.

**Comment by jamietr1** [comment]
Hmm? When I "Check for updates" in my themes, Obsidian reports none. When I look at the installed Minimal theme, it says 6.0.0. But when I look here on GitHub, I see the latest theme release as 5.3.2. Should I be seeing a release > 6.0.0?

**Comment by kepano** [comment]
Try updating again

**Comment by jamietr1** [comment]
I just updated to 6.0.1 and that fixed the problem! Thanks for the help!
