### ISSUE TITLE
Colorful window frame isn't entirely hidden in focus mode

### ISSUE THREAD

**Issue by frankreporting** [kepano/obsidian-minimal#403]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.0

### Describe the bug

When using colorful window frame and going into focus mode, the upper left corner behind the traffic lights still retains a little chunk of colored background, when it appears it should be hidden completely. See below:

<img width="118" alt="Screen Shot 2022-09-02 at 3 53 46 PM" src="https://user-images.githubusercontent.com/2828254/188244409-aa2217c3-d1a4-46e0-ae10-354eefb8df1e.png">

In addition, when colorful window frame is disabled, there's a phantom border retained when the ribbon disappears, as in the screenshot below:

<img width="103" alt="Screen Shot 2022-09-02 at 3 59 10 PM" src="https://user-images.githubusercontent.com/2828254/188244553-f5c53131-210f-477a-ab41-b70ea4193cc0.png">

### Debug info

SYSTEM INFO:
	Obsidian version: v0.16.2
	Installer version: v0.14.15
	Operating system: Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 21.6.0
	Login status: logged in
	Catalyst license: vip
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 9
	Restricted mode: off
	Plugins installed: 64
	Plugins enabled: 61
		1: MetaEdit v1.7.2
		2: Remember cursor position v1.0.7
		3: QuickAdd v0.5.5
		4: Quick Switcher++ v2.0.7
		5: Paste URL into selection v1.7.0
		6: Pane Relief v0.3.1
		7: Pandoc Plugin v0.2.5
		8: Note Folder Autorename v0.1.2
		9: Natural Language Dates v0.6.1
		10: Multi-cursor v0.0.2
		11: Minimal Theme Settings v6.0.2
		12: Markdown Attributes v1.1.1
		13: Obsidian42 - Jump-to-Date v1.0.12
		14: Obsidian42 - BRAT v0.6.35
		15: Readwise Official v2.0.1
		16: Link Favicons v1.7.4
		17: Imgur Plugin v2.2.1
		18: Hotkeys++ v0.2.7
		19: Hotkeys for templates v1.4.3
		20: Templater v1.13.0
		21: Typewriter Scroll v0.2.2
		22: Get Info v1.1.0
		23: CustomJS v1.0.12
		24: Dataview v0.5.43
		25: Advanced Cursors v0.5.1
		26: Advanced Mobile Toolbar v1.7.7
		27: Advanced Slides v1.17.6
		28: Advanced Tables v0.17.3
		29: Advanced URI v1.24.0
		30: Another Quick Switcher v6.3.2
		31: Auto Link Title v1.2.5
		32: Better Word Count v0.8.1
		33: Calendar v1.5.10
		34: Citations v0.4.4
		35: Contextual Typography v2.2.4
		36: Copy as HTML v1.0.5
		37: Customizable Page Header and Title Bar v4.7.2
		38: Editor Syntax Highlight v0.1.3
		39: Find orphaned files and broken links v1.6.1
		40: Focus Mode v1.9.0
		41: Folder Note v0.7.3
		42: Show Whitespace v0.3.1
		43: Sortable v0.2.6
		44: Style Settings v0.4.11
		45: Tag Wrangler v0.5.3
		46: Task Collector (TC) v0.7.8
		47: User Plugins v1.3.0
		48: Wikilinks to MDLinks v0.0.12
		49: Note Auto Creator v1.2.0
		50: Reading Time v1.1.1
		51: Code Editor Shortcuts v1.10.0
		52: Metadata Menu v0.1.27
		53: Native Scrollbars v1.0.1
		54: Periodic Notes v1.0.0-beta.3
		55: Excalidraw v1.7.18
		56: Settings Search v1.2.0
		57: Hard Breaks v0.1.1
		58: Hotkey Helper v0.3.15
		59: Outliner v3.0.0
		60: Obsidian Better Internal Link Inserter v1.0.0
		61: Hider v1.2.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by wowo101** [comment]
This seems related to/have the same root cause as https://github.com/kepano/obsidian-minimal/issues/401#issue-1359896006.
