### ISSUE TITLE
Cannot modify font

### ISSUE THREAD

**Issue by ZhenlongMa** [kepano/obsidian-minimal#406]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

5.3.2

### Describe the bug

After I updated minimal theme, I have found that Custom fonts in Minimal Theme Settings doesn't work. No matter what I set, the font displayed in the main interface won't change. Could you please tell me how I can customize the font? Thanks

### Debug info

SYSTEM INFO:
	Obsidian version: v0.13.23
	Installer version: v0.12.19
	Operating system: Windows 10 Pro 10.0.19044
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: on
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 4
	Safe mode: off
	Plugins installed: 5
	Plugins enabled: 2
		1: Style Settings
		2: Minimal Theme Settings

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Comment by kepano** [comment]
I am not able to reproduce. Also note that version 5.3.2 is no longer supported.
