### ISSUE TITLE
Search result highlighted in dark but unable to recognize

### ISSUE THREAD

**Issue by lesca** [kepano/obsidian-minimal#407]
### Is the bug present when using the default Obsidian theme?

No. 

### Is the bug present when snippets and plugins are disabled?

Yes. 

### Minimal theme version

5.3.2

### Describe the bug

The bug conditions:
1. dark mode
2. live preview mode or source mode
3. search results highlighted in code block (enclosed with <code>```</code> or <code>`</code>)

bug example as below:
![image](https://user-images.githubusercontent.com/5976219/188366245-6a9b00ad-e499-481c-8922-660b793be2b4.png)

it won't happen if it's highlighted in body, header, etc.
![image](https://user-images.githubusercontent.com/5976219/188366371-7fee7429-10b5-42a9-829a-f2448d0835cd.png)

My current color settings
![image](https://user-images.githubusercontent.com/5976219/188366203-7434c288-c4d8-4d8d-8ec1-ff639ad87ff6.png)

It would be grateful to fix this or provide a workaround. Thanks. 

### Debug info

```
SYSTEM INFO:
	Obsidian version: v0.15.9
	Installer version: v0.14.6
	Operating system: Windows 10 Enterprise 10.0.22000
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 11
	Plugins enabled: 11
		1: Advanced Tables v0.17.3
		2: File Explorer Note Count v1.2.0
		3: Tag Wrangler v0.5.3
		4: Wrap with shortcuts v1.1.0
		5: Excalidraw v1.7.19
		6: Obsidian Git v1.31.0
		7: Hotkeys++ v0.2.7
		8: Consistent attachments and links v1.0.8
		9: Unique attachments v1.0.3
		10: Excel to Markdown Table v0.4.0
		11: Minimal Theme Settings v5.3.2

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

```

**Comment by kepano** [comment]
Unable to reproduce with Obsidian 1.0 and Minimal 6.0.12
