### ISSUE TITLE
Tabs and Find/Replace are overlapping in focus mode

### ISSUE THREAD

**Issue by nickchomey** [kepano/obsidian-minimal#409]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.0.4

### Describe the bug

The tabs and Find/replace modals overlap each other, such that you can't use the Find text box or related buttons

![image](https://user-images.githubusercontent.com/88559987/188967323-a7a9724f-4b8b-49ba-bcb2-e51cab1afa6b.png)

### Debug info

SYSTEM INFO:
	Obsidian version: v0.16.2
	Installer version: v0.15.9
	Operating system: Windows 10 Home 10.0.22622
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 71
	Plugins enabled: 2
		1: Minimal Theme Settings v6.0.5
		2: Style Settings v0.4.11

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
You mean in focus mode?
