### ISSUE TITLE
Disabling maximize image on click?

### ISSUE THREAD

**Issue by cansar** [kepano/obsidian-minimal#41]
Pardon the 2 issues in one day, I promise I’ll be done after this: Is there an easy way to disable the image maximize on mouse press behavior via custom css or a future setting (if it’s of interest to others)? I tried it myself via CSS but couldn’t quite make it work. It’s really helpful but I tend to stare at zoomed images for work and found that there are plugins that do this without having to keep the mouse button pressed. Thank you again for this incredible theme.

**Comment by kepano** [comment]
Sorry, I misunderstood your request. The click/hold to zoom is not a setting yet but you should be able to revert that behavior with a snippet.

**Comment by accept82** [comment]
Good day! Please describe in detail how to fix this, I am using a third-party plugin for working with images and your setting in the theme interferes very much. Or, make a separate setting in your Minimal Theme Settings plugin that will disable this enlargement of the photo.

**Comment by kepano** [comment]
This is solved [as of 4.1.0](https://github.com/kepano/obsidian-minimal/releases/tag/4.1.0) using the new Style Settings toggle

**Comment by accept82** [comment]
> This is solved [as of 4.1.0](https://github.com/kepano/obsidian-minimal/releases/tag/4.1.0) using the new Style Settings toggle

I can't find this setting, can you tell me how to do it step by step?

**Comment by kepano** [comment]
`Style Settings > Minimal Theme > Features > Disable image zoom`

**Comment by cansar** [comment]
Also note that you need to install the "Style Settings" plugin separately.

**Comment by accept82** [comment]
Guys! Thank you so much for your help, it worked!

**Comment by Graywaren** [comment]
Excuse the necro, but I'm leaving this here in case anyone else stumbles on it from google searching and, like me, doesn't want to have to install the Style Settings plug-in just to turn this off. I was able to disable it using this css in a snippet:
```
/* Disables Minimal Theme Image Zoom On Click */
body:not(.zoom-off):not(.is-mobile) .workspace-leaf-content[data-type=markdown] .view-content div:not(.canvas-node-content) img {
    cursor: unset;
}
```
Note: I haven't tested it extensively, but if I find somewhere it didn't work or an issue I'll update the comment.
