### ISSUE TITLE
Minimal Status Bar Has No Affect

### ISSUE THREAD

**Issue by ggstrader** [kepano/obsidian-minimal#412]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.0.4

### Describe the bug

Obsidian v0.16.2

Toggling `Minimal Theme Settings -> Features -> Minimal Status Bar` only toggles the outline of the status bar. Based on the description it sounds like it should be using a minified status bar like California Coast

### Debug info

![image](https://user-images.githubusercontent.com/101308963/189408761-432cc04e-4b97-4b18-9436-e376c8def23b.png)
![image](https://user-images.githubusercontent.com/101308963/189408800-301b91d5-04d9-40f2-ad84-8bebbc2162a8.png)

**Comment by kepano** [comment]
I cannot reproduce. Looks like you have some custom CSS. Have you tried disabling your snippets?

**Comment by ggstrader** [comment]
> I cannot reproduce. Looks like you have some custom CSS. Have you tried disabling your snippets?

I disabled all except one that colors the workspace because that made the lack of change more obvious, but with that disabled and

**Comment by kepano** [comment]
Unfortunately I cannot reproduce. You should try in a new vault, what you are describing as the desired behavior is the default for Minimal.

**Comment by ggstrader** [comment]
> Unfortunately I cannot reproduce. You should try in a new vault, what you are describing as the desired behavior is the default for Minimal.

Yeah, I was in the middle of that. I found that it's the "Quick Explorer" plugin, which I wasn't really using anyways
