### ISSUE TITLE
Change vertical spacing between File Tree items, Primary Navigation (with text labels) and Tag list items

### ISSUE THREAD

**Issue by janpeeters70** [kepano/obsidian-minimal#413]
I find the vertical spacing between list items in sidebars a bit too big. I can tweak this with CSS snippets but a setting in Minimal Theme Settings or Style Settings to be able to diminish the vertical spacing. 
This would count especially for vertical spacing between File Tree items, Primary Navigation (with text labels) and Tag list items.

Thanks for considering.

**Comment by kepano** [comment]
This is a better fit for a snippet than being added to the theme
