### ISSUE TITLE
[FR] custom icon for database folder plugin

### ISSUE THREAD

**Issue by afland** [kepano/obsidian-minimal#415]
The database folder icon does not mix very well with minimal right now, so it would be great if you could add a custom icon like for other major plugins. 

![image](https://user-images.githubusercontent.com/67392684/189544545-3f3ab07f-1d91-446e-90dd-d35387f5eb83.png)

**Comment by kepano** [comment]
You should open this request on the plugin repo. As of Obsidian 0.16.x plugins should follow the new icon guidelines found here https://forum.obsidian.md/t/0-16-0-theme-migration-guide/42537/1

**Comment by afland** [comment]
> You should open this request on the plugin repo. As of Obsidian 0.16.x plugins should follow the new icon guidelines found here https://forum.obsidian.md/t/0-16-0-theme-migration-guide/42537/1

So all of the custom icons enabled by the Custom Icons option will be gone? 
![image](https://user-images.githubusercontent.com/67392684/189546072-dc6f2f2d-1cb8-4750-8f3c-4afd2c29bf7a.png)

**Comment by kepano** [comment]
Yes, see 6.0 release notes
