### ISSUE TITLE
Have a separate translucency settings for full screen window

### ISSUE THREAD

**Issue by I7T5** [kepano/obsidian-minimal#416]
Problem: 
- The translucent sidebar looks great by default when I'm not in fullscreen and can see my menu bar (Mac user), and the wallpaper tinges doesn't just exist on the sidebar. 
- However, when in full screen, the sidebar translucency becomes a bit annoying. At least, I think so. Personally I would like for it to be less transparent, or not translucent at all, just use the default color or the general tinge of that part of the window. (Not sure if it's clearly expressed. Refer to how Apple's Dictionary sidebar responds, as attached.) 

Solution: 
- Maybe the translucency may just be increased by some fixed percentage when entering full screen? 
- Or have a separate setting in Style Settings for translucency when in full screen? 
- Apple's Dictionary Sidebar response

Not fullscreen: 
<img width="1440" alt="Screen Shot 2022-09-12 at 14 14 17" src="https://user-images.githubusercontent.com/105357663/189585463-4357bb1f-fb06-41a3-9e4f-34b8e07205e2.png">

Full screen: 
<img width="1440" alt="Screen Shot 2022-09-12 at 14 01 26" src="https://user-images.githubusercontent.com/105357663/189583876-54c214b0-7b6a-408c-8060-bd958a9b4992.png">

Wallpaper: 
![Firewatch Landscape Remastered by tiko0815-10 (dragged)](https://user-images.githubusercontent.com/105357663/189584112-5a141707-5e38-478a-81dc-2ed6f055281f.jpeg)

In case if anyone likes my wallpaper, here's the [link](https://dynamicwallpaper.club/wallpaper/hzmh33daz4). It's dynamic too! 

Menu bar: 
- Cat: [Runcat](https://kyome.io/runcat/index.html?lang=en)
- Arrow thingy: [Hidden Bar](https://superbits.co/hidden/)

**Comment by kepano** [comment]
This will be fixed in the core app
