### ISSUE TITLE
Inline code blocks in header are displayed wrong

### ISSUE THREAD

**Issue by qyurila** [kepano/obsidian-minimal#418]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

5.3.2

## Small Caps

Inline code blocks in `h4`~`h6` should be displayed with no '**small caps**' attribute, but they do.

![image](https://user-images.githubusercontent.com/68494132/190040978-fe425a52-3438-4dbe-aeb4-287a7104d565.png)

Personally, I don't really like the 'small caps' attribute for `h4` ~ `h6` and wish there would be an option to disable it.

## Wrong Font in Live Preview Mode / Editing View

Additionally, in Live Preview Mode and Editing View, inline code blocks in `h1` ~ `h6` should have global **Monospace font**, but currently they follows **Text font**.

![image](https://user-images.githubusercontent.com/68494132/190040915-aa9510cd-6a8c-4c87-bf78-323b83b04d99.png)

### Debug info

```
SYSTEM INFO:
	Obsidian version: v0.15.9
	Installer version: v0.15.9
	Operating system: Windows 10 Pro 10.0.22000
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 7
	Plugins enabled: 2
		1: Minimal Theme Settings v5.3.2
		2: Code Editor Shortcuts v1.10.0

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by kepano** [comment]
Small caps can be disabled using Style Settings plugin. Please also note that I am no longer providing support for Minimal 5.3.2, much of this will change with the Obsidian 0.16 update which you can access if you have an insider membership

**Comment by qyurila** [comment]
Just checked Obsidian 1.0 and Minimal update, it's fixed! Thank you for the effort and great theme!
