### ISSUE TITLE
Lack of style in exported PDF

### ISSUE THREAD

**Issue by benwrth** [kepano/obsidian-minimal#419]
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

5.3.2

### Describe the bug

When exporting a note to PDF, all color (apart from links) is not present. A note which looks like this:
![image](https://user-images.githubusercontent.com/66076534/190207804-c515d45e-ee4c-4131-ad47-0d977134948c.png)
Comes out like this:
![image](https://user-images.githubusercontent.com/66076534/190207852-6cd34835-d5a6-4ed3-a6c4-d93775365837.png)

As well as almost all the color missing, the divider bar under the H1 heading is also missing. Although these element are missing, some of the custom settings I have applied have transferred over to the PDF as I have de-capitalised the lower headings and changed some font weights.

Any help would be greatly appreciated, thanks!

### Debug info

SYSTEM INFO:
	Obsidian version: v0.15.9
	Installer version: v0.15.9
	Operating system: Windows 10 Home 10.0.22000
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 6
	Plugins enabled: 6
		1: Minimal Theme Settings v5.3.2
		2: Style Settings v0.4.11
		3: Advanced Tables v0.17.3
		4: Excalidraw v1.7.19
		5: Icon Folder v1.3.4
		6: Tasks v1.13.1

**Comment by kepano** [comment]
This is not a Minimal bug since it is also present in the default theme. Please see forum threads on this topic.
