### ISSUE TITLE
Tags look and feel

### ISSUE THREAD

**Issue by michaello** [kepano/obsidian-minimal#42]
How to achieve the same look and feel for tags from your preview photos? Here’s what I got on 4.0:

![IMG_0410](https://user-images.githubusercontent.com/4096232/136686167-47b6a09b-a5f7-4b10-b1dc-58cf7e60bbd8.jpeg)

**Comment by kepano** [comment]
The screenshots are from an older version. You would need to create your own CSS snippet with a background fill if you prefer the old style. See forum: https://forum.obsidian.md/t/getting-comfortable-with-obsidian-css/133

**Comment by michaello** [comment]
I see, thanks! 😀
