### ISSUE TITLE
Header size variation is too little

### ISSUE THREAD

**Issue by robertandrews** [kepano/obsidian-minimal#420]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6

### Describe the bug

I felt this about previous versions and, now that I have installed Obsidian 0.16 and Minimal 6, I still feel it...

1. Overall, the header font sizes used are too small.
2. There is too little variation between header sizes.

Please note...

* The minimal differentiation between H1 and H2.
    * This does not allow for intended use of H1 - impact of page title.
* H1 and H2 actually appear the same size as normal-paragraph bold, causing confusion between headers and normal paragraph material.
* Headers 4 to 6 resort to capitals to overcome sizes of 1 to 3 starting too low, but mix of capitals and non-capitals is not optimal.
* Majority of the content of headers 5 to 6 appear smaller than normal-paragraph text.

<img width="599" alt="Screenshot 2022-09-15 at 16 05 52" src="https://user-images.githubusercontent.com/3158787/190440109-99ae6240-ffe7-41b3-ae48-9072391f98fb.png">

These observations always held me back from using Minimal. I am pleased they haven't made their way into the new Default theme, though I do still think there are differentiation issues at 5 and 6, which again look quite close to normal-paragraph bold...

<img width="426" alt="Screenshot 2022-09-15 at 16 15 30" src="https://user-images.githubusercontent.com/3158787/190441719-7848f8b5-943e-40e6-ad8f-73ecf21a48fd.png">

My preference would be that you raise the starting size of H1 as with the new Default theme, thereby giving more opportunities to 1) differentiate headers from each other and 2) differentiate headers from body text.

To be sure, there is no technical "bug" here and, of course, this may be a matter of personal taste rather than fact, but this seemed the best way of noting it. So please take the issue or modify as you see fit.

Good luck with the projects.

### Debug info

None

**Comment by kepano** [comment]
The sizes are modeled after Apple Notes.

All of the heading sizes can be customized via Style Settings
https://minimal.guide/Plugins/Style+Settings

**Comment by evanrelf** [comment]
For anyone else wanting the default theme's header sizes:

1. Install "Style Settings" (if you haven't already) like @kepano described: https://minimal.guide/Plugins/Style+Settings
2. Merge these settings with whatever you have in `.obsidian/plugins/obsidian-style-settings/data.json`:

   ```json
   {
     "minimal-style@@h1-size": "2em",
     "minimal-style@@h2-size": "1.6em",
     "minimal-style@@h3-size": "1.37em",
     "minimal-style@@h4-size": "1.25em",
     "minimal-style@@h5-size": "1.12em",
     "minimal-style@@h6-size": "1.12em"
   }
   ```

3. Restart Obsidian
