### ISSUE TITLE
Support defining foreground colour of highlighted text. 

### ISSUE THREAD

**Issue by xndko** [kepano/obsidian-minimal#422]
**Is your feature request related to a problem? Please describe.**
When highlighting a text using the highlightr plugin the preview text colour is borderline impossible to read with the dark theme applied. There is - as far as I'm aware - no implemented solution to this. Style settings support changing the text colour however that alters *all* text which means sections which are not highlighted become unreadable; e.g. setting text colour to something dark renders it readable when highlighted but simultaneously renders the rest of the document text unreadable. See pictures below. 

**Describe the solution you'd like**
Support for defining foreground colour of highlighted text. 

Editing mode: 
![editing](https://user-images.githubusercontent.com/102994494/190895844-249d0fce-d43d-4a15-a788-dd35c126b667.png)

Preview mode:
![preview](https://user-images.githubusercontent.com/102994494/190895847-a1ea6e3d-cccb-4237-a311-86f7e18bb7bc.png)

**Comment by AMGMNPLK** [comment]
How is this solved?
