### ISSUE TITLE
Kanban Interaction: Linked page metadata

### ISSUE THREAD

**Issue by Oblique82** [kepano/obsidian-minimal#423]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.0.5

### Describe the bug

The kanban board now shows a "1." Next to 'linked page metadata (a feature of the kanban plugin that displays metadata fields from attached notes)

### Debug info

N/A

**Comment by kepano** [comment]
Please provide screenshots and steps to reproduce

**Comment by Oblique82** [comment]
apologies - for some reason I am no longer able to reproduce withy the
latest version - appears to have been resolved

thanks again

-Tim
