### ISSUE TITLE
Dataview edit button location is pushed too far to the left

### ISSUE THREAD

**Issue by ronaldsuwandi** [kepano/obsidian-minimal#424]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

5.3.2

### Describe the bug

Edit button for DataView is too far to the left because of `margin-left: 0 !important;`. See screenshot to compare with original theme. Original theme edit button is more accessible

<img width="2464" alt="1 - dataview edit button location" src="https://user-images.githubusercontent.com/4120788/191156357-e20249b0-dc0e-4556-b2a0-f800c98fdb3f.png">
edit location at `margin-left: 0 !important;` (current Minimal theme implementation)

<hr> 
<img width="1907" alt="2 - dataview edit button without margin-left" src="https://user-images.githubusercontent.com/4120788/191156369-bd2ba183-b4e4-4089-bea6-87ef805f1bcb.png">
disabled `margin-left: 0 !important;` to test out the result

<hr>
<img width="1315" alt="3 - dataview edit button on original theme" src="https://user-images.githubusercontent.com/4120788/191156371-503a4166-544e-4915-8004-45152c780de3.png">
edit button on original theme

### Debug info

SYSTEM INFO:
	Obsidian version: v0.15.9
	Installer version: v0.15.9
	Operating system: Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:28 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8110 21.6.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 20
	Plugins enabled: 20
		1: Calendar v1.5.10
		2: Advanced Tables v0.17.3
		3: Minimal Theme Settings v5.3.2
		4: Dataview v0.5.46
		5: Emoji Shortcodes v2.1.2
		6: Natural Language Dates v0.6.1
		7: QuickAdd v0.5.5
		8: Unique attachments v1.0.3
		9: Outliner v3.0.0
		10: Paste URL into selection v1.7.0
		11: Style Settings v0.4.11
		12: Workspaces Plus v0.3.2
		13: Buttons v0.4.16
		14: Find orphaned files and broken links v1.6.1
		15: Homepage v2.2.1
		16: Pane Relief v0.3.5
		17: Customizable Page Header and Title Bar v4.6.2
		18: Editor Syntax Highlight v0.1.3
		19: Zoom v1.0.1
		20: Obsidian Git v2.1.0

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
This is not a bug. See 5.2 release notes
https://github.com/kepano/obsidian-minimal/releases/tag/5.2.0
