### ISSUE TITLE
In Focus Mode, the back and forward buttons are unreachable with tabs

### ISSUE THREAD

**Issue by firstdivision15** [kepano/obsidian-minimal#426]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

6.0.5

### Describe the bug

If the focus mode is toggled, then the tabs will block the forward and backward buttons.
![image](https://user-images.githubusercontent.com/80803420/191640396-58a31b8b-52bf-423b-b1cc-8d77b4c4c156.png)
The back and forward buttons are hidden under the tabs in this image

### Debug info

SYSTEM INFO:
	Obsidian version: v0.16.3
	Installer version: v0.15.9
	Operating system: Windows 10 Home 10.0.22000
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 14
	Plugins enabled: 11
		1: Paste URL into selection v1.7.0
		2: Quick Latex for Obsidian v2.3.7
		3: Admonition v9.0.5
		4: Obsidian Charts v3.6.3
		5: Natural Language Dates v0.6.1
		6: Kanban v1.3.20
		7: Minimal Theme Settings v6.0.5
		8: Style Settings v0.4.11
		9: Advanced Tables v0.17.3
		10: Calendar v1.5.10
		11: Tasks v1.13.1

**Comment by kepano** [comment]
This is fixed in 6.0.6
