### ISSUE TITLE
Automatic selection of light/dark mode not working

### ISSUE THREAD

**Issue by ma-sadeghi** [kepano/obsidian-minimal#429]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

5.3.2

### Describe the bug

My Ubuntu automatically switches to dark/light mode based on sunset/sunrise. Obsidian theme seems to be working fine with switching to night mode, but it doesn't switch back to light mode in the morning, and requires a complete restart of the application.

### Debug info

SYSTEM INFO:
	Obsidian version: v0.15.9
	Installer version: v0.15.9
	Operating system: #202204271406~1653440576~20.04~6277a18-Ubuntu SMP PREEMPT Thu Ma 5.17.5-76051705-generic
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 17
	Plugins enabled: 13
		1: Smart Typography v1.0.18
		2: File Tree Alternative Plugin v2.2.3
		3: Obsidian Git v2.4.1
		4: Admonition v9.0.5
		5: Tasks v1.13.1
		6: Advanced Tables v0.17.3
		7: Folder Note v0.7.3
		8: Minimal Theme Settings v5.3.2
		9: Outliner v3.0.0
		10: Open File by Magic Date v0.1.0
		11: Omnisearch v1.5.2
		12: Templater v1.14.3
		13: Style Settings v0.4.11

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
This is a Linux issue that has been solved in Obsidian 1.0.2 if you use Appearance > Adapt to system

**Comment by ma-sadeghi** [comment]
@kepano Thank you! I updated my Obsidian to 1.0.3 and it worked like a charm! Thank you once again!
