### ISSUE TITLE
Focus mode tabs are "jumpy"

### ISSUE THREAD

**Issue by nickchomey** [kepano/obsidian-minimal#431]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.0.6

### Describe the bug

The tabs are very jumpy/sensitive when you hover them - they appear and disappear more quickly than is comfortable. 

I think the main issue is that the tabs don't extend to the top of the window, so if you quickly move up to them you end up going past them and they disappear. 

Another issue - not sure if anything can be done about it though - is that when you scroll high enough on the title for the tabs appear, the tabs then take the place of the title bar and there's only a very small amount of space remaining to scroll upwards with the pointer.

I see a few possible solutions:
1. make the tabs taller so that there isn't any space above them, so that you can't move above them
2. add some sort of invisible hover space above the visible part of the tab
3. make the title and tabs appear all at once rather than sequentially. 

Perhaps a combination of 1 or 2 & 3 would be good?

Here's a screenrecording. 

https://user-images.githubusercontent.com/88559987/192626646-9bf17d97-03b3-4739-a5fd-d94558e139ee.mp4

### Debug info

.

**Comment by kepano** [comment]
Unfortunately what you are describing is not possible within the limitations of CSS because the view header is nested the DOM structure in a way that it cannot target the tab header. 

You might want to set a hotkey for the Focus Mode feature so that you can turn it on and off more easily.
