### ISSUE TITLE
Readwise and Minimal theme causes ![rw-book-cover](URL) images to improperly stretch

### ISSUE THREAD

**Issue by ofilipowicz** [kepano/obsidian-minimal#432]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

5.3.1

### Describe the bug

Readwise exports highlights to Obsidian and adds a book cover to each note. A book cover is inserted as:

```
![rw-book-cover](https://play-lh.googleusercontent.com/McJwuNc1Gbs8-XrPCH77Ar-qZMGujN6L0_zb_jv_0oBe2vwnmIboESQjPsTSu1uINbg)
```

Without Minimal theme or Readwise plugin everything works. When you combine both of them, it causes these books covers in Edit mode to stretch to full width:

<img width="689" alt="Screenshot 2022-09-29 at 20 35 54" src="https://user-images.githubusercontent.com/7127243/193115782-130f2e2f-5eaf-4470-9b71-6a782608048b.png">

It works just fine on default theme. Probably some CSS clash.

### Debug info

SYSTEM INFO:
	Obsidian version: v0.15.9
	Installer version: v0.15.9
	Operating system: Darwin Kernel Version 21.6.0: Sat Jun 18 17:05:47 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8101 21.6.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 28
	Plugins enabled: 28
		1: Advanced Tables v0.17.3
		2: Calendar v1.5.10
		3: Kanban v1.3.17
		4: Dataview v0.5.43
		5: Templater v1.12.0
		6: Outliner v3.0.0
		7: Editor Syntax Highlight v0.1.3
		8: Checklist v2.2.8
		9: QuickAdd v0.5.5
		10: Periodic Notes v0.0.17
		11: Copy button for code blocks v0.1.0
		12: Cycle through Panes v0.1.0
		13: Obsidian Leaflet v5.0.3
		14: Fantasy Calendar v2.3.8
		15: Dice Roller v8.6.4
		16: Settings Search v1.2.0
		17: Vault Statistics v0.1.2
		18: Show Current File Path v0.5.2
		19: Buttons v0.4.16
		20: Advanced Slides v1.16.6
		21: Excalidraw v1.7.18
		22: ExcaliBrain v0.1.10
		23: LanguageTool Integration v0.3.0
		24: Minimal Theme Settings v5.3.2
		25: Natural Language Dates v0.6.1
		26: Sortable v0.2.6
		27: Contextual Typography v2.2.4
		28: Readwise Official v2.0.1

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
You can turn off maximize media in Minimal Theme Settings
https://minimal.guide/Block+types/Images

**Comment by ofilipowicz** [comment]
@kepano It doesn't do anything.

**Comment by kepano** [comment]
I am not able to reproduce the issue... You should try in a fresh vault without plugins or snippets.

**Comment by ofilipowicz** [comment]
I tried with a new vault, installing just these 2 plugins. Same behaviour. Disabling "Maximize media" should fix this, as it wouldn't then try to stretch images at all. However, it just doesn't do anything. Even when Readwise plugin is disabled, disabling "Maximize media" setting does nothing, theme always tries to fill full width with images.

**Comment by kepano** [comment]
Are you also using image grids? See **Minimal Theme Settings > Layout > Image grids**

**Comment by brajbhushan-tripathi** [comment]
I am also facing the same issue, even after disabling the "Maximize media" images are still stretched to fit the line width.
![image](https://user-images.githubusercontent.com/32623356/214896812-876e27a4-41f0-41e1-8951-dbc6a9f69587.png)
![image](https://user-images.githubusercontent.com/32623356/214896887-7874d8ab-18d8-4772-bead-7c2741620af1.png)

**Comment by kepano** [comment]
You can change the Readwise template to not have a max height, or change it to have a max width.

**Comment by brajbhushan-tripathi** [comment]
> You can change the Readwise template to not have a max height, or change it to have a max width.

Readwise template does not have any height or width setup. Moreover this looks perfectly fine with other themes. 
![image](https://user-images.githubusercontent.com/32623356/214948566-80d8f6b1-e4b7-4d0f-a150-74e0cde6c5c2.png)
![image](https://user-images.githubusercontent.com/32623356/214948665-2d22899a-133f-4f4b-b066-01b212ae9828.png)

**Comment by dsiu** [comment]
@brajbhushan-tripathi : i have the same issue too.  Here is my fix:

```css
/* Fix Readwise book cover image size for Minimal Theme */
img[alt=rw-book-cover] {
    inline-size: auto !important; 
    max-height: 200px;
}
```
