### ISSUE TITLE
Focus mode hides output of Path Title plugin only halfway

### ISSUE THREAD

**Issue by xmacex** [kepano/obsidian-minimal#433]
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

5.3.2

### Describe the bug

In Focus mode, the folder path by the [_Path Title_ plugin](https://github.com/jdeal/obsidian-path-title-plugin) is only partially hidden.

Take f.ex. this note. We see the path in the title.

![Screenshot 2022-09-30 at 13 10 09](https://user-images.githubusercontent.com/879300/193258871-cb25134a-94af-4486-b01d-7a737a615ee4.png)

Minimal theme Focus Mode hides the title as expected, and tries to hide the folder too. The latter is only halfway hidden, and peeks down from the top. One would expect it to be completely hidden, like the rest of the title.

![Screenshot 2022-09-30 at 13 10 26](https://user-images.githubusercontent.com/879300/193258836-4c72f6d9-1097-4919-8d00-5e78307b97f9.png)

### Debug info

Here's the relevant piece of the DOM if it is useful.

![Screenshot 2022-09-30 at 13 17 01](https://user-images.githubusercontent.com/879300/193259390-46f8d0f5-fc75-4ee6-a73f-88ecc5302770.png)

**Comment by kepano** [comment]
Thanks for your report. I am no longer supporting versions of Minimal below 6.0 (requires Obsidian 0.16x). Furthermore Obsidian 0.16 now displays the path in the note title.

**Comment by xmacex** [comment]
Got it, thanks!
