### ISSUE TITLE
Filename is cut off.

### ISSUE THREAD

**Issue by FrocketGaming** [kepano/obsidian-minimal#434]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

5.3.2

### Describe the bug

Filename title is cut off, for each file when using the sliding panes plugin.

I fixed it by removing the --line-adaptive-height and just changing it to 100%. Otherwise, the text is cut in half.

.view-header-title-container {
  padding-left: 0;
  padding-right: 0px;
  position: absolute;
  width: 100%;
  max-width: var(--max-width);
  margin: 0 auto;
  left: 0;
  right: 0; }

### Debug info

SYSTEM INFO:
	Obsidian version: v0.15.9
	Installer version: v0.15.9
	Operating system: Windows 10 Pro 10.0.22000
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 31
	Plugins enabled: 31
		1: Admonition v9.0.5
		2: Advanced Tables v0.17.3
		3: Collapse All v1.5.3
		4: Copy button for code blocks v0.1.0
		5: Dataview v0.5.46
		6: Dictionary v2.21.1
		7: Editor Syntax Highlight v0.1.3
		8: File Explorer Note Count v1.2.0
		9: Find and replace in selection v1.0.1
		10: Fullscreen mode plugin v0.1.2
		11: Hotkeys++ v0.2.7
		12: Kanban v1.3.20
		13: Kindle Highlights v1.7.0
		14: Note Refactor v1.7.1
		15: Obsidian Git v2.5.0
		16: Outliner v3.0.0
		17: Paste URL into selection v1.7.0
		18: Sliding Panes (Andy's Mode) v3.3.0
		19: Tag Wrangler v0.5.3
		20: Better Word Count v0.8.1
		21: Sortable v0.2.6
		22: Highlightr v1.2.2
		23: Notion-Like Tables v4.3.1
		24: Markdown prettifier v0.1.3
		25: Table Extended v1.6.1
		26: Excel to Markdown Table v0.4.0
		27: Novel word count v2.6.0
		28: List Callouts v1.0.6
		29: Icons v0.3.0
		30: Minimal Theme Settings v5.3.2
		31: Contextual Typography v2.2.4

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
I am no longer providing support for versions below Minimal 6.0 — note that sliding panes functionality is now available in the core app as of Obsidian 0.16

**Comment by FrocketGaming** [comment]
I see, thanks for that. It doesn't appear I can actually update the plugin through Obsidian which is why my version is so far behind. Is that a known bug? How do I get it updated to the correct version?

**Comment by kepano** [comment]
Currently Obsidian 0.16 is only available if you have access to the insider builds via [Catalyst](https://obsidian.md/pricing)

**Comment by FrocketGaming** [comment]
I wasn't referring to that. I was referring to your plugins. Obsidian does not update to the most recent version for the Minimal Settings Plugin. It constantly says 'Updated' but it never actually updates. So it's stuck several version back.

**Comment by kepano** [comment]
This is because the new versions require Obsidian 0.16

**Comment by FrocketGaming** [comment]
Ah I see. Thanks!
