### ISSUE TITLE
Edit mode: list indent issues

### ISSUE THREAD

**Issue by Erimus-Koo** [kepano/obsidian-minimal#435]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

5.3.2

### Describe the bug

![image](https://user-images.githubusercontent.com/17139670/193620559-20609bdb-5226-4666-9faf-9a92dc330307.png)

# Edit Mode
- The second line of list get a wrong padding. List first line's 'b' is a little right to the second line's 'A'.
- The code block in list, the first part get a left margin, but the follows not.

# Preview Mode
Everything looks good.
![image](https://user-images.githubusercontent.com/17139670/193622570-02821cd9-6ef3-4ac3-a203-28aedff4d5f9.png)

### Debug info

# Preview in Github
-   broot
    A new way to see and navigate directory trees : [https://dystroy.org/broot](https://dystroy.org/broot)

    ```bash
    echo "deb [signed-by=/usr/share/keyrings/azlux-archive-keyring.gpg] http://packages.azlux.fr/debian/ bullseye main" | sudo tee /etc/apt/sources.list.d/azlux.list
    sudo wget -O /usr/share/keyrings/azlux-archive-keyring.gpg  https://azlux.fr/repo.gpg
    sudo apt update
    sudo apt install broot
    # 运行broot，按提示安装br到.bashrc，完成后需要source。
    sudo broot
    ```

# Source code
```

-   broot
    A new way to see and navigate directory trees : [https://dystroy.org/broot](https://dystroy.org/broot)

    ```bash
    echo "deb [signed-by=/usr/share/keyrings/azlux-archive-keyring.gpg] http://packages.azlux.fr/debian/ bullseye main" | sudo tee /etc/apt/sources.list.d/azlux.list
    sudo wget -O /usr/share/keyrings/azlux-archive-keyring.gpg  https://azlux.fr/repo.gpg
    sudo apt update
    sudo apt install broot
    # 运行broot，按提示安装br到.bashrc，完成后需要source。
    sudo broot
    ```

```

**Comment by kepano** [comment]
As mentioned in the issue template, I am no longer supporting versions below Minimal 6.0 — please test with Obsidian 0.16 and Minimal 6+ and reopen if it's still an issue
