### ISSUE TITLE
Indent alignment issues with ordered lists

### ISSUE THREAD

**Issue by HankMai** [kepano/obsidian-minimal#438]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

6.0.8

### Describe the bug

![image](https://user-images.githubusercontent.com/33268545/195613745-3aedb65d-3937-444e-9bea-c770b1176750.png)
The second line of the ordered list has an inexplicable indentation that makes it misaligned with the first line

### Debug info

SYSTEM INFO:
	Obsidian version: v1.0.0
	Installer version: v0.15.9
	Operating system: Windows 10 Enterprise 10.0.22000
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: on

**Comment by kepano** [comment]
Closed in 6.0.13 
https://github.com/kepano/obsidian-minimal/releases/tag/6.0.13
