### ISSUE TITLE
Gap near top of left-hand sidebar

### ISSUE THREAD

**Issue by necopinus** [kepano/obsidian-minimal#439]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.0.8

### Describe the bug

With the latest version of Obsidian on iOS/iPadOS (1.4.0) and the most recent version of Minimal Theme (6.0.8), there's a weird gap between the quick controls on the left side of the left-hand sidebar and the top of the sidebar. See screenshot below.

![Screenshot 2022-10-13 at 08 19 51](https://user-images.githubusercontent.com/134362/195624840-2b9c2f90-9d6e-40c0-873e-0df8fe5d6702.png)

I've answered that this bug "isn't" present in the default theme, but I think this may be because of how the quick-controls are styled in the default theme as opposed to Minimal - the same gap is visible in the default theme, but because the quick controls aren't styled differently than the rest of the left-hand sidebar it isn't obvious. (The screenshot below shows the same region with the default theme.)

![Screenshot 2022-10-13 at 08 21 58](https://user-images.githubusercontent.com/134362/195624846-bcadccf7-102e-4c13-af4d-30bdaca11516.png)

### Debug info

SYSTEM INFO:
	Operating system: ios 15.7 (Apple iPad)
	Obsidian version: 1.4.0 (80)
	API version: v1.0.0
	Login status: logged in
	Catalyst license: vip
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 5
	Plugins enabled: 0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.

**Comment by kepano** [comment]
Closed in 6.0.13 
https://github.com/kepano/obsidian-minimal/releases/tag/6.0.13
