### ISSUE TITLE
Alignment problem of "#" in tags in Live Preview

### ISSUE THREAD

**Issue by LeoAdL** [kepano/obsidian-minimal#440]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.0.11

### Describe the bug

Hi Kepano!

Thank you for the work! As you can see, the # in tags is misaligned (I have the issue on both mac OS and Android):
![image](https://user-images.githubusercontent.com/29279079/195654492-2ad90e1d-c611-4600-a3ff-0f5e3086ea54.png)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.0.0
	Installer version: v1.0.0
	Operating system: Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101 21.6.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 1
	Restricted mode: on

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.

**Comment by kepano** [comment]
Closed in 6.0.13 
https://github.com/kepano/obsidian-minimal/releases/tag/6.0.13
