### ISSUE TITLE
File rename modal not visible

### ISSUE THREAD

**Issue by pielgrzym** [kepano/obsidian-minimal#442]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

0.6.12

### Describe the bug

Bug manifests when using two settings:
- `Style settings` plugin with `Minimal > Tab title bar > Tab title visibility > Hover only`
- inline titles disabled in main obsidian appereance settings 

In this circumstances when you try to rename current file by pressing F2, the modal rename dialog does not appear. You can still change the title however, because the focus is left on invisible tab title - you just can't see what is happening.
I think that if the title in tab is not visible the theme should fall back to rename modal window.

### Debug info

SYSTEM INFO:
	Obsidian version: v1.0.0
	Installer version: v0.15.9
	Operating system: #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1 (2022-09-24) 5.19.0-2-amd64
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 11
	Plugins enabled: 9
		1: Jump to link v0.4.4
		2: Obsidian Git v2.5.1
		3: Pane Relief v0.4.0
		4: Paste URL into selection v1.7.0
		5: Auto Note Mover v1.2.0
		6: Dataview v0.5.46
		7: Calendar v1.5.10
		8: Minimal Theme Settings v6.0.5
		9: Style Settings v0.4.12

**Comment by kepano** [comment]
Closed in 6.0.13 
https://github.com/kepano/obsidian-minimal/releases/tag/6.0.13
