### ISSUE TITLE
Line numbers are too far to the left in live preview on mobile.

### ISSUE THREAD

**Issue by SamAdams51** [kepano/obsidian-minimal#443]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.0.12

### Describe the bug

On my iPad, the line numbers in live preview mode are too far to the left, making them almost unreadable.

### Debug info

SYSTEM INFO:
	Operating system: ios 15.7 (Apple iPad)
	Obsidian version: 1.4.0 (80)
	API version: v1.0.0
	Login status: not logged in
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 6
	Restricted mode: off
	Plugins installed: 10
	Plugins enabled: 8
		1: Templater v1.14.3
		2: Contextual Typography v2.2.4
		3: Minimal Theme Settings v6.0.5
		4: Style Settings v0.4.12
		5: Music notation v1.0.7
		6: Dynamic Table of Contents v0.0.27
		7: Note Refactor v1.7.1
		8: Advanced Tables v0.17.3

**Comment by SamAdams51** [comment]
### Debug Info

SYSTEM INFO:
	Operating system: ios 15.7 (Apple iPad)
	Obsidian version: 1.4.0 (80)
	API version: v1.0.0
	Login status: not logged in
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 6
	Restricted mode: off
	Plugins installed: 10
	Plugins enabled: 8
		1: Templater v1.14.3
		2: Contextual Typography v2.2.4
		3: Minimal Theme Settings v6.0.5
		4: Style Settings v0.4.12
		5: Music notation v1.0.7
		6: Dynamic Table of Contents v0.0.27
		7: Note Refactor v1.7.1
		8: Advanced Tables v0.17.3

**Comment by kepano** [comment]
This is intentional, please see documentation
https://minimal.guide/Features/Active+line+highlighting

**Comment by SamAdams51** [comment]
I know that this is intentional, and I like it. In the Version before it worked fine but now the line numbers are **too far to the left**, making them unreadable (see screenshot). The note in the screen shot was made in a brand new vault, no community plug-ins, no snippets.

![IMG_0227](https://user-images.githubusercontent.com/42751459/196052887-fc06ff55-8556-44b1-8db6-4ba659579cc0.jpeg)

**Comment by SamAdams51** [comment]
Hi Stephan,

I commented the issue a few seconds ago and attached a screenshot, which shows the problem pretty clearly. Please, reopen the issue.

Best regards and thanks for this super theme.

**Comment by kepano** [comment]
Got it. I will investigate.

**Comment by kepano** [comment]
Closed in 6.0.13 
https://github.com/kepano/obsidian-minimal/releases/tag/6.0.13

**Comment by SamAdams51** [comment]
Super 👍.  Thanks a lot again.

Viele Grüße Helmut
