### ISSUE TITLE
Request Chinese support

### ISSUE THREAD

**Issue by gogogolive** [kepano/obsidian-minimal#444]
Hello, I am a user in China. 
I like your work very much, but sometimes I feel very depressed because of the language problem. 
I hope Minimal can have a good Chinese setting page, which may not be a problem for your work, but it is very important to me. 
I'd be very grateful. 
Good luck.

**Comment by kepano** [comment]
This should be moved to the [Minimal Theme Settings repo](https://github.com/kepano/obsidian-minimal-settings). Also would be great to see localization as a pull request!
