### ISSUE TITLE
Cannot double click to maximize window after last update

### ISSUE THREAD

**Issue by beerens20** [kepano/obsidian-minimal#445]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

6.0.12

### Describe the bug

After the update to version 1.0 this morning 10/14 I am no longer able to double click on the edge of the window to make it expand to fit my screen.  I'm running a MacBook Pro 2021 model.

### Debug info

SYSTEM INFO:
	Obsidian version: v1.0.0
	Installer version: v0.15.9
	Operating system: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 21.6.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 10
	Plugins enabled: 9
		1: Advanced Tables v0.17.3
		2: Natural Language Dates v0.6.1
		3: Obsidian Tabs v1.0.7
		4: Calendar v1.5.10
		5: Vantage - Advanced search builder v1.4.2
		6: Dataview v0.5.47
		7: Outliner v4.0.0
		8: Tasks v1.15.1
		9: Zoom v1.0.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
I believe this issue is present regardless of theme and has been fixed in Obsidian 1.0.1
