### ISSUE TITLE
Faded images in PDF exports

### ISSUE THREAD

**Issue by jjadup** [kepano/obsidian-minimal#446]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.0.12

### Describe the bug

When I export a note to PDF which has an embedded image, the image appears faded in the PDF.

This is only the case when using **dark mode**, not light mode. I understand faded images in dark mode _in the Obsidian app_ is a feature, but _in a PDF_ it is not.

### Debug info

SYSTEM INFO:
	Obsidian version: v1.0.0
	Installer version: v0.15.9
	Operating system: #56-Ubuntu SMP Tue Sep 20 13:23:26 UTC 2022 5.15.0-50-generic
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: on

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.

**Comment by jjadup** [comment]
I just made the following snippet as a workaround in the meantime:

```css
@media print{
  body {
    --image-muted: 1;
  }
}
```

**Comment by kepano** [comment]
Closed in 6.0.13 
https://github.com/kepano/obsidian-minimal/releases/tag/6.0.13
