### ISSUE TITLE
Image Zoom in Callout box broken transparency

### ISSUE THREAD

**Issue by Hendo-exe** [kepano/obsidian-minimal#447]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.0.12

### Describe the bug

When clicking to zoom on an image in a callout box the transparency is different to a normal image zoom.
![image](https://user-images.githubusercontent.com/62796283/195961248-aef75a4b-690d-4a89-85a5-d1fb3f2c7171.png)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.0.0
	Installer version: v0.14.6
	Operating system: Windows 10 Home 10.0.19043
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 14
	Plugins enabled: 12
		1: Advanced Tables v0.17.3
		2: Banners v1.3.3
		3: Dangling links v0.3.0
		4: Timeline v1.1.0
		5: Dataview v0.5.47
		6: Obsidian Leaflet v5.0.4
		7: Dice Roller v8.6.9
		8: TTRPG Statblocks v2.21.8
		9: Initiative Tracker v8.0.11
		10: Fantasy Calendar v2.3.10
		11: Minimal Theme Settings v6.0.5
		12: Style Settings v0.4.12

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Closed in 6.0.13 
https://github.com/kepano/obsidian-minimal/releases/tag/6.0.13

Requires Style Settings > Minimal > Callouts > Color blending: off
