### ISSUE TITLE
checkbox color changes accent color

### ISSUE THREAD

**Issue by e2la** [kepano/obsidian-minimal#448]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.0.12

### Describe the bug

changing the checkbox color changes many different parts of the theme (seems to override the accent color?) with 'colorful active states' turned on (minimal theme settings > features)

https://user-images.githubusercontent.com/99437376/195996665-7f41ff33-5bcd-490e-ae63-b947ed90ad7d.mp4

### Debug info

SYSTEM INFO:
	Obsidian version: v1.0.0
	Installer version: v0.15.9
	Operating system: Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 21.6.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 15
	Plugins enabled: 11
		1: Natural Language Dates v0.6.1
		2: Emoji Shortcodes v2.1.2
		3: Omnisearch v1.6.4
		4: Periodic Notes v0.0.17
		5: Tag Wrangler v0.5.3
		6: Advanced URI v1.28.2
		7: Calendar v1.5.10
		8: Style Settings v0.4.12
		9: Dataview v0.5.47
		10: Hider v1.2.3
		11: Minimal Theme Settings v6.0.5

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Closed in 6.0.13 
https://github.com/kepano/obsidian-minimal/releases/tag/6.0.13

**Comment by MiracleXYZ** [comment]
However the new `interactive-accent` variable cannot be found anywhere in the settings. I opened a new issue #455 to address this.
