### ISSUE TITLE
Colorful window frame works only if app window is maximised.

### ISSUE THREAD

**Issue by SamAdams51** [kepano/obsidian-minimal#449]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.0.12

### Steps to reproduce

1. Choose the Minimal Theme

1. Set the switch "Colorful window frame" in Minimal Theme Settings to ON.

1. Make obsidian window fill part of the screen.

### Expected result

The top of the app should show the accent color regardless of the size of the app window.

### Actual result

The top of the app shows the accent color only if the app window is maximised. If the app window in not maximised, the accent color is showing on the right edge of the window only.

**Screenshot - app window is not maximised:**
![Screenshot3](https://user-images.githubusercontent.com/42751459/195998509-5ce7eac1-0e38-45b2-84f0-47b2c494ec1e.png)

![Screenshot1](https://user-images.githubusercontent.com/42751459/195998644-a69ec202-ea8d-4ba1-b83b-d35e1a01bd3c.png)

**Screenshot - app window is maximised:**
![Screenshot2](https://user-images.githubusercontent.com/42751459/195998515-5103daff-87bc-4c5a-be40-0e23303ff22f.png)

### Environment

- Operating system: macOS Monterey Vers. 12.6

The Debug info is wrong in two aspects:

1. I have only one snippet enabled, not five.

1. I have only the eight plug-ins listed installed and enabled, not nine installed.

**Comment by kepano** [comment]
I am not able to reproduce this. Can you try in a new vault without any any snippets or extra plugins?

**Comment by ondvrsn** [comment]
Hi, you all

I had exact same issue on my iMac:

- macOS 12.6
- Obsidian 1.0.0
- Minimal theme 6.0.13
- Minimal Theme Settings 6.0.5
- Style Settings 0.4.12

I could not figure out what exactly caused this bug.
However, after couple of primitive trials, I could finally make my window title behaviour as expected:

- Reset `Style Settings` plugin configurations to default.
- Quit Obsidian.app
- Delete `{my_vault_path}/.obsidian/appearance.json`

**Comment by SamAdams51** [comment]
Hello everyone,
the problem has cured itself.
I tried a lot with the new Obsidian/Minimal theme and experimented around. Don't ask me how or why, but suddenly the problem is gone.
I'm sorry if I wasted your time.
