### ISSUE TITLE
Inconsistent underline when linking to non-existing notes

### ISSUE THREAD

**Issue by x-desire** [kepano/obsidian-minimal#450]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.0.12

### Describe the bug

Minor bug.

I have changed the following in Minimal Theme Settings:

**Underline internal links**: off
**Underline external links**: on

With these settings, when in editor mode **internal links to notes that haven't been created yet are underlined**. As I understand, they shouldn't be. At the same time, internal links to **existing** notes display correctly, without underline. External links also display correctly, with underline.

When switching to reading mode the same internal links to non-existing notes are not underlined anymore.

I also noticed that within callouts everything works fine and links to non-existing notes aren't underlined.

### Debug info

SYSTEM INFO:
	Obsidian version: v1.0.0
	Installer version: v0.14.6
	Operating system: Windows 10 Pro
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 18
	Plugins enabled: 17
		1: Advanced Tables v0.17.3
		2: Dataview v0.5.47
		3: Auto Link Title v1.2.5
		4: Templater v1.14.3
		5: Contextual Typography v2.2.4
		6: Style Settings v0.4.12
		7: Sortable v0.2.6
		8: Copy Block Link v1.0.4
		9: Natural Language Dates v0.6.1
		10: Hide Sidebars on Window Resize v1.0.4
		11: Periodic Notes v0.0.17
		12: Calendar v1.5.10
		13: Omnisearch v1.6.4
		14: Copy Image and URL context menu v1.3.6
		15: Image Toolkit v1.3.1
		16: Better Word Count v0.8.1
		17: Minimal Theme Settings v6.0.5

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
This is a bug in Obsidian not Minimal. It will be fixed in the next version of Obsidian.
