### ISSUE TITLE
Support for DB folder plugin - row height not stable

### ISSUE THREAD

**Issue by imeed166** [kepano/obsidian-minimal#451]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.0.13

### Describe the bug

When using the DB folder plugin, everything works normally, until I add a text column and add text to the cells. The height of the rows changes, whereas when using the default theme, the height of the rows doesn't change. Here's a video demonstrating what I'm talking about.

https://user-images.githubusercontent.com/38974541/196060483-cfe61081-6a6e-4f21-bb78-fc2aac92f8f0.mov

Can you please make it behave like in the default theme and keep the height of the rows stable, thank you.

### Debug info

 SYSTEM INFO:
	Obsidian version: v1.0.0
	Installer version: v0.15.6
	Operating system: Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 21.4.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 5
	Plugins enabled: 2
		1: Dataview v0.5.47
		2: DB Folder v2.7.3

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Support for DB folder is out of scope for Minimal
