### ISSUE TITLE
Card maximum width setting is ignored

### ISSUE THREAD

**Issue by Tragula** [kepano/obsidian-minimal#452]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.0.13

### Describe the bug

Cards seem to be scaled to fill the width of the note regardless of the "card maximum width" setting in the style settings plugin. Adjusting the settings "Dataview -> Dataview maximum column width" or "Tables -> Maximize table width (beta)" has no effect on cards either.

![Minimal Cards Bug](https://user-images.githubusercontent.com/90611500/196122698-5db23cb1-27bd-42cf-8108-10052e5e4155.jpg)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.0.0
	Installer version: v0.15.6
	Operating system: Windows 10 Home 10.0.19044
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 39
	Plugins enabled: 3
		1: Dataview v0.5.47
		2: Minimal Theme Settings v6.0.5
		3: Style Settings v0.4.12

**Comment by kepano** [comment]
This will be fixed in the next version, but note that using the `fr` unit is not the best choice in this context.

Also note that there are helper classes such as `cards-cols-4` to set the number of columns (1-8)
https://minimal.guide/Block+types/Cards

**Comment by kepano** [comment]
Closed in [Minimal 6.1.0](https://github.com/kepano/obsidian-minimal/releases/tag/6.1.0)
