### ISSUE TITLE
Word Wrap > Scroll in Minimal style settings not working and incorrect syntax highlighting

### ISSUE THREAD

**Issue by I7T5** [kepano/obsidian-minimal#453]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

6.0.13

### Describe the bug

Code > Word Wrap > Scroll in Minimal Style Settings not working. 
Btw, the `print` and `abs` in python is highlighted as keywords but not functions. Is there any way to fix this?
And I think recoloring for comments and punctuations are not working either. 

<img width="1440" alt="Screen Shot 2022-10-18 at 10 18 50" src="https://user-images.githubusercontent.com/105357663/196320182-476a1a13-2efb-4614-9d40-f5c06e6eafe7.png">

Thanks. 

### Debug info

SYSTEM INFO:
	Obsidian version: v1.0.0
	Installer version: v0.14.15
	Operating system: Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101 21.6.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 19
	Plugins enabled: 5
		1: Minimal Theme Settings v6.0.5
		2: Hider v1.2.3
		3: Typewriter Scroll v0.2.2
		4: Style Settings v0.4.12
		5: Hotkeys for templates v1.4.3

**Comment by kepano** [comment]
There are two different syntax highlighting libraries in use with Obsidian: Prism (in read mode) and CodeMirror (in edit). Unfortunately Minimal does not control the syntax highlighting itself.

https://prismjs.com/

**Comment by kepano** [comment]
The White Space property requires Obsidian 1.0.1+ which is not out yet :)

**Comment by kepano** [comment]
Closed in [Minimal 6.1.0](https://github.com/kepano/obsidian-minimal/releases/tag/6.1.0)
