### ISSUE TITLE
Syntax highlighting for variables

### ISSUE THREAD

**Issue by I7T5** [kepano/obsidian-minimal#454]
**Is your feature request related to a problem? Please describe.**
I want to use different syntax highlighting for variables and `+-*/%` etc. 

**Describe the solution you'd like**
Have a separate controller for either variables or the signs.

**Comment by kepano** [comment]
I would recommend creating your own snippet if you want more control over syntax highlighting

**Comment by kepano** [comment]
I will add a separate variable in Obsidian core that will become available later on Minimal. In the meantime you can use
```css
.token.operator, .cm-operator {
    color: red;
}
```

**Comment by I7T5** [comment]
Thanks!

**Comment by I7T5** [comment]
What if I want to use a different color for dark mode?

**Comment by kepano** [comment]
Closed in [Minimal 6.1.0](https://github.com/kepano/obsidian-minimal/releases/tag/6.1.0)
