### ISSUE TITLE
Nowhere to customize `ax3` or `interactive-accent`

### ISSUE THREAD

**Issue by MiracleXYZ** [kepano/obsidian-minimal#455]
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

6.0.13

### Describe the bug

I used to customize the interactive accent i.e. `ax3` variable via the Checkbox Color option, but it stopped working after updating to 6.0.13.

It seems that `ax3` got split into `checkbox-color` and `interactive-accent`, but the latter cannot be found anywhere in the Settings.

### Debug info

...

**Comment by kepano** [comment]
Closed in [Minimal 6.1.0](https://github.com/kepano/obsidian-minimal/releases/tag/6.1.0)
