### ISSUE TITLE
Image grid does not work inside callouts

### ISSUE THREAD

**Issue by decatetsu** [kepano/obsidian-minimal#458]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.0.13

### Describe the bug

Image grid feature does not work inside callouts.

### Debug info

SYSTEM INFO:
	Obsidian version: v1.0.0
	Installer version: v0.14.15
	Operating system: Windows 10 Pro 10.0.22621
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 6
	Restricted mode: off
	Plugins installed: 26
	Plugins enabled: 22
		1: Templater v1.14.3
		2: QuickAdd v0.5.5
		3: Local Quotes v1.8.4
		4: Hotkeys for starred files and searches v0.0.4
		5: Sortable v0.2.6
		6: Smart Typography v1.0.18
		7: Obsidian Charts v3.6.3
		8: Meld Encrypt v1.6.2
		9: Kanban v1.4.6
		10: Hover Editor v0.11.4
		11: Advanced Tables v0.17.3
		12: Contextual Typography v2.2.4
		13: List Callouts v1.0.9
		14: Minimal Theme Settings v6.0.5
		15: Style Settings v0.4.12
		16: Tag Wrangler v0.5.3
		17: Admonition v9.0.5
		18: Calendar v1.5.10
		19: Commander v0.2.1
		20: Dataview v0.5.47
		21: LanguageTool Integration v0.3.0
		22: Default New Tab Page v0.9.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
I do not plan to address this use case
