### ISSUE TITLE
Feature: Allow h1, h2, h3, etc to have a different size in editor

### ISSUE THREAD

**Issue by pecigonzalo** [kepano/obsidian-minimal#46]
Thanks for this great theme, I was wondering if it would be possible to allow headings to have a different size in editor mode (like they do in the default theme). I quite like the pseudo WYSIWG experience in Obsidian due to that as I can get a sneak peak into to what it would look like and it helps me quickly find h1, h2, h3 sections.

If this is currently possible, I could not find it sorry :(

**Comment by kepano** [comment]
Right now the best solution for this is to write your own CSS snippet. See forum https://forum.obsidian.md/t/getting-comfortable-with-obsidian-css/133

**Comment by accept82** [comment]
> Как и для вашего сведения, это сработало для меня:
> 
> ```
> :root {
> 
>   --h1:1.5em;
>   --h2:1.25em;
>   --h3:1em;
>   --h4:0.90em;
> }
> ```
> 
> но вы можете настроить числа по своему вкусу.

Thank you friend! Very helpful! Everything is super!

**Comment by N1cl4s** [comment]
> Just as an FYI, this worked well for me:
> 
> ```
> :root {
> 
>   --h1:1.5em;
>   --h2:1.25em;
>   --h3:1em;
>   --h4:0.90em;
> }
> ```
> 
> but you can adjust the numbers to your liking.

Do you happen to know how I can make the heading bold in that syntax you posted?

**Comment by kepano** [comment]
All of the variables can be found near the top of the CSS file, see 
https://github.com/kepano/obsidian-minimal/blob/master/obsidian.css#L177
