### ISSUE TITLE
Images resized in dynamic preview

### ISSUE THREAD

**Issue by perfidopelato** [kepano/obsidian-minimal#460]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.0.13

### Describe the bug

The images are always resized to fill the screen width, when switching to Preview Mode the images are correctly displayed in their original size. 

### Debug info

SYSTEM INFO:
	Operating system: ios 16.0.3 (Apple iPhone)
	Obsidian version: 1.4.0 (80)
	API version: v1.0.0
	Login status: logged in
	Catalyst license: supporter
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: on

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.

**Comment by kepano** [comment]
I am not sure I understand. Have you tried turning off `Maximize media` in Minimal Theme Settings?

See documentation
https://minimal.guide/Block+types/Images

**Comment by perfidopelato** [comment]
Yes, `Maximize Media` is already off. 

These are my settings:
```
{
  "theme": "theme-light",
  "lightStyle": "minimal-light",
  "darkStyle": "minimal-dark",
  "lightScheme": "minimal-macos-light",
  "darkScheme": "minimal-macos-dark",
  "editorFont": "-apple-system,BlinkMacSystemFont,\"Segoe UI Emoji\",\"Segoe UI\",Roboto,Oxygen-Sans,Ubuntu,Cantarell,sans-serif",
  "lineHeight": 1.5,
  "lineWidth": 50,
  "lineWidthWide": 60,
  "maxWidth": 88,
  "textNormal": 16,
  "textSmall": 11,
  "imgGrid": false,
  "imgWidth": "img-default-width",
  "tableWidth": "table-default-width",
  "iframeWidth": "iframe-default-width",
  "mapWidth": "map-default-width",
  "chartWidth": "chart-default-width",
  "colorfulHeadings": false,
  "colorfulFrame": false,
  "colorfulActiveStates": true,
  "trimNames": false,
  "labeledNav": false,
  "fullWidthMedia": false,
  "bordersToggle": false,
  "minimalStatus": true,
  "focusMode": false,
  "underlineInternal": false,
  "underlineExternal": false,
  "useSystemTheme": true,
  "folding": true,
  "lineNumbers": false,
  "readableLineLength": true,
  "devBlockWidth": false,
  "accentHue": 217,
  "accentSat": 87,
  "trimCols": true,
  "maxColWidth": "18em",
  "minimalIcons": true,
  "fancyCursor": true,
  "frostedSidebar": true,
  "bordersTitle": false,
  "uiFont": "-apple-system,BlinkMacSystemFont,\"Segoe UI Emoji\",\"Segoe UI\",Roboto,Oxygen-Sans,Ubuntu,Cantarell,sans-serif",
  "textFont": "-apple-system,BlinkMacSystemFont,\"Segoe UI Emoji\",\"Segoe UI\",Roboto,Oxygen-Sans,Ubuntu,Cantarell,sans-serif",
  "monoFont": "Menlo,SFMono-Regular,Consolas,Roboto Mono,monospace",
  "relationLinesPreview": true,
  "relationLinesEdit": false
}
```

And this is what I get:
![267166EE-E8BC-49B8-964F-AA6C553095CD](https://user-images.githubusercontent.com/17023798/197410269-42b5e287-7148-4dd1-9bf0-21ec40a93b8c.png)

![081615BF-2CF2-434E-B63A-D353CE5B44BA](https://user-images.githubusercontent.com/17023798/197410286-e5f7c800-fa69-42fe-a9c3-1071d93b15fc.png)

**Comment by perfidopelato** [comment]
OK, I've found it! 

To fix this I've to disable `Readable line length` in the Editor settings.

**Comment by ltroj** [comment]
Maybe someone else will stray here who has the same problem: For me, the only solution was to uninstall the Minimal theme, restart Obsidian and reinstall Minimal. Since then it works as intended.

**Comment by cm0s2** [comment]
I'm having the same issue, even though I have "Maximize Media" turned off. As @perfidopelato wrote, it can be fixed turning off "Readable line length" in the editor settings but it would be nice if the bug could be resolved.

**Comment by ltroj** [comment]
The issue is back for me again, too.

**Comment by Nobody17** [comment]
I also have this issue, `maximize media` is turned off in the settings.
In reading view, the image is displayed correctly.
![Screenshot basb reading mode](https://user-images.githubusercontent.com/24973487/235867147-fac0c333-060d-4e9c-9c38-6dcd8f8b0b4c.png)
In editing view it fills the full width. The height stays the same, so aspect ratio is also not the same and it looks weird.
![Screenshot basb edit mode](https://user-images.githubusercontent.com/24973487/235867150-d173ccdb-1b3d-488f-9437-abc8ca9ba480.png)
Like mentioned earlier in another comment, it does not happen when `readable line length` is turned off, but I have a big screen and would like to use that setting.

This happens to me on Windows 10 and Android.
