### ISSUE TITLE
Kanban plugin font family overwrite

### ISSUE THREAD

**Issue by miharekar** [kepano/obsidian-minimal#463]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.1.0

### Describe the bug

I use Lora serif font and when I use the kanban plugin the font-family seems to be not loaded and wrong:

<img width="572" alt="CleanShot 2022-10-21 at 09 11 23" src="https://user-images.githubusercontent.com/986645/197135106-54222aa8-1f38-4372-bd44-bbee162605f3.png">

which results in default font:

<img width="303" alt="CleanShot 2022-10-21 at 09 11 35" src="https://user-images.githubusercontent.com/986645/197135137-6e5f136e-896d-4e4b-8e6c-2638012228fc.png">

But the moment I uncheck the kanban style, it renders correctly:

<img width="596" alt="CleanShot 2022-10-21 at 09 12 14" src="https://user-images.githubusercontent.com/986645/197135237-320893a3-7d9f-4286-a29e-530c999fdabf.png">

<img width="314" alt="CleanShot 2022-10-21 at 09 12 21" src="https://user-images.githubusercontent.com/986645/197135254-4ebd429a-31ba-4def-9f6f-5bfe59691554.png">

It works correctly in the default obsidian theme, and disabling all the plugins (except kanban) and snippets doesn't do anything.

### Debug info

SYSTEM INFO:
	Obsidian version: v1.0.2
	Installer version: v0.15.6
	Operating system: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 21.6.0
	Login status: logged in
	Catalyst license: vip
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 8
	Plugins enabled: 1
		1: Kanban v1.4.6

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Fixed in 6.1.1

**Comment by miharekar** [comment]
Awesome, thanks! 🙏
