### ISSUE TITLE
Inconsistency of top bar and sidebar with Obsidian 1.0 and `Transluent window` on

### ISSUE THREAD

**Issue by YangHanlin** [kepano/obsidian-minimal#466]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.1.2

### Describe the bug

**Brief description**

With Obsidian 1.0 and `Apperance > Transluent window` enabled, Minimal theme behaves incorrectly for the sidebar and the top bar.

**Steps to reproduce**

1. Install Obsidian 1.0, Minimal theme and its companion plugin (Minimal Theme Settings);
2. Set `Apperance > Transluent window` to enabled, `Appearance > Base color scheme` to `Dark` and `Minimal Theme Settings > Dark mode color scheme` to `Everforest`.

(Actually the issue also exists for other color schemes like `Default` or `Atom`, and for light color schemes as well; but `Everforest` is one of the schemes that make it obvious.)

**Actual behavior**

The appearance of the sidebar and the top bar (see screenshot below; red rectangles are added) seems not to be consistent with other parts of the UI.

![Screenshot of Obsidian 1.0.0 with Minimal Theme (scheme: Everforest)](https://user-images.githubusercontent.com/8692892/197349397-663593bb-51d0-4d8f-bfc9-aeb78eaeb1ed.png)

**Expected behavior**

Apperance of the sidebar and the top bar is consistent with other UI components (as in the screenshot below, with Obsidian 0.15.9).

![Screenshot of Obsidian 0.15.9 with Minimal Theme (scheme: Everforest)](https://user-images.githubusercontent.com/8692892/197350848-50c8e507-f789-43cb-ba62-2cbbd2d471cc.png)

### Debug info

```
SYSTEM INFO:
	Obsidian version: v1.0.0
	Installer version: v0.15.9
	Operating system: Windows 10 Pro 10.0.22621
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Minimal Theme Settings v6.1.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by kepano** [comment]
Sorry I am not sure I see what you mean. When Translucency is enabled the sidebar become and top area becomes translucent. There are some changes coming in Obsidian 1.0.2 that should improve translucency broadly for all themes.

**Comment by YangHanlin** [comment]
> Sorry I am not sure I see what you mean.

@kepano Sorry I didn't state clearly. I think the colors specific to each color scheme are not applied to the sidebar and the top area after translucency is enabled, therefore causing these two areas seem not in harmony with other UI components. The expected behavior is to apply colors specific to each color scheme to the sidebar and the top area even if translucency is enabled (as shown in the second screenshot; it is taken with Obsidian 0.19.5 and **translucency enabled**). Or is it an intentional change?

> There are some changes coming in Obsidian 1.0.2 that should improve translucency broadly for all themes.

Obsidian 1.0.2 is an insider version which I'm unfortunately not eligible to install for now. I'll see whether this issue still exists after it is officially released.

**Comment by kepano** [comment]
With 1.0.2 the sidebar and title bar will be consistent with each other, currently there is a bug in Obsidian causing the top bar to not always have translucency

**Comment by YangHanlin** [comment]
> With 1.0.2 the sidebar and title bar will be consistent with each other, currently there is a bug in Obsidian causing the top bar to not always have translucency

I see. Thanks!
