### ISSUE TITLE
Code Block text wrapping even after wrapping mode set to Scroll

### ISSUE THREAD

**Issue by dvdmtw98** [kepano/obsidian-minimal#467]
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.1.2

### Describe the bug

Even after changing the word wrap setting to scroll text inside code blocks continue to wrap

![image](https://user-images.githubusercontent.com/31100937/197387429-d732a510-8847-4033-b6bc-425b20d66522.png)

![image](https://user-images.githubusercontent.com/31100937/197387455-5a9fa1ca-7d6d-4794-ac17-834dc85d092e.png)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.0.2
	Installer version: v1.0.0
	Operating system: Windows 10 Home Single Language 10.0.22000
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 4
	Restricted mode: off
	Plugins installed: 13
	Plugins enabled: 12
		1: Clear Unused Images v1.0.6
		2: File Explorer Note Count v1.2.0
		3: Minimal Theme Settings v6.1.0
		4: Style Settings v0.4.12
		5: Excalidraw v1.7.25
		6: Obsidian42 - BRAT v0.6.35
		7: Table Generator v1.3.1
		8: Wrap with shortcuts v1.2.0
		9: Image Toolkit v1.3.1
		10: Better Word Count v0.8.1
		11: Advanced Tables v0.17.3
		12: Auto Link Title v1.2.5

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Fixed in 6.1.3

**Comment by dvdmtw98** [comment]
@kepano I am no sure if I am doing something wrong but even on 6.1.4 after enabling the scroll option the code blocks are still wrapping

![image](https://user-images.githubusercontent.com/31100937/197447104-125e5750-4082-49ef-b814-33c542b1abbb.png)

![image](https://user-images.githubusercontent.com/31100937/197447154-5706c410-0786-4918-8123-364fd217ec5d.png)
