### ISSUE TITLE
Search results quite hard to read with Cappuccin light high contrast

### ISSUE THREAD

**Issue by ryadaj** [kepano/obsidian-minimal#468]
**Is your feature request related to a problem? Please describe.**
The text in search results/backlinks menu is quite hard to read when using the Cappuccin high contrast mode. Could be modified using Style Settings but I felt it merited an issue here since it would affect all users. As a mild dyslexic, this is a bit of a challenge 🙃

**Describe the solution you'd like**
It would be good if the font in search results/backlinks results were made more readable when using Cappuccin high contrast light mode.

PS. Beautiful work on this wonderful colour scheme!!

edit: added a screenshot in comments, and meant to say that text which is **highlighted** is specifically what I find difficult to read.

**Comment by ryadaj** [comment]
<img width="1800" alt="Screen Shot 2022-10-23 at 10 14 11" src="https://user-images.githubusercontent.com/82765301/197397824-d39806e9-8ef5-4581-b0f1-bd26719e34bf.png">

**Comment by kepano** [comment]
Fixed in 6.1.3
