### ISSUE TITLE
Accent color not working with some themes

### ISSUE THREAD

**Issue by icebruce** [kepano/obsidian-minimal#469]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.1.0

### Describe the bug

The accent colour defined in the "Appearance" setting does not work with some themes.

Example:

Dracula with custom accent color works as expected
![image](https://user-images.githubusercontent.com/66655064/197421152-b5a15481-71c0-4dab-84e2-01e51de689d6.png)

Atom theme with custom colour does not work
![image](https://user-images.githubusercontent.com/66655064/197421268-77e971b7-1b91-4c57-be87-8f72da03af93.png)

Note: when loading Obsidian the colour is displayed for a brief moment but then gets overridden by the accent colour of the theme

### Debug info

SYSTEM INFO:
	Obsidian version: v1.0.2
	Installer version: v0.14.6
	Operating system: Windows 10 Pro 10.0.19043
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off

**Comment by kepano** [comment]
Fixed in 6.1.4
