### ISSUE TITLE
Make color of inactive tabs configurable

### ISSUE THREAD

**Issue by eikowagenknecht** [kepano/obsidian-minimal#470]
**Is your feature request related to a problem? Please describe.**
With the window frame color settings I use, the inactive tabs are not just muted, but really hard to read. 

**Describe the solution you'd like**
I'd love to either have a setting for how muted they should be or for the text color.

![image](https://user-images.githubusercontent.com/1475672/197589208-0bf64a07-ecfc-4d92-a07f-6e507e4d3c70.png)

**Comment by kepano** [comment]
This is already configurable via Style Settings > Minimal > Tab text color

make sure you are using the latest version of Minimal.
