### ISSUE TITLE
Option to disabled Code Wrap not working even after the latest update

### ISSUE THREAD

**Issue by dvdmtw98** [kepano/obsidian-minimal#472]
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.1.4

### Describe the bug

The ability to disable code wrap not working even on the latest version of the theme

Image of Issue: https://github.com/kepano/obsidian-minimal/issues/467#issuecomment-1288391550

Previous Opened Issue: https://github.com/kepano/obsidian-minimal/issues/467

### Debug info

SYSTEM INFO:
	Obsidian version: v1.0.2
	Installer version: v1.0.0
	Operating system: Windows 10 Home Single Language 10.0.22621
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 5
	Restricted mode: off
	Plugins installed: 12
	Plugins enabled: 12
		1: Clear Unused Images v1.0.6
		2: File Explorer Note Count v1.2.0
		3: Minimal Theme Settings v6.1.0
		4: Style Settings v0.4.12
		5: Excalidraw v1.7.25
		6: Table Generator v1.3.1
		7: Wrap with shortcuts v1.2.0
		8: Image Toolkit v1.3.1
		9: Better Word Count v0.8.1
		10: Advanced Tables v0.17.3
		11: Auto Link Title v1.2.5
		12: Sortable v0.2.6

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
I am unable to reproduce the issue.

Please try disabling snippets and plugins.

**Comment by dvdmtw98** [comment]
@kepano I disabled all by snippets and all plugins as will (leaving Style Settings & Minimal Settings) but still no difference
Also my Obsidian debug info still shows I have 3 snippets enabled not sure why

```
SYSTEM INFO:
	Obsidian version: v1.0.2
	Installer version: v1.0.0
	Operating system: Windows 10 Home Single Language 10.0.22621
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 3
	Restricted mode: off
	Plugins installed: 12
	Plugins enabled: 2
		1: Minimal Theme Settings v6.1.0
		2: Style Settings v0.4.12

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

## Sandbox Vault Details

Sandbox Vault with Minimal theme and just the Style Settings Plugin but still the scroll is not working

![image](https://user-images.githubusercontent.com/31100937/197683625-f10eb996-54f2-4a66-8345-1a0c0adc9c12.png)

![image](https://user-images.githubusercontent.com/31100937/197683794-8306d08f-a1b0-4e74-8ecc-c2e82f9ff931.png)

```
SYSTEM INFO:
	Obsidian version: v1.0.2
	Installer version: v1.0.0
	Operating system: Windows 10 Home Single Language 10.0.22621
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Style Settings v0.4.12

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by kepano** [comment]
To answer your last question, no, the scroll bar would be on each line not on the container. That's because there is no container for the entire code block in edit mode.

Can I ask, what is your use case? Is your entire file filled with code? Obsidian is not a code editor you may be trying to do something it's not really intended for.

You can find feature requests in the forum for code wrap/scroll: https://forum.obsidian.md/t/live-preview-better-treatment-of-code-blocks-code-wrap-horizontal-scroll-and-smart-indent/33718

If you want to use Obsidian as a code editor I would recommend turning off Readable Line Length and using a snippet to allows all of the text on the page to overflow. Then the scroll bar would be on the entire pane but it would mean that regular paragraphs stop wrapping also.

**Comment by kepano** [comment]
If you update to 6.1.5 the lines should now wrap when syntax highlighting is present. Unfortunately it means that the scrolling is still per line for the reasons stated above.

**Comment by dvdmtw98** [comment]
So I use Obsidian to maintain a repository of code snippets on various languages along with notes on some other topics. Some of the code snippets have very long lines and with the code wrap enabled they end up taking 2-3 lines which looks strange when in an IDE its just one line.

Was hopping there would have been a way to enable scroll on the entire container which would have been ideal for my case. Looking at the forum discussion and what you have mentioned this is not possible so I guess I have no option but to just role with it.

But leaving this aside why is the code blocks not wrapping when its set to certain languages is there some mistake on my part ?
