### ISSUE TITLE
[Obsidian Mobile] Heading level 3 is not too different from the default font

### ISSUE THREAD

**Issue by pyxelr** [kepano/obsidian-minimal#474]
Hi,

I am finding it hard to detect headings level 3 (`### H3`) inside the Obsidian mobile app. Unfortunately, H3's font size is 99% identical to the default font. Here is an example with some "_lorem ipsum_" text mixing H3s with the default font:

![minimal_theme](https://user-images.githubusercontent.com/30161753/197864845-b870650f-3453-416b-94d9-3e70c64d751b.jpg)

On the contrary, here is how it looks for the default theme:

![default_theme](https://user-images.githubusercontent.com/30161753/197864899-ed87d156-560e-4855-a5a5-c72a2a7769fc.jpg)

As a solution, I could try the colourful headings, but I am syncing my plugin settings with Obsidian sync, and on desktop I prefer not seeing any colourful headings. Perhaps, I could also try the [Style settings](https://github.com/mgmeyers/obsidian-style-settings) plugin, but I believe that there might be other users finding the same problem.

**Comment by pyxelr** [comment]
After some further testing, I have found out what works best for me (I'm using Minimal theme with `Atom` light mode and `Dracula` dark mode color schemes). So, I've installed the [Style settings](https://github.com/mgmeyers/obsidian-style-settings) plugin and for each heading (H2-H6), I've set up the following:
- text color (light): `#652CA9`
- text color (dark): `#BEB1CE`
- divider line: ✓

At the moment, it looks pretty readable; so we may close this issue, although it may serve as an inspiration for a global modification.

![minimal_modified](https://user-images.githubusercontent.com/30161753/197873147-ff8bf323-cc22-4db5-ae16-b3e168ce15ba.jpg)

**Comment by kepano** [comment]
Headings can be customized via Style Settings, no plans to change the defaults
