### ISSUE TITLE
In Win11, the upper right switch window is darker than other areas.

### ISSUE THREAD

**Issue by i-iooi-i** [kepano/obsidian-minimal#475]
![image](https://user-images.githubusercontent.com/1827701/198016239-4a4c29ea-6d38-42bc-8b7f-4cddeebf459c.png)

![image](https://user-images.githubusercontent.com/1827701/198016464-80767bae-bf91-4cb0-95b1-501122149181.png)

Hello, I'm using Minimal with "Style Settings", which is the best theme I've ever used.
But there is a small problem. I use the WIN11 system. There will always be a darker color in the button at the upper right corner. This area will interfere with the vision, especially in the white theme.
Do you have any plans to solve this problem in the future? thank you. 💕

**Comment by i-iooi-i** [comment]
![image](https://user-images.githubusercontent.com/1827701/198017720-8773019d-dbfc-4851-b152-afbdaa41870d.png)

![image](https://user-images.githubusercontent.com/1827701/198017938-3f111bc0-0258-4a37-a23f-5f925ea19b37.png)

Even if "Style Settings" is stopped, this problem still exists.
The use of "Style Settings" will only make this area more obvious.

**Comment by kepano** [comment]
Fixed in 6.1.8

**Comment by i-iooi-i** [comment]
> Fixed in 6.1.8

Thanks, everything is perfect now
