### ISSUE TITLE
Unexpected Transparency 

### ISSUE THREAD

**Issue by shindgewongxj** [kepano/obsidian-minimal#478]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

6.1.0

### Describe the bug

Unexpected transparency on left sidebar with focus mode on.

### Debug info

SYSTEM INFO:
	Obsidian version: v1.0.3
	Installer version: v1.0.0
	Operating system: Darwin Kernel Version 22.2.0: Sun Oct 16 18:10:49 PDT 2022; root:xnu-8792.60.32.0.1~11/RELEASE_X86_64 22.2.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: adapt to system
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 3
	Plugins enabled: 3
		1: Minimal Theme Settings v6.1.0
		2: Advanced Tables v0.17.3
		3: Mind Map v1.1.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Can you share screenshots of the issue?

**Comment by shindgewongxj** [comment]
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/59656935/198202066-4e244ac4-44b0-47b9-867e-1804ea5f7672.png">

**Comment by kepano** [comment]
Fixed in 6.1.9
