### ISSUE TITLE
Setting the table width to wide in the minimal settings doesnt allow overwriting it in a specific file to `table-max`

### ISSUE THREAD

**Issue by tim-hilde** [kepano/obsidian-minimal#481]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.1.9

### Describe the bug

Setting the table width to wide in the minimal settings doesnt allow overwriting it in a specific file to `table-max`. Using `max` works though

### Debug info

SYSTEM INFO:
	Obsidian version: v1.0.3
	Installer version: v0.14.6
	Operating system: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 22.1.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 35
	Restricted mode: off
	Plugins installed: 72
	Plugins enabled: 69
		1: Divide & Conquer v0.4.0
		2: Advanced Mobile Toolbar v1.8.0
		3: Better footnote v1.0.1
		4: Calendar v1.5.10
		5: Typewriter Scroll v0.2.2
		6: Code block from selection v1.0.7
		7: Convert url to preview (iframe) v0.5.0
		8: Creases v0.6.5
		9: Dataview v0.5.47
		10: floating toc v2.2.3
		11: Garble Text v1.2.0
		12: Hotkey Helper v0.3.15
		13: Hotkeys++ v0.2.7
		14: Lapel v0.1.0
		15: Macros v0.1.0
		16: Markdown Table Editor v0.3.1
		17: Metadata Extractor v1.0.2
		18: Default New Tab Page v0.10.0
		19: Natural Language Dates v0.6.1
		20: Admonition v9.0.5
		21: Advanced Slides v1.18.1
		22: Advanced URI v1.28.2
		23: Another Quick Switcher v7.2.1
		24: Apply Patterns v2.1.1
		25: Auto Hide v0.4.4
		26: Bulk Rename v0.4.4
		27: Obsidian Charts v3.6.3
		28: Contextual Typography v2.2.4
		29: Copy Block Link v1.0.4
		30: Daily Stats v1.0.4
		31: Dynamic Highlights v0.3.1
		32: Dynamic Table of Contents v0.0.27
		33: Obsidian Enhancing Export v1.1.7
		34: Excel to Markdown Table v0.4.0
		35: Obsidian Git v2.8.0
		36: Heading Shifter v1.3.0
		37: Hider v1.2.3
		38: Hotkeys for templates v1.4.3
		39: Hover Editor v0.11.6
		40: Kanban v1.5.1
		41: LanguageTool Integration v0.3.0
		42: Minimal Theme Settings v6.1.0
		43: Pandoc Reference List v1.2.10
		44: Query Control v0.5.0
		45: QuickShare v1.0.1
		46: Quiet Outline v0.3.3
		47: Regex Find/Replace v1.2.0
		48: Remember File State v1.0.6
		49: Smart Typography v1.0.18
		50: Sortable v0.2.6
		51: Style Settings v0.4.12
		52: System Dark Mode v1.1.1
		53: Table Generator v1.3.1
		54: Tabout v1.0.0
		55: Todoist Link v2.0.5
		56: Version History Diff v2.0.8
		57: Force note view mode v1.1.1
		58: Zotero Integration v2.2.30
		59: Obsidian42 - BRAT v0.6.36
		60: Table Enhancer v0.2.2
		61: Pane Relief v0.4.1
		62: Periodic Notes v0.0.17
		63: Plugin Changelogs v1.3.0
		64: Supercharged Links v0.9.3
		65: Templater v1.14.3
		66: Workspaces Plus v0.3.2
		67: QuickAdd v0.5.5
		68: Obsidian42 - Strange New Worlds v0.0.35
		69: Omnisearch v1.7.8

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Fixed in 7.0
