### ISSUE TITLE
Custom Spacing for Headings

### ISSUE THREAD

**Issue by GinoReiji** [kepano/obsidian-minimal#482]
I only use live editing mode and I'm just wondering if there's a way to increase the space between the headers? Adding space by pressing enter works but the space become too large, since my text size is set as large for ease of reading. 

Right now my work-around is to have a css file for the spacing, it works, but after awhile, my cursor stops moving properly - i.e., it only shows up at the end of the block and if I want to, say, choose a word in the middle of the sentence, I can't just click there, I have to use the 🠔 key to go to where I want it to. Turning off the css fixes this problem straight away. If I restarted Obsidian and reactivate the css file, it works again but not long after that, the problem persists again

Below is the script I've been using to create the headings. I don't know much about css so there have been a lot of copy and paste. Not sure what I've done wrong. I've also tried to make the space for H1 bigger than the rest, but it doesn't work

`.mod-cm6 .cm-editor .HyperMD-header, .markdown-reading-view .markdown-preview-section :is(h1,h2,h3,h4,h5,h6) {
    line-height: 1em !important;
    margin:5px 0px 10px 0px !important;
    padding: 1px 0px 5px 0px !important;
}`

**Comment by kepano** [comment]
New settings for this in 7.0, note it requires Obsidian 1.3.7+ (insider)
