### ISSUE TITLE
Add color scheme from Stephan Ango's site to Minimal Theme

### ISSUE THREAD

**Issue by ryadaj** [kepano/obsidian-minimal#487]
**Problem**
Minimal Theme has been a wonderful help to my issue already, so thank you for creating this theme! However, my vision likes to be complicated and I struggle with mild dyslexia that is worsened/improved by certain colour combinations.

It's also challenging for me to develop my own color schemes using Style Settings as I'm not sufficiently creative or technically able to choose good/effective combinations.

**Solution**

The palatte on Stephan Ango's (your) blog is very clean and makes for one of the most easy-to-read I've come across. It would be wonderful if you would be willing to add this as a color scheme to Minimal Theme, but I understand if not, since this is your personal blog.

<img width="1800" alt="Screenshot 2022-11-09 at 12 48 59" src="https://user-images.githubusercontent.com/82765301/200903340-baeeae43-02ae-401c-86ac-4424b74f98fd.png">

<img width="1800" alt="Screenshot 2022-11-09 at 12 48 44" src="https://user-images.githubusercontent.com/82765301/200903360-06748253-f23f-4bbf-8cdd-f94ceab78743.png">

**Comment by kepano** [comment]
Have you considered using the Gruvbox color scheme that comes with Minimal Theme Settings?

**Comment by kepano** [comment]
I don't plan to add this color scheme to the official list but you can achieve a similar look by importing the following style settings

```
{
  "minimal-style@@bg1@@light": "#FFFCF0",
  "minimal-style@@bg2@@light": "#FFFCF0",
  "minimal-style@@ui1@@light": "#E3E0D4",
  "minimal-style@@ax1@@light": "#000000",
  "minimal-style@@tx2@@light": "#5A5046CC",
  "minimal-style@@h2-size": "1.2em",
  "minimal-style@@h1-size": "1.8em",
  "minimal-style@@inline-title-weight": 600,
  "minimal-style@@ax1@@dark": "#DAD6C6",
  "minimal-style@@bg1@@dark": "#2B2B2C",
  "minimal-style@@bg2@@dark": "#2B2B2C",
  "minimal-style@@tx1@@dark": "#DAD6C6",
  "minimal-style@@ax2@@dark": "#62ABA4",
  "minimal-style@@ax2@@light": "#62ABA4",
  "minimal-style@@ax3@@dark": "#62ABA4",
  "minimal-style@@ax3@@light": "#62ABA4",
  "minimal-style@@tx2@@dark": "#A8A49FCC"
}
```

**Comment by ryadaj** [comment]
Ahhh thanks for those settings! I love the result and really appreciate you sharing this with me.

**Comment by ryadaj** [comment]
FYI

<img width="1912" alt="Screenshot 2022-11-09 at 14 59 07" src="https://user-images.githubusercontent.com/82765301/200928965-08e40aae-904b-4599-b155-2deb99dc79ce.png">

<img width="1912" alt="Screenshot 2022-11-09 at 14 58 29" src="https://user-images.githubusercontent.com/82765301/200928906-e9c7ca32-b501-4787-874b-91807b77fc98.png">

**Comment by ryadaj** [comment]
Gonna go ahead and say thank you so much for the [Flexoki](https://github.com/kepano/obsidian-minimal/releases/tag/7.3.0) update, which is basically what I asked for here. You da best!!
