### ISSUE TITLE
Image Grid not putting all images in to a grid

### ISSUE THREAD

**Issue by Radther** [kepano/obsidian-minimal#489]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

6.1.9

### Describe the bug

The image grid doesn't consistently put images in to a grid. Sometimes it'll only put 2 or 3 images in to a grid and the rest will be full width on their own. 

Here are some example images:

![image](https://user-images.githubusercontent.com/5844281/201215822-2e0195b3-cb5a-4da5-9cb5-6e5596c5764e.png)
![image](https://user-images.githubusercontent.com/5844281/201215861-6e7b9601-8862-4f8b-a618-f1e4a0ba7099.png)

Here you can see that only the bottom two images are next to each other despite the source having what should be two more rows above it. 

[TestImages.zip](https://github.com/kepano/obsidian-minimal/files/9984933/TestImages.zip)

Here is a test vault that exhibits the issue. This was created using a completely fresh vault with nothing else installed but the required plugins. 

### Debug info

SYSTEM INFO:
	Obsidian version: v1.0.3
	Installer version: v0.15.9
	Operating system: Windows 10 Pro 10.0.19043
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 2
		1: Contextual Typography v2.2.4
		2: Minimal Theme Settings v6.1.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by Alejandro-Stolz** [comment]
This happened to me too, can you try to resize the images? ![[imagename.png||100x100]] change 100x100 for the dimensions that suit you. In my case, after doing that, they did rearrange in a grid

**Comment by Radther** [comment]
> This happened to me too, can you try to resize the images? ![[imagename.png||100x100]] change 100x100 for the dimensions that suit you. In my case, after doing that, they did rearrange in a grid. If that does not work, try to write them next to each other, instead of making a new line in between

I managed to get around it by making sure all of the images are png or jpeg. Lot of effort though. I think it's webp in particular that seem to break things.

**Comment by Alejandro-Stolz** [comment]
Ah, I didn't even realize they were webp. I'm glad you could solve it :)

**Comment by Servinjesus1** [comment]
I'd like to add that `BMP` images also do not work.

Now that we know more details of the bug, I'd appreciate if the author updated the title and description to reflect the core issue being image grids not working with all image types. Hopefully that helps produce some momentum on this!

**Comment by kepano** [comment]
Fixed in 7.0
