### ISSUE TITLE
Missing custom icon

### ISSUE THREAD

**Issue by davidedellagiustina** [kepano/obsidian-minimal#49]
I'm using the Excalidraw plugin, and it appears that the "save" icon is missing from the set of customized ones:
![immagine](https://user-images.githubusercontent.com/22601842/139554012-db3abead-a02f-4a7a-8fe9-e47d52ee3cd2.png)

Moreover, it would be really cool if the Excalidraw canvas colors could match the theme, too! (should I move this to a new issue?)

**Comment by kepano** [comment]
Fixed in 4.0.6
