### ISSUE TITLE
After update to 6.1.9 titles in tab title bar are not visible unless mouse cursor is over them

### ISSUE THREAD

**Issue by myndatlas** [kepano/obsidian-minimal#490]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.1.9

### Describe the bug

After the update to 6.1.9 Titles in tab title bar are not visible except when hovered over with the cursor.
It did not occur in an an earlier version, I think it may have been 6.0.5 but I failed to take note of it so I am not exactly sure.

This occurs in all my vaults and in the sandbox vault. It does not occur with the default or any other theme. It occurs regardless of light/dark mode, any contrast setting or color scheme. It occurs regardless of the Minimal Theme Settings Plugin being installed.

It occurs on macOS Catalina 10.15.7 (Obsidian v1.0.3), iPadOS 15.7.1 (Obsidian v1.4.1 (83)), Raspberry Pi OS 64-Bit Bullseye, aarch64 (Obsidian v1.0.3), but does not occur on iOS 15.6.1 (iPhone 13) where I can't open multiple tabs side by side in the same way as the other devices. (The debug info below is from a sandbox vault on the Mac.) 

Focus mode is off (and works as expected when on).

Tab Title Bar when not being hovered over with minimal theme:
![Screenshot 2022-11-12 at 5 22 54 PM](https://user-images.githubusercontent.com/94186933/201486732-49c4de6a-5fa0-43db-bd30-65226405f573.png)

Vs the same when hovered over:
![Screenshot 2022-11-12 at 5 22 49 PM](https://user-images.githubusercontent.com/94186933/201486742-2d76f9ee-52f8-4b56-900b-a7b2d40ae5a9.png)

Compare to the default theme:
![Screenshot 2022-11-12 at 5 21 34 PM](https://user-images.githubusercontent.com/94186933/201486716-644988f0-ad53-4973-a7ca-30b4f83158d6.png)

*Screenshots have minimal theme settings plugin installed and low contrast mode on so there is a visual difference between that and the default theme in the screenshots. It occurs even without this installed on the sandbox vault as in the debug below.

### Debug info

SYSTEM INFO:
	Obsidian version: v1.0.3
	Installer version: v1.0.0
	Operating system: Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64 19.6.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: on

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.

**Comment by kepano** [comment]
This is a feature. You can change the setting in Style Settings > Titles > Tab title bar

**Comment by myndatlas** [comment]
Thank you! 

I had no idea that I would need a totally different plugin to turn the default behaviour back on.

**Comment by kepano** [comment]
Minimal theme is a minimal theme 😉
