### ISSUE TITLE
Dayspring/Al Dente Color Scheme

### ISSUE THREAD

**Issue by LuckyLouLou** [kepano/obsidian-minimal#492]
**Is your feature request related to a problem? Please describe.**
My fav theme was al dente but I stopped using it when it was no longer maintained. Just noticed that the  [Dayspring](https://github.com/erykwalder/dayspring-theme) theme was recently released and it looks great! But I'm just loving the Minimal theme features. 

**Describe the solution you'd like**
Would it be possible to add a Dayspring color theme the minimalist theme settings plugin?

**Comment by kepano** [comment]
This can be achieve using Style Settings
https://minimal.guide/Plugins/Style+Settings
