### ISSUE TITLE
A "Pin" Checkbox Style

### ISSUE THREAD

**Issue by m-paul** [kepano/obsidian-minimal#493]
**Is your feature request related to a problem? Please describe.**
It is possible to mark a checkbox as a star or bookmark, but I would like to mark one with a "pin" icon. 
![image](https://user-images.githubusercontent.com/18966599/201728974-994a639c-c2cf-4852-834c-b1a26093aa98.png)

**Describe the solution you'd like**
I want a means of either customizing existing checkbox styles for alternative icons or the addition of a pin style.

**Comment by kepano** [comment]
See #526
