### ISSUE TITLE
Checklist action on preview mode

### ISSUE THREAD

**Issue by vando** [kepano/obsidian-minimal#494]
When a checklist has a dash `- [/]` and got click on preview mode it changes to _to-do_/_not-started_ mode.

Is it possible to change from `- [/]` to `-[x]` when click task in preview mode? 

_In progress_:

![1659060979196](https://user-images.githubusercontent.com/390505/202025435-604f8282-6dce-409d-ba8e-a553db481006.png)

Then click and change to _Done_:

![1659060979197](https://user-images.githubusercontent.com/390505/202025517-5809c7f3-2b58-45b3-94a4-73a18b9d7593.png)

Thanks in advance.

**Comment by kepano** [comment]
This is not something themes can control. You should ask in the Obsidian Forum
