### ISSUE TITLE
Title sizes are inconsistent with the default theme

### ISSUE THREAD

**Issue by TheRealGramdalf** [kepano/obsidian-minimal#495]
**Is your feature request related to a problem? Please describe.**
Titles
# Like this
are inconsistent between the default theme and minimal. 
![image](https://user-images.githubusercontent.com/79593869/202057247-8ae59596-88e3-4f34-b149-1f8afa55739a.png)
![image](https://user-images.githubusercontent.com/79593869/202057275-650a4af0-f915-4a5d-b226-442931869536.png)

**Describe the solution you'd like**
As not all people want this functionality, a toggle to enable the default bold + larger font would be great.

**Comment by kepano** [comment]
You can edit this in Style Settings. Otherwise this is the purpose of a theme.
