### ISSUE TITLE
Gap on right side bar

### ISSUE THREAD

**Issue by GabrielSegatto** [kepano/obsidian-minimal#499]
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.1.9

### Describe the bug

![Captura de Tela (100)](https://user-images.githubusercontent.com/23456539/203815045-0f81cd56-e544-44cb-9412-24473b988c5a.png)

Hi!

I not sure if this can be fixed with the theme or some other CSS snippet, but when I use the dark mode, there is a small gap is then the open note and the right sidebar that are only noticeable whit stacked tabs activated

### Debug info

SYSTEM INFO:
	Obsidian version: v1.0.3
	Installer version: v1.0.3
	Operating system: Windows 10 Home Single Language 10.0.22000
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 24
	Plugins enabled: 10
		1: Admonition v9.0.5
		2: Text Format v1.8.5
		3: Natural Language Dates v0.6.1
		4: Flashcards v1.6.5
		5: Minimal Theme Settings v6.1.0
		6: Hider v1.2.3
		7: Contextual Typography v2.2.4
		8: Style Settings v0.4.12
		9: Paste URL into selection v1.7.0
		10: Sidebar Expand on Hover v1.0.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Issues that are present in the default theme should be reported on Obsidian Forums. It's not specific to Minimal.
