### ISSUE TITLE
Fonts changing to custom one.

### ISSUE THREAD

**Issue by 4l1fe** [kepano/obsidian-minimal#50]
Hey. I've tried to replace css vars
```
  Font styles

  /* Preview mode */

  --text:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif;
  
  /* Editor mode */

  --text-editor:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif;
  
  /* Code */

  --font-monospace:Menlo,SFMono-Regular,Consolas,"Roboto Mono",monospace;

  /* UI */

  --font-ui:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif;
```
 to my preferable font `Ubuntu Mono` but it didn't apply.

May i ask to give me a hint how to change the fonts?

**Comment by kepano** [comment]
I would recommend using the Minimal Theme Settings plugin to change font. Make sure that the name of the font exactly matches the name on your system, you may also need to add quotes around it.

**Comment by 4l1fe** [comment]
Oh, that's interesting. Theme is configuring by a plugin. Ok, thank you, i'm trying it.
