### ISSUE TITLE
Unexpected display error on tabs with focus mode on

### ISSUE THREAD

**Issue by shindgewongxj** [kepano/obsidian-minimal#501]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.1.11

### Describe the bug

<img width="1210" alt="Screenshot" src="https://user-images.githubusercontent.com/59656935/205472517-76f94f32-7fbd-4913-bfab-9f2fc6b8072e.png">

### Debug info

SYSTEM INFO:
	Obsidian version: v1.0.3
	Installer version: v1.0.0
	Operating system: Darwin Kernel Version 22.2.0: Mon Nov 14 23:08:10 PST 2022; root:xnu-8792.61.2~6/RELEASE_X86_64 22.2.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 3
	Plugins enabled: 3
		1: Minimal Theme Settings v6.1.0
		2: Advanced Tables v0.18.0
		3: Mind Map v1.1.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by shindgewongxj** [comment]
<img width="1235" alt="Screenshot 2022-12-21 at 8 16 59 AM" src="https://user-images.githubusercontent.com/59656935/208791503-1be069cf-b0f2-4011-bc93-33d1ec287bd6.png">
The right sidebar icon would be hidden mistakenly as well.

**Comment by kepano** [comment]
I am not able to reproduce this
