### ISSUE TITLE
Excalidraw theme issue 

### ISSUE THREAD

**Issue by zsviczian** [kepano/obsidian-minimal#502]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.1.11

### Describe the bug

From my experience, the issues raised in #427 and #491 are not fully resolved. Would it be possible to add an option to the theme to not affect Excalidraw at all?

I love the minimal theme... but the way it handles Excalidraw styling interferes with the dark/light mode switch in Excalidraw. See this screenshot as an example. 

![image](https://user-images.githubusercontent.com/14358394/205512105-93adfb52-5b87-465b-9815-bf243c980ba8.png)

I use Obsidian in dark mode, but I frequently draw on a light canvas in Excalidraw. This is not supported by the minimal theme.

I am planning to add the Alternative Dark mode demonstrated in [this video](https://youtu.be/LtR04fNTKTM) to the core Excalidraw plugin package, but the script is overridden by the Minimal Theme settings. Since Minimal Theme is so popular, I'm concerned that the alternative dark mode will not work for many of my users.

If I clean excalidraw from the theme, dark/light mode switch works as expected, and so does the alternative dark mode script.

https://user-images.githubusercontent.com/14358394/205512474-ed2b0f17-bfe4-4a6b-8947-99c5f04fa51e.mp4

### Debug info

SYSTEM INFO:
	Obsidian version: v1.1.0
	Installer version: v1.0.3
	Operating system: Windows 10 Home 10.0.22621
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v6.1.11
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 56
	Plugins enabled: 17
		1: Dataview v0.5.47
		2: Map View v2.2.0
		3: Obsidian42 - BRAT v0.6.36
		4: Obsidian42 - Jump-to-Date v1.0.14
		5: Obsidian42 - WordNet Dictionary v2.0.1
		6: Recent Files v1.3.3
		7: Hot Reload v0.1.9
		8: Custom Frames v2.4.4
		9: ExcaliBrain v0.1.16
		10: Customizable Page Header and Title Bar v4.7.1
		11: Kanban v1.5.1
		12: Advanced Tables v0.17.3
		13: Banners v1.3.3
		14: Templater v1.16.0
		15: Pane Relief v0.4.1
		16: Excalidraw v1.8.2
		17: Minimal Theme Settings v6.1.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
The problem I see is that there are too many levels of override happening. There is a cleaner way to solve this within Excalidraw plugin itself:

1. Use Obsidian's default theme variables instead of custom colors. This way Excalidraw will automatically respond to themes instead of forcing theme developers to create custom rules for Excalidraw
2. Use the `.theme-light` and `.theme-dark` variables on the Excalidraw container itself, so that the variable definitions get passed in

Doing these two things would enable me to completely remove any Excalidraw styling in Minimal

**Comment by zsviczian** [comment]
Unfortunately, changing the Excalidraw component's css because of Obsidian is unlikely to succeed. Even smaller Obsidian specific changes are resisted by the Excalidraw product team... Obsidian is just one of many use-cases. I have to cook with what's out of the box in Excalidraw.

I also don't think the Excalidraw theme should necessarily follow the dark/light theme setting of Obsidian, but rather of the drawing being edited. I for one, always use Obsidian in dark mode, but most of my drawings have a lighter background. In the plugin settings the user can fine tune the canvas color settings (i.e. to match or not the Obsidian theme)

![image](https://user-images.githubusercontent.com/14358394/205592210-c28d706b-b824-4796-8231-46ec56b8a48d.png)
