### ISSUE TITLE
"cssClass: embed-strict" no longer works

### ISSUE THREAD

**Issue by ernest67** [kepano/obsidian-minimal#503]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.1.12

### Describe the bug

After upgrading to v1.1.0 the css class "cssClass: embed-strict" no longer works - even I added "cssClass: embed-strict" to YAML there are no changes to the document. Is there any way you can fix it please?

The first photo shows that I have added the helper class in the YAML section, while the second photo shows that I have removed the helper class. As you can see, whether adding the helper class or not does not change anything. 
![Screenshot 2022-12-06 at 18 48 15](https://user-images.githubusercontent.com/95947701/205996293-dcd7c236-448a-4e4e-8593-6d443ad3055e.png)
![Screenshot 2022-12-06 at 18 48 56](https://user-images.githubusercontent.com/95947701/205996427-8ba3e15f-160d-4b91-9440-a0e50e8cb19b.png)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.1.0
	Installer version: v0.15.8
	Operating system: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64 22.1.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal v6.1.12
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 40
	Plugins enabled: 36
		1: Admonition v9.0.5
		2: Minimal Theme Settings v6.1.0
		3: Advanced Tables v0.18.0
		4: Better Word Count v0.8.1
		5: Calendar v1.5.10
		6: Checklist v2.2.10
		7: Dataview v0.5.47
		8: Hider v1.2.3
		9: Hotkeys++ v0.2.7
		10: Icons v0.3.0
		11: Kanban v1.5.1
		12: Mind Map v1.1.0
		13: Outliner v4.1.1
		14: Paste URL into selection v1.7.0
		15: Style Settings v0.4.12
		16: Indentation Guides v1.0.8
		17: Electron Window Tweaker v1.0.8
		18: Sortable v0.2.6
		19: Tag Wrangler v0.5.5
		20: Book Search v0.5.8
		21: Buttons v0.4.19
		22: Icon Folder v1.4.3
		23: Contextual Typography v2.2.4
		24: Smart Typography v1.0.18
		25: Highlightr v1.2.2
		26: Annotator v0.2.8
		27: Folder Note v0.7.3
		28: File Tree Alternative Plugin v2.2.4
		29: Linter v1.9.0
		30: Templater v1.16.0
		31: QuickAdd v0.7.0
		32: Natural Language Dates v0.6.1
		33: Recent Files v1.3.5
		34: Hover Editor v0.11.8
		35: Readwise Official v2.0.1
		36: Banners v1.3.3

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Fixed in 6.1.13
