### ISSUE TITLE
color changing for code-punctuation and code-comment seems not working

### ISSUE THREAD

**Issue by dalezys** [kepano/obsidian-minimal#504]
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.1.11

### Describe the bug

color changing in style setting for code-punctuation and code-comment seems not working. 

### Debug info

{
  "minimal-style@@code-size": "12px",
  "minimal-style@@minimal-code-scroll": true,
  "minimal-style@@code-normal@@dark": "#E6BB82",
  "minimal-style@@code-function@@dark": "#EFA162",
  "minimal-style@@code-keyword@@dark": "#DE8C8C",
  "minimal-style@@code-important@@dark": "#A1C0E9",
  "minimal-style@@code-property@@dark": "#AD7B5F",
  "minimal-style@@code-punctuation@@dark": "#8BB7C6",
  "minimal-style@@code-string@@dark": "#82A970",
  "minimal-style@@code-value@@dark": "#9082BE"
}

**Comment by kepano** [comment]
Which version of Obsidian are you using? Try updating to the latest.

Please paste the debug info (command palette → debug info)

**Comment by dalezys** [comment]
V1.0.3, I think that’s the latest version (debug info below). I have also attached pictures of a code sample and my style setting just for your reference. 

Thank you for your time.




SYSTEM INFO:
	Obsidian version: v1.0.3
	Installer version: v0.14.15
	Operating system: Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 21.6.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 42
	Plugins enabled: 35
		1: Calendar v1.5.10
		2: Minimal Theme Settings v6.1.0
		3: Obsidian Memos v1.9.7
		4: Advanced Tables v0.18.0
		5: Tasks v1.19.0
		6: cMenu v1.1.2
		7: Editor Syntax Highlight v0.1.3
		8: Checklist v2.2.10
		9: Dataview v0.5.47
		10: Dictionary v2.22.0
		11: Kanban v1.5.1
		12: Mind Map v1.1.0
		13: Paste URL into selection v1.7.0
		14: Tag Wrangler v0.5.5
		15: Templater v1.16.0
		16: Media Extended v2.11.1
		17: Style Settings v0.4.12
		18: Convert url to preview (iframe) v0.5.0
		19: QuickAdd v0.7.0
		20: Tracker v1.10.9
		21: Random Structural Diary v1.1.2
		22: Timelines v0.3.2
		23: Remember cursor position v1.0.7
		24: Auto Link Title v1.2.5
		25: Customizable Menu v2.2.0
		26: Local images v0.14.2
		27: Wikilinks to MDLinks v0.0.12
		28: Excalidraw v1.8.4
		29: Remotely Save v0.3.25
		30: Media Extended BiliBili Plugin v0.3.1
		31: Customizable Page Header and Title Bar v4.6.2
		32: Note Refactor v1.7.1
		33: Folder Note v0.7.3
		34: Heatmap Calendar v0.5.2
		35: Image Toolkit v1.3.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.





{
  "minimal-style@@code-size": "12px",
  "minimal-style@@minimal-code-scroll": true,
  "minimal-style@@code-normal@@dark": "#E6BB82",
  "minimal-style@@code-comment@@dark": "#ACA497",
  "minimal-style@@code-function@@dark": "#EFA162",
  "minimal-style@@code-keyword@@dark": "#DE8C8C",
  "minimal-style@@code-important@@dark": "#A1C0E9",
  "minimal-style@@code-property@@dark": "#AD7B5F",
  "minimal-style@@code-punctuation@@dark": "#8BB7C6",
  "minimal-style@@code-string@@dark": "#82A970",
  "minimal-style@@code-value@@dark": "#9082BE"
}

**Comment by kepano** [comment]
This is unrelated to Minimal, it is due to the difference in syntax highlighting libraries used in read vs edit mode. See official Obsidian forum.
