### ISSUE TITLE
Alignment Issues

### ISSUE THREAD

**Issue by ernest67** [kepano/obsidian-minimal#506]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.1.12

### Describe the bug

Ever since I upgraded to Obsidian 1.1.0, there has been some cosmetic changes that have been bugging me. I would really appreciate if you could kindly look into this. Thanks a lot and appreciate your contribution to the development of Obsidian, it has definitely changed my life.

Problem 1
In **reading mode**, the words pointed by the arrow are not aligned with the rest of the paragraph. This happens whenever the text in the bullet point has to occupy 2 or more lines.
![image](https://user-images.githubusercontent.com/95947701/206450771-6777025d-a75a-40cd-9d4c-d5c70d7898b7.png)

Problem 2
The spacing between the bullet points and the text has increased significantly in **live preview mode** (but becomes normal when I switch to reading mode)
![image](https://user-images.githubusercontent.com/95947701/206451019-987db278-288b-4c90-a7d1-d2b6624db6b4.png)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.1.0
	Installer version: v0.15.8
	Operating system: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64 22.1.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal v6.1.12
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 41
	Plugins enabled: 36
		1: Admonition v9.0.5
		2: Minimal Theme Settings v6.1.0
		3: Advanced Tables v0.18.0
		4: Better Word Count v0.8.1
		5: Calendar v1.5.10
		6: Checklist v2.2.10
		7: Dataview v0.5.47
		8: Hider v1.2.3
		9: Hotkeys++ v0.2.7
		10: Icons v0.3.0
		11: Kanban v1.5.1
		12: Mind Map v1.1.0
		13: Paste URL into selection v1.7.0
		14: Style Settings v0.4.12
		15: Indentation Guides v1.0.8
		16: Electron Window Tweaker v1.0.8
		17: Sortable v0.2.6
		18: Tag Wrangler v0.5.5
		19: Book Search v0.5.8
		20: Buttons v0.4.19
		21: Icon Folder v1.4.3
		22: Contextual Typography v2.2.4
		23: Smart Typography v1.0.18
		24: Highlightr v1.2.2
		25: Annotator v0.2.8
		26: Folder Note v0.7.3
		27: File Tree Alternative Plugin v2.2.4
		28: Linter v1.9.0
		29: Templater v1.16.0
		30: QuickAdd v0.7.0
		31: Natural Language Dates v0.6.1
		32: Recent Files v1.3.5
		33: Hover Editor v0.11.8
		34: Readwise Official v2.0.1
		35: Banners v1.3.3
		36: Outliner v4.1.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Fixed in 6.1.13
