### ISSUE TITLE
List and checkbox elements misaligned

### ISSUE THREAD

**Issue by dcao** [kepano/obsidian-minimal#507]
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.1.13

### Describe the bug

List and checkbox elements are misaligned:

<img width="388" alt="image" src="https://user-images.githubusercontent.com/6006837/206784878-6c4d4c7c-f56f-4bb1-964a-866b4dfd7ad2.png">

This appeared with the Obsidian 1.1 update and the Minimal 6.1.12 update.

### Debug info

SYSTEM INFO:
	Obsidian version: v1.1.0
	Installer version: v0.15.9
	Operating system: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 22.1.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: adapt to system
	Community theme: Minimal v6.1.13
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 34
	Plugins enabled: 26
		1: Advanced Tables v0.18.0
		2: Kanban v1.5.1
		3: Tag Wrangler v0.5.5
		4: Dataview v0.5.47
		5: Vimrc Support v0.8.0
		6: Minimal Theme Settings v6.1.0
		7: Sortable v0.2.6
		8: Hider v1.2.3
		9: Style Settings v0.4.12
		10: Note Refactor v1.7.1
		11: Time Tracker v0.6.1
		12: Zoom v1.1.1
		13: Contextual Typography v2.2.4
		14: Outliner v4.1.1
		15: Hover Editor v0.11.8
		16: Map View v2.2.0
		17: Tasks v2.0.0
		18: Obsidian42 - BRAT v0.6.36
		19: Chat View v1.3.0
		20: Periodic Notes v1.0.0-beta.3
		21: Natural Language Dates v0.6.1
		22: Recent Files v1.3.5
		23: Longform v2.0.0
		24: Projects v1.3.0
		25: Better Word Count v0.9.1
		26: Omnisearch v1.9.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Fixed in 6.1.14

**Comment by dcao** [comment]
Thanks for the prompt reply!

The alignment is still subtly off for me, with 6.1.14:

<img width="115" alt="Screenshot 2022-12-09 at 1 12 45 PM" src="https://user-images.githubusercontent.com/6006837/206796959-a87d0229-7cd0-40eb-b379-3b4a97325ccb.png">

On my config, I fixed this by changing the checkbox's right margin from 6px to 2px, but I don't know if this will fix alignment universally.
