### ISSUE TITLE
Missing icon for the command palette in Obsidian for iOS 

### ISSUE THREAD

**Issue by manuelhubacher** [kepano/obsidian-minimal#51]
I’ve encountered a minor inconvenience when using the theme on my iPad/iPhone. When I pin _open command palette_ to the toolbar, I’m just getting a grey square instead of the expected icon (![Bildschirmfoto 2021-11-01 um 11 14 13](https://user-images.githubusercontent.com/17408325/139656852-0621a293-d909-450d-9f78-a3ee97a28127.png))

![Bildschirmfoto 2021-10-24 um 14 06 34](https://user-images.githubusercontent.com/17408325/139656698-38ef7480-874e-4443-a344-bbc35ee3653f.png)

**Comment by kepano** [comment]
Fixed in 4.0.6
