### ISSUE TITLE
Canvas font changes when editing

### ISSUE THREAD

**Issue by laffan** [kepano/obsidian-minimal#512]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.1.17

### Describe the bug

The font changes to a mystery sans serif font when editing notes through the canvas. This does not happen anywhere else, nor does it happen when using the default Obsidian theme. 

![Screenshot 2022-12-18 214805](https://user-images.githubusercontent.com/5421145/208356977-b0088bb0-965b-475f-ac76-e851e86dc66c.png)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.1.6
	Installer version: v1.0.3
	Operating system: Windows 10 Home 10.0.22621
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v6.1.17
	Snippets enabled: 0
	Restricted mode: on

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.

**Comment by kepano** [comment]
I think this might be a bug with Minimal Theme Settings but it looks you don't have it enabled. Did you have Minimal Theme Settings before? I am curious if you disabled the Minimal Theme Settings plugin but did not restart the app. There is a setting in Minimal Theme Settings to define your editor font.
