### ISSUE TITLE
Last row is hidden in tables

### ISSUE THREAD

**Issue by ironhak** [kepano/obsidian-minimal#513]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

last version

### Describe the bug

When creating a new table the last row border line is hidden:

![Screenshot 2022-12-19 at 12 26 01](https://user-images.githubusercontent.com/62611612/208415689-551c46a2-2eb7-4117-944f-5a9cf5d5cdcc.png)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.0.3
	Installer version: v0.15.9
	Operating system: Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000 21.6.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 4
	Restricted mode: off
	Plugins installed: 26
	Plugins enabled: 23
		1: Hider v1.2.4
		2: Text Snippets v0.1.2
		3: Advanced Tables v0.18.0
		4: Calendar v1.5.10
		5: Clear Unused Images v1.0.6
		6: Dataview v0.5.47
		7: File path to URI v1.4.1
		8: Highlightr v1.2.2
		9: Hotkeys for starred files and searches v0.0.4
		10: Image Toolkit v1.3.1
		11: Kindle Highlights v1.8.1
		12: Minimal Theme Settings v6.1.1
		13: Media Extended v2.11.1
		14: Natural Language Dates v0.6.1
		15: Paste URL into selection v1.7.0
		16: Templater v1.16.0
		17: Typewriter Scroll v0.2.2
		18: Underline v1.2.1
		19: Wikilinks to MDLinks v0.0.12
		20: Zoom v1.1.1
		21: Style Settings v0.4.12
		22: Note Refactor v1.7.1
		23: Chat View v1.4.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Are you using helper classes or Style Settings? Which preferences do you have turned on?
https://minimal.guide/Block+types/Tables

**Comment by ironhak** [comment]
Resolved by disabling “row lines” and enabling “cell lines”. Unfortunately this removed all lines separators in data view tables, I had to add individual helper classes for them.
