### ISSUE TITLE
Table width settings doesn't fix issue

### ISSUE THREAD

**Issue by ajtruex** [kepano/obsidian-minimal#517]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.1.17

### Describe the bug

Cannot make the table width go back to normal even after following the instructions on [https://minimal.guide/](https://minimal.guide/). The column widths are massive. Why would I need 2 additional plugins to fix what is the default in the Default theme?  

### Debug info

SYSTEM INFO:
	Obsidian version: v1.1.8
	Installer version: v0.15.9
	Operating system: Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64 21.6.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal v6.1.17
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 21
	Plugins enabled: 18
		1: Media Extended v2.11.1
		2: Icons v0.3.0
		3: Hotkeys++ v0.2.7
		4: Better Word Count v0.9.1
		5: Gallery v0.5.8
		6: Excalidraw v1.8.6
		7: Calendar v1.5.10
		8: Ozan's Image in Editor Plugin v2.1.5
		9: Reminder v1.1.15
		10: QuickAdd v0.8.0
		11: Advanced URI v1.31.2
		12: Advanced Tables v0.18.1
		13: Natural Language Dates v0.6.1
		14: Image Layouts v0.10.0
		15: Icon Folder v1.4.3
		16: Style Settings v0.4.12
		17: Contextual Typography v2.2.4
		18: Minimal Theme Settings v6.1.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Have you tried changing Style Settings > Tables > Maximize table width

> Why would I need 2 additional plugins to fix what is the default in the Default theme?

Minimal is an opinionated theme. Tables are maximized by default because it's my preference. There are hundreds of other themes you can choose to use :)
