### ISSUE TITLE
Export PDF code blocks are not legible in dark mode

### ISSUE THREAD

**Issue by batrand** [kepano/obsidian-minimal#518]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.1.17

### Describe the bug

# Steps to reproduce
- Show Debug Info > Sandbox Vault
- Add a code block, like so:
![image](https://user-images.githubusercontent.com/8514709/209249755-8201db67-7ea5-4091-bb1e-81096175bdcd.png)
- Export to PDF. The code block is legible.
![image](https://user-images.githubusercontent.com/8514709/209249800-ca80a130-6ba5-4fbc-bd99-5328e3ccc75f.png)
- Switch to light mode
![image](https://user-images.githubusercontent.com/8514709/209249956-b28a6c50-a796-47d9-8b20-8e15ded910a5.png)
- Export PDF again. Code block is still legible
![image](https://user-images.githubusercontent.com/8514709/209249987-b95911d1-e4d5-4479-beb1-5555658a91da.png)
- Now install Minimal theme and use it, use light mode, export PDF, code block still legible
![image](https://user-images.githubusercontent.com/8514709/209250112-4ff90dd7-f5a7-4bc5-81a2-8515cc058c95.png)
- Switch to dark mode, export PDF again. Code block is not legible
![image](https://user-images.githubusercontent.com/8514709/209250190-851d73c8-4ab5-48f2-beec-58b68fa3431d.png)

# Expected
- Dark Mode Export PDF should have legible code block

# Actual
- Dark Mode Export PDF does not have legible code block

### Debug info

SYSTEM INFO:
	Obsidian version: v1.1.8
	Installer version: v1.1.8
	Operating system: Windows 10 Pro 10.0.22621
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v6.1.17
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 0
	Plugins enabled: 0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.

**Comment by MaxHasBeenUsed** [comment]
Same issue for in-line code, just to remind.
