### ISSUE TITLE
Add shortcuts to command palette for alternate Todo Marks

### ISSUE THREAD

**Issue by 1activegeek** [kepano/obsidian-minimal#521]
**Is your feature request related to a problem? Please describe.**
I'm unable to quickly/easily mark todo items with a specific type of Todo status that is supported by the Minimal Theme.

**Describe the solution you'd like**
See the post I created in the forum referenced below. I believe after re-reading documentation and seeing some of the command palette entries you already have, that these could be inserted here? Similar to the built-in function (or maybe its from my Tasks plugin) to cycle between bullet, todo, and complete todo status. 

https://forum.obsidian.md/t/shortcut-keys-for-todo-types-canceled-important-question-etc/41981/2

**Comment by kepano** [comment]
This is out of scope for the theme. It should probably be done as a plugin.
