### ISSUE TITLE
Image inside a callout got cut off at the right in edit mode

### ISSUE THREAD

**Issue by dustiiiaaa** [kepano/obsidian-minimal#522]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.1.17

### Describe the bug

Image embedded in a callout got cut off at the right when in edit mode but not in preview mode. The issue persists even with no plugins and snippets.

minimal theme edit mode (with the problematic callout at the top, original image at the bottom)
![minimal-callout](https://user-images.githubusercontent.com/121802614/210231265-8b8c2ddc-f5d7-4712-b57f-4476d59fc7c6.png)

minimal theme preview mode (expected behaviour)
![image](https://user-images.githubusercontent.com/121802614/210231862-5a349c25-6ccf-4e06-88ac-b1b011a0e312.png)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.1.8
	Installer version: v1.1.8
	Operating system: #1 SMP PREEMPT Wed Dec 21 21:15:06 UTC 2022 5.10.161-1-MANJARO
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v6.1.17
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 0
	Plugins enabled: 0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.

**Comment by kepano** [comment]
Fixed in 7.0
