### ISSUE TITLE
🔴 Question about "Minimal Movie Cards" 

### ISSUE THREAD

**Issue by Thomas-Harrell** [kepano/obsidian-minimal#524]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.1.18

### Describe the bug

> 💬 Hello, I'm not a developer, but I'll try to describe the problem as clearly as possible
> 
> 💬 I really like your theme, this is some of the problems I have encountered with the card view and I have solved them myself as much as possible

# 1️⃣ How to make the image fill the card

> 💡 Custom CSS snippets are turned off, only the plugin remains "Minimal Theme Settings, Dataview, Contextual Typography, Style Settings"

- Tried to adjust [cssclass](https://minimal.guide/Features/Helper+classes#Cards), But no effect
- I know that "Style Settings" can be adjusted, but then the text part will also be affected, the text part in the official document screenshot is not affected
- I see this problem in the screenshots of the official document
- But the official screenshots only have this problem with the labeled one, but not with the others
- I've tried using developer tools to find the CSS section, but no luck
- Using a 16:9 landscape image or another image does not work either

> the image i used: https://www.themoviedb.org/t/p/original/FzDXRZKz964xVbq7QmT4cnhegT.jpg
> 
> Pictures from the official docs: https://user-images.githubusercontent.com/10565871/148671516-348f2b48-440c-484b-8dc2-27006879a1a7.png

![001](https://user-images.githubusercontent.com/106761803/211061752-076e9859-a199-4edb-9dcd-1db3df731e07.png)

# 2️⃣ "Line height of numbers" & "gray horizontal lines"

- As shown in the screenshot, the height of the numbered rows is different from the other rows, and then there is no gray horizontal line between the numbered rows and the other rows
- I know that the gray horizontal line appears when the plugin "Style Settings" is turned on, but after I turn off the plugin "Style Settings", the height of the number row is still different from the other rows
- But after I add some other symbols to the number row, the height of the number row is the same as the other rows
- I didn't set another font in Obsidian
- I tried to change the settings in the plugin "Style Settings" and the plugin "Minimal Theme Settings", but it did not work

![000](https://user-images.githubusercontent.com/106761803/211061782-9f4362b3-0744-49b6-8caa-6cb35e8b1d20.png)

# 3️⃣ "Gray filled blocks" and "gray horizontal lines"

- The gray fill color block in the image is still there even if you use "cards-cover".
- The gray horizontal line also appears as soon as the "Contextual Typography" plugin is turned on
- The gray fill block can be hidden by modifying the background contrast, But this is not what is wanted
- It looks like the only way to modify it is to add additional CSS

![01](https://user-images.githubusercontent.com/106761803/211063879-f1d7fca4-977a-4db9-a723-b2dc5725a423.jpg)

### Debug info

# 💡Information on some versions (I don't know if it will help)
```
1️⃣ Software

Obsidian: 1.1.9 (ARM macOS)

2️⃣ Theme

Minimal: 6.1.18

3️⃣ Plugins

Minimal Theme Settings: 6.1.1

Dataview: 0.5.52

Contextual Typography: 2.2.4

Style Settings: 0.4.12
```

**Comment by kepano** [comment]
Please do not open questions on the repo, there is a Discord channel and forum topic
https://minimal.guide/Help

The CSS classes used in the movie gallery examples are

```
---
cssClasses: table-max, cards-cover, cards-2-3, cards
---
```

See https://minimal.guide/Guides/Create+a+movie+database
