### ISSUE TITLE
Bug using Contextual Typography plugin with Minimal theme

### ISSUE THREAD

**Issue by darkmarcos** [kepano/obsidian-minimal#525]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.1.18

### Describe the bug

Há um problema ao utilizar o pluggin Contextual Typography com o Minimal, que não acontece usando outros temas.

Em um contexto em que uso um "Callout", configurado com o snippet MCL, para flutuar à esquerda de um texto, funciona normalmente em outros temas. Mas quando ativo o Minimal (especialmente junto com o plugin Contextual Typography) o problema acontece.

There is an issue when using the Contextual Typography plugin with Minimal theme, which does not happen using other themes.

In a context where a "Callout" is used, configured with the "MCL snippet", to float to the left of a text, it works normally in other themes. But when I activate Minimal (especially together with the Contextual Typography plugin) the problem happens.

**With Minimal and Contextual Typography and MCL**
![image](https://user-images.githubusercontent.com/87239997/211069656-044f7f35-68cd-4402-afd7-06ab2cc4b0d5.png)

**With Minimal and MCL, without Contextual Typhography**
![image](https://user-images.githubusercontent.com/87239997/211069796-36865b31-40c4-47f1-9ae4-d624f7050459.png)

**With Contextual Typography and MCL, without Minimal (using default obsidian theme)**
![image](https://user-images.githubusercontent.com/87239997/211069890-5c23249d-a411-4c38-b5d3-b3fc24d88fc9.png)

### Debug info

**Contextual Typography**
https://github.com/mgmeyers/obsidian-contextual-typography

**MCL**
https://github.com/efemkay/obsidian-modular-css-layout

**Comment by kepano** [comment]
I am not offering compatibility with MCL. Please contact the developer of MCL.
