### ISSUE TITLE
Suggestion for new Checklist extra items

### ISSUE THREAD

**Issue by FabianoLothor** [kepano/obsidian-minimal#526]
I'd like to see additional icons for the checklists.

`- [@]` for `person` 👤
`- [P]` for `people`  👥 or `- [g]` for `group`  👥  or `- [m]` for `meeting`  👥
`- [r]` for `reference` 🔗
`- [m]` for `movie` 🎬
`- [v]` for `video` 🎥
`- [e]` for `entertainment`  🎭
`- [E]` for `education`  🎓 or `- [S]` for `study`  🎓
 `- [v]` for `video game` 👾 or  `- [v]` for `video game` 🎮
 `- [C]` for `chat` 💬 or  `- [C]` for `conversation` 💬
 `- [t]` for `thinking/thought` 💭
 `- [g]` for `gambling` 🎲

**Comment by FabianoLothor** [comment]
Those are just suggestions, don't need to add all of them, personally I would really like to see the @person option.

**Comment by kepano** [comment]
I don't plan to add more custom checkboxes but you can create your own by following the approach in the code.
