### ISSUE TITLE
The font size of the card title in the Kanban plugin is too large

### ISSUE THREAD

**Issue by TheCodeverse** [kepano/obsidian-minimal#528]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes(Using the Minimal theme); No(using the default Obsidian theme)

### Minimal theme version

6.1.18

### Describe the bug

The font size of the card title in the Kanban plugin is too large, please fix it, thanks!

### Debug info

none

**Comment by kepano** [comment]
Fixed in 6.2

**Comment by TheCodeverse** [comment]
> Fixed in 6.2

After I just updated the 6.2.0 version, I found that the problem of too large font size of the card title in the Kanban plugin has been fixed, thank you
