### ISSUE TITLE
Buttons aren't visible on iOS 

### ISSUE THREAD

**Issue by trainbuffer** [kepano/obsidian-minimal#530]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.1.19

### Describe the bug

Buttons and other tappable/changeable areas aren't visible using Minimal. Default theme looks fine.

Here is an example of _Settings>Appearance_:

<img src=https://user-images.githubusercontent.com/3751726/211693186-36fcac3e-940e-4057-ac2d-67d524b34f7f.jpeg width="400" height="800"> <img src=https://user-images.githubusercontent.com/3751726/211693192-0e1c8068-d8bf-4a19-8958-73df0aa2f2d5.jpeg width="400" height="800">

### Debug info

```
SYSTEM INFO:
      Operating system: ios 16.2 (Apple iPhone)
      Obsidian version: 1.4.2 (89)
      API version: v1.1.10
      Login status: logged in
      Catalyst license: insider
      Live preview: on
      Legacy editor: off
      Base theme: light
      Community theme: Minimal v6.1.19
      Snippets enabled: 0
      Restricted mode: on
```

**Comment by kepano** [comment]
Fixed in 6.3.0
