### ISSUE TITLE
Outline style for callouts cuts off the top with Admonition Plugin

### ISSUE THREAD

**Issue by Pray3r** [kepano/obsidian-minimal#531]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

6.1.19

### Describe the bug

The bug same as #509 , 
I tested on a new vault with only Minimal Theme and  Admonition Plugin installed.
Maybe it's a new feature request that to support [Admonition Plugin](https://github.com/valentine195/obsidian-admonition)? I'am not  sure.

<img width="1018" alt="Screen Shot" src="https://user-images.githubusercontent.com/16086935/211748025-26961aa6-8fb3-48f8-8632-ef74e7c1683e.png">

### Debug info

SYSTEM INFO:
	Obsidian version: v1.1.9
	Installer version: v1.1.9
	Operating system: MacOS Monterey 12.0.1
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: adapt to system
	Community theme: Minimal v6.1.19
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Admonition v9.0.5

**Comment by kepano** [comment]
I don't plan to add support for Admonitions plugin since those are natively supported in Obsidian now

**Comment by Pray3r** [comment]
Oh, thx.
For a few reasons([HTML in Code blocks nested in callouts don’t work in Live Preview](https://forum.obsidian.md/t/html-in-code-blocks-nested-in-callouts-dont-work-in-live-preview/35469)), I'm still using Admonitions plugin. 
If some people have the same problem, I have a simple way to solve it:
```css
.callouts-outlined .callout .callout-title {
    margin-top: 0px;
}
```

<img width="776" alt="Screen Shot" src="https://user-images.githubusercontent.com/16086935/211970387-802580e8-768e-48d1-a218-86640a50b320.png">
