### ISSUE TITLE
Color issue  with top of left sidebar in Low Contrast Mode

### ISSUE THREAD

**Issue by asterox** [kepano/obsidian-minimal#533]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

6.1.1

### Describe the bug

In low contrast mode, at the top of the left sidebar, there's an off-color block at the very top-left corner.

<img width="304" alt="Screenshot 2023-01-13 at 12 15 41 PM" src="https://user-images.githubusercontent.com/418566/212380562-a93013c2-40d6-450d-b6a0-4a67185ca0fd.png">

### Debug info

SYSTEM INFO:
	Obsidian version: v1.1.9
	Installer version: v1.0.0
	Operating system: Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 22.2.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v6.2.0
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 13
	Plugins enabled: 11
		1: Vantage - Advanced search builder v1.4.2
		2: Natural Language Dates v0.6.1
		3: Calendar v1.5.10
		4: Minimal Theme Settings v6.1.1
		5: Hider v1.2.4
		6: Style Settings v0.4.12
		7: Contextual Typography v2.2.4
		8: Kanban v1.5.1
		9: Commander v0.4.9
		10: Settings Search v1.2.0
		11: Recent Files v1.3.5

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Fixed in 6.2.1
