### ISSUE TITLE
img-grid  doesn't work any more

### ISSUE THREAD

**Issue by Issam-seghir** [kepano/obsidian-minimal#534]
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.2.0

### Info
Contextual typography 2.2.4
Minimal Theme Setting 6.2.0
Obsidian 1.1.8

###  Settings 
![image](https://user-images.githubusercontent.com/74573675/214272316-f528c0ba-1824-4293-975c-f964839cd6d0.png)

### Example

> The problem still happens even if i deactivate all other plugins / all snippets

![test](https://i.imgur.com/RrZ4QQB.gif)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.1.8
	Installer version: v1.1.8
	Operating system: Windows 10 Pro 10.0.19044
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v6.2.0
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 64
	Plugins enabled: 56
		1: Advanced Cursors v0.5.1
		2: Advanced Mobile Toolbar v1.8.0
		3: Advanced Tables v0.18.1
		4: Advanced URI v1.31.1
		5: AidenLx's Folder Note v0.16.4
		6: AidenLx's Folder Note - folderv component v1.0.0
		7: Banners v1.3.3
		8: Better footnote v1.0.1
		9: Book Search v0.5.8
		10: Calendar v1.5.10
		11: Charts View v1.1.9
		12: Code Editor Shortcuts v1.10.0
		13: Copy Block Link v1.0.4
		14: Customizable Page Header and Title Bar v4.6.2
		15: Dataview v0.5.47
		16: DB Folder v3.0.1
		17: Dynamic RTL v0.2.11
		18: Editor Syntax Highlight v0.1.3
		19: Excalidraw v1.8.7
		20: File Explorer Note Count v1.2.0
		21: File Tree Alternative Plugin v2.2.4
		22: Folder Note Core v1.3.5
		23: Footnote Shortcut v0.0.9
		24: Hider v1.2.3
		25: Highlightr v1.2.2
		26: Icon Folder v1.4.3
		27: Image Toolkit v1.3.1
		28: Imgur Plugin v2.2.1
		29: Kanban v1.5.1
		30: LanguageTool Integration v0.3.3
		31: Linter v1.9.0
		32: Multi-Column Markdown v0.7.6
		33: Natural Language Dates v0.6.1
		34: Note Refactor v1.7.1
		35: Obsidian Charts v3.7.1
		36: Obsidian Columns v1.4.0
		37: obsidian markmind v1.6.5
		38: Omnisearch v1.9.1
		39: Ozan's Image in Editor Plugin v2.1.6
		40: Paste URL into selection v1.7.0
		41: Periodic Notes v0.0.17
		42: Plugin Update Tracker v1.4.3
		43: QuickAdd v0.7.0
		44: Quick Switcher++ v2.3.4
		45: Recent Files v1.3.5
		46: Remember cursor position v1.0.7
		47: RTL Support v0.3.0
		48: Smarter Markdown Hotkeys v1.16.3
		49: Sortable v0.2.6
		50: Style Settings v0.4.12
		51: Tag Wrangler v0.5.5
		52: Tasks v1.19.0
		53: Templater v1.16.0
		54: Theme Picker v1.0.8
		55: Contextual Typography v2.2.4
		56: Minimal Theme Settings v6.2.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Are you in edit mode? Image grids don't work in edit mode unfortunately.

**Comment by Issam-seghir** [comment]
> Are you in edit mode? Image grids don't work in edit mode unfortunately.

Edit or Preview mode nothing changes

**Comment by Issam-seghir** [comment]
I will link my [comment ](https://github.com/whyt-byte/Blue-Topaz_Obsidian-css/issues/505#issuecomment-1404866341)(with the solution i find)  from the blue topaz theme repo because it's the same problem with img-grid minimal theme snippet
