### ISSUE TITLE
Blank settings page

### ISSUE THREAD

**Issue by aashish108** [kepano/obsidian-minimal#535]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.2.1

### Describe the bug

Settings page is blank on my Samsung Galaxy Tab S8+. It's not blank on my Samsung Galaxy S22 Ultra though, so the theme has issues on tablets it seems. 

### Debug info

Not sure how to get debug info on Android.
But current Obsidian version is 0.1.4

**Comment by kepano** [comment]
Can you update to the latest version of Obsidian, theme and plugin and also provide screenshots?
