### ISSUE TITLE
theme.css has a line that is 200 thousand characters long

### ISSUE THREAD

**Issue by digidoor** [kepano/obsidian-minimal#536]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.2.1

### Describe the bug

I think this is the whole of main.min.css being written to the themes\Minimal\theme.css in the vault's .obsidian directory. Regardless of how this happens, it causes problems for editing. Lite-XL takes over 30 seconds to open the file, and Lapce simply hangs even if you wait 20 minutes. I don't know to what degree having everything on one line helps with performance (I'm guessing very little if at all), but it's not at all worth it unless it's an improvement by at least an order of magnitude.

Another possibility is that this is completely by accident. The theme.css file has a mix of unix and dos-style line endings, so Vim shows many lines with a little ^M character at the end to show dos carriage returns that shouldn't be there since not all the lines have it. Mabey that one huge line is actually meant to be thousands of lines but got mangled in moving between systems. Anyway, I think code file contents that crash text editors qualifies as a bug.

### Debug info

This is completely irrelevant to the issue, but here you go:

SYSTEM INFO:
	Obsidian version: v1.1.9
	Installer version: v1.1.9
	Operating system: Windows 10 Pro 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v6.2.1
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 25
	Plugins enabled: 18
		1: Advanced Tables v0.18.1
		2: Commander v0.4.9
		3: Dataview v0.5.55
		4: Editor Syntax Highlight v0.1.3
		5: Janitor v1.0.7
		6: Metadata Menu v0.4.18
		7: Plugin Update Tracker v1.4.5
		8: Recent Files v1.3.5
		9: Settings Search v1.3.6
		10: Leader Hotkeys v0.2.1
		11: Contextual Typography v2.2.4
		12: Tag Wrangler v0.5.6
		13: Style Settings v0.4.12
		14: Chronology v1.1.3
		15: Cycle through Panes v0.1.0
		16: Vimrc Support v0.9.0
		17: Paste URL into selection v1.7.0
		18: Minimal Theme Settings v6.2.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
This is normal. The `theme.css` file is minified with Sass, so it's not meant to be editable.

If you want to edit the theme, I would recommend forking it and following the build instructions:
https://minimal.guide/Contributing/Local+development

There is also an unminified version in the root called Minimal.css that you can edit. However please be aware that editing theme files is not recommended because you will lose your changes if you ever update via the theme store. If you are making big changes, you should fork the theme.
