### ISSUE TITLE
Broken indentation for multiline blockquotes in lists

### ISSUE THREAD

**Issue by jjspace** [kepano/obsidian-minimal#537]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.2.1

### Describe the bug

Multiline blockquotes lose the indentation of the current level in a list for lines beyond the first.

Editor - source mode:
![2023-01-31_12-28](https://user-images.githubusercontent.com/8007967/215837932-59aff488-28e5-4037-b8f6-8dd319a760ed.png)

Editor - live preview mode:
![2023-01-31_12-28_1](https://user-images.githubusercontent.com/8007967/215837995-044d1425-bbfb-4468-a4b4-5b6f64c8aed7.png)

Reading mode:
![2023-01-31_12-28_2](https://user-images.githubusercontent.com/8007967/215838023-dab9533f-c2f9-46ed-af70-a7f0a7d78f9f.png)

### Debug info

Test markdown
```md
- level 1
  > blockquote
- still level 1
  > blockquote
  > with multiple lines
  
  with text after
- more level 1
  - level 2
    > blockquote
  - still level 2
    > blockquote
    > with multiple lines
    
    and text after it
  - more level 2
    with only text
```

**Comment by kepano** [comment]
This issue seems to be present in the default theme so it should be opened on the official forum
