### ISSUE TITLE
Heatmap Plugin is full width in Reading mode.

### ISSUE THREAD

**Issue by cjolson** [kepano/obsidian-minimal#538]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.2.1

### Describe the bug

[This Reddit post](https://www.reddit.com/r/ObsidianMD/comments/1028ir1/heatmap_calendar_fills_the_whole_width_in_reading/) has no comments, but it describes exactly the problem I'm having. 

In Live Preview, the Heatmap plugin is confined to the width of the page contents – but in Reading mode it spans the entire page and doesn't have any margins.

This is only a problem using the Minimal theme. Using the Default theme is fine.

### Debug info

SYSTEM INFO:
	Obsidian version: v1.1.9
	Installer version: v1.1.9
	Operating system: Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64 22.2.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal v6.2.1
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 32
	Plugins enabled: 31
		1: Hider v1.2.4
		2: Minimal Theme Settings v6.2.0
		3: Style Settings v0.4.12
		4: Advanced Tables v0.18.1
		5: Banners v1.3.3
		6: Better Word Count v0.9.4
		7: Calendar v1.5.10
		8: Dataview v0.5.55
		9: Homepage v2.7.3
		10: Hotkeys++ v0.2.7
		11: Kanban v1.5.1
		12: Linter v1.10.2
		13: Natural Language Dates v0.6.1
		14: Note Refactor v1.7.1
		15: Recent Files v1.3.5
		16: Tag Wrangler v0.5.6
		17: Workspaces Plus v0.3.3
		18: Templater v1.16.0
		19: Obsidian Charts v3.7.1
		20: Sortable v0.3.0
		21: Heatmap Calendar v0.5.4
		22: QuickAdd v0.8.0
		23: Bible Linker v1.4.4
		24: Paste URL into selection v1.7.0
		25: Reading Time v1.1.1
		26: Plugin Update Tracker v1.4.5
		27: PDF Highlights v0.0.4
		28: Buttons v0.4.19
		29: Tasks v1.24.0
		30: Contextual Typography v2.2.4
		31: Supercharged Links v0.9.3

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Fixed in 7.0
