### ISSUE TITLE
Allow option to disable the Theme's alternative checkboxes.

### ISSUE THREAD

**Issue by nimide** [kepano/obsidian-minimal#539]
**Is your feature request related to a problem? Please describe.**

I have incorporated the alternative checkboxes from Minimal, LYT Mode, AnuPpuccin, and ITS themes all via css snippets, and I have to comment out the minimal theme's checkboxes in order to get them to work like I would like.

**Describe the solution you'd like**

All I need is a setting to turn off the theme's alternative checkboxes so I can re-incorporate them via a snippet. This allows me to synthesize several sets of alternative checkboxes into one cohesive set.

**Comment by kepano** [comment]
this can be achieved by adding more specificity to your snippet
