### ISSUE TITLE
Hotkeys for Alternative Checkboxes

### ISSUE THREAD

**Issue by objectmethod** [kepano/obsidian-minimal#542]
**Is your feature request related to a problem? Please describe.**
It would be great if we could assign hotkeys to the alternative checkboxes.

**Describe the solution you'd like**
It would be great if we could assign hotkeys to the alternative checkboxes.

**Comment by kepano** [comment]
This out of scope for a theme. Would require a plugin. I recommend making this request on Discord of forums.
