### ISSUE TITLE
Canvas : Markdown highlighting doesn't work on unfocussed blocks

### ISSUE THREAD

**Issue by laffan** [kepano/obsidian-minimal#545]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.2.3

### Describe the bug

Markdown highlighting (ie. text wrapped in "==") only works when the block is highlighted.
![Screenshot 2023-02-17 at 1 12 32 AM](https://user-images.githubusercontent.com/5421145/219602984-fcddc829-124b-4914-90d8-2a440ff480be.png)

(Screenshot taken in restricted mode.)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.1.9
	Installer version: v1.1.9
	Operating system: Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:46 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6020 22.3.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal v6.2.3
	Snippets enabled: 0
	Restricted mode: on

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.

**Comment by kepano** [comment]
It looks like from the screenshot your text is not wrapped — you need `==` signs on both sides of the text. The issue of only showing a highlight when the text is wrapped only on one side is present in the default theme too.
