### ISSUE TITLE
Disclosure arrow icons overlay the note's line numbers

### ISSUE THREAD

**Issue by AutomatingData** [kepano/obsidian-minimal#546]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

6.2.3

### Describe the bug

Minimal theme overlays disclosure [arrow](url) icon over line numbers making it difficult to see both. Attached screenshot shows line 2 is disclosed (arrow pointing down) and line 4 is closed (arrow pointing right).
![ObsidianMinimalThemeLineNumbers](https://user-images.githubusercontent.com/125692031/219757732-acdc5837-6956-4cb4-905c-3a6637e0cba0.jpg)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.1.9
	Installer version: v1.0.3
	Operating system: Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000 22.3.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v6.2.3
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 14
	Plugins enabled: 12
		1: Auto Link Title v1.4.1
		2: Calendar v1.5.10
		3: Custom window title v0.3.5
		4: Advanced Tables v0.18.1
		5: Dataview v0.5.55
		6: Templater v1.16.0
		7: Note Refactor v1.7.1
		8: Focus Mode v1.11.4
		9: Better Word Count v0.9.4
		10: Emoji Toolbar v0.4.0
		11: Minimal Theme Settings v6.2.0
		12: Hider v1.2.4

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Should be fixed in 7.0
