### ISSUE TITLE
Checked List Items

### ISSUE THREAD

**Issue by 702573n** [kepano/obsidian-minimal#55]
I would like to switch the style of checked list items (text after a checkbox). On default the text of checked items doesn't changed. I would like to grey out the text and line-through.

Another style option is to disable small-caps on smaller headings.

**Comment by kepano** [comment]
This is not currently on my roadmap, but the quick (and fairly simple) solution is to use a CSS snippet. [See forum post for instructions.](https://forum.obsidian.md/t/getting-comfortable-with-obsidian-css/133).

**Comment by wenlzhang** [comment]
To grey out checked tasks in preview mode, the following snippet can be used:
https://forum.obsidian.md/t/dont-strike-through-nested-checkboxes-when-outer-checkbox-is-checked/8389/3
To strike through checked tasks, one can change `text-decoration: none;` to `text-decoration: line-through;`. I am not sure how to achieve both at the same time, though.

To disable small-caps on headers, the following can be used:
https://gist.github.com/wenlzhang/e80b53869c01a96659cee67b736e423d

**Comment by kepano** [comment]
Both options are now available in Style Settings as of 4.2.9
