### ISSUE TITLE
Option to prevent images from being greyed out when not moused over?

### ISSUE THREAD

**Issue by adamreiswig** [kepano/obsidian-minimal#550]
**Is your feature request related to a problem? Please describe.**
Images in my documents are slightly greyed out unless I mouse over them. I can't find an option to turn this functionality off. I would prefer my images to be at full brightness all the time. I think it is a function of the Minimal theme as I don't see this behavior with other themes.

**Describe the solution you'd like**
Could we get an option to disable this behavior?

Cheers!

-Adam

**Comment by kepano** [comment]
You can change this behavior using Style Settings plugin

https://minimal.guide/Plugins/Style+Settings
