### ISSUE TITLE
Add filetype icons to the theme

### ISSUE THREAD

**Issue by Nevarro** [kepano/obsidian-minimal#553]
**Is your feature request related to a problem? Please describe.**
If you add a variety of file attachments in Obsidian, they become quite hard to distinguish. Would it be possible to add small icons for the most common file types?

**Describe the solution you'd like**
File is attached to a note, instead of the original file-icon, a file icon based on the filetype is displayed (for .docx/.xlsx/.pptx/.pdf/.mp3/.mp4/...

**Comment by kepano** [comment]
This should be done via snippets or plugin
