### ISSUE TITLE
Heading sizes are all too small, please add settings to change heading sizes

### ISSUE THREAD

**Issue by AVGVSTVS96** [kepano/obsidian-minimal#554]
When using the Minimal theme, my headings are all very small, and there is little if any differentiation between header sizing.
I have spent a while searching for a way to revert heading sizes to default but have not found it in Minimal theme settings or Style settings. 

My notes rely on nested headings of different sizes and look super cluttered when all the text is almost the same size as the headings.
I looked through the CSS file but couldn't find the text size adjustment, I don't know CSS well.

Any help would be appreciated.

**Comment by kepano** [comment]
Heading sizes can be changed using Style Settings
https://minimal.guide/Plugins/Style+Settings

You can find the default values in app.css
