### ISSUE TITLE
Horizontal lines under headings

### ISSUE THREAD

**Issue by silidev** [kepano/obsidian-minimal#555]
I think many people would love if you could include heading lines like these in your wonderful theme!

![image](https://user-images.githubusercontent.com/16080894/229896510-b4d55f21-4185-40c7-9ee9-1ba2efb56de2.png)

CSS for these:
```
.cm-header-1:before { /* horizontal line */
    position: absolute;
    top: 100%;
    overflow: hidden;
    width: 100%;
    height: 2px;
    content: '\a0';
    background-color: #888888;
}
```

**Comment by kepano** [comment]
This is already supported via Style Settings
https://minimal.guide/Plugins/Style+Settings

**Comment by silidev** [comment]
S
Oh sorry, thank you very much!

--
Viele Grüße - Helge

Stephan Ango ***@***.***> schrieb am Di., 4. Apr. 2023, 23:45:
