### ISSUE TITLE
Media always maximized if image grid is enabled (Reading view)

### ISSUE THREAD

**Issue by ltroj** [kepano/obsidian-minimal#556]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

6.3.2

### Describe the bug

Steps to reproduce:
- Sandbox vault
- Install Minimal theme (6.3.2)
- Install Contextual Typography plugin
- Install Minimal Theme Settings plugin
- In Minimal Theme Settings enable *Image grids*
- Make sure *Maximize media* is switched off
- Embed an image in a note ``![[image.png]]``
- Switch to Reading view

The image always fills the full line width. This causes small images to be displayed oversized.
The effect gets even more visible if *Readable line length* is disabled in the Obsidian Editor settings.

![Reading view](https://user-images.githubusercontent.com/25671166/230062679-1bb97c8d-e4fa-40f6-ba2e-fc9a44cda379.png)

![Editing view](https://user-images.githubusercontent.com/25671166/230062696-c8c52e37-0279-4a98-afc0-6640f63fcfb6.png)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.1.16
	Installer version: v1.1.16
	Operating system: Windows 10 Pro 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v6.3.2
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 2
		1: Contextual Typography v2.2.4
		2: Minimal Theme Settings v6.3.1

**Comment by kepano** [comment]
Fixed in 7.0
