### ISSUE TITLE
An event alternate checkbox type

### ISSUE THREAD

**Issue by basilioss** [kepano/obsidian-minimal#558]
**Is your feature request related to a problem? Please describe.**
Methods such as [Bullet Journal](https://bulletjournal.com) often use a special symbol/bullet for events, but currently there is no appropriate checkbox for this.

**Describe the solution you'd like**
`- [e]` checkbox or something similar that renders with some event related icon.

**Comment by kepano** [comment]
Consider using the calendar icon `-[<]` (scheduling) or creating your own snippet, see https://github.com/kepano/obsidian-minimal/blob/master/src/scss/features/checklist-icons.scss
