### ISSUE TITLE
[Suggestion] Numerials in Ordered List

### ISSUE THREAD

**Issue by sissilab** [kepano/obsidian-minimal#559]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Thanks for your great work!!! Really a nice theme.
Have an idea about numerals at the beginning of each ordered list item. 
Can we Implement operations as follows: 
1. firstly input `1. Weather` (1st level)
2. press Enter: display `2. ` at the following line
3. press Tab to indent: display `a. ` (2nd level) in replace of `2. ` -> e.g. I input `a. Rain`
4. pree Enter: display `b. `  at the following line
5. press Tab to indent: display `i. ` (3rd level) in replace of `b. ` -> e.g. I input `i. Storm`
6. ...
```
1. Weather
  a. Rain
    i. Storm
   ii. Mild Rain
2. Mood
```

The operation way is similar to edit in Confluence Wiki.

**Comment by kepano** [comment]
You can accomplish this with a snippet using the `--list-numbered-style` variable

**Comment by sissilab** [comment]
> You can accomplish this with a snippet using the `--list-numbered-style` variable
Thanks for your suggestion. But it only works on **Reading View** mode as follows:
```css
ol {
  list-style-type: decimal
}

ol ol {
  list-style-type: lower-alpha;
}

ol ol ol {
  list-style-type: lower-roman;
}
```
If expecting it works on **Live Preview** mode, maybe we need to listen the edit event (e.g. `cm-formatting cm-formatting-list cm-formatting-list-ol cm-list-1`) and modify the list style dynamically.
