### ISSUE TITLE
No cursor on mobile device

### ISSUE THREAD

**Issue by echo-saurav** [kepano/obsidian-minimal#56]
I cant see any cursor on mobile device
![Screenshot_20211109-132400_Obsidian](https://user-images.githubusercontent.com/76121100/140886564-7189d00a-f8f1-4f05-bd18-aa6e52a46d09.png)

**Comment by kepano** [comment]
It looks like you have several plugins and/or snippets active that could be conflicting with Minimal. Please disable all plugins/snippets and restart Obsidian. Then activate them one by one and you will find which one is the culprit.
