### ISSUE TITLE
Muting of colours in status bar makes Obsidian Sync errors easy to miss

### ISSUE THREAD

**Issue by claremacrae** [kepano/obsidian-minimal#564]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.3.3

### Describe the bug

I've been using the Minimal theme for a couple of days - thank you - and just noticed that when the Minimal theme enabled, it is not possible to see the colour of the Obsidian Sync icon.

<img width="235" alt="image" src="https://github.com/kepano/obsidian-minimal/assets/4840096/55be207a-74bb-403a-94b4-bc322da43fcc">

The above screenshot is with all snippets disabled and all plugins disabled.

Because Obsidian Sync doesn't persist information about sync errors for long, if you don't notice the Red Sync Icon straight after a conflict, you may never know you had a conflict and may have lost or corrupted data.

So I feel it's essential that the colour of the Sync icon is visible at all times, to increase the chance of conflicts being spotted.

This is what the sync icon looks like with the Default theme:

<img width="243" alt="image" src="https://github.com/kepano/obsidian-minimal/assets/4840096/b2377278-9523-4f36-8f5f-2fc84b758542">

### Debug info

```
SYSTEM INFO:
	Obsidian version: v1.3.0
	Installer version: v1.1.9
	Operating system: Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 19.6.0
	Login status: logged in
	Catalyst license: vip
	Insider build toggle: on
	Live preview: off
	Legacy editor: off
	Base theme: light
	Community theme: Minimal v6.3.3
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 84
	Plugins enabled: 0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
```

**Comment by kepano** [comment]
Minimal is minimal :)

FYI only the success and working state is set to gray, the error state uses the error color.

**Comment by claremacrae** [comment]
I learned today that if my vault gets re-indexed it means my Sync connection got wiped out too, and so a Sync icon stuck on the Pause symbol is an indication of an error state.

https://discord.com/channels/686053708261228577/900870622631063552/1149452637402583050

I would have noticed this if the Sync icon was colour.

I feel that the decision to close this should be reconsidered, @kepano.
