### ISSUE TITLE
Progress Bar Colors

### ISSUE THREAD

**Issue by cjolson** [kepano/obsidian-minimal#565]
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.3.3

### Describe the bug

The documentation displays blue for the color of a [completed progress bar](https://minimal.guide/Block+types/Progress+bars). However, [mine is orange (as in the 40-50% range)](https://github.com/kepano/obsidian-minimal/assets/18406537/97a93b4b-525e-463e-8e3f-06362c1349e2).

Additionally, the color of the bar seems to be dependent on the raw value of `x` as opposed to the percentage. If I set my progress as 35 / 70 – `<progress value="35" max="70"></progress>`, [it uses the red coloring](https://github.com/kepano/obsidian-minimal/assets/18406537/e9581319-c90b-425c-9705-8309c5a5dac0). I would expect orange since it is 50%, but it seems to be using red because the `x` value is in the 30s.

### Debug info

SYSTEM INFO:
	Obsidian version: v1.3.0
	Installer version: v1.1.16
	Operating system: Darwin Kernel Version 22.4.0: Mon Mar  6 21:01:02 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8112 22.4.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: adapt to system
	Community theme: Minimal v6.3.3
	Snippets enabled: 3
	Restricted mode: off
	Plugins installed: 19
	Plugins enabled: 19
		1: Readwise Official v2.0.1
		2: Tag Wrangler v0.5.8
		3: Plugin Update Tracker v1.4.6
		4: Homepage v3.0.2
		5: Dataview v0.5.55
		6: Advanced Tables v0.18.1
		7: Better Word Count v0.9.6
		8: Natural Language Dates v0.6.1
		9: Obsidian Git v2.19.1
		10: Recent Files v1.3.5
		11: Sortable v0.3.1
		12: Calendar v1.5.10
		13: Templater v1.16.0
		14: Bible Linker v1.4.4
		15: Banners v1.3.3
		16: CustomJS v1.0.13
		17: Vault Changelog v0.1.0
		18: Minimal Theme Settings v6.3.1
		19: Style Settings v1.0.3

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by cjolson** [comment]
Actually, just tried changing my accent color (which was orange), and that resolves the first part of the issue. However, I do think it might make sense to not use the accent color for the completed bar since it is confusing. 

The second portion of this issue is possibly working as intended, but it was confusing on my end. My work around is to normalize all my progress bars to percent values, but if it's possible to fix it would be very user friendly if I didn't have to. Thanks.

**Comment by kepano** [comment]
Fixed in 7.0
