### ISSUE TITLE
'Edit this block' overlaps with 'Toggle sidebar' in embedded PDF viewer

### ISSUE THREAD

**Issue by Comprehensive-Jason** [kepano/obsidian-minimal#567]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.3.3

### Describe the bug

In the embedded PDF viewer, the 'Edit this block' button covers the 'Toggle sidebar' button. 
![image](https://github.com/kepano/obsidian-minimal/assets/68677082/930f77b2-0436-45d0-b5e3-859a70159316)

In the Default Theme, the buttons do not overlap.
![image](https://github.com/kepano/obsidian-minimal/assets/68677082/e00742c1-1c88-40ac-92c0-04369537b9e2)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.3.1
	Installer version: v1.1.9
	Operating system: Windows 10 Home 10.0.22624
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v6.3.3
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 3
	Plugins enabled: 0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.

**Comment by kepano** [comment]
Fixed in 7.0
