### ISSUE TITLE
Browsing themes impossible

### ISSUE THREAD

**Issue by thistlillo** [kepano/obsidian-minimal#57]
When using this theme on Windows 10 (latest obsidian version), it is not possible to scroll the list of the themes: only the first four are shown.

1. Go to Settings
2. then "Appearance"
3. In "Community themes" click on "Browse"
4. only four themes are shown. Scrolling via touchpad does not work. No scrollbars are shown.

**Comment by kepano** [comment]
Which version of Minimal Theme do you have? You can see this by opening your Minimal.css file.

Alternatively, try updating to the latest version of Minimal, I believe this bug is fixed now.
