### ISSUE TITLE
PDF Viewer doesn't display 2nd page

### ISSUE THREAD

**Issue by Smitty010** [kepano/obsidian-minimal#570]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.3.3

### Describe the bug

This started when the pdf viewer was updated a week or so ago.  All of my multipage pdfs show the 2nd page of the pdf as blank.  I'm not entirely convinced it's the theme (though everything displays correctly in the default theme).  I thought it might be interaction with SNW plugin, but disabling that doesn't seem to fix things.  Admittedly, I have a lot of plugins.  But I don't think anything else messes with the page like SNW does.  

If you have something else you think I should try turning off, I'm happy to oblige.  Obsidian 1.3.4 says it has changes to prevent plugins from messing with the pdf viewer.  However, in my case, there's still a problem.  

I got into the developer console and found the pdf viewer div.  I can see where it breaks out all of the pages, but HTML/CSS was never my thing, so I don't have enough experience to know what looks off.  I'm happy to look at something if you can point me in the right direction.

And yes, I think it's very odd that it's only page 2 (I have both an 11 and a 22 page pdf I've looked at).  All of the other pages seem to be fine.

I'm just not sure where else to look or who to ask.  

### Debug info

SYSTEM INFO:
	Obsidian version: v1.3.4
	Installer version: v1.2.7
	Operating system: Windows 10 Pro 10.0.22621
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal v6.3.3
	Snippets enabled: 6
	Restricted mode: off
	Plugins installed: 96
	Plugins enabled: 71
		1: Tasks v3.7.0
		2: Templater v1.16.0
		3: Dataview v0.5.56
		4: Calendar v1.5.10
		5: Advanced Tables v0.18.1
		6: Kanban v1.5.3
		7: Excalidraw v1.9.2
		8: Admonition v9.3.1
		9: Outliner v4.7.1
		10: Mind Map v1.1.0
		11: Natural Language Dates v0.6.1
		12: QuickAdd v1.0.2
		13: Periodic Notes v0.0.17
		14: Advanced Mobile Toolbar v1.8.0
		15: Annotator v0.2.10
		16: Banners v1.3.3
		17: ExcaliBrain v0.1.13
		18: Homepage v3.0.2
		19: Minimal Theme Settings v6.3.1
		20: Note Refactor v1.7.1
		21: Quick Switcher++ v3.3.0
		22: Recent Files v1.3.5
		23: Spaced Repetition v1.10.1
		24: Auto Link Title v1.4.1
		25: Style Settings v1.0.5
		26: Find orphaned files and broken links v1.9.0
		27: Tracker v1.10.9
		28: Emoji Toolbar v0.4.1
		29: Status Bar Pomodoro Timer v0.1.14
		30: Buttons v0.4.19
		31: Folder Note v0.7.3
		32: Workspaces Plus v0.3.3
		33: Tag Wrangler v0.5.8
		34: DB Folder v3.4.0
		35: Hotkeys++ v0.2.7
		36: PlantUML v1.6.6
		37: Local images v0.14.2
		38: Fullscreen mode plugin v0.1.2
		39: Projects v1.15.3
		40: Longform v2.0.3
		41: Dialogue v1.0.2
		42: Plugin Update Tracker v1.5.0
		43: Multi-Column Markdown v0.8.0
		44: Wikipedia v1.0.3
		45: Metadata Menu v0.4.21
		46: Highlightr v1.2.2
		47: Text Format v2.2.1
		48: Commander v0.5.0
		49: Reading Time v1.1.1
		50: Icon Folder v2.0.1
		51: Pane Relief v0.5.0
		52: Text Extractor v0.4.5
		53: Task Marker v0.4.2
		54: Toggle Meta Yaml v1.2.0
		55: Hotkeys for templates v1.4.3
		56: Open vault in VSCode v1.2.1
		57: Grandfather v1.0.1
		58: No dupe leaves v0.0.8
		59: Icon Shortcodes v0.9.7
		60: Editor Syntax Highlight v0.1.3
		61: Omnisearch v1.14.0
		62: Contextual Typography v2.2.5
		63: Text Generator v0.3.18
		64: Callout Manager v1.0.1
		65: Quiet Outline v0.3.15
		66: Supercharged Links v0.9.7
		67: LanguageTool Integration v0.3.3
		68: File Explorer Note Count v1.2.1
		69: Linter v1.15.0
		70: MetaEdit v1.8.0
		71: Obsidian42 - Strange New Worlds (SNW) v1.2.2

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Are you using any of the PDF options in Style Settings?

**Comment by Smitty010** [comment]
Here's data.json for style:
{
  "typomagical-text@@callout-style": "callout-default",
  "minimal-style@@h3-weight": 900,
  "supercharged-links@@d229-5e3a-before": "🤵",
  "supercharged-links@@e632-93a6-before": "🎞️",
  "minimal-style@@embed-strict": true,
  "minimal-style@@embed-hide-title": false,
  "minimal-style@@h1-l": true,
  "minimal-style@@h2-l": true
}

So, it think "no".  Also I tried turning off all of my snippets (because I hadn't done that).  No change.

**Comment by Smitty010** [comment]
This problem seems to have gone away.  I'm not sure whether it was a fix to the minimal theme or some other plugin that corrected the problem.  But, PDFs now seem to be displaying correctly
