### ISSUE TITLE
Youtube embed miss aligned in live preview mode

### ISSUE THREAD

**Issue by kbhbhk** [kepano/obsidian-minimal#572]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.3.3

## `![](https://youtu.be/...)`

→ This like embed video not aligned with note line in live preview. Aligned well in reading view.

## Screenshot in Live Preview:
![스크린샷 2023-05-31 오후 3 02 00](https://github.com/kepano/obsidian-minimal/assets/130442702/e9b34205-0add-46e0-a464-da4ef356ac87)

## Screenshot in Reading View:
![스크린샷 2023-05-31 오후 3 02 09](https://github.com/kepano/obsidian-minimal/assets/130442702/f714d7ca-6f16-4a28-bc82-8db1607529fb)

## `+`other user same bug report:
https://forum.obsidian.md/t/embedded-youtube-links-not-aligned/60376

### Debug info

SYSTEM INFO:
	Obsidian version: v1.3.4
	Installer version: v1.2.7
	Operating system: Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000 22.3.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v6.3.3
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 5
	Plugins enabled: 0

**Comment by JohnIrle** [comment]
I am also seeing this and have noticed that putting one space in front of the embed will align it correctly.

**Comment by kbhbhk** [comment]
Oh I checked about it and it really does. And I also tried multiple space in front of `!` and then embed thumbnail moves together. hmm

**Comment by kbhbhk** [comment]
Oh I checked about it and it really does. And I also tried multiple space in front of ! and then embed thumbnail moves together. hmm

**Comment by ironhak** [comment]
Will this be fixed?

**Comment by kepano** [comment]
Fixed in 6.3.4
