### ISSUE TITLE
Map View navigation buttons

### ISSUE THREAD

**Issue by esm7** [kepano/obsidian-minimal#574]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

6.3.3

### Describe the bug

There is a small but problematic conflict between the Minimal Theme and the Map View plugin (https://github.com/esm7/obsidian-map-view), on which the controls div of the plugin overlaps the floating navigation controls in Minimal (see screenshot).
I am unsure how to fix this in Map View in a way that will work correctly both in the default theme and in Minimal, and the most straight-forward way would be to just add a simple rule in Minimal that would take this box further down:

```
.map-view-graph-controls {
    top: 36px;
}
```
(maybe it needs to be marked `!important` for Minimal to properly override the default)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.3.5
	Installer version: v1.1.9
	Operating system: #1 SMP PREEMPT Wed May 17 11:03:28 UTC 2023 5.4.243-1-MANJARO
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: adapt to system
	Community theme: Minimal v6.3.3
	Snippets enabled: 5
	Restricted mode: off
	Plugins installed: 23
	Plugins enabled: 20
		1: Better File Link v1.1.3
		2: Advanced URI v1.24.0
		3: Copy Block Link v1.0.4
		4: Natural Language Dates v0.6.1
		5: QuickAdd v0.5.5
		6: Pane Relief v0.4.2
		7: Another Quick Switcher v8.9.2
		8: Calendar v1.5.10
		9: Obsidian General Stuff v1.0.1
		10: Hotkeys for specific files v1.2.1
		11: RTL Support v1.1.1
		12: Excalidraw v1.7.18
		13: Periodic Notes v0.0.17
		14: Completr v3.1.3
		15: Tasks v3.9.0
		16: Tracker v1.10.9
		17: Translate v1.4.4
		18: Vimrc Support v0.7.2
		19: Obsidian Dev Tools Plugin v1.0.0
		20: Map View v3.1.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Was not able to reproduce, I have now removed any Map View specific rules from Minimal.
