### ISSUE TITLE
PDF reader inverts colors when "Basic color scheme" is dark

### ISSUE THREAD

**Issue by BorgeJorge** [kepano/obsidian-minimal#576]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.3.3

### Describe the bug

Not sure this is a bug, but it's the only theme I've used that inverts the colors when I go into the PDF reader. It'd be great to at least have the option of retaining the normal PDF color scheme.

### Debug info

See above

**Comment by kepano** [comment]
See Style Settings options for this

**Comment by BorgeJorge** [comment]
Ah, thank you!
