### ISSUE TITLE
Tree spacing varies slightly

### ISSUE THREAD

**Issue by chuckharmston** [kepano/obsidian-minimal#577]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.3.3

### Describe the bug

There are some minor variations in the spacing between tree items using stock Minimal on an empty-ish vault. In the screenshots below, the only installed plugin is Hider with "Hide vault Name" enabled for an easier comparison. 

Pretty trivial problem, but can be a little bit jarring when flipping between tabs in fuller vaults.

![CleanShot 2023-06-12 at 19 03 00@2x](https://github.com/kepano/obsidian-minimal/assets/23885/19c4371d-cd51-4607-9fad-37b11dc267c2)

![CleanShot 2023-06-12 at 19 03 02@2x](https://github.com/kepano/obsidian-minimal/assets/23885/6d0cacc6-29e2-49df-92f2-07c4df4d79c9)

![CleanShot 2023-06-12 at 19 03 06@2x](https://github.com/kepano/obsidian-minimal/assets/23885/e03e1573-477b-47b1-97e4-b61437e6b1d7)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.3.5
	Installer version: v1.3.5
	Operating system: Darwin Kernel Version 23.0.0: Mon May 22 22:51:48 PDT 2023; root:xnu-10002.0.40.505.5~4/RELEASE_X86_64 23.0.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: adapt to system
	Community theme: Minimal v6.3.3
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Hider v1.2.4

**Comment by kepano** [comment]
These issues appear to be present in the default theme as well. I'll fix it in the default theme, don't tell anyone 😂
