### ISSUE TITLE
Fancy Cursors with Vim mode causes cursor to behave incorrectly

### ISSUE THREAD

**Issue by ezbrzcvr** [kepano/obsidian-minimal#58]
In Vim mode, when transitioning from Normal mode to Insert mode, the cursors position is placed to the **right** of the current character that the block cursor is on. Correct behaviour is that the cursor be placed on the **left**. 
This is a cursor visual bug only, any typed characters are placed in the correct position, upon which the cursor then updates.

**Current Behaviour**

https://user-images.githubusercontent.com/87576423/141073830-35f2cd50-77df-4118-b499-fe406feb970d.mov

**Correct Behaviour (w/ Fancy Cursors Disabled)**

https://user-images.githubusercontent.com/87576423/141073943-50878770-5907-443b-aa52-ce11ae4bdb7e.mov

**Comment by liang-0131** [comment]
I have the same problem

**Comment by 23727** [comment]
Also experiencing this bug

**Comment by kepano** [comment]
This will be fixed in Minimal 4.2

**Comment by 23727** [comment]
> This will be fixed in Minimal 4.2

This is good news! Thank you 👍
