### ISSUE TITLE
🔴 Dataview Table Display Error in Version 7.0.0

### ISSUE THREAD

**Issue by Thomas-Harrell** [kepano/obsidian-minimal#582]
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.0.0

## 00
- Obsidian: 1.3.5
- Minimal Theme: 7.0.0
- Dataview: 0.5.56
- Style Settings: 1.0.6
## 01
- In version 7.0.0, using `cssclass: max` will cause "Dataview-Table" to display an error
- Makes the table width displayed in “Dateview-Table” wrong
- But using `cssclass: wide` is normal
- This is also normal in older versions
## 02
- In version 7.0.0, "Dateview-Table" always shows "Row lines"
- Option "Style Settings > Minimal > Tables > Row lines" disappeared in version 7.0.0
- Only “Style Settings > Minimal > Tables > Column lines” options remain
- Cannot use "Style Settings > Minimal > Tables > Row lines & Column lines" to adjust whether the table borders are displayed or not as in the old version.

### Debug info

None

**Comment by kepano** [comment]
Fixed in 7.0.1
