### ISSUE TITLE
Heading Spacing Inconsistency

### ISSUE THREAD

**Issue by Comprehensive-Jason** [kepano/obsidian-minimal#585]
**Is your feature request related to a problem? Please describe.**
I noticed Minimal 7.0 changed the value of `--p-spacing` from 0.75em to 1.5em, presumably to keep paragraphs in the same place when switching between Live Preview and Reading Mode.
 
Currently, heading spacing in Minimal 7.0 differs dramatically between Live Preview and Reading Mode, as shown below:
<img src="https://github.com/kepano/obsidian-minimal/assets/68677082/de3bd999-5aac-4642-852f-315820ab8897" alt="drawing" width="400"/>

It would be good to add CSS to make them similarly consistent. 
I use the following CSS snippet to make them so:
```
/*Make Paragraph Spacing Consistent*/
body{
    --p-spacing: 1.5rem;
}
/*Make Top Heading Spacing more compact and consistent between Reading and Live Preview*/
body{
    --heading-spacing: 1.5rem;
}
.cm-s-obsidian .cm-line.HyperMD-header {
    padding-top: 1.5rem;
}
/*Remove Top Padding for first heading*/
.cm-s-obsidian .cm-line.HyperMD-header:first-of-type {
    padding-top: 0rem;
}
/*Remove Top Padding for immediately consecutive headings*/
.cm-s-obsidian .cm-line.HyperMD-header + .cm-line.HyperMD-header {
    padding-top: 0rem;
}
/*Make Bottom Heading Spacing more compact and consistent between Reading and Live Preview*/
.cm-s-obsidian .cm-line.HyperMD-header {
    padding-bottom: 1.5rem;
}
```
Here's what it looks like in action.
<img src="https://github.com/kepano/obsidian-minimal/assets/68677082/970eee32-f51c-4363-a6ca-726c86ab89ba" alt="drawing" width="400"/>

**Describe the solution you'd like**
Implementing some CSS like mine would make the Minimal theme much more usable when switching modes, and would complete the previous work on `--p-spacing`.

**Comment by kepano** [comment]
This is intentional as Markdown syntax recommends adding empty line breaks between headings. Note that the spacing setting can be changed under Style Settings > Text

**Comment by laawn** [comment]
@kepano 

Related to this thread: since 7.0.0, my header spacing has changed. In editing mode, which I use solely; I no longer have spacing before or after headers. You mention spacing settings in Style Settings, but this only applies to Reading mode. Are the changes to header spacing in Editing mode intentional? If so, I'm curious why this change was made.

Thanks!
