### ISSUE TITLE
Strange border line with minimal theme setting plugin open

### ISSUE THREAD

**Issue by guba-exe** [kepano/obsidian-minimal#587]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

7.0.3

### Describe the bug

When I use minimal theme with minimal theme setting plugin open, strange border line appeared like shown below.
<img width="1197" alt="image" src="https://github.com/kepano/obsidian-minimal/assets/82076559/79044b36-cf06-4bb6-965e-880f48517160">

### Debug info

SYSTEM INFO:
	Obsidian version: v1.3.5
	Installer version: v1.3.3
	Operating system: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103 22.4.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal v7.0.3
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 39
	Plugins enabled: 1
		1: Minimal Theme Settings v6.3.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
https://minimal.guide/Features/Line+width
