### ISSUE TITLE
Ugly colored stripes

### ISSUE THREAD

**Issue by prdlik007** [kepano/obsidian-minimal#588]
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.0.3

### Describe the bug

is there anywhere to turn off those ugly colored stripes? This really isn't a minimal look.

### Debug info

![image](https://github.com/kepano/obsidian-minimal/assets/99074493/00bcde11-828c-4009-95b0-50ab994c8e7a)

**Comment by avirosso** [comment]
Workaround: Plugin "Minimal Theme Settings": Deactivate "Maximise media" ...

**Comment by kepano** [comment]
What are these images?

As mentioned above you can disable maximize media in Minimal Theme Settings

**Comment by prdlik007** [comment]
This is not the issue. I write - 1 emoji, 1 space, paste url a this strange image appears automatically, not by me.

![image](https://github.com/kepano/obsidian-minimal/assets/99074493/582ce438-b33d-4568-b320-0487b70d2479)

**Comment by prdlik007** [comment]
It´s a favicon image 
![image](https://github.com/kepano/obsidian-minimal/assets/99074493/52d8e182-62c6-4ad2-a844-726cdfd676b1)

It started doing this after the last update. So I consider it a bug. Favicon shouldn't stretch.

**Comment by kepano** [comment]
- How are you bringing these icons into your note? Are you using a plugin?

- Does turning off "maximize media" in Minimal Theme Settings solve the issue?

- Can you share your debug info? Access it via command palette: "Show debug info"

**Comment by prdlik007** [comment]
I use this plugin: https://github.com/joethei/obsidian-link-favicon for at least 2 years with no problem.

Turning off "maximize media" solve this issue. But I like maximazed media on. :)

SYSTEM INFO:
	Obsidian version: v1.3.7
	Installer version: v1.1.9
	Operating system: Windows 10 Pro 10.0.19045
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal v7.0.3
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 30
	Plugins enabled: 30
		1: Emoji Toolbar v0.4.1
		2: Calendar v1.5.10
		3: Focus Mode v1.11.4
		4: Tag Wrangler v0.5.11
		5: Recent Files v1.3.6
		6: Taskbone OCR v1.0.0
		7: Note Refactor v1.7.1
		8: Reading Time v1.1.1
		9: Remember cursor position v1.0.7
		10: Status Bar Pomodoro Timer v0.1.14
		11: Image Toolkit v1.3.1
		12: Minimal Theme Settings v6.3.1
		13: Kanban v1.5.3
		14: Vault Statistics v0.1.3
		15: File Explorer Note Count v1.2.1
		16: Contextual Typography v2.2.5
		17: Copy Image and URL context menu v1.5.0
		18: Enhancing Mindmap v0.2.4
		19: Obsidian42 - Strange New Worlds (SNW) v1.2.2
		20: DeepL v1.0.5
		21: Auto Link Title v1.4.1
		22: Checklist v2.2.12
		23: Dataview v0.5.56
		24: Awesome Reader v0.1.4
		25: MSG Handler v0.0.6
		26: AI Notes Summary v1.0.3
		27: Fleeting Notes Sync v0.6.1
		28: Whisper v1.5.1
		29: Copilot v2.3.2
		30: Link Favicons v1.8.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Fixed in 7.0.5
