### ISSUE TITLE
Line numbers > Highlight active line causes overflow in edit view

### ISSUE THREAD

**Issue by daneah** [kepano/obsidian-minimal#589]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.0.3

### Describe the bug

When the **Line numbers** > **Highlight active line** setting is enabled, the edit view panel is made wider than any of the contents of the file, causing horizontal scrolling when none would otherwise be necessary. Turning the setting off removes the overflow.

The video below is from my full vault, but I also confirmed this happens in the sandbox vault after installing Minimal and Style Settings.

https://github.com/kepano/obsidian-minimal/assets/1808306/ec2567fd-e78d-4a90-b480-d892f493d2ec

### Debug info

```
SYSTEM INFO:
	Obsidian version: v1.3.5
	Installer version: v1.3.5
	Operating system: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 22.4.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v7.0.3
	Snippets enabled: 4
	Restricted mode: off
	Plugins installed: 24
	Plugins enabled: 22
		1: Admonition v9.3.2
		2: Advanced Tables v0.18.1
		3: Citations v0.4.5
		4: Dataview v0.5.56
		5: Graph Analysis v0.15.4
		6: Smart Random Note v0.2.1
		7: Stille v1.3.3
		8: Tasks v4.0.1
		9: Tracker v1.10.9
		10: Zoom v1.1.2
		11: Calendar v1.5.10
		12: Obsidian42 - BRAT v0.7.0
		13: NLP v0.1.3
		14: Text Generator v0.3.20
		15: Footnote Shortcut v0.1.2
		16: Style Settings v1.0.6
		17: Folder Note v0.7.3
		18: Tag Wrangler v0.5.11
		19: Longform v2.0.3
		20: Pandoc Plugin v0.4.1
		21: Frontmatter Tag Suggest v0.4.1
		22: Map of Content v0.1.18

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by daneah** [comment]
FWIW I have been using the Style Settings plugin and only just became aware of the Minimal Theme Settings plugin, not sure how I missed that—feel free to parry this if you like, unless you have a lot of users using the same combo as I was 😄

**Comment by kepano** [comment]
Will be fixed in the next release

**Comment by RomanMunar** [comment]
https://github.com/kepano/obsidian-minimal/issues/589#issuecomment-1616002594
> Will be fixed in the next release
