### ISSUE TITLE
Cursor not visible on empty lines when you start editing note if Live Preview is enabled

### ISSUE THREAD

**Issue by VKondakoff** [kepano/obsidian-minimal#59]
Hi!

Cursor not visible on empty lines when you start editing note if Live Preview is enabled.
Here is a short video with a new note:

https://user-images.githubusercontent.com/230824/141698622-7aca7bf9-c75d-45a1-9fd6-c58ef10b1ee5.mov

This is not reproducible with default theme. 
(macOS Monterey, Obsidian 0.13.2, Minimal 4.1.0)

**Comment by kepano** [comment]
This is fixed as of 4.1.1
