### ISSUE TITLE
iphone overflows edit area

### ISSUE THREAD

**Issue by tkern** [kepano/obsidian-minimal#593]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.0.3

### Describe the bug

The edit area is overflowing to the left. since there is barely no padding between the text and the line numbers, the text is starting/hovering over the line numbers

![07B4A08D-74F4-4826-8B25-E08EFD46B9AA_1_101_o](https://github.com/kepano/obsidian-minimal/assets/7567280/3f814c8a-615e-40a4-99bc-81ededf8fac1)

### Debug info

```
SYSTEM INFO:
	Operating system: ios 16.6 (Apple iPhone)
	Obsidian version: 1.4.6 (105)
	API version: v1.3.5
	Login status: logged in
	Catalyst license: insider
	Live preview: off
	Legacy editor: off
	Base theme: adapt to system
	Community theme: Minimal v7.0.3
	Snippets enabled: 9
	Restricted mode: on

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
```

**Comment by kepano** [comment]
Have you tried with snippets turned off?

**Comment by kepano** [comment]
Should be fixed in 7.0.4 can you confirm?

**Comment by tkern** [comment]
> Should be fixed in 7.0.4 can you confirm?

Still the same look here (restricted mode on, 0 snippets)

**Comment by kepano** [comment]
Oh I see the issue. Currently you need Minimal Theme Settings plugin if you want to use line numbers because Obsidian doesn't have a way for themes to detect that line number is active.

**Comment by tkern** [comment]
@kepano you are right, that solved the issue
