### ISSUE TITLE
Image grids not working on iOS

### ISSUE THREAD

**Issue by lksvnr55** [kepano/obsidian-minimal#594]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

7.04

### Describe the bug

Image grids feature turned on:

![image](https://github.com/kepano/obsidian-minimal/assets/83208966/c59d05e9-2e7d-4de4-9cc1-81562f4662ce)

Image grid feature turned off:

![image](https://github.com/kepano/obsidian-minimal/assets/83208966/1500155f-7d71-437a-850d-797c4c141641)

### Debug info

SYSTEM INFO:
	Operating system: ios 16.5.1 (Apple iPad)
	Obsidian version: 1.4.6 (105)
	API version: v1.3.5
	Login status: logged in
	Catalyst license: none
	Live preview: off
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v7.0.4
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 33
	Plugins enabled: 30
		1: Dataview v0.5.56
		2: Workbench v1.6.1
		3: Hider v1.2.5
		4: QuickAdd v1.2.1
		5: Calendar v1.5.10
		6: Linter v1.16.0
		7: Sort & Permute lines v0.7.0
		8: Banners v1.3.3
		9: Advanced URI v1.36.3
		10: Sortable v0.3.1
		11: Smart Typography v1.0.18
		12: Archiver v0.23.2
		13: Templater v1.16.0
		14: Copy as HTML v1.1.3
		15: Numerals v1.2.0
		16: Commander v0.5.0
		17: Metadata Menu v0.4.21
		18: Double Colon Conceal v1.2.2
		19: Daily Notes Viewer v0.2.1
		20: Readwise Official v2.0.1
		21: Translate v1.4.4
		22: Global Search and Replace v0.3.0
		23: Jelly Snippets v0.1.5
		24: GPT-3 Notes v0.2.7
		25: Links v1.2.3
		26: Advanced Tables v0.18.1
		27: Blur v1.0.0
		28: Minimal Theme Settings v6.3.1
		29: Style Settings v1.0.6
		30: Simple Embeds v1.14.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
You can change the crop setting in `Style Settings > Images > Image crop` try changing to `Show full image`

See documentation
https://minimal.guide/Block+types/Image+grids

**Comment by lksvnr55** [comment]
Thanks, I tried that. For portrait images, a large blank space is created above and below the grid. And for landscape images, nothing happens - in fact, there's no grid at all, the images line up underneath each other whether the feature is on or not.

**Comment by kepano** [comment]
Is this new since 7.0? Or is it the same on older versions of the theme?

Also note that Image Grids only work in read mode, not live preview.

**Comment by lksvnr55** [comment]
This has been happening since version 7. In version 6 it worked perfectly. I don't use Live Preview.

In the desktop version it works without problems even in Minimal 7.

Desktop, Minimal 7:

![image](https://github.com/kepano/obsidian-minimal/assets/83208966/d63fe064-7cfe-4efc-acf5-41217f18338e)

Mobile, Minimal 7:

![image](https://github.com/kepano/obsidian-minimal/assets/83208966/ae727049-8053-4831-8560-c3e56e408348)

**Comment by kepano** [comment]
Please reopen if this is still occurring.
