### ISSUE TITLE
On the alignment of the outline arrow & Disappearance of the left margin in the iOS version

### ISSUE THREAD

**Issue by Thomas-Harrell** [kepano/obsidian-minimal#595]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.0.5

## 00

- Obsidian Version 1.3.5

- Obsidian iOS Version 1.4.6

- Minimal Theme Version 7.0.5

## 01

https://github.com/kepano/obsidian-minimal/issues/591 02

Use can fix: `.tree-item-self {align-items: center;}`

<img src="https://github.com/kepano/obsidian-minimal/assets/106761803/d699de26-759f-40c9-b4a9-618d18add16e" alt="01" width="400">

## 02

https://github.com/kepano/obsidian-minimal/issues/583 01

<img src="https://github.com/kepano/obsidian-minimal/assets/106761803/ebd1da9d-050e-4c08-8833-cf83d4a29250" alt="02" width="400">

### Debug info

None

**Comment by kepano** [comment]
Please open separate issues for separate bugs
