### ISSUE TITLE
The alignment issue between the "Outline" & "Search" arrow and the text

### ISSUE THREAD

**Issue by Thomas-Harrell** [kepano/obsidian-minimal#596]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.0.5

## 00

- Obsidian Version 1.3.5

- Minimal Theme Version 7.0.5

## 01

- The arrow is not vertically aligned with the text

- Use `.tree-item-self {align-items: center;}` can fix

<img width="350" alt="01" src="https://github.com/kepano/obsidian-minimal/assets/106761803/d699de26-759f-40c9-b4a9-618d18add16e">

<img width="350" alt="02" src="https://github.com/kepano/obsidian-minimal/assets/106761803/b063e700-393b-493b-a2e5-f7b3c9acdfbb">

### Debug info

None

**Comment by kepano** [comment]
This is an Obsidian bug that was introduced recently and will be fixed in Obsidian app directly.
