### ISSUE TITLE
Possible to increase gif size (see attachment)?

### ISSUE THREAD

**Issue by davebhc71** [kepano/obsidian-minimal#60]
Cosmetic FR for otherwise OUTSTANDING Theme! Thanks much for your efforts.
![IMG_0331](https://user-images.githubusercontent.com/80698092/141968650-f8449db2-a443-417a-a339-caf6ea7b0838.jpeg)

**Comment by kepano** [comment]
I am not able to reproduce this issue. Are you using the latest version of Minimal Theme? Do you have any other snippets or plugins that could be causing this issue?

<img width="414" alt="Screen Shot 2021-11-16 at 9 56 45 AM" src="https://user-images.githubusercontent.com/10565871/142039665-a77bec2c-fb1f-4959-8e4d-247b730a0a26.png">
