### ISSUE TITLE
Missing caret for folding headers

### ISSUE THREAD

**Issue by laawn** [kepano/obsidian-minimal#603]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.0.5

### Describe the bug

Very recently (within the last 2 days), the carets on the left of headers are no longer showing up in Preview mode when I have "Folding heading" enabled in the Editor settings. It still shows up in Reading mode but I don't use this mode. 

I tried to adjust the margin-left via CSS but no matter how much I adjusted it, the carets did not reappear.

### Debug info

The below debug info was from the Sandbox Vault, which has the same problem when installing Minimal theme and enabling "folding heading."

SYSTEM INFO:
	Obsidian version: v1.3.5
	Installer version: v1.2.8
	Operating system: Windows 10 Pro 10.0.22621
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v7.0.5
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 0
	Plugins enabled: 0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.

**Comment by laawn** [comment]
I forgot to mention. Activating "Readable line length" in the Editor settings fixes it but obviously shrinks the available content on the screen. Seems the carets are hiding in the left gutter.

**Comment by MichaelHHeng** [comment]
Same here, collapsing the headings is not possible. It's fixed by activating "Readable file length".
