### ISSUE TITLE
Image viewer in image grids

### ISSUE THREAD

**Issue by Fan4Metal** [kepano/obsidian-minimal#610]
Hi! I'm using minimal theme for image grids feature mainly. And it would be great to have some kind of image viewer when you click on an thembnail image in grid. Currently when you press on an image it is shown enlarged, but only when you keep pressing mouse key. What i suggest is an image stays enlarged and you can scroll it to the next using arrow buttons (or scroll wheel) - some kind of viewer.

**Comment by kepano** [comment]
Not something that can be done via a theme. See previous issues. Needs to be requested on Obsidian app, see open feature requests in the official forum.
