### ISSUE TITLE
Line numbers/gutter overlap content with note in sidebar

### ISSUE THREAD

**Issue by itspriddle** [kepano/obsidian-minimal#611]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.0.7

### Describe the bug

On desktop (macOS), when line numbers are enabled they overlap with note content if the note is in the sidebar.

This seems related to https://github.com/kepano/obsidian-minimal/issues/541. I haven't been able to nail down the specific commit, but it is one from the 7.0.0 release as `wget https://github.com/kepano/obsidian-minimal/releases/download/6.3.11/theme.css -O theme.css` eliminates the issue.

Screenshots:

1. 6.3.11 
<img width="381" alt="image" src="https://github.com/kepano/obsidian-minimal/assets/49571/9970e87b-258b-4cc0-b6fa-81fc1f8d0a26">

2. 7.0.0
<img width="359" alt="image" src="https://github.com/kepano/obsidian-minimal/assets/49571/ae7add58-6409-411f-8c17-cb6839b14cc9">

### Debug info

```
SYSTEM INFO:
	Obsidian version: v1.3.5
	Installer version: v1.3.5
	Operating system: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:23 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6020 22.5.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v7.0.7
	Snippets enabled: 4
	Restricted mode: off
	Plugins installed: 20
	Plugins enabled: 19
		1: Calendar v1.5.10
		2: Templater v1.16.0
		3: Open with v0.3.1
		4: Dataview v0.5.56
		5: Advanced Tables v0.18.1
		6: Kanban v1.5.3
		7: Advanced URI v1.36.3
		8: Periodic Notes v0.0.17
		9: Minimal Theme Settings v6.3.1
		10: Style Settings v1.0.6
		11: Hotkeys for specific files v1.3.1
		12: Tasks v4.1.0
		13: Recent Files v1.3.6
		14: Linkify v1.0.12
		15: Hotkey Helper v0.3.18
		16: Commander v0.5.0
		17: Contextual Typography v2.2.5
		18: Admonition v9.3.3
		19: Hider v1.2.5

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

Note I did attempt to deactivate all snippets and plugins and the issue persists.

**Comment by waltcf** [comment]
I am able to reproduce the issue. I was running into it on my iPhone, but I'm able to duplicate the behavior in the Sandbox vault on the desktop app if I make the window narrow enough:

![image](https://github.com/kepano/obsidian-minimal/assets/90991600/7fe2bcc9-41a5-421b-aa1a-198e834fd4a9)

SYSTEM INFO:
	Obsidian version: v1.4.1
	Installer version: v1.3.5
	Operating system: Darwin Kernel Version 21.6.0: Mon Apr 24 21:10:53 PDT 2023; root:xnu-8020.240.18.701.5~1/RELEASE_X86_64 21.6.0
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v7.1.2
	Snippets enabled: 0
	Restricted mode: on

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.

**Comment by yoghurtdewdew** [comment]
Similar problem.

It overlaped something when I using lapel plugin ( https://github.com/liamcain/obsidian-lapel ). Hope there might be some compatibility.

![image](https://github.com/kepano/obsidian-minimal/assets/63794438/cf0ac5fc-9b47-4b37-b1be-c17b1c140d8e)
![image](https://github.com/kepano/obsidian-minimal/assets/63794438/ffbdfc81-0d6d-443a-beb4-388761a25810)

**Comment by HiveTechDev** [comment]
Same issue. iPhone 11 and 15. Obsidian Mobile version 1.4.8. Plugin version (latest updated)

**Comment by HiveTechDev** [comment]
> Same issue. iPhone 11 and 15. Obsidian Mobile version 1.4.8. Plugin version (latest updated)

Note :: This was fixed for me when I installed the companion plugin  "minimal theme settings"
All i had to do was install the plugin no other changes

**Comment by waltcf** [comment]
Can confirm: installation of Minimal Theme Settings plugin solves the issue.

([Per kepano via Obsidian Discord](https://discord.com/channels/686053708261228577/931008597557649410/1157401706812948480): "the reason is that themes cannot access the current state of line numbers on/off, so Minimal Theme Settings adds the ability for the theme to respond to that")

I believe this bug can be closed.

**Comment by itspriddle** [comment]
I have Minimal Theme Settings installed, along with Style Settings and I am still seeing it.

Not sure if folks who it is working for are checking in the sidebar, but that is specifically where I am seeing it right now. 

<img width="1386" alt="image" src="https://github.com/kepano/obsidian-minimal/assets/49571/1f9fa84c-1a8f-4ff2-8b9d-498482084554">

**Comment by kepano** [comment]
Fixed in 7.2.3

**Comment by itspriddle** [comment]
That works, thank you!

**Comment by osmalpkoras** [comment]
I am experiencing the same bug in Minimal v7.3.3 with Obsidian v1.4.16. Has the bug reappeared?
