### ISSUE TITLE
Overflow horizontally on iPhone edit mode

### ISSUE THREAD

**Issue by ronaldsuwandi** [kepano/obsidian-minimal#614]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.0.7

### Describe the bug

Keep getting overflow horizontally when using edit mode in iPhone (preview mode works fine). Screen recording below showing the comparison between minimal theme and default theme (default theme doesn't have this problem)

https://github.com/kepano/obsidian-minimal/assets/4120788/e65ef81a-4c44-45d5-bdd9-30a87d9e4955

### Debug info

SYSTEM INFO:
	Operating system: ios 16.5.1 (Apple iPhone)
	Obsidian version: 1.4.6 (105)
	API version: v1.3.5
	Login status: logged in
	Catalyst license: none
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal v7.0.7
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 31
	Plugins enabled: 20
		1: Advanced Tables v0.18.1
		2: Dataview v0.5.56
		3: Emoji Shortcodes v2.2.0
		4: Minimal Theme Settings v6.3.2
		5: Natural Language Dates v0.6.1
		6: Paste URL into selection v1.7.0
		7: QuickAdd v1.2.1
		8: Style Settings v1.0.6
		9: Buttons v0.4.19
		10: Contextual Typography v2.2.5
		11: Outliner v4.7.1
		12: Zoom v1.1.2
		13: Default New Tab Page v0.11.0
		14: Obsidian42 - Strange New Worlds (SNW) v1.2.2
		15: Copy as HTML v1.1.3
		16: Copy Image and URL context menu v1.5.0
		17: Better Word Count v0.9.6
		18: Footnote Shortcut v0.1.2
		19: Quick Switcher++ v3.3.3
		20: Excalidraw v1.9.8

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by trainbuffer** [comment]
Do you have "Highlight active line" enabled in _Style Settings > Minimal_? I usually don't use the setting on mobile, but see this behavior with it on (in source/live preview modes). See -> 

https://github.com/kepano/obsidian-minimal/issues/613

**Comment by ronaldsuwandi** [comment]
@trainbuffer thanks! this has been driving me crazy. 

Turns out enabling highlight active line also affect desktop and not just on mobile. Disabling it "fixes" the issue
