### ISSUE TITLE
Font Size setting is not independent of application font size setting and applies across all themes.

### ISSUE THREAD

**Issue by Kuiriel** [kepano/obsidian-minimal#618]
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.0.7

### Describe the bug

The size of the main text is controlled via several settings that I am trying to make independent.

I like to use one theme for when I am working generally with notes, switching to the Minimal Theme when I want to focus by entering a Scrivener style 'Composition Mode' where the screen is black and text is green and large. I want the general text font size to be one when using the default or other theme, and much larger while in Minimal Theme.

I am under the impression that as is, this is not possible.

Currently:

Overall 'general' font size and overall zoom is set in Obsidian > Options > Appearance. If I ctrl-mouse-scroll, the size of the font varies also. Okay, so I won't touch this when flipping between themes, I think.

Minimal Theme Settings allows setting Typography > Text Font Size. So I increase this, everything looks great. But this does not use values greater than 30 and changes the number in the basic Obsidian Appearance settings.

So when I switch back to other themes, the font size stays to whatever Minimal Theme Settings or basic Appearance settings has been set to.

The values aren't stored independently.

I can even adjust the font size of my other theme while using it (Blue Topaz) simply by adjusting the font size in Minimal Theme Settings, indicating it's not changing for the Minimal Theme, but for Obsidian generally.

### Debug info

SYSTEM INFO:
	Obsidian version: v1.3.5
	Installer version: v1.3.4
	Operating system: Windows 10 Pro 10.0.22621
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 36
	Plugins enabled: 28
		1: Calendar v1.5.10
		2: Kanban v1.5.3
		3: Tag Wrangler v0.5.11
		4: Note Refactor v1.7.1
		5: Dictionary v2.22.0
		6: Find orphaned files and broken links v1.9.0
		7: Underline v1.2.1
		8: File Explorer Note Count v1.2.1
		9: Tasks v4.2.0
		10: Periodic Notes v0.0.17
		11: Quick Explorer v0.2.8
		12: Longform v2.0.3
		13: Novel word count v2.17.1
		14: Advanced Tables v0.19.0
		15: Note Folder Autorename v0.1.2
		16: AidenLx's Folder Note - folderv component v1.0.0
		17: Folder Note Core v1.3.5
		18: AidenLx's Folder Note v0.16.5
		19: Fantasy Calendar v3.0.0
		20: Outliner v4.7.1
		21: Better Word Count v0.9.6
		22: Style Settings v1.0.6
		23: Minimal Theme Settings v6.3.2
		24: Timelines v0.3.2
		25: ProZen v0.3
		26: Ghost Fade Focus v3.0.0
		27: Obsidian42 - Strange New Worlds (SNW) v1.2.2
		28: Toggle Case v1.1.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Yes, this is intentional. Minimal Theme Settings previously worked in the way you describe, it stored a separate value only used by Minimal. But this was seen as a bug by other users so now it uses the main Appearance font size value 🤷‍♂️

If you want to set the main font size only for Minimal then I would suggest doing this as a CSS snippet.

**Comment by Kuiriel** [comment]
Whaa... that's so silly of them. I'm sorry, what a frustrating change for you to have to make to revert good work. They already had the feature and then couldn't use an existing feature to do the other thing it was made to do!

So I can make a snippet that only applies when a particular theme is active, then. Probably something like....

body {
--font-text-size: 30;
}

But if it's not too much trouble to ask, what do I do to make sure the CSS snippet only applies when using the Minimal Theme?

**Comment by kepano** [comment]
Put it in .minimal-theme instead of body

**Comment by Kuiriel** [comment]
big_font_minimal_theme.css in the .obsidian>snippets folder

.minimal-theme {
--font-text-size: 30;
}

No effect?

I am probably missing some basic CSS knowledge, it's been years since I've meddled with websites.

**Comment by kepano** [comment]
You need a valid unit, e.g. 30px

Please use the #appearance channel for further help with CSS as this out of the scope for this repo

**Comment by Kuiriel** [comment]
Ya, that's the level of I forget how to do it I was at. lol. It's also 2am here. Thank you, I'll take any further queries there. For anyone else who comes looking though, it turns out the code was 

.minimal-theme {
--font-adaptive-normal: 30px;
}

And thank you for your courtesy and assistance, I now have the Scrivener style composition mode I wanted in Obsidian ^_^
