### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by briskmap4926** [kepano/obsidian-minimal#619]
**Is your feature request related to a problem? Please describe.**
When viewing notes the path to the note is hidden unless you mouse over the top of the note where the path shows on the default theme. 

**Describe the solution you'd like**
It would be nice to have an option to always show the path to the note and not have to mouse over the top part of the note just to see where it is stored.

**Comment by kepano** [comment]
this is already implemented, see Style Settings → Titles → Tab title bar

**Comment by briskmap4926** [comment]
Ah! Thank you. I looked for this but missed it.
