### ISSUE TITLE
Obsidian desktop 1.4 not displaying for Properties   

### ISSUE THREAD

**Issue by JoelAnderson-UU** [kepano/obsidian-minimal#622]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.1.1

### Describe the bug

In Live Preview, the Default Theme (and Shimmering Focus, which I also checked) display the possibility of toggling the full lis to of Properties open or closed.  This is currently invisible in Minimal, although it is possible in Source view.  This can be seen in the two screenshots:  The first is Default, the second is Minimal:

<img width="380" alt="Live preview default theme" src="https://github.com/kepano/obsidian-minimal/assets/102857667/86a70460-db90-4561-97ba-85b5a4b2993c">
<img width="344" alt="Live preview Minimal theme" src="https://github.com/kepano/obsidian-minimal/assets/102857667/307c40af-74fa-44df-ab4d-d4cd5045c4e3">

### Debug info

SYSTEM INFO:
	Obsidian version: v1.4.1
	Installer version: v1.3.5
	Operating system: Darwin Kernel Version 22.6.0: Wed Jul  5 22:17:35 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8112 22.6.0
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal v7.1.1
	Snippets enabled: 5
	Restricted mode: off
	Plugins installed: 145
	Plugins enabled: 77
		1: Dataview v0.5.56
		2: Admonition v9.3.3
		3: Advanced URI v1.36.4
		4: Calendar v1.5.10
		5: DEVONlink v2.2.1
		6: Frontmatter Tag Suggest v0.4.1
		7: Hotkeys for templates v1.4.3
		8: Hotkeys++ v0.2.7
		9: Kanban v1.5.3
		10: Limelight v1.1.0
		11: macOS Keyboard Navigation v1.1.2
		12: Natural Language Dates v0.6.1
		13: Note Refactor v1.7.1
		14: Obsidian Query Language v2.1.1
		15: Path Title v1.0.7
		16: Quick Explorer v0.2.8
		17: Remember cursor position v1.0.7
		18: Sort & Permute lines v0.7.0
		19: Sortable v0.3.1
		20: Tag Wrangler v0.5.11
		21: Templater v1.16.0
		22: Text expand v0.11.2
		23: Excel to Markdown Table v0.4.0
		24: Find orphaned files and broken links v1.9.0
		25: Advanced Tables v0.19.1
		26: Query Control v0.5.0
		27: DB Folder v3.4.0
		28: Commander v0.5.0
		29: Dangling links v0.3.0
		30: File Chucker v1.0.1
		31: Hotkeys for specific files v1.3.1
		32: QuickAdd v1.2.1
		33: Shortcut Launcher v1.0.1
		34: Plugin Groups v2.1.0
		35: Omnisearch v1.15.1
		36: Pandoc Plugin v0.4.1
		37: Obsidian42 - Strange New Worlds (SNW) v1.2.2
		38: Obsidian42 - BRAT v0.7.0
		39: Readwise Official v2.0.1
		40: Media Extended v2.11.1
		41: Copy Block Link v1.0.4
		42: Markbase for Obsidian v0.1.3
		43: QuickShare v1.3.1
		44: Emoji Titler v1.0.4
		45: Actions URI v1.2.3
		46: Obsidian Clipper v0.2.1
		47: Weekly Review v1.1.0
		48: Crossbow v1.3.0
		49: Quiet Outline v0.3.15
		50: Send Tasks to OmniFocus v1.0.7
		51: Dice Roller v9.3.0
		52: Colorful Note Borders v0.2.4
		53: Metadata Extractor v1.1.0
		54: Graph Presets v0.10.0
		55: Workspaces Plus v0.3.3
		56: Journey v0.0.7
		57: Path Finder v1.1.7
		58: File Creation and Last Modified Timestamps in Status Bar v1.2.0
		59: Linter v1.17.0
		60: Vault name in status bar v1.0.1
		61: Alias from heading v1.0.12
		62: Link with alias v1.0.6
		63: Automatic List Styles v0.1.0
		64: AutoMOC v1.3.0
		65: Apple Books Highlights v1.0.1
		66: File Color v1.0.3
		67: Smart Rename v1.0.1
		68: Weaver v0.5.3
		69: Importer v1.0.3
		70: Zen v0.6.2
		71: Metadata Menu v0.5.1
		72: Digital Garden v2.45.2
		73: Table to CSV Exporter v0.1.4
		74: Folder notes v1.4.4
		75: Hide Folders v1.0.1
		76: Markdown Tree v0.1.0
		77: Footnote Shortcut v0.1.2

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Minimal is minimal 😃

You can use Style Settings to turn it back on

**Comment by JoelAnderson-UU** [comment]
Great stuff!  Once there's hot keyed command to toggle the visibility of Properties in the note, I'll prefer to leave it off, but until then, I'll have the "Properties" heading there.

<img width="566" alt="Screenshot 2023-07-28 at 15 50 35" src="https://github.com/kepano/obsidian-minimal/assets/102857667/6e257c83-12b3-4529-bb23-1460d8944e4e">
