### ISSUE TITLE
Increase the font size in the title

### ISSUE THREAD

**Issue by accept82** [kepano/obsidian-minimal#63]
Is it possible to somehow increase the font in the title?
![18-11-2021_10-37_s8772](https://user-images.githubusercontent.com/90281362/142372569-8b083a85-4187-4956-a919-1893ec455b80.png)

**Comment by kepano** [comment]
You can now do this with a snippet as of the latest release 4.1.2

```
:root {
--font-title:1.1em;
}
```

**Comment by accept82** [comment]
Thank you very much for your reply! Or you can write step by step how to do it, I just don't understand theme devices

**Comment by accept82** [comment]
Once again, thank you very much, figured out everything works fine)))
