### ISSUE TITLE
eink: Buttons Debug info don't show text

### ISSUE THREAD

**Issue by wgross** [kepano/obsidian-minimal#630]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

7.2.0

### Describe the bug

Opening the debug info from the command palette shows a dialog with no text in the buttons. 
The text is shown when hovering over the buttons. 

<img width="406" alt="image" src="https://github.com/kepano/obsidian-minimal/assets/470052/e1a3787c-5111-476a-b480-78e8fa6eb265">

### Debug info

SYSTEM INFO:
	Obsidian version: v1.4.3
	Installer version: v1.1.9
	Operating system: Windows 10 Pro 10.0.22621
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal v7.2.0
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 12
	Plugins enabled: 11
		1: Calendar v1.5.10
		2: DB Folder v3.4.0
		3: Juggl v1.4.0
		4: Diagrams v1.5.0
		5: Obsidian Git v2.20.7
		6: Dataview v0.5.56
		7: Footnote Shortcut v0.1.2
		8: Excalidraw v1.9.16
		9: QuickAdd v1.2.1
		10: Projects v1.16.3
		11: Minimal Theme Settings v7.2.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Fixed in 7.6.2
