### ISSUE TITLE
eink: selected text is indiscernible from non-selected text

### ISSUE THREAD

**Issue by loftkid** [kepano/obsidian-minimal#634]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

7.2

### Describe the bug

when i select text with my cursor, the highlight seems transparent.

it is not tho—as when i highlight text on the current line, the translucent white is visible over the grey "current line" highlight turned on in my settings

<img width="174" alt="screenshot 806" src="https://github.com/kepano/obsidian-minimal/assets/64423044/1ab450eb-fc47-46c9-a2e3-8fd4064169bb">

(only the uppercase words are highlighted)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.3.7
	Installer version: v1.3.4
	Operating system: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 22.5.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal v7.2.0
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 50
	Plugins enabled: 16
		1: Paste URL into selection v1.7.0
		2: Contextual Typography v2.2.5
		3: Templater v1.16.0
		4: Style Settings v1.0.6
		5: Actions URI v1.2.4
		6: Outliner v4.8.0
		7: Hider v1.2.5
		8: File Explorer Note Count v1.2.1
		9: Footnote Shortcut v0.1.2
		10: Copy Block Link v1.0.4
		11: Open Gate v1.9.1
		12: ABC Music Notation v1.4.0
		13: Minimal Theme Settings v7.2.1
		14: Tab Switcher v1.3.0
		15: Wordy v1.3.1
		16: Plugin Update Tracker v1.5.2

**Comment by artofka** [comment]
The same thing on Mac using sandbox and only minimal theme style and theme installed: 
<img width="1014" alt="image" src="https://github.com/kepano/obsidian-minimal/assets/28753260/6beae147-99d8-47fe-ae8a-42112dcb3999">
Also some buttons are text with the same text as background:
<img width="1019" alt="image" src="https://github.com/kepano/obsidian-minimal/assets/28753260/e8c87e06-9da0-4f15-b3ea-941b70c1f427">

SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.4.16
	Operating system: Darwin Kernel Version 23.4.0: Fri Mar 15 00:11:05 PDT 2024; root:xnu-10063.101.17~1/RELEASE_X86_64 23.4.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: Minimal v7.5.4
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 17
	Plugins enabled: 2
		1: Minimal Theme Settings v7.5.0
		2: Calendar v1.5.10

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by artofka** [comment]
I've found that selection is appear if it's different from #000 or #fff

<img width="698" alt="image" src="https://github.com/kepano/obsidian-minimal/assets/28753260/70e4bc1a-5a1d-446b-a6ae-6c4896c80247">
<img width="689" alt="image" src="https://github.com/kepano/obsidian-minimal/assets/28753260/5e19cb5a-0e6d-4ba1-8f18-d13ee25c87b0">

**Comment by kepano** [comment]
Closed in 7.6.2, note this requires Obsidian 1.6+
