### ISSUE TITLE
Tooltip is misaligned

### ISSUE THREAD

**Issue by joymayson** [kepano/obsidian-minimal#637]
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

1.7.2

### Describe the bug

移入时，Tooltip 定位出现偏差，未能水平对齐，如下图所示：
<img width="518" alt="CleanShot 2023-08-25 at 5 44 38 @Obsidian@2x" src="https://github.com/kepano/obsidian-minimal/assets/63134288/6fb46bf2-967a-4509-bfa7-738bb537e421">

而默认主题则是能水平对齐：
<img width="508" alt="CleanShot 2023-08-25 at 5 46 48 @Obsidian@2x" src="https://github.com/kepano/obsidian-minimal/assets/63134288/dff6c583-6168-4e5f-8043-1f91daf0ed55">

### Debug info

SYSTEM INFO:
	Obsidian version: v1.3.7
	Installer version: v1.3.5
	Operating system: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 22.6.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal v7.2.1
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 42
	Plugins enabled: 38
		1: Fantasy Calendar v3.0.0
		2: Dataview v0.5.56
		3: Editor Syntax Highlight v0.1.3
		4: Kanban v1.5.3
		5: Obsidian Memos v1.9.7
		6: DB Folder v3.4.0
		7: Minimal Theme Settings v6.3.2
		8: Calendar v1.5.10
		9: Excalidraw v1.9.14
		10: Outliner v4.8.0
		11: DataLoom v8.1.0
		12: Editing Toolbar v2.3.1
		13: Number Headings v1.13.0
		14: Copy Block Link v1.0.4
		15: Callout Manager v1.0.1
		16: Style Settings v1.0.6
		17: Natural Language Dates v0.6.1
		18: Advanced Codeblock v1.1.5
		19: Emoji Toolbar v0.4.1
		20: Auto Link Title v1.4.1
		21: Image Toolkit v1.3.1
		22: JSON/CSV Importer v0.31.0
		23: Omnisearch v1.15.2
		24: Text Extractor v0.4.6
		25: Attachment Name Formatting v2.1.0
		26: File Cleaner v0.1.5
		27: Copilot v2.4.1
		28: Clear Unused Images v1.1.0
		29: Paste image Png to Jpeg v1.0.4
		30: Advanced Tables v0.19.1
		31: Link Embed v2.0.8
		32: 盘古 PanGu v1.6.1
		33: Numerals v1.2.0
		34: Easy Typing v5.1.10
		35: Local Images Plus v0.15.7
		36: Obsidian shared to Notion v0.7.6
		37: Excel to Markdown Table v0.4.0
		38: Linter v1.19.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by RyotaUshio** [comment]
I was able to reproduce the same problem in the sandbox vault.

```
SYSTEM INFO:
	Obsidian version: v1.4.14
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 22.3.0: Thu Jan  5 20:53:49 PST 2023; root:xnu-8792.81.2~2/RELEASE_X86_64 22.3.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v7.3.0
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 0
	Plugins enabled: 0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
```
