### ISSUE TITLE
decrease gutter width?

### ISSUE THREAD

**Issue by scottjl** [kepano/obsidian-minimal#64]
when using this theme, the space between the line numbers and the left side, where the file names appears, is almost 1" on my screen. if i collapse the left-side pane (where the file names are) this white space _increases_ to about 3", wasting very much of my screen space.

i'd like to reclaim that space, push the line numbers over left more, is there an easy way to do this?

sorry i'm not familiar with CSS, but i can edit the .css file and insert/edit whatever code is needed if someone can give it to me.

thanks!

**Comment by kepano** [comment]
Can you provide screenshots of the issue? Please also let me know if you are using any plugins or the Live Preview beta.

**Comment by scottjl** [comment]
I'm new to Obsidian, found your theme in the list and liked it. Not running any plugins in these screenshots, but same look with a few plugins I've tried enabled as well, so no change there. I'm using a M1 MBA MacOS 15.0.1, and Windows 10 system, including screen shots from both. I did blue out my folder names for privacy. The red arrows indicate the space I want to shrink. I tried various settings but none of them seems to make it any smaller, or larger.

Sorry line numbers weren't enabled in Windows, I forgot to turn them on. I compare the space of the gap to the digits in line numbers. It looks like I have space to go up to the millions or more! I'd rather that space be used to present more text.

 If I'm doing something wrong, please feel free to tell me.

Mac:

![mac-1](https://user-images.githubusercontent.com/353381/142471637-99e4bdcc-8d7d-4319-9651-d5d74cf19545.jpg)
![mac-2](https://user-images.githubusercontent.com/353381/142471844-32f00c67-da35-47d5-9948-e3adfab976c3.jpg)

Windows:

![windows-1](https://user-images.githubusercontent.com/353381/142471889-65917218-bd2b-40ec-b465-46eb0358bf70.jpg)
![windows-2](https://user-images.githubusercontent.com/353381/142471896-84eeda14-71fc-4037-9b7a-756b32f7916a.jpg)

**Comment by kepano** [comment]
Oh I see. You can change this in the settings. The settings you are looking for are the following:

Obsidian Settings
- `Editor > Readable line length` — turn this off if you want lines to go full width

Minimal Theme Settings (this is the companion plugin for Minimal)
- `Minimal Theme Settings > Typography > Normal line width` — number of characters per line
- `Minimal Theme Settings > Typography > Maximum line width` — maximum percentage of the pane width

The last setting is probably the one you want to change

**Comment by scottjl** [comment]
i see. yes. this is exactly what i'm looking for. thank you! here i was thinking it was the gutter space i needed to change. i've reclaimed the space. thank you again.
