### ISSUE TITLE
empty space on top left sidebar

### ISSUE THREAD

**Issue by pedrohgmacedo** [kepano/obsidian-minimal#646]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

7.2.1

### Describe the bug

There's an empty space on top left sidebar when text labels for navigation is enabled. 

Normal navigation:
![image](https://github.com/kepano/obsidian-minimal/assets/118010672/3aa32c88-4d0f-44a1-b44f-b2ca3787792b)

Text labels navigation:
![image](https://github.com/kepano/obsidian-minimal/assets/118010672/c3362dfe-d38f-4d58-9915-9a8bb153a044)

That space is not even draggable. 

### Debug info

SYSTEM INFO:
	Obsidian version: v1.4.14
	Installer version: v1.4.13
	Operating system: Windows 10 Pro 10.0.22621
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: light
	Community theme: Minimal v7.2.1
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 25
	Plugins enabled: 16
		1: Better Command Palette v0.17.1
		2: Open in other editor v0.0.5
		3: Keyshots v2.1.0
		4: Style Settings v1.0.7
		5: Hotkey Helper v0.3.18
		6: Filename Heading Sync v1.9.0
		7: Code Styler v1.0.11
		8: Floating Search v3.4.5
		9: Hider v1.2.5
		10: Minimal Theme Settings v7.2.2
		11: Commander v0.5.0
		12: File Explorer++ v1.1.3
		13: Iconize v2.3.1
		14: Recent Files v1.3.8
		15: Dataview v0.5.59
		16: Advanced Tables v0.19.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Fixed in 7.2.2
