### ISSUE TITLE
Minimal Theme CSS breaks Dataview in specific cases

### ISSUE THREAD

**Issue by Eldresh** [kepano/obsidian-minimal#649]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.2.3

### Describe the bug

The following piece of CSS from the minimal theme results in, obviously, tables having a display of 'none' if their result is an error. Which is fine in some instances, but if you have a dataview query outputting multiple tables and _some_ of them have .dataview-error-box then _none_ of the tables  that actually have results display. [The Dataview Example Vault](https://github.com/s-blu/obsidian_dataview_example_vault/) has some good examples for this in 30 Dataview Resources > 31 Query Overviews > Queries by DVJS function.

```
.block-language-dataviewjs:has(.dataview-error-box) table.dataview {
    display: none
}
```
Default CSS:
![image](https://github.com/kepano/obsidian-minimal/assets/32151068/a0fe3285-0f47-4f2a-88c7-8ffbcf611178)

The exact above CSS, but with display: initial (edit: occurred to me it should have a display of 'table', not 'initial', but you get the idea):
![image](https://github.com/kepano/obsidian-minimal/assets/32151068/88ce257a-6a2f-4dd2-9922-ad6e325919ed)
![image](https://github.com/kepano/obsidian-minimal/assets/32151068/da5db142-5a0d-40a3-b387-d8a638bbd451)
![image](https://github.com/kepano/obsidian-minimal/assets/32151068/fcf80857-609b-4963-bf96-46262ad0fc18)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.4.14
	Installer version: v1.4.13
	Operating system: Windows 10 Pro 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v7.2.3
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 5
	Plugins enabled: 3
		1: Dataview v0.5.59
		2: Minimal Theme Settings v7.2.4
		3: Style Settings v1.0.7

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by nshcr** [comment]
Same question, made a PR to fix it.
