### ISSUE TITLE
Level 5 headings and Level 6 headings with lowercase letters do not display properly

### ISSUE THREAD

**Issue by 0nobody** [kepano/obsidian-minimal#652]
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.3.2

### Describe the bug

![Quicker_20231011_181132](https://github.com/kepano/obsidian-minimal/assets/77912926/adfc38fc-602c-403b-8424-f838d19376df)

After entering a five-level heading or a six-level heading in a note, the lowercase letters in the title are not lowercase.

### Debug info

Sorry, I won't have done this.

**Comment by kepano** [comment]
This is a feature not a bug. You can change this in Style Settings under font variant

**Comment by 0nobody** [comment]
Sorry I didn't fix this, can you be a little more specific.

**Comment by 0nobody** [comment]
I found the Style Settings plugin in the Community Plugins Market and solved this problem. Sorry to disturb your work, thank you very much.
