### ISSUE TITLE
Image Grid always treats LaTeX entries as seperate 

### ISSUE THREAD

**Issue by dsandall** [kepano/obsidian-minimal#654]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.3.2

### Describe the bug

When using the Image Grids feature, LaTeX snippets like this `$$ F_x = zzy $$` always render in a separate column from the image or the surrounding text. My ideal use case is being able to type in mostly text with small snippets of LaTeX in one column, and images in the next. 
An example of what I'm referring to:
![image](https://github.com/kepano/obsidian-minimal/assets/91931921/e4df1f00-0aac-4ade-8836-52d637433090)
![image](https://github.com/kepano/obsidian-minimal/assets/91931921/21edf705-ab6c-479e-bc8a-64f03e9ee7e3)

If this is intended, may I ask why?
Either way, a huge thanks for the image grids functionality and this theme as a whole - there's no better option for quickly making columns in Obsidian (that I've found) 

### Debug info

SYSTEM INFO:
	Obsidian version: v1.4.14
	Installer version: v1.4.13
	Operating system: Windows 10 Pro 10.0.22621
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v7.3.2
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 22
	Plugins enabled: 19
		1: Lapel v0.1.1
		2: Annotator v0.2.10
		3: Binary File Manager v0.3.0
		4: Callout Manager v1.0.1
		5: Code Editor Shortcuts v1.14.0
		6: Dataview v0.5.59
		7: Editor Syntax Highlight v0.1.3
		8: Minimal Theme Settings v7.2.4
		9: Natural Language Dates v0.6.1
		10: Omnisearch v1.17.1
		11: Outliner v4.8.0
		12: Settings Search v1.3.9
		13: txt as md v0.0.1
		14: Text Extractor v0.4.8
		15: Templater v1.16.3
		16: Tasks v4.9.0
		17: Task Collector (TC) v1.0.12
		18: Style Settings v1.0.7
		19: Paste URL into selection v1.7.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Yes this is expected. To create a space add a line break.
