### ISSUE TITLE
Line numbers far from the text

### ISSUE THREAD

**Issue by Deohgu** [kepano/obsidian-minimal#655]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

1.4.14

## Bug
Line numbers display before the gutter, at the far edge of the screen, instead of near the text.  
This makes it very hard to make usage of the line numbers.  

### Line number setting
`Options > Editor > Show line number`

### Obsidian **without** Minimal theme

Line numbers near the text.
![image](https://github.com/kepano/obsidian-minimal/assets/45941521/41d1d6cc-e926-4b21-9385-5d934accaefb)

### Obsidian **with** Minimal theme

Line numbers at the far edge of the viewport.
![image](https://github.com/kepano/obsidian-minimal/assets/45941521/350ba7f5-c017-48bc-bd6e-35ad8d071dba)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.4.14
	Installer version: v1.3.5
	Operating system: Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64 22.6.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v7.3.2
	Snippets enabled: 0
	Restricted mode: on

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.

**Comment by kepano** [comment]
this is a feature not a bug

https://minimal.guide/features/active-line
