### ISSUE TITLE
Backlinks in document looks different in LP

### ISSUE THREAD

**Issue by tim-hilde** [kepano/obsidian-minimal#66]
Backlinks in document look quite different in LP than in preview

<img width="741" alt="Bildschirmfoto 2021-11-21 um 21 57 40" src="https://user-images.githubusercontent.com/44113468/142818762-4ee3e777-eb42-4012-9357-15f7e2757e71.png">

**Comment by kepano** [comment]
This is solved if you update to the latest. Thanks!
