### ISSUE TITLE
Unexpected Embedded Callout Padding

### ISSUE THREAD

**Issue by shindgewongxj** [kepano/obsidian-minimal#661]
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.3.3

### Describe the bug

If there's no lines between embedded callouts, the second one will not be rendered as a callout, and the first embedded callout following the root callout will snap to the title.

For source:

```
> [!git-merge]
> > [!git-pull-request]
> > [!git-commit]
```

It looks like:

<img width="667" alt="image" src="https://github.com/kepano/obsidian-minimal/assets/59656935/e3929f7b-95bc-41cd-af7e-3380d0760abd">

And for source:

```
> [!git-merge]
> 
> > [!git-pull-request]
>
> > [!git-commit]
```

<img width="655" alt="Screenshot 2023-10-25 at 3 50 46 PM" src="https://github.com/kepano/obsidian-minimal/assets/59656935/1ee23578-ab63-47a2-a860-152c945fab22">

### Debug info

SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103 23.1.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: adapt to system
	Community theme: Minimal v7.3.3
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 8
	Plugins enabled: 8
		1: Advanced Tables v0.19.1
		2: Hider v1.3.1
		3: Mermaid Tools v1.1.0
		4: Mindmap NextGen v1.9.0
		5: Minimal Theme Settings v7.3.0
		6: Style Settings v1.0.7
		7: Typewriter Scroll v0.2.2
		8: Kanban v1.5.3

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Closing since this also affects default theme. You should open this on Obsidian Forums.
