### ISSUE TITLE
eink: default state button text is not visible in light color

### ISSUE THREAD

**Issue by kwonoj** [kepano/obsidian-minimal#664]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.3.5

### Describe the bug

<img width="228" alt="image" src="https://github.com/kepano/obsidian-minimal/assets/1210596/58abb848-e470-4a10-ac81-56229f828776">

For some reason, I'm seeing default state's button text is not visible with eink + light color combination.

### Debug info

SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.14
	Operating system: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000 23.0.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal v7.3.5
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 3
	Plugins enabled: 3
		1: Omnisearch v1.18.1
		2: Natural Language Dates v0.6.1
		3: Minimal Theme Settings v7.3.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by artofka** [comment]
I've found that removing button class solve that issue:
<img width="686" alt="image" src="https://github.com/kepano/obsidian-minimal/assets/28753260/0ad30e9f-626c-4bf0-bca6-176afffd0d11">

**Comment by kepano** [comment]
Closed in 7.6.2, note this requires Obsidian 1.6+
