### ISSUE TITLE
Toggleable Bullet Points for multiline Dataview Tables

### ISSUE THREAD

**Issue by VerAn1015** [kepano/obsidian-minimal#665]
I use dataview tables a lot to easily breakdown information and absorb them easily. However, when I use the minimal theme, the bullet points disappear and this is a problem especially when there are multiline lists. Without the bullet points, it would seem like the ideas are just in 1 continuous line and are only separated by linebreaks when it is not. When I am new to the information and is still trying to learn it, there is no way of knowing when the first idea ends, and when the next begins.
![image](https://github.com/kepano/obsidian-minimal/assets/148541981/fc0931ca-a07d-4e88-9dd8-7ca31305d9ef)

What I am proposing is to have the bullet points in dataview tables toggleable in the style settings, or maybe even better for multiline lists only. It would be much appreciated. Thank you!

**Comment by kepano** [comment]
Style Settings > Dataview > Force table lists inline (OFF)
