### ISSUE TITLE
Keep the header when use a link as that

### ISSUE THREAD

**Issue by AMGMNPLK** [kepano/obsidian-minimal#666]
This is a demand that more people asked on the internet:

https://forum.obsidian.md/t/keep-colorful-headings-when-theyre-links/65928
https://www.reddit.com/r/ObsidianMD/comments/14klsuv/heading_style_over_link_style/
https://forum.obsidian.md/t/possible-to-ignore-link-color-in-headings/49244

I tried the snippets they offered but didn't worked for me.

I think that @kepano can find a better solution for this, so we can know that a header is both, a link and a header at the same time.

**Comment by kepano** [comment]
This should be achieved via snippets
