### ISSUE TITLE
iframes not being rendered properly

### ISSUE THREAD

**Issue by dvdmtw98** [kepano/obsidian-minimal#669]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.3.5

### Describe the bug

iframes are not being rendered properly in Minimal Theme. This occurs in both Live Preview and Reading Mode.

<img src='https://github.com/kepano/obsidian-minimal/assets/31100937/ca0f9842-02d0-4728-8c43-825cc7f9ca1b' width='500'>

Default Theme

<img src='https://github.com/kepano/obsidian-minimal/assets/31100937/2b837f69-4cae-40f9-b983-569c8df7f242' width='500'>

### Debug info

SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.16
	Operating system: Windows 10 Pro 10.0.22621
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v7.3.5
	Snippets enabled: 9
	Restricted mode: off
	Plugins installed: 12
	Plugins enabled: 12
		1: Style Settings v1.0.7
		2: Wrap with shortcuts v1.3.0
		3: Table Generator v1.4.1
		4: File Explorer Note Count v1.2.1
		5: Better Word Count v0.10.0
		6: Auto Link Title v1.4.1
		7: Advanced Tables v0.19.1
		8: Image Toolkit v1.4.0
		9: Dataview v0.5.64
		10: Reading Time v1.1.1
		11: Sortable v0.3.1
		12: Minimal Theme Settings v7.3.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by dvdmtw98** [comment]
@kepano is the rendering of `iframes` something that will be fixed? This problem exists for me in `7.5.2` as well.

**Comment by kepano** [comment]
Fixed in 7.5.3
