### ISSUE TITLE
Zero Padding-LeftRight on iOS 15 in Preview Mode

### ISSUE THREAD

**Issue by meherranjan** [kepano/obsidian-minimal#67]
I am using iPhone 13 Pro with iOS 15.1.1 and the padding left and right for the main body of the text is not present in Preview Mode. It works well in Edit Mode though.

**Comment by kepano** [comment]
Which version of Minimal are you using?

Are you using the plugins Minimal Theme Settings or Style Settings?

**Comment by kepano** [comment]
I am not able to reproduce this with the latest version of Minimal.

**Comment by meherranjan** [comment]
I am using the latest Obsidian version which has separate section for theme ( Appearance ). The minimal version is 4.1.7 (I found it using iSH app, to vim into the themes directory). 

I can attach a screenshot but it will be of less value. I was trying to reproduce this on desktop by toggling the developer tools and emulating a mobile but it works fine for some reason.

**Comment by meherranjan** [comment]
Not reproducible on 4.1.8.

We can mark this issue closed. 👍
