### ISSUE TITLE
在编辑模式下最上面的【文档属性】会偏离中心，变成居左模式了，预览则是居中的。 

### ISSUE THREAD

**Issue by SunKaedes** [kepano/obsidian-minimal#673]
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.0.0

### Describe the bug

在编辑模式下最上面的【文档属性】会偏离中心，变成居左模式了，预览则是居中的。 可以让编辑模式也是居中吗。

### Debug info

在编辑模式下最上面的【文档属性】会偏离中心，变成居左模式了，预览则是居中的。 可以让编辑模式也是居中吗。

**Comment by kepano** [comment]
This is fixed now

**Comment by SunKaedes** [comment]
Good and fast.
