### ISSUE TITLE
[FR] Background color for headings

### ISSUE THREAD

**Issue by ourigen** [kepano/obsidian-minimal#677]
**Is your feature request related to a problem? Please describe.**
Not related to a problem but a cosmetic change that I can see being useful.
I would love to have a setting available either through Minimal Theme Settings or Style Settings that allows changing background color of headings. Right now, we can only change the color of the text if Colorful Headings is toggled on.

**Describe the solution you'd like**
Expose a setting that allow changing the background color of headings.  Having the background be distinct colors as well has advantages of better catching your eyes and sectioning a note. If feasible, I think allowing the background color to fill  margin to margin would look best.

Example:

<img width="995" alt="Screenshot 2023-12-16 at 11 52 49 AM" src="https://github.com/kepano/obsidian-minimal/assets/79729735/194dfbd4-4c27-4684-b202-aa8f99db07e6">

**Comment by kepano** [comment]
This can be done with snippets, I don't plan to add it
