### ISSUE TITLE
.cm-focused class is missing when editing table in Obsidian 1.5.3 and Minimal Theme 7.4.3

### ISSUE THREAD

**Issue by ronaldsuwandi** [kepano/obsidian-minimal#680]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.4.3

### Describe the bug

When editing a table `.cm-focused` class is removed. I have my custom css that depends on that class to highlight non-focused editors [reference](https://forum.obsidian.md/t/small-improvement-over-minimal-theme-dim-unfocused-editor-more-obvious-sync-button/59600)

It still works but when editing table it just think that no editor is in focus

### Debug info

SYSTEM INFO:
	Obsidian version: v1.5.3
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 22.6.0: Wed Jul  5 22:17:35 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8112 22.6.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: light
	Community theme: Minimal v7.4.3
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 33
	Plugins enabled: 31
		1: Better Word Count v0.10.0
		2: Bulk Rename v0.5.2
		3: Buttons v0.4.19
		4: Contextual Typography v2.2.5
		5: Copy as HTML v1.1.3
		6: Copy Block Link v1.0.4
		7: Copy Image and URL context menu v1.5.1
		8: DataLoom v8.15.10
		9: Dataview v0.5.64
		10: Default New Tab Page v0.11.4
		11: Emoji Shortcodes v2.2.0
		12: Excel to Markdown Table v0.4.0
		13: File Creation and Last Modified Timestamps in Status Bar v1.2.0
		14: Find orphaned files and broken links v1.9.1
		15: Footnote Shortcut v0.1.3
		16: Hider v1.3.1
		17: Image Toolkit v1.4.1
		18: Minimal Theme Settings v7.3.1
		19: Natural Language Dates v0.6.2
		20: Obsidian42 - Strange New Worlds (SNW) v1.2.3
		21: Note Refactor v1.8.2
		22: Paste URL into selection v1.7.0
		23: Outliner v4.8.0
		24: Quick Switcher++ v3.3.9
		25: QuickAdd v1.6.1
		26: Regex Find/Replace v1.2.0
		27: Sort & Permute lines v0.7.0
		28: Style Settings v1.0.7
		29: Unique attachments v1.0.3
		30: Word Splitting for Japanese in Edit Mode v1.0.0
		31: Zoom v1.1.2

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
This is unrelated to Minimal. Themes do not control classes.
