### ISSUE TITLE
After updating obsidian version to 1.5.3, installing the sortable plug-in cannot sort the cssclass of cards.

### ISSUE THREAD

**Issue by KleinBlue4685** [kepano/obsidian-minimal#682]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.4.5

### Describe the bug

After updating obsidian version to 1.5.3, installing the sortable plug-in cannot sort the cssclass of cards.
<img width="749" alt="截屏2023-12-28 17 24 06" src="https://github.com/kepano/obsidian-minimal/assets/37221530/be5b60f9-8209-4456-bfef-eaf7e0f8b3d1">

### Debug info

After updating obsidian version to 1.5.3, installing the sortable plug-in cannot sort the cssclass of cards.

**Comment by Cruisername** [comment]
Experiencing the same issue. Sorting in cards view shows a blank menu, both with and without the sortable plugin.
