### ISSUE TITLE
in Ob 1.5.3 setted cards, only show cards border.

### ISSUE THREAD

**Issue by sishen0112** [kepano/obsidian-minimal#683]
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.3.1

### Describe the bug

<img width="1518" alt="image" src="https://github.com/kepano/obsidian-minimal/assets/11689187/97762b82-913d-4dd6-ba05-f85056e74729">

it is all right in Ob 1.4.6. but I update Ob version to 1.5.3, the phenomenon is comming.

### Debug info

---
cssclasses: cards
---

```dataview
table without id
cover as 封面,
file.link as 书名,
"作者："+author as 作者,
"豆瓣评分："+score as 豆瓣评分,
"年份："+ year as 年份,
"收录日期："+dateformat(file.cday, "yyyy-MM-dd") as 收录日期,
"状态："+status as 状态
from #Book 
where year=2023 and status="读完"
sort file.cday desc
```

**Comment by kepano** [comment]
Please update to the latest version of Minimal
