### ISSUE TITLE
--file-margins styling is breaking banners plugin

### ISSUE THREAD

**Issue by Net-Slayer** [kepano/obsidian-minimal#684]
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

7.6.4

### Describe the bug

Basically 
```css
--file-margins: var(--size-4-2) var(--size-4-12)
```
Breaks any use of css styling for banners that use calc() alongside the var(--file-margins)
Where by default --file-margins is a single value, styling that expects a single ultimate value will break if there are css calculations involving --file-margins from the minimal theme.

I've made a quick css snippet workaround in the link below:
https://github.com/noatpad/obsidian-banners/issues/146#issuecomment-1874767994

Note: System debug info says 12 snippets are enabled, this not the case, all are disabled but I have 12 snippets in the folder.

### Debug info

SYSTEM INFO:
	Obsidian version: v1.5.3
	Installer version: v1.4.16
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Minimal v7.4.6
	Snippets enabled: 12
	Restricted mode: off
	Plugins installed: 33
	Plugins enabled: 1
		1: Banners v2.0.5-beta

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
File margins is a theming variable so this should be reported on the banners plugin, since other themes may also choose to override it.
