### ISSUE TITLE
Image Grid: Empty links (=linked images) are displayed in 2 grid positions

### ISSUE THREAD

**Issue by eikowagenknecht** [kepano/obsidian-minimal#685]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.4.7

### Describe the bug

```md
[![](Media/Thumbnails/2023-12-28_google-photo_171336.jpg)](https://photos.google.com/lr/photo/1234567)
```

Code like this is for example inserted by the Google Photos plugin.

It is displayed like this:

![grafik](https://github.com/kepano/obsidian-minimal/assets/1475672/c518a4ea-e411-4877-bcb3-280253b0ce8f)

I'd expect it like the red border here:
![grafik](https://github.com/kepano/obsidian-minimal/assets/1475672/8d891b39-6f73-4a08-a571-dc02c1586d5e)

When there is another image next to it, the "empty space" is 1/3rd etc.

### Debug info

SYSTEM INFO:
	Obsidian version: v1.5.3
	Installer version: v1.4.13
	Operating system: Windows 10 Pro 10.0.22635
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: off
	Live preview: off
	Base theme: dark
	Community theme: Minimal v7.4.7
	Snippets enabled: 5
	Restricted mode: off
	Plugins installed: 27
	Plugins enabled: 16
		1: Auto Link Title v1.5.0
		2: Dataview v0.5.64
		3: Duplicate Line v2.2.11
		4: Find orphaned files and broken links v1.9.1
		5: Google Photos v1.6.5
		6: Linter v1.22.0
		7: Minimal Theme Settings v7.3.1
		8: Sort & Permute lines v0.7.0
		9: Tag Wrangler v0.6.1
		10: Templater v2.1.0
		11: Style Settings v1.0.7
		12: Homepage v3.6.0
		13: Natural Language Dates v0.6.2
		14: Excalidraw v2.0.16
		15: Modal forms v1.37.0
		16: Contextual Typography v2.2.5

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Should be resolved in 7.5.4
