### ISSUE TITLE
Small display bug in fold indicator

### ISSUE THREAD

**Issue by shawnyeager** [kepano/obsidian-minimal#686]
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.3.1

### Describe the bug

First, thanks for this brilliant theme, @kepano. I appreciate it.

The caret indicating a foldable block below is misplaced when the parent item is without a bullet. See the attached screenshot.

![mininal-display-glitch](https://github.com/kepano/obsidian-minimal/assets/980297/1b89bd87-0200-4281-ac77-5bcfa1d88144)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.5.3
	Installer version: v1.5.3
	Operating system: Darwin Kernel Version 23.2.0: Wed Nov 15 21:59:33 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8112 23.2.0
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: on
	Live preview: on
	Base theme: light
	Community theme: Minimal v7.4.7
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 11
	Plugins enabled: 10
		1: Hider v1.3.1
		2: Dataview v0.5.64
		3: Kanban v1.5.3
		4: Minimal Theme Settings v7.3.1
		5: Style Settings v1.0.7
		6: Omnivore v1.9.1
		7: Calendar v1.5.10
		8: Micro.publish v2.4.0
		9: QuickAdd v1.6.1
		10: Auto Template Trigger v1.1.3

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
This should be fixed, reopen if it's not.
