### ISSUE TITLE
Image missing for "Minimal Theme Settings: Show block widths toggle" description

### ISSUE THREAD

**Issue by trainbuffer** [kepano/obsidian-minimal#687]
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

n/a

### Describe the bug

The image here: https://minimal.guide/features/block-width#Developers for the block width guides is missing. 

### Debug info

n/a

**Comment by kepano** [comment]
Good catch, thanks!
