### ISSUE TITLE
Obsidian on Windows works slower when using this theme and related plugins

### ISSUE THREAD

**Issue by juanbretti** [kepano/obsidian-minimal#688]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.4.7

### Describe the bug

When installed and enabled the Minimal theme, the Obsidian application works slow. Noticeably slow.

I have also installed the 
- Minimal Theme Settings, version 7.3.1
- Style Settings, version 1.0.7

I tried (having installed the previously mentioned plugins) disable the extensions. But still slow.
Also, if I have enable or disabled the CSS snippets, Obsidian still running slow.

This does not happen when using the Default theme.

This issue was also posted at https://forum.obsidian.md/t/slowdown-lag-typing-obsidian-sync-windows/75009, where another user mentioned having the same issue.

### Debug info

# When the theme is installed
```
SYSTEM INFO:
	Obsidian version: v1.5.3
	Installer version: v1.4.13
	Operating system: Windows 10 Pro 10.0.22631
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: dark
	Community theme: Minimal v7.4.7
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 18
	Plugins enabled: 15
		1: Tag Wrangler v0.6.1
		2: Natural Language Dates v0.6.2
		3: Editor Syntax Highlight v0.1.3
		4: Text Format v2.4.0
		5: Omnivore v1.9.1
		6: Image Converter v1.1.7
		7: Excalidraw v2.0.17
		8: Templater v2.1.0
		9: Dataview v0.5.64
		10: Calendar v1.5.10
		11: Mind Map v1.1.0
		12: Settings Search v1.3.10
		13: Homepage v3.6.0
		14: Minimal Theme Settings v7.3.1
		15: Style Settings v1.0.7

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

# When the theme is removed
```
SYSTEM INFO:
	Obsidian version: v1.5.3
	Installer version: v1.4.13
	Operating system: Windows 10 Pro 10.0.22631
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: dark
	Community theme: none
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 16
	Plugins enabled: 13
		1: Tag Wrangler v0.6.1
		2: Natural Language Dates v0.6.2
		3: Editor Syntax Highlight v0.1.3
		4: Text Format v2.4.0
		5: Omnivore v1.9.1
		6: Image Converter v1.1.7
		7: Excalidraw v2.0.17
		8: Templater v2.1.0
		9: Dataview v0.5.64
		10: Calendar v1.5.10
		11: Mind Map v1.1.0
		12: Settings Search v1.3.10
		13: Homepage v3.6.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by kepano** [comment]
Is the problem present with only Minimal theme and no community plugins?

**Comment by juanbretti** [comment]
Thank you for your reply.

What I notice slow compared to the default theme, is the find files and typing.
Typing in particular gets very laggy.

I tested on a sandbox vault. This sandbox vault has 10300 `.md` files.
I tested with and without the related plugins to Minimal.
This is the debug for this vault:

```
SYSTEM INFO:
	Obsidian version: v1.5.3
	Installer version: v1.4.13
	Operating system: Windows 10 Pro 10.0.22631
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: adapt to system
	Community theme: Minimal v7.4.7
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 2
		1: Minimal Theme Settings v7.3.1
		2: Style Settings v1.0.7

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

I noticed if I install the two related plugins, using the following `data.json`, the application gets slow. In particular, Search files gets slower.

`.obsidian/plugins/obsidian-minimal-settings/data.json`

```json
{
  "theme": "moonstone",
  "lightStyle": "minimal-light",
  "darkStyle": "minimal-dark-tonal",
  "lightScheme": "minimal-default-light",
  "darkScheme": "minimal-things-dark",
  "editorFont": "",
  "lineHeight": 1.5,
  "lineWidth": 40,
  "lineWidthWide": 50,
  "maxWidth": 88,
  "textNormal": 21,
  "textSmall": 13,
  "imgGrid": true,
  "imgWidth": "img-default-width",
  "tableWidth": "table-default-width",
  "iframeWidth": "iframe-default-width",
  "mapWidth": "map-default-width",
  "chartWidth": "chart-default-width",
  "colorfulHeadings": true,
  "colorfulFrame": true,
  "colorfulActiveStates": true,
  "trimNames": true,
  "labeledNav": false,
  "fullWidthMedia": true,
  "bordersToggle": true,
  "minimalStatus": true,
  "focusMode": false,
  "underlineInternal": true,
  "underlineExternal": true,
  "useSystemTheme": false,
  "folding": true,
  "lineNumbers": false,
  "readableLineLength": false,
  "devBlockWidth": false
}
```

`.obsidian/plugins/obsidian-style-settings/data.json`
```json
{
  "minimal-style@@h1-size": "2em",
  "minimal-style@@h2-size": "1.5em",
  "minimal-style@@frame-background@@dark": "#3D3F41"
}
```

So, to make this vault work fast, I need to switch back to the default theme.
Even if I turn off the related plugins, Obsidian is still slow.

Does it make sense?
Thank you for your interest on this issue.

**Comment by kepano** [comment]
I am not able to reproduce this issue. I need help identifying whether the issue is with the theme or one of the plugins. So you need to first turn off all plugins and test with only the theme.

Follow these steps:

1. Set Obsidian to `Restricted mode: ON` under Settings → Community Plugins
2. Shut down and reopen Obsidian
3. Try your search performance with default vs. Minimal theme

**Comment by DovieW** [comment]
@kepano I have an issue for Obsidian on Linux with multiple themes. I only notice the slowness when pressing the down key to move the cursor down quickly. It stutters and jumps a lot. Also some stuttering with other operations.

I have Style Settings and Minimal Theme Settings installed. If I disable both of these plugins, it makes no difference.

When I switch to the default theme, performance is back to normal.

**Comment by DovieW** [comment]
With restricted mode on and Minimal theme enabled it seems to be slightly better, but eventually starts stuttering as well while scrolling with the cursor.

**Comment by DovieW** [comment]
I'm noticing that it only seems to be an issue when there are lots of different elements in the file. For example, headings, links, inline code and code blocks.

I'm even seeing some strange behavior where the cursor will jump around to different elements for seemingly no reason while just holding the down arrow.

**Comment by qlassiqa** [comment]
I had to switch to an entirely different theme myself because Minimal stopped feeling "minimal" due to severe typing lag. 

The more content a note has and the more variate that content is (code blocks, headings, callouts, etc.), the more typing lag I experience, **to the point of being impossible to write because Obsidian can't keep up anymore with my typing speed**.

The only workaround was switching to a different theme - I've tried quite a lot of themes, and only Minimal poses this typing lag problem for some reason...

And yes, I tested in all scenarios, even a fresh Obsidian install with no other plugins, no snippets, latest version, yet something in this theme leads to typing lag.

P.S. if I dare to use snippets and plugins, Obsidian really becomes impossible to use with the Minimal theme :(

**Comment by kepano** [comment]
I can't think of anything that changed in Minimal that could cause this. I would recommend installing older versions of Minimal. This would help identify which version of Minimal introduced this issue. 

I don't personally have a Windows device, so I would love some help from anyone who is able to test this and help identify the issue.

**Comment by juanbretti** [comment]
@kepano , I use two Windows machines. I am trying to isolate the issue.
Sadly, I think it is the combination of **Minimal Theme** + **Minimal Theme Settings** + **Style Settings**.

Still testing, will post back when I have a better idea or able to reproduce the issue.

**Comment by qlassiqa** [comment]
In my case it doesn't matter the combination of plugins, it doesn't even matter if I use any plugins, it lags no matter what :(

**Comment by kepano** [comment]
@juanbretti @qlassiqa please go to the Releases and try older versions of Minimal, e.g. pre 7.0 and see if the issue is present. If it is then the issue is likely related to Obsidian itself and not Minimal.

If the issue is not present in older versions try installing newer ones e.g 7.1, 7.2, 7.3. Ideally you can help determine in which version the performance issue began.

**Comment by HoodyEz** [comment]
I have the same problem, i try with a older version and the lag is not present.

**Comment by qlassiqa** [comment]
> I have the same problem, i try with a older version and the lag is not present.

Did you look at what version the old version is? This will help find out when the problem occurred.

**Comment by kepano** [comment]
@HoodyEz what is the latest version of Minimal that does not have this issue? I need more specifics.

**Comment by DovieW** [comment]
I just want to point out that the stuttering that I've been seeing is identical on other themes that I've tried.
I've switched back to the default for now.

**Comment by BassWasTaken** [comment]
I have experienced similar issues- Obsidian performing severely slower to the point of being almost unusable. I think the issue occurs with noted with lots of embedded internal links, which I use a lot to build up dashboards and the like. Could there be something in the theme that puts more weight on this feature?

**Comment by qlassiqa** [comment]
> I have experienced similar issues- Obsidian performing severely slower to the point of being almost unusable. I think the issue occurs with noted with lots of embedded internal links, which I use a lot to build up dashboards and the like. Could there be something in the theme that puts more weight on this feature?

I use almost no internal links and the problem persists, so that's not it. We're waiting for @HoodyEz to tell us what older version they tested that worked well...

**Comment by kepano** [comment]
Additional reports are not useful, unless you can provide steps to reproduce the issue. So far I still don't have anything to work off of.

You can download [old releases](https://github.com/kepano/obsidian-minimal/releases) of Minimal and install them. Ideally this should help identify in which version the performance issue was introduced.

**Comment by Comprehensive-Jason** [comment]
I feel rather confident that this issue is related to Excalidraw: https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/1456. 
We found that Excalidraw + Minimal theme produces a bunch of CSS rejiggering that slows rendering time, producing a delay per character typed as the CSS readjusts. 

Zsolt has already made a number of changes to Excalidraw's CSS, which has fixed most of the issues with CSS when using default theme. However, lag still exists when using Excaliraw and Minimal concurrently. Here's a test I did previously: https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/1456#issuecomment-1861760774

**Comment by qlassiqa** [comment]
> I feel rather confident that this issue is related to Excalidraw

Actually the problem was first found/reported without any other plugins whatsoever, and I don't use Excalidraw, so that's not it.

**Comment by HoodyEz** [comment]
I tried version 7.2.0 but idk, my PC is not that fast, even in version 7.2.0 it is very slow, I will continue trying other versions.

**Comment by HoodyEz** [comment]
> I feel rather confident that this issue is related to Excalidraw: [zsviczian/obsidian-excalidraw-plugin#1456](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/1456). We found that Excalidraw + Minimal theme produces a bunch of CSS rejiggering that slows rendering time, producing a delay per character typed as the CSS readjusts.
> 
> Zsolt has already made a number of changes to Excalidraw's CSS, which has fixed most of the issues with CSS when using default theme. However, lag still exists when using Excaliraw and Minimal concurrently. Here's a test I did previously: [zsviczian/obsidian-excalidraw-plugin#1456 (comment)](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/1456#issuecomment-1861760774)
> 
> I believe changes to CSS need to be made on Minimal's end as well to ensure there is no lag when using both.

Yeeeeeeeees, in excalidraw too.

**Comment by kepano** [comment]
It's possible that Excalidraw is causing it's own performance issues, but I don't think [Minimal's Excalidraw code](https://github.com/kepano/obsidian-minimal/blob/master/src/scss/plugins/excalidraw.scss) should affect performance, since it's only mapping variables.

**Comment by juanbretti** [comment]
I still haven't found how to reproduce this issue.
But I noticed: **for example**, if I turn **Sync** on and off, the app returns to fluid. But after some time, the app returns to becoming laggy.
Like some _cache_ or _garbage collector_ gets full, and resets when something changes: like Sync on and off.

Sorry for this vague comment, but I'm still trying to find the reason for the lag response.

🤞Looking forward to the updated version of Electron!

**Comment by zsviczian** [comment]
Since there is a mention of Excalidraw here... I am looking for Minimal theme users who have the energy and motivation to help with a bit of problem finding by elimination. Please see the testing-task and respond here: https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/1456#issuecomment-1956043440

**Comment by juanbretti** [comment]
I will reopen this issue if I find a way to reproduce.
