### ISSUE TITLE
Typography Setting Control for Headings

### ISSUE THREAD

**Issue by meherranjan** [kepano/obsidian-minimal#69]
I like the theme and I find the theme settings sufficient but I would like to see typography setting for headings i.e. H1-H6. It would be great to control the `font-size, font-variant, letter-spacing and color`. Even great would be to have separate setting for preview and editor mode.

I know I can do it with custom CSS but I think many can benefit from this flexibility out of the box.

**Comment by kepano** [comment]
Heading sizes and weight can be controlled via Style Settings. I will be adding color in a future update.

**Comment by kepano** [comment]
Color is now available as of Minimal 4.1.8

**Comment by meherranjan** [comment]
@kepano I do not see an option for heading size and weight in the style setting. Is it named differently?

**Comment by kepano** [comment]
You need to have the Style Settings plugin, this feature is not available in Minimal Theme Settings
