### ISSUE TITLE
In Obsidian version 1.5.3, the drag handle of the table cannot be moved

### ISSUE THREAD

**Issue by LIl-Pi9G** [kepano/obsidian-minimal#692]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.4.7

### Describe the bug

The first picture is the table in the default obsidian theme, and the second picture is the minimal theme. In the minimal theme, I cannot drag the handle of the table.
![2024-02-01_12-50-28](https://github.com/kepano/obsidian-minimal/assets/59461842/e76a20b5-ae03-4b38-b38a-91082ead32f4)
![2024-02-01_12-51-40](https://github.com/kepano/obsidian-minimal/assets/59461842/9cece338-5f40-44dd-b467-85aea90a1597)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.5.3
	Installer version: v1.5.3
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: Minimal v7.4.7
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 0
	Plugins enabled: 0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.

**Comment by kepano** [comment]
This will be fixed in the next version, but in the meantime you can still drag. It's just that the grabber doesn't move.
