### ISSUE TITLE
Graph view not showing highlighted note

### ISSUE THREAD

**Issue by davidrips** [kepano/obsidian-minimal#696]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

7.4.8

### Describe the bug

Typically in graph note, when you hover over a currently open note in a different pane, that note's node is highlighted on the graph. This isn't working when Minimal theme is active. This is in both light and dark modes. 

### Debug info

SYSTEM INFO:
	Obsidian version: v1.5.3
	Installer version: v1.5.3
	Operating system: Darwin Kernel Version 23.3.0: Wed Dec 20 21:33:31 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8112 23.3.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: light
	Community theme: Minimal v7.4.8
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 39
	Plugins enabled: 22
		1: Recent Files v1.3.10
		2: Collapse All v2.0.0
		3: DEVONlink v2.2.1
		4: Reveal Active File Button v2.0.3
		5: Auto Filename v1.1.0
		6: Add links to current note v0.0.9
		7: Dataview v0.5.64
		8: Advanced new file v1.5.1
		9: Waypoint v1.4.0
		10: Multi Properties v1.0.0
		11: Rapid Notes v1.2.5
		12: Multi Tag v0.10.0
		13: Tagged Documents Viewer v1.0.2
		14: Note Gallery v0.0.59
		15: Supercharged Links v0.11.1
		16: Style Settings v1.0.7
		17: ZotLit v1.1.4
		18: Zotero Integration v3.1.7
		19: Minimal Theme Settings v7.3.1
		20: 3D Graph v1.0.5
		21: Tag Wrangler v0.6.1
		22: Hotkeys for templates v1.4.3

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
I am not able to reproduce this issue. The active node is highlighted with your accent color. You can also change it using Style Settings plugin.

**Comment by davidrips** [comment]
You know, I didn't dig into the Style Settings deep enough – for some reason all of the color choices are set to transparent, including the active note one in the graphs section. Changing that fixed it. Thanks for looking into it!
