### ISSUE TITLE
Flag in the theme option for avoid hiding of the title bar

### ISSUE THREAD

**Issue by progressify** [kepano/obsidian-minimal#698]
**Is your feature request related to a problem? Please describe.**
In my vault I often have notes with the same name but in different folders.
Can be useful to avoid the hiding of the title bar for having always in mind in what folder I am.

**Describe the solution you'd like**
I prefer to have an option in the theme settings, a flag, to avoid this behaviour.

Screencast for showing what I mean
https://github.com/kepano/obsidian-minimal/assets/11472632/46b76edc-d5a8-4c38-af0e-3c9cb4c86890

**Comment by kepano** [comment]
it's already available, go to Style Settings → Titles

**Comment by progressify** [comment]
oh ok thanks
I didn't know it was necessary to download an additional plugin

resolved 😂 ❤️
