### ISSUE TITLE
Obsidian 1.5.3, default settings, Fedora 36 - Obsidian won't open URL links in my browser

### ISSUE THREAD

**Issue by KipIngram** [kepano/obsidian-minimal#699]
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.4.8

### Describe the bug

Obsidian won't open URLs in my browser.  Internal links seem to work fine.  I have tried with my default browser set to both Chrome and Brave.  I have confirmed that links in pdf files open properly.  I have ensured I'm in live preview mode when attempting to follow the links.  Right click / "open this link" also does nothing.  I also relaunched Obsidian and created a new empty vault, to get fully default settings - this also did not solve the problem (but in that case I was running with the default theme rather than Minimal).

### Debug info

SYSTEM INFO:
	Obsidian version: v1.5.3
	Installer version: v1.5.3
	Operating system: #1 SMP PREEMPT_DYNAMIC Thu May 11 16:51:53 UTC 2023 6.2.15-100.fc36.x86_64
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Minimal v7.4.8
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 8
	Plugins enabled: 0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.

**Comment by KipIngram** [comment]
I should also note that I have launched Obsidian from a terminal window, by running the AppImage file.  When I click a link in a note, it does print out there in the terminal window that it's "Opening URL <url>".  So it is trying, it looks like.

**Comment by kepano** [comment]
If the bug is present with the default theme then the bug should be reported in the Obsidian Forum
