### ISSUE TITLE
Table border is black on dark theme

### ISSUE THREAD

**Issue by skorphil** [kepano/obsidian-minimal#70]
Tables have black border on dark theme so they are hard to distinguish

**Comment by kepano** [comment]
Can you share a screenshot?

**Comment by owenfiscus** [comment]
Not sure if this exactly the same issue that @skorphil is referring to, but when I have tables in preview mode using the dark theme there is not a visible outer border.

<img width="220" alt="Screen_12 12 2021_11 20 47_AM" src="https://user-images.githubusercontent.com/8652398/145726402-717a7114-824c-41f3-84a7-46b3466f2b9b.png">

**Comment by skorphil** [comment]
> Not sure if this exactly the same issue that @skorphil is referring to, but when I have tables in preview mode using the dark theme there is not a visible outer border.
> 
> <img width="220" alt="Screen_12 12 2021_11 20 47_AM" src="https://user-images.githubusercontent.com/8652398/145726402-717a7114-824c-41f3-84a7-46b3466f2b9b.png">
> 

Yeap, that's what I mean

**Comment by kepano** [comment]
I see. There is also no outer in border in light mode. This is a feature not a bug 😄

As of Minimal 4.1.7 there are many new helper classes available to help you style tables 
https://github.com/kepano/obsidian-minimal/releases/tag/4.1.7
