### ISSUE TITLE
Color choice for overfilled progress bars

### ISSUE THREAD

**Issue by hanseHansen** [kepano/obsidian-minimal#701]
Definitely a small thing, but I'm just a little bothered that a progress bar filled over 100% reverts back to red (or whatever "red" color is set in style settings plugin). I'd love to choose not only the "completed" color, but also the over-completed color. Maybe I'm just missing an obvious solution, and I would imagine there is a way to customize it on my own using CSS, but I'm not quite that savvy.

If it wouldn't be too hard to add that option, or if someone smarter than me has a good work-around, that'd be awesome!

**Comment by kepano** [comment]
this was already added, see #565

**Comment by hanseHansen** [comment]
I think that [#565 ](https://github.com/kepano/obsidian-minimal/issues/565) is about customizing the completed progress bar color (definitely great and perfectly functional!) and automatically normalizing progress bar values to percentages. Those are great!

The problem I have is that whenever a progress bar is valued at >100%, it defaults to the color defined as "Red" in Style Settings. 150%? Red progress bar. 200%? Red progress bar. I track how many words I've written each day on academic projects; if my goal one day is 200 (defining the max), and I write 250 (the value) then I run into this issue. The bars render as filled, but use the aforementioned "Red" color defined in Style Settings.

Hopefully that makes a little more sense! And sorry to be a bother!

**Comment by kepano** [comment]
I don't really see this as something to be solved in the core theme because HTML progress bars are not meant to be filled more than 100%. However, you can definitely create some custom styling using a snippet to tailor the appearance to your needs.

**Comment by hanseHansen** [comment]
Makes sense. Thanks for the advice!
