### ISSUE TITLE
Mermaid Gantt Tables compressed to the point of being unusable

### ISSUE THREAD

**Issue by aenony** [kepano/obsidian-minimal#703]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.4.8

### Describe the bug

<img width="680" alt="image" src="https://github.com/kepano/obsidian-minimal/assets/57414041/cbba4cb3-a73e-40f7-a839-d27b4e770a26">

Not a problem with any other theme. Not sure why this is happening - can't seem to fix it via CSS either.

### Debug info

SYSTEM INFO:
	Obsidian version: v1.5.3
	Installer version: v1.5.3
	Operating system: Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2/RELEASE_X86_64 23.2.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: light
	Community theme: Minimal v7.4.8
	Snippets enabled: 4
	Restricted mode: off
	Plugins installed: 62
	Plugins enabled: 25
		1: Minimal Theme Settings v7.3.1
		2: Calendar v1.5.10
		3: Recent Files v1.3.10
		4: Admonition v10.2.0
		5: Activity History v0.1.4
		6: Todoist Sync v1.12.0
		7: Templater v2.2.1
		8: Iconize v2.10.1
		9: Day Planner v0.18.0
		10: Heatmap Calendar v0.6.0
		11: Dataview v0.5.64
		12: Toggl Track v0.11.0
		13: Solve v0.9.0
		14: Style Settings v1.0.7
		15: Tracker v1.13.2
		16: Dashboards v0.2.0
		17: Advanced Tables v0.21.0
		18: Excalidraw v2.0.23
		19: Habit Tracker v0.3.4
		20: Periodic Notes v0.0.17
		21: floating toc v2.4.6
		22: Multi-Column Markdown v0.9.1
		23: ProgressBar v0.5.0
		24: Obsidian Badge v0.4.1
		25: Habit Tracker 21 v1.2.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Can you provide the mermaid code for this chart?

**Comment by aenony** [comment]
````mermaid
gantt
    dateFormat  YYYY-MM-DD

    %% Current Time: 24:59:58
    title       2024

    section Nonagons
    A            :active,    des1, 2024-01-01,30d


	section Timeline
	B        : active,    goal3, 2024-02-10,10d

````

I deleted the original but that's essentially it.

**Comment by kepano** [comment]
This seems similar to #694 which I haven't been able to reproduce. Do you have readable line length on or off?
