### ISSUE TITLE
Ability to select colors for bold and italic

### ISSUE THREAD

**Issue by pztrn** [kepano/obsidian-minimal#71]
Can ability to select colors for different font styles be added, please? Currently in editor mode there are no possibility to figure out is text is bold, italic or just normal text.

**Comment by kepano** [comment]
Currently this can be done via CSS snippets:
https://forum.obsidian.md/t/getting-comfortable-with-obsidian-css/133

I will explore adding it to Style Settings

**Comment by kepano** [comment]
This is now available in Minimal 4.2.8 under Advanced section of Style Settings
