### ISSUE TITLE
Line number and Cursor alignment incorrect in notes with Tables

### ISSUE THREAD

**Issue by dvdmtw98** [kepano/obsidian-minimal#711]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.5.3

### Describe the bug

Alignment of cursor and the line number drift apart when the note contains table. With only one table the alignment is only slightly off but when multiple tables are added the alignments is completely off.

Also tested in Sandbox Vault with Minimal Theme, Style Settings and Minimal Settings. Same problem.

### Default Theme
The line number and cursor are on the same line.

![Screenshot_3490](https://github.com/kepano/obsidian-minimal/assets/31100937/b50aa4a1-3a4a-4bb5-b189-0662920228f8)
![Screenshot_3492](https://github.com/kepano/obsidian-minimal/assets/31100937/0adce54d-2fef-4988-82c7-5c9f4473cb21)

### Minimal Theme
The line number and cursor are completely off at the end of the 3rd table on the page.

![Screenshot_3486](https://github.com/kepano/obsidian-minimal/assets/31100937/4c2fc97e-3608-4ecb-9e09-0a1aa2ecfe02)
![Screenshot_3488](https://github.com/kepano/obsidian-minimal/assets/31100937/995d178e-fe48-4754-8d85-5102f3da30af)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.5.11
	Installer version: v1.5.11
	Operating system: Windows 10 Pro 10.0.22621
	Login status: not logged in
	Insider build toggle: on
	Live preview: on
	Base theme: dark
	Community theme: Minimal v7.5.3
	Snippets enabled: 9
	Restricted mode: off
	Plugins installed: 17
	Plugins enabled: 17
		1: Auto Link Title v1.5.3
		2: Better Word Count v0.10.1
		3: Broken Links v1.2.2
		4: Clear Unused Images v1.1.0
		5: Dataview v0.5.65
		6: File Explorer Note Count v1.2.1
		7: Image Toolkit v1.4.1
		8: Minimal Theme Settings v7.3.1
		9: Quick Switcher++ v4.0.0
		10: Sortable v0.3.1
		11: Style Settings v1.0.8
		12: Table Generator v1.4.1
		13: Tag Wrangler v0.6.1
		14: Templater v2.2.3
		15: Wrap with shortcuts v1.3.0
		16: Update modified date v1.3.2
		17: Modal forms v1.40.2

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by Cubius** [comment]
after a little digging with the dev tools i traced the issue down to `.cm-embed-block.cm-table-widget.markdown-rendered{margin-top:-8px!important;padding:var(--table-drag-padding);overscroll-behavior-x:none}`

or more specifically the `margin-top:-8px!important`

my css isnt good enough to check what else this might touch upon (and frankly the 220k+ long single line in `theme.css` is a mess) but a simple workaround of creating a css snippet and adding `.cm-embed-block.cm-table-widget.markdown-rendered{margin-top:0px!important}` works well enough for me for now

**Comment by dvdmtw98** [comment]
@kepano any chance this alignment issue would be resolved in the theme soon? The above snippet does work as a interim solution.

**Comment by kepano** [comment]
Fixed in 7.7.8
