### ISSUE TITLE
I want make h1 is biggest,and h6 is smallest.not only defferent in colors.thank you .

### ISSUE THREAD

**Issue by qxyp** [kepano/obsidian-minimal#714]
H1 # first issues   The heading 1 is the biggest.
H2 ## heading2   The heading 2 is smaller than heading 1
H3 ### heading3   The heading 3 is smaller than heading 2
H3 #### heading4   The heading 4 is smaller than heading 3
H5 ##### heading5   The heading 5 is smaller than heading 4
H6 ###### headingy   The heading 6 is smallest.

not only diferent in colors.  thank you

**Comment by kepano** [comment]
Please use Style Settings for this
