### ISSUE TITLE
eink: Calendar element's text is not visible when selected

### ISSUE THREAD

**Issue by artofka** [kepano/obsidian-minimal#719]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

7.5.4

### Describe the bug

Text and dots on calendar elements (month, day) is not visible while element active and it's background color is changing

<img width="317" alt="image" src="https://github.com/kepano/obsidian-minimal/assets/28753260/e7d9b2fe-cd4c-4dbb-9f08-9f87c1d04c44">
<img width="325" alt="image" src="https://github.com/kepano/obsidian-minimal/assets/28753260/2a4c4313-f26e-4b0f-961c-b86113fa9b47">

### Debug info

SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.4.16
	Operating system: Darwin Kernel Version 23.3.0: Wed Dec 20 21:28:58 PST 2023; root:xnu-10002.81.5~7/RELEASE_X86_64 23.3.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: Minimal v7.5.4
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 17
	Plugins enabled: 17
		1: Natural Language Dates v0.6.2
		2: Omnisearch v1.21.1
		3: Image in Editor v2.2.6
		4: Paste URL into selection v1.7.0
		5: Quiet Outline v0.3.25
		6: Style Settings v1.0.8
		7: Duplicate Line v3.1.2
		8: Image Layouts v0.15.4
		9: Image Toolkit v1.4.1
		10: Kanban v1.5.3
		11: List Callouts v1.2.7
		12: Hider v1.3.1
		13: Excalidraw v2.0.25
		14: Minimal Theme Settings v7.5.0
		15: Inline Encrypter v1.1.0
		16: Dataview v0.5.66
		17: Calendar v1.5.10

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
fixed in 7.6.5
