### ISSUE TITLE
Feature: Dataview helper classes on in Live Preview mode

### ISSUE THREAD

**Issue by frankreporting** [kepano/obsidian-minimal#72]
Love the new table helper classes for Dataview. Is it possible to make it so those styles are applied to Dataview tables in Live Preview mode as well?

**Comment by kepano** [comment]
That is the plan, eventually. Unfortunately Live Preview does not yet support tables. Once Obsidian team adds table support I will work on making the styles match.

**Comment by kepano** [comment]
Oops sorry, I just realized that Dataview tables are being handled differently since the latest update. I will look into this shortly.

**Comment by kepano** [comment]
After some exploration it seems that this is not possible yet:

<img width="764" alt="Screen Shot 2021-12-07 at 6 17 36 PM" src="https://user-images.githubusercontent.com/10565871/145136650-7d03207d-bf9a-4071-9497-ef99c1b6bb04.png">

https://discord.com/channels/686053708261228577/908079085257908234/915907263993102348

**Comment by kepano** [comment]
In the meantime Minimal 4.1.9 brings updates Dataview in Live Preview mode to match the normal Preview mode.

**Comment by kepano** [comment]
This is now supported as of Obsidian 0.13.20
