### ISSUE TITLE
Easier checkbox style changing

### ISSUE THREAD

**Issue by narotuwi** [kepano/obsidian-minimal#724]
It is annoying when I want to change the checkbox type to one that is not empty or done and so I have to turn off reading view, and then edit the text to change it to something else. 

I would like to be able to change the checkbox type using something like a context menu or by hovering over the checkbox and instead of left clicking on it, I could enter the corresponding character for that checkbox type.

**Comment by kepano** [comment]
This is unrelated to what themes can do. Take a look at plugins that can help with this.
