### ISSUE TITLE
Image zoom on click without hold

### ISSUE THREAD

**Issue by p33k** [kepano/obsidian-minimal#728]
**Is your feature request related to a problem? Please describe.**
I like the possibility to click + hold on an image to zoom it. this is much better than in the stock theme.
however for my planned workflow I want the image to stay zoomed without holding the mouse.
so another mode (or short cut) for a zoom toggle would be awesome) 

**Describe the solution you'd like**
1. Click --> image zoom
2. Click --> image zoom closes

**Comment by kepano** [comment]
That's not possible for themes

**Comment by p33k** [comment]
if someone else wants this, the plugin obsidian-image-toolkit does exactly that (with "Disable image zoom" in Style Settings when using minimal theme): https://github.com/sissilab/obsidian-image-toolkit
