### ISSUE TITLE
Toggles for heading/list folding are not in their proper place in live preview mode

### ISSUE THREAD

**Issue by ernest67** [kepano/obsidian-minimal#73]
![Screenshot 2021-12-11 at 09 36 59](https://user-images.githubusercontent.com/95947701/145659359-4b7ec86b-e1e7-40bd-973f-b049c1c06086.png)

Environment:
Operating System: macOS 12.0.1
Obsidian Version: v.0.13.8

Issue:
As shown in the screenshot, the toggles for heading/list folding are not in their proper place in the **live preview mode**, I have tried using other themes but seems like this problem only happens in the minimal theme.

It would be awesome if you could look into this!

**Comment by kepano** [comment]
Can you provide the code for the first element?

**Comment by kepano** [comment]
Take a look at this thread on Discord, as I believe this is related to Obsidian itself https://discord.com/channels/686053708261228577/908079085257908234/918877297510072361

**Comment by bwydoogh** [comment]
> Take a look at this thread on Discord, as I believe this is related to Obsidian itself https://discord.com/channels/686053708261228577/908079085257908234/918877297510072361

I am not sure.

See attached screenshots: default theme (first; alignment is perfect) and Minimal (second). I am having the issue only when using Minimal; default theme (or Yin / Yang, Things, ...) does not have this issue in Live Preview.

![image](https://user-images.githubusercontent.com/1235571/145677344-701ee5cc-6e79-41cd-9379-59d3a26a2fdf.png)
![image](https://user-images.githubusercontent.com/1235571/145677347-addf232d-498a-4f93-9278-c64b9974a64d.png)

**Comment by bwydoogh** [comment]
Seems to happen in notes with code blocks (dataview, tasks, ...)

**Comment by ernest67** [comment]
The code for the first element is as follows:

```ad-key
title: Immediate Aftermath
collapse:none
C saw her family in the hospital within _an hour_ of their injuries occurring was considered *within* the **"immediate aftermath"** of the accident in the [[Alcock v Chief Constable of the South Yorkshire Police|Alcock]] control mechanisms
```

Once again really appreciate your help and taking your time to respond to our comments/requests!

Have a good day!

**Comment by kepano** [comment]
I believe this is now fixed. Please reopen if you're still noticing with the latest release (4.2.8)
