### ISSUE TITLE
Hamburger menu for right side panel not shown when in Focus mode

### ISSUE THREAD

**Issue by rafaelliu** [kepano/obsidian-minimal#738]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.5.4

### Describe the bug

Enabling Focus mode on the companion Plugin seems to break styling for the right side panel's hamburger icon. No icon is shown, but the space for it is kept and clicking on it actually works. Issue is not present when disabling Focus mode.

### Debug info

SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.5.3
	Operating system: Darwin Kernel Version 23.3.0: Wed Dec 20 21:33:31 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8112 23.3.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: off
	Base theme: dark
	Community theme: Minimal v7.5.4
	Snippets enabled: 3
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Minimal Theme Settings v7.5.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by rafaelliu** [comment]
<img width="879" alt="Screenshot 2024-05-28 at 3 56 12 PM" src="https://github.com/kepano/obsidian-minimal/assets/236667/ea41badb-70da-43f3-b0cf-95189adc23ef">

**Comment by kepano** [comment]
This should be fixed in 7.6.9
