### ISSUE TITLE
How to cancel indentation in bullet lists cards?

### ISSUE THREAD

**Issue by OB0NE** [kepano/obsidian-minimal#741]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.6.9

### Describe the bug

**Is your feature request related to a problem? Please describe.**
Is there any way to cancel the indentation in list-cards?
![TEM0085_0688](https://github.com/kepano/obsidian-minimal/assets/144986313/b43b4b9a-c72c-4ada-b1b3-78e1d74c65a5)
I want to achieve what the [demo](https://minimal.guide/cards#Turn+bullet+lists+into+cards) is like:
![image](https://github.com/kepano/obsidian-minimal/assets/144986313/cb9d67ac-e625-4f03-a3e5-95cffa49f6eb)
I have tried to adjust the "Nested list indentation" in _Style Settings_, It can reduce the indentation but can't be set to 0.
![image](https://github.com/kepano/obsidian-minimal/assets/144986313/d2db1466-7b0c-4fe7-b653-6d5352139971)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.6.2
	Installer version: v1.5.3
	Operating system: Windows 10 Enterprise 10.0.22631
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: on
	Live preview: on
	Base theme: adapt to system
	Community theme: Minimal v7.6.9
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Style Settings v1.0.8

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Fixed in 7.6.10
