### ISSUE TITLE
The Filter "circle" in Image filters doesn't work

### ISSUE THREAD

**Issue by OB0NE** [kepano/obsidian-minimal#742]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.6.9

### Describe the bug

The Filter "circle" in [Image filters](https://minimal.guide/images#Image+filters) doesn't work:
![image](https://github.com/kepano/obsidian-minimal/assets/144986313/cfce9b61-8207-4ffe-a2b1-e7d32ee5d095)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.6.2
	Installer version: v1.5.3
	Operating system: Windows 10 Enterprise 10.0.22631
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: on
	Live preview: on
	Base theme: adapt to system
	Community theme: Minimal v7.6.9
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Style Settings v1.0.8

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Fixed in 7.6.12
