### ISSUE TITLE
Font Weight of Internal Links in 1.6.3

### ISSUE THREAD

**Issue by BaughBerry** [kepano/obsidian-minimal#743]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.6.10

### Describe the bug

The font weight of internal links has increased since updating Obsidian to 1.6.3 and Minimal Theme to 7.6.10. Internal links now look bolded instead of like regular text. 

### Debug info

SYSTEM INFO:
	Obsidian version: v1.6.2
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 23.5.0: Wed May  1 20:14:59 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8122 23.5.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: light
	Community theme: Minimal v7.6.10
	Snippets enabled: 17
	Restricted mode: off
	Plugins installed: 15
	Plugins enabled: 13
		1: Folder Note Core v1.3.5
		2: AidenLx's Folder Note v0.16.5
		3: Book Search v0.7.3
		4: Dataview v0.5.66
		5: Minimal Theme Settings v7.5.0
		6: Style Settings v1.0.8
		7: Supercharged Links v0.12.1
		8: Various Complements v10.0.0
		9: Callout Manager v1.1.0
		10: Iconize v2.12.0
		11: Slurp v0.1.11
		12: Bible Linker v1.5.4
		13: QuickAdd v1.9.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
This sounds related to your snippets or Style Settings preferences.

**Comment by BaughBerry** [comment]
I tried turning off all my snippets, and there's no setting in Style Settings for internal link font weight. I turned off Style Settings and there was no change. 

The issue goes away with the default theme.

I also made a snippet to adjust the font weight of internal links, but it only affects the links in dataview or callouts. 

I should also note, the font weight goes back to normal in reading mode and source mode, this is only for editing/live preview mode.

**Comment by BaughBerry** [comment]
Here's a screenshot showing the difference between a dataview link (below) and an in-line link (above)

<img width="245" alt="Screenshot 2024-06-07 at 1 13 13 PM" src="https://github.com/kepano/obsidian-minimal/assets/129925078/4fb1e6a0-fbef-4ac9-9fcb-d594fa38980f">

**Comment by kepano** [comment]
I am not able to reproduce. Try the latest version of Minimal to see if that helps. If not you'll need to use Developer Tools to see where the additional bold style is coming from.

**Comment by BaughBerry** [comment]
Using developer tools I was able to find this section;


element.style {
    --zoom-factor: 1;
    --accent-h: 140;
    --accent-s: 28%;
    --accent-l: 65%;
    --text-on-accent: var(--text-on-accent-inverted);
    --font-text-size: 17px;
}
<style>
body.theme-light.css-settings-manager {
    --h5-color: #C76359;
    --h3-color: #CE9839;
    --code-normal: #259AC0;
    --h2-color: #8DBF9E;
    --italic-color: #D4AF6C;
}
body.is-frameless.is-hidden-frameless {
    padding-top: 0 !important;
}
<style>
.theme-light.minimal-notion-light {
    --base-h: 39;
    --base-s: 18%;
    --base-d: 96%;
    --accent-h: 197;
    --accent-s: 71%;
    --accent-l: 52%;
    --bg2: #f7f6f4;
    --bg3: #e8e7e4;
    --ui1: #ededec;
    --ui2: #dbdbda;
    --ui3: #aaa9a5;
    --tx1: #37352f;
    --tx2: #72706c;
    --tx3: #aaa9a5;
    --hl1: rgba(131,201,229,0.3);
    --link-weight: 500;
}

And change link weight to 400 which resolved my issue.

However, the link weight resets every time I reload obsidian. Is there a way to permanently change the link weight to 400?

**Comment by kepano** [comment]
Oh, yes, that's part of the Sky theme. Has been since the start. Removing it in 7.7.0 to prevent confusion.
