### ISSUE TITLE
Title bar / breadcrumb trail hidden unless hovering in Obsidian 1.6.2

### ISSUE THREAD

**Issue by jmhammond** [kepano/obsidian-minimal#744]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.6.10

### Describe the bug

In the newly released Obsidian 1.6.2, the minimal theme seems to be hiding the titlebar / navigation breadcrumb unless we hover with the cursor.

Here's without a hover: 
<img width="981" alt="2024-06-07_16-27-30" src="https://github.com/kepano/obsidian-minimal/assets/84139/a12656d1-2fe5-474c-9e54-82d1be128c0b">

and here's hovering:
<img width="976" alt="2024-06-07_16-26-10" src="https://github.com/kepano/obsidian-minimal/assets/84139/4dd64a2f-7f4d-45d7-85f8-609a8e2617e7">

when enabling a default theme (going with Flexoki to match my minimal choice), notice the title is visible:
<img width="876" alt="2024-06-07_16-27-57" src="https://github.com/kepano/obsidian-minimal/assets/84139/82ac02d4-d156-4b6d-b2da-950873e3b866">

but when going back to minimal, it vanishing:
<img width="938" alt="2024-06-07_16-28-19" src="https://github.com/kepano/obsidian-minimal/assets/84139/37728624-9b6f-4e78-9348-36751a2b85b2">

and finally, this still applies with all plugins disabled (restricted mode).  I have no CSS snippets.
<img width="973" alt="2024-06-07_16-29-35" src="https://github.com/kepano/obsidian-minimal/assets/84139/bc110c2e-5281-4ad3-befb-b2e88950c619">

---

It also happens in the sandbox vault when the only thing I install is Minimal Theme. 

### Debug info

SYSTEM INFO:
	Obsidian version: v1.6.2
	Installer version: v1.6.2
	Operating system: Darwin Kernel Version 23.5.0: Wed May  1 20:19:05 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8112 23.5.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: light
	Community theme: Minimal v7.6.10
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 14
	Plugins enabled: 10
		1: Zoom v1.1.2
		2: Readwise Official v2.0.1
		3: Paste URL into selection v1.7.0
		4: Outliner v4.8.1
		5: Omnisearch v1.23.0
		6: Git v2.24.2
		7: Homepage v3.8.0
		8: Enhancing Export v1.10.5
		9: Hider v1.4.0
		10: Minimal Theme Settings v7.5.0  

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by jmhammond** [comment]
Here's the sandbox vault pictures -- this probably would have been sufficient for the report --

<img width="1015" alt="2024-06-07_16-39-38" src="https://github.com/kepano/obsidian-minimal/assets/84139/40c61038-1c6d-4af1-9204-85898226337c">

<img width="1013" alt="2024-06-07_16-39-25" src="https://github.com/kepano/obsidian-minimal/assets/84139/70723edf-2267-41f0-a1c5-2cd72355a896">

**Comment by kepano** [comment]
This is a feature. Minimal is minimal! You can change this in the Style Settings options.
