### ISSUE TITLE
Black text on active item

### ISSUE THREAD

**Issue by artofka** [kepano/obsidian-minimal#745]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.5.0

### Describe the bug

Bookmarks text in eink theme is black
<img width="1543" alt="image" src="https://github.com/kepano/obsidian-minimal/assets/28753260/5ac1384e-4437-44d4-8b68-d639cb7861ac">

Also in hotkeys
<img width="1536" alt="image" src="https://github.com/kepano/obsidian-minimal/assets/28753260/8119cd6c-ae08-470a-906d-6477da634aca">

And on some hovered buttons in settings
<img width="1541" alt="image" src="https://github.com/kepano/obsidian-minimal/assets/28753260/78a65501-5bfc-475c-b352-f2db50351384">

### Debug info

SYSTEM INFO:
	Obsidian version: v1.6.2
	Installer version: v1.5.12
	Operating system: Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64 23.5.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: Minimal v7.6.10
	Snippets enabled: 3
	Restricted mode: off
	Plugins installed: 13
	Plugins enabled: 1
		1: Minimal Theme Settings v7.5.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
I fixed the hotkey issue but was not able to reproduce the others

**Comment by kepano** [comment]
All of these should now be fixed in 7.7.2
