### ISSUE TITLE
Table is missing outside border

### ISSUE THREAD

**Issue by gtsiolis** [kepano/obsidian-minimal#747]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.6.11

### Describe the bug

Inserting a table adds a table without an outside border.

<img width="216" alt="Screenshot 2024-06-10 at 14 21 54" src="https://github.com/kepano/obsidian-minimal/assets/120486/5e0aba3a-fa8f-4097-a40b-dfba92dd2651">

### Debug info

SYSTEM INFO:
	Obsidian version: v1.6.2
	Installer version: v1.4.14
	Operating system: Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020 23.5.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: Minimal v7.6.11
	Snippets enabled: 0
	Restricted mode: on

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.

**Comment by kepano** [comment]
Minimal is minimal! If you want to control table style use classes or Style Settings
https://minimal.guide/tables

**Comment by gtsiolis** [comment]
Ah, I had a feeling this could be intentional. Thanks, @kepano. 😃
