### ISSUE TITLE
Can't get tables to adhere to cssClasses in Minimal 4.2

### ISSUE THREAD

**Issue by janpeeters70** [kepano/obsidian-minimal#75]
Hi Stephan, 
Thanks for your theme. It makes working in Obsidian a real pleasure.
I've installed 4.2 beta (after sending you some coffee). Images work brilliantly when I add the classes that you showcased in the video, but my tables stick to the normal width. Do you have an idea what could cause this behavior? 
I'm using the Advanced Tables plugin. I have the latest Style Settings and Contextual Typography installed. I also deactivated all plugins and my custom CSS snippets, but that didn't help either.

**Comment by kepano** [comment]
Oops! Yes I should have made it clearer in the docs that this only affects Dataview tables as of the current beta. The next beta will include standard tables too.

**Comment by janpeeters70** [comment]
That's great news. Thank you.
