### ISSUE TITLE
App ribbon overlapping with vault change menu

### ISSUE THREAD

**Issue by TheFermi0n** [kepano/obsidian-minimal#750]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.7.0

### Describe the bug

In the screen recording below, it is visible that with the `Ribbon style` set to `Bottom left hover (horizontal)` using Minimal's options in the Style settings plugin, it becomes impossible to access the vault change menu!

![](https://github.com/kepano/obsidian-minimal/assets/63984668/4c079698-42e7-463c-a05c-e5cdd6bb34da)

For the `Bottom left hover (vertical)`, it is still usable but overlaps.

![image](https://github.com/kepano/obsidian-minimal/assets/63984668/ea048b62-f8a2-45da-bc94-a2a1a76e20bb)

## SYSTEM INFO:
	- Obsidian version: v1.6.3
	- Installer version: v1.5.12
	- Operating system: Darwin Kernel Version 21.6.0: Wed Apr 24 06:02:02 PDT 2024; root:xnu-8020.240.18.708.4~1/RELEASE_X86_64 21.6.0
	- Login status: logged in
	- Catalyst license: none
	- Insider build toggle: off
	- Live preview: on
	- Base theme: adapt to system
	- Community theme: Minimal v7.7.0
	- Snippets enabled: 3
	- Restricted mode: off
	- Plugins installed: 60
	- Plugins enabled: 36
					1: Quick Latex v2.6.5
					2: Pandoc Reference List v2.0.25
					3: Templater v2.3.3
					4: Zotero Integration v3.1.8
					5: Latex Suite v1.9.3
					6: macOS Keyboard Navigation v1.1.2
					7: PDF Highlights v0.0.4
					8: Folder notes v1.7.22
					9: Settings Search v1.3.10
					10: Importer v1.6.2
					11: Linter v1.24.0
					12: Extended MathJax v0.4.1
					13: Better Command Palette v0.17.1
					14: Image Captions v1.1.0
					15: Link Converter v0.1.6
					16: Citations v0.4.5
					17: Better Word Count v0.10.1
					18: Recent Files v1.4.1
					19: Enhancing Export v1.10.5
					20: Grandfather v1.0.1
					21: Automatic Table Of Contents v1.4.0
					22: Copy Block Link v1.0.4
					23: Hover Editor v0.11.20
					24: Better footnote v1.0.1
					25: Tidy Footnotes v0.1.1
					26: Word Splitting for Japanese in Edit Mode v1.0.0
					27: Code Editor Shortcuts v1.14.0
					28: Dataview v0.5.66
					29: Periodic Notes v0.0.17
					30: Markdown Furigana v1.3.0
					31: Advanced Slides v1.20.0
					32: Touch Bar Macros v1.0.3
					33: Hider v1.4.0
					34: Footnote Shortcut v0.1.3
					35: Minimal Theme Settings v7.5.0
					36: Style Settings v1.0.8

**Comment by kepano** [comment]
Added a [new option in 7.7.1](https://github.com/kepano/obsidian-minimal/releases/tag/7.7.1) to expand ribbon.

There are many configurations you can choose from so not all will work perfectly together:

- you can also hide the vault profile with Hider
- you can also move the vault profile to the top in Sidebar options
