### ISSUE TITLE
scrolling a pdf slows, then stalls obsidian

### ISSUE THREAD

**Issue by notuntoward** [kepano/obsidian-minimal#751]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.7.1

### Describe the bug

Scrolling pdfs using the default pdf reader is much slower when I'm using Minimal theme, in fact, when I drag the attached pdf into a new note, and scroll within it, scrolling stops completely for a second or so.   Eventually, obsidian itself stalls, and can't open a new tab, etc.   This seems specific to Minimal -- there are no scrolling problems with the default theme or e.g. Gitsidian.  This is in a sandbox, with no plugins installed.
 
[Sadana24contextualOptSurvey.pdf](https://github.com/user-attachments/files/15809250/Sadana24contextualOptSurvey.pdf)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.6.3
	Installer version: v1.5.12
	Operating system: Windows 10 Home 10.0.22631
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 0
	Plugins enabled: 0

RECOMMENDATIONS:
	none

[Sadana24contextualOptSurvey.pdf](https://github.com/user-attachments/files/15809278/Sadana24contextualOptSurvey.pdf)

**Comment by kepano** [comment]
Try turning off blending — go to Style Settings → PDFs → Blend PDFs in light mode and set to OFF

**Comment by notuntoward** [comment]
Thanks, this helps, although there's still a long lag the first time I load that file -- less so on others.  When would I want Blend PDFs set to ON?

**Comment by kepano** [comment]
if you want the pages to blend I to the background color, e.g. on warm schemes like flexoki

**Comment by notuntoward** [comment]
Unfortunately, 

> Style Settings → PDFs → Blend PDFs in light mode == OFF

only worked for the example pdf I gave yesterday.  Today, a pdf (attached) froze obsidian almost immediately.  Yet pdf scrolling -- and the rest of obsidian -- is fine after I switch to the Nordic theme, which is too bad, because I like Minimal better.
[Li18HyperbandNovelBanditbased.pdf](https://github.com/user-attachments/files/15830426/Li18HyperbandNovelBanditbased.pdf)

**Comment by kepano** [comment]
What kind of device are you using? It sounds like it might be better for you to use a theme that is more optimized for performance than Minimal, such as the default theme or themes that mainly modify colors.

You may need to turn off other PDF features that are performance intensive e.g. invert PDFs in dark mode.

**Comment by notuntoward** [comment]
I'm using a Surface Laptop Studio, i7, 16G of RAM.  It's a fairly fast laptop, or at least it was a couple years ago.

I tried turning off invert PDFs in dark mode, but obsidian still froze on that pdf.  Thanks for the suggestion, though.
