### ISSUE TITLE
Text color used when creating new files/folders is white

### ISSUE THREAD

**Issue by jasonekratz** [kepano/obsidian-minimal#752]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.7.1

### Describe the bug

When selecting items in the sidebar (files/folders) the accent color for the text in any of the appearances seems to be white (whereas its black or something close for the default theme). When typing out the new file/folder name the text is also white and extremely hard to read. This can be adjusted easily enough with Style Settings and changing "text on accent" but seems like maybe it should be a darker color vs white. To me this is a bug because the white text on the light backgrounds in light mode is basically impossible to read.

### Debug info

none.

**Comment by jasonekratz** [comment]
Some screenshots of what I'm referring to. This is the MacOS appearance but as noted same thing happens with any of them.

<img width="305" alt="shot1" src="https://github.com/kepano/obsidian-minimal/assets/25267246/0fbaafc1-11c7-4c9c-86f6-beaafc420d32">

<img width="301" alt="shot2" src="https://github.com/kepano/obsidian-minimal/assets/25267246/9f77ee38-e563-42d4-a218-92e999386f24">

**Comment by ArthurZyy** [comment]
我也遇到这个问题了，目前的解决办法是：
关闭插件【Minimal Theme Settings】中的选项【Colorful active states】

**Comment by kepano** [comment]
Should be fixed in 7.7.2
