### ISSUE TITLE
Offset of List-type properties in Dataview tables

### ISSUE THREAD

**Issue by acronid** [kepano/obsidian-minimal#753]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

No

### Minimal theme version

7.7.2

### Describe the bug

Ever since Obsidian 1.6 update, there is a left-side offset for list-type properties in Dataview tables. There was no such offset before 1.6 when using Minimal Theme.
The screenshot below is from Sandbox Vault with only Dataview plugin and Minimal Theme installed, both at default settings.

![Obsidian_2024-06-16_15-52-23](https://github.com/kepano/obsidian-minimal/assets/31851007/8d8cd395-bdf7-408f-9f94-dea71b48b06e)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.6.3
	Installer version: v1.5.3
	Operating system: Windows 10 Pro 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: Minimal v7.7.2
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Dataview v0.5.66

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Fixed in 7.7.3
