### ISSUE TITLE
With Obsidian 1.6.4, Minimal requires second click to activate some Obsidian UI elements

### ISSUE THREAD

**Issue by claremacrae** [kepano/obsidian-minimal#755]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.7.3

### Describe the bug

Has something changed about the way that taps/clicks are detected on iPad in 1.6.4?

There seems to be a pattern again that when I tap on a pane that does not have focus, I have to tap a second time.
I seem to recall that used to happen a long time ago and then was fixed.

I narrowed it down to happening when Minimal is enabled.

**Example steps to reproduce:**

1. Have the file browser visible
2. Enable Appearance > Show tab title bar
3. Click on a filename in the explorer to load a file
4. Click in the title bar to toggle from Reading to Editing, or vice versa

- **Expected**:
    - mode changes
- **Actual**:
    - have to click a second time to change the mode

Copied from [discord](https://discord.com/channels/686053708261228577/817515900349448202/1253627738829492284).

### Debug info

```
SYSTEM INFO:
	Operating system: ios 15.6.1 (Apple iPad13,11)
	Obsidian version: 1.6.4 (146)
	API version: v1.6.4
	Login status: logged in
	Catalyst license: vip
	Live preview: off
	Base theme: light
	Community theme: Minimal v7.7.3
	Snippets enabled: 9
	Restricted mode: on

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
```

**Comment by kepano** [comment]
Can you try restarting Obsidian? I am not able to reproduce this.

**Comment by claremacrae** [comment]
Apologies for not replying sooner. I have been completely tied up with the Obsidian metadata issue.
