### ISSUE TITLE
Selecting multiple notes makes their titles invisible

### ISSUE THREAD

**Issue by animusastralis** [kepano/obsidian-minimal#757]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.7.3

### Describe the bug

There is yet another bug in gruvbox light & high contrast scheme.

Screenshot describes it best:

![Obsidian_mCB08hili9](https://github.com/kepano/obsidian-minimal/assets/11203702/7fee293b-0060-4968-99b8-cbcec1f7c656)

'Colorful active states' option doesn't affect this issue.

### Debug info

SYSTEM INFO:
	Obsidian version: v1.6.5
	Installer version: v1.5.12
	Operating system: Windows 10 Pro 10.0.22631
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: light
	Community theme: Minimal v7.7.3
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 11
	Plugins enabled: 1
		1: Minimal Theme Settings v8.0.2

**Comment by kepano** [comment]
Fixed in 7.7.4
