### ISSUE TITLE
[FR]: Add option to Turn off Minimal theme Tables

### ISSUE THREAD

**Issue by ianTevesAcc** [kepano/obsidian-minimal#759]
**OB Classis Tables are better than Minimal Tables - So I'd like to use that instead**
I just like the classic Obsidian tables so I'd like an option to turn off the minimal tables to be replaced with the classic OB theme tables.

**Add Toggle for minimal tables for minimal theme settings**
Thats it. A toggle that would turn off Minimal theme tables and be replaced with Ob classic theme tables.

Thank you ^^

**Comment by kepano** [comment]
https://minimal.guide/tables

**Comment by robinmanuelthiel** [comment]
> https://minimal.guide/tables

How does this explain how to disable Minimal Tables?
