### ISSUE TITLE
Image grid in Live Preview

### ISSUE THREAD

**Issue by DutchPete** [kepano/obsidian-minimal#76]
Image grid in Minimal 4.2.0 works great. The only thing is that it is not rendered in Live Preview, only in Reading/Preview mode, if I am not mistaken.

Will you add LP support?

**Comment by kepano** [comment]
Unfortunately this is not possible because of the way images are grouped in Live Preview. Image grids rely on consecutive image elements being grouped within one parent container, but that is not how they are treated in Live preview. To do so would require a change in Obsidian.

**Comment by DutchPete** [comment]
OK, that's a pity, but it is now clear why. Many thanks for the feedback. I'll close this issue.
