### ISSUE TITLE
Add option to always invert image

### ISSUE THREAD

**Issue by SiddharthManthan** [kepano/obsidian-minimal#760]
**Is your feature request related to a problem? Please describe.**
Currently, in order to invert image, you have to add #invert to all image links.

**Describe the solution you'd like**
- Add an option to make it default. Options to make #invertW would also be nice for those vaults where majority images are black.
- A way to exclude some images (by adding #exclude-invert ?)

**Comment by kepano** [comment]
I think this is better achieved as a snippet, you can adapt the code here:
https://github.com/kepano/obsidian-minimal/blob/master/src/scss/features/image-filters.scss
