### ISSUE TITLE
Scrolling doesn't work when I am trying to select long text in Live preview mode.

### ISSUE THREAD

**Issue by rwiteshbera** [kepano/obsidian-minimal#762]
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.7.5

### Describe the bug

When I try to select a long text in Obsidian, it does not scroll to complete the selection in Live Preview mode. However, it works fine in Source mode. I am using the default Obsidian theme.

	•	Device: MacOS Sonoma 14.5
	•	Obsidian Version: 1.6.5

### Debug info

SYSTEM INFO:
	Obsidian version: v1.6.5
	Installer version: v1.6.3
	Operating system: Darwin Kernel Version 23.5.0: Wed May  1 20:19:05 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8112 23.5.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: Things v2.1.20
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Clear Unused Images v1.1.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
If the issue is present in default theme it should be reported on Obsidian forums.
