### ISSUE TITLE
Button text sometimes not visible on e-ink

### ISSUE THREAD

**Issue by metametapod** [kepano/obsidian-minimal#764]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.5.4

### Describe the bug

When using the E-ink (beta) light mode color scheme and background contrast of either Default or High, some buttons appear blank with a border but no text. Using an Onyx Boox Palma. Looks similar to #664.

<img src="https://github.com/user-attachments/assets/1387cc42-e509-4b22-80b4-9c51cb6f0446" alt="Screenshot_20240711-164757" style="max-width: 100%;" width="412">

<img src="https://github.com/user-attachments/assets/a12a12b1-f02c-4f87-9795-70ae0eb9ebf2" alt="Screenshot_20240711-164840" style="max-width: 100%;" width="412">

### Debug info

SYSTEM INFO:
	Operating system: android 11 (ONYX Palma)
	Obsidian version: 1.5.12 (134)
	API version: v1.5.12
	Login status: logged in
	Catalyst license: none
	Live preview: on
	Base theme: adapt to system
	Community theme: Minimal v7.5.4
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 12
	Plugins enabled: 1
		1: Minimal Theme Settings v8.0.2

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Please try the latest version of Obsidian and Minimal

**Comment by metametapod** [comment]
Thank you, I tried with Obsidian 1.6.5 and the latest Minimal and I think that fixed it. Looks like I had Obsidian updates mistakenly excluded by Aurora Store.
