### ISSUE TITLE
Hotkey for different todo items

### ISSUE THREAD

**Issue by 0xRaduan** [kepano/obsidian-minimal#765]
**Is your feature request related to a problem? Please describe.**
I am looking to improve speed of creating different types of todos(see picture), however it's extremely tedious to type them out manually. I can create shortcuts other way, but would prefer there to be an obsidian-native way of doing that(either via `/` or some other mechanism)

<img width="264" alt="image" src="https://github.com/user-attachments/assets/eed31762-7611-4913-b36b-c0893a0a99d4">

**Describe the solution you'd like**
Introduce a command to quickly do that via keyboard(probably, with `/` command)

**Comment by kepano** [comment]
This is not something themes can control. You'll need to use/create a plugin for that.
