### ISSUE TITLE
Blockquote Alignment in reading mode

### ISSUE THREAD

**Issue by Wnb369** [kepano/obsidian-minimal#767]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.7.8

### Describe the bug

There is an alignment issue with RTL (Right-to-Left) blockquotes in Reading Mode. When writing a blockquote, the text aligns too closely to the blockquote border. In Editing Mode, the text is correctly spaced from the border, but in Reading Mode, it is not.This bug does not occur in the [Flexoki](https://github.com/kepano/flexoki) theme.

**Steps to Reproduce:**

1. Create a blockquote with RTL text, such as `> این یک متن است`
2. Switch between Editing and Reading Modes to observe the issue.

**Expected Behavior:**

The text in RTL blockquotes should maintain a consistent space from the blockquote border in both modes. 

**Actual Behavior:**

In Reading Mode, the text aligns too closely to the blockquote border, as shown in the attached screenshots.

**Screenshots:**

Correct spacing in Editing Mode:
![1](https://github.com/user-attachments/assets/8beeed9b-9aca-4557-8600-320edb4caf51)

Incorrect spacing in Reading Mode:
![2](https://github.com/user-attachments/assets/1b6ed801-7beb-4855-b201-fd8bbaaf0601)

thx.

### Debug info

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Windows 10 Pro 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: light
	Community theme: Minimal v7.7.8
	Snippets enabled: 0
	Restricted mode: on

**Comment by kepano** [comment]
Fixed in 7.7.9
