### ISSUE TITLE
Cards ignore table-max, table-100, or table-wide values

### ISSUE THREAD

**Issue by starb-ctrl** [kepano/obsidian-minimal#768]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.7.9

### Describe the bug

In the cssclasses property, no matter whether I put table-max, table-100, or table-wide, the width of the table still appears the same. However, other values, such as cards-cols-5, seem to register correctly. I have also tried changing the "card maximum width" setting with the Style Settings plugin, but it has no effect.
My cards used to display correctly until I updated Obsidian, the Minimal theme, and Style Settings and Minimal Theme Settings plugins. Everything is fully up to date to the most recent versions. The tables are generated using DataviewJS.

This is my YAML:
```
---
cssclasses:
  - cards
  - cards-cover
  - table-max
  - cards-cols-5
tags:
  - frontpage
---
```

![minimal cards](https://github.com/user-attachments/assets/0d9c523b-9d7c-462c-9c9b-4d03901dd65a)

### Debug info

```
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Windows 10 Enterprise 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Base theme: light
	Community theme: Minimal v7.7.9
	Snippets enabled: 3
	Restricted mode: off
	Plugins installed: 23
	Plugins enabled: 9
		1: Style Settings v1.0.8
		2: Dataview v0.5.67
		3: Minimal Theme Settings v8.0.2
		4: Better File Link v1.1.4
		5: Custom Attachment Location v0.0.9
		6: Iconize v2.14.3
		7: Neighbouring Files v1.0.6
		8: ReadItLater v0.4.0
		9: Simple Embeds v1.14.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by kepano** [comment]
1. Is your query using Dataview or DataviewJS?
2. Have you tried turning off snippets?

**Comment by starb-ctrl** [comment]
1. DataviewJS. Yes, I think it might be that issue! I had looked around to make sure my issue hadn't been mentioned before, but I was only searching for issues mentioning Cards, not realizing it had more to do with DataviewJS -- apologies, my mistake!
2. Yes.
