### ISSUE TITLE
The centre table with cssclass: table-max. 

### ISSUE THREAD

**Issue by HelloMugen** [kepano/obsidian-minimal#771]
**Is your feature request related to a problem? Please describe.**
I've been using cssclass: table-max. 
There is a problem that has troubled me for a long time. 
I want to know if I can center the table? Now it is on the left by default, which is very awkward in table-max situations with a small number of columns.
![image](https://github.com/user-attachments/assets/ee77fed3-fa37-4f5e-bac6-b86510a3fad4)

**Describe the solution you'd like**
maybe it can like this ?
![image](https://github.com/user-attachments/assets/1cfe1f2e-fe27-4c09-8c84-56482df93aff)

**Comment by kepano** [comment]
Added in 7.7.11
