### ISSUE TITLE
Right click for readable line length and line numbers not available when readable line length is on

### ISSUE THREAD

**Issue by oldjove** [kepano/obsidian-minimal#776]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.7.13

### Describe the bug

As of Obsidian 1.7 it should be possible to right click in the gutter of markdown files to toggle readable line length and line numbers. This works fine with Minimal installed if readable line length is turned off, but once it's on it seems impossible to "find" the gutter. I've tried this in the default them with all plugins on and the feature works fine. I've also tried this in the sandbox vault with Minimal installed and I have the same issue.

### Debug info

SYSTEM INFO:
	Obsidian version: v1.7.0
	Installer version: v1.6.7
	Operating system: Windows 10 Enterprise LTSC 2019 10.0.17763
	Login status: logged in
	Catalyst license: vip
	Insider build toggle: on
	Live preview: on
	Base theme: dark
	Community theme: Minimal v7.7.13
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 83
	Plugins enabled: 72
		1: Admonition v10.3.2
		2: Calendar v1.5.10
		3: Book Search v0.7.4
		4: Copy as HTML v1.1.3
		5: Copy Block Link v1.0.4
		6: Dataview v0.5.67
		7: Folder notes v1.7.26
		8: Fullscreen mode plugin v0.1.2
		9: Kanban v2.0.51
		10: Link Headers Directly v1.0.2
		11: List Callouts v1.2.7
		12: Meld Encrypt v2.3.7
		13: Minimal Theme Settings v8.0.2
		14: Natural Language Dates v0.6.2
		15: Jump-to-Date v1.0.16
		16: Pandoc Plugin v0.4.1
		17: Paste URL into selection v1.7.0
		18: Periodic Notes v0.0.17
		19: Plugin Update Tracker v1.5.2
		20: PodNotes v2.13.2
		21: Projects v1.17.4
		22: QuickAdd v1.11.0
		23: Recent Files v1.4.1
		24: Remember File State v1.1.2
		25: Smart Typography v1.0.18
		26: Sort & Permute lines v0.7.0
		27: Style Settings v1.0.8
		28: Tag Wrangler v0.6.1
		29: Tasks v7.7.0
		30: Text Format v3.1.0
		31: Zotero Integration v3.1.8
		32: Wikipedia v1.0.3
		33: Pandoc Reference List v2.0.25
		34: Multi Properties v1.1.2
		35: Advanced Tables v0.21.0
		36: Metadata Menu v0.8.7
		37: Better Export PDF v1.9.1
		38: Enhancing Export v1.10.7
		39: MSG Handler v0.0.6
		40: Omnivore v1.10.4
		41: Templater v2.4.1
		42: Raindrop Highlights v0.0.22
		43: PDF++ v0.40.8
		44: Go Up v1.1.2
		45: Typewriter Scroll v0.2.2
		46: Image to text OCR v1.0.2
		47: Media Extended v3.2.4
		48: Advanced Canvas v3.1.0
		49: Better Search Views v0.2.2
		50: Auto Template Trigger v1.2.2
		51: Workspaces Plus v0.3.3
		52: Editor full screen v2.1.0
		53: Slurp v0.1.12
		54: Click Clack v0.1.2
		55: Text Analysis v1.1.0
		56: BibTeX Manager v0.8.12
		57: Creases v0.7.0
		58: Footnote Shortcut v0.1.3
		59: Docxer v2.0.1
		60: The Queue v1.1.2
		61: Outliner v4.8.1
		62: Tasks Calendar Wrapper v0.3.1
		63: Semantic Canvas v1.1.3
		64: Plugins Annotations v1.4.0
		65: Search In Canvas v1.1.1
		66: Text Extractor v0.5.2
		67: Linter v1.25.0
		68: Index Notes v1.0.1
		69: Image Metadata v1.1.0
		70: Dashboard navigator v1.1.1
		71: Super Duper Audio Recorder v1.1.0
		72: Hover Editor v0.11.20

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Minimal doesn't have a gutter in the same way the default theme does because it is optimized for the concept of block widths: https://minimal.guide/features/block-width

Unfortunately I don't think there is a way to support both, so this is a "won't fix".

**Comment by oldjove** [comment]
Okay, fair enough. Thanks for the explanation.
