### ISSUE TITLE
This is a question about CSS styling

### ISSUE THREAD

**Issue by Novice-level** [kepano/obsidian-minimal#780]
(The current content is translated by software. Please excuse me if there is any impoliteness. ) 

I would like to ask the author about the issue of custom CSS styles. I can only think of asking here.

Currently, my custom CSS style file does not take effect in "the editing mode of the whiteboard card" and "right-click to open in a new window".

I have searched online and still haven't found relevant posts. However, I found that the effect of the minimal theme can work normally. But my code knowledge is close to zero and I can't understand the code content of the theme file, so I come to ask the author for advice. 

(Screenshots are for demonstration purposes and the minimal theme has not been enabled.) 
![image|200](https://github.com/user-attachments/assets/fdeff184-dbf8-4dbb-ae0a-71628dbfc38c)
![image|200](https://github.com/user-attachments/assets/26debe47-58d7-492b-90de-c7d471b92ff3)

**Comment by kepano** [comment]
Please use the appearance channels in Obsidian's official community
https://obsidian.md/community

**Comment by Novice-level** [comment]
> 请使用 Obsidian 官方社区中的出现频道 https://obsidian.md/community

OK. Thank you for your suggestion. I'll give it a try.
