### ISSUE TITLE
Checkmarks too dim in dark mode

### ISSUE THREAD

**Issue by silidev** [kepano/obsidian-minimal#785]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.7.18

### Describe the bug

SYSTEM INFO:
	Operating system: android 14 (samsung SM-S926B)
	Obsidian version: 1.6.7 (149)
	API version: v1.6.7
	Login status: not logged in
	Live preview: on
	Base theme: dark
	Community theme: Minimal v7.7.18
	Snippets enabled: 0
	Restricted mode: on

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.

### Debug info

In dark mode the checkboxes are so dim, they are hard to make out when the screen dims in dark environments. With pitch black background enabled in minimal theme settings it is even worse, interestingly.

This is not cosmetic, but makes you overlook checkboxes.

Checkboxes are also quite dim in vanilla Obsidian, but minimal theme often pushes it below visibility.

![Screenshot_20240904_212503_Obsidian](https://github.com/user-attachments/assets/b4d69399-bbc6-41a8-983f-6f5b17eb8763)
![Screenshot_20240904_214532_Obsidian](https://github.com/user-attachments/assets/719007de-b101-4c23-bb4f-c5312857086c)

**Comment by kepano** [comment]
The default is intentionally low contrast. Take a look at Style Settings and the built-in color schemes in Minimal Theme Settings if you want to customize UI colors.
