### ISSUE TITLE
Custom Characters/icons for Checkbox Representation

### ISSUE THREAD

**Issue by RedMoikle** [kepano/obsidian-minimal#787]
The current implementation of the theme provides alternative checkbox states beyond checked and unchecked. I would like to request the ability for users to define and customize these states according to their preferences.

Requested Feature:

Custom Character for Checkbox Representation: Allow users to specify a character or text string to be displayed within the checkbox format (e.g., - [@]) in Obsidian markdown files.

Custom Icon Support: Enable users to upload an image file, or specify an emoji or Unicode symbol, to be used as an icon associated with each custom checkbox state.

Dynamic Icon Display: Modify the theme to dynamically display the appropriate icon or character based on the defined custom states within ObsidianMD markdown files.

Use Case Example: For instance, a user might define - [@] as a custom checkbox state and choose the devil face emoji 😈 to represent it. When editing markdown files in ObsidianMD, checkboxes formatted as - [@] would display the 😈 emoji instead of the default checkboxes. This could be used to mark particularly challenging tasks.

This feature would enhance customization options within the "minimal theme," allowing users to tailor checkbox appearances to better fit their personal or workflow-specific needs.

**Comment by RedMoikle** [comment]
There have already been a couple of similar feature requests, however adding the ability for users to define their own would cover all cases, so users won't come asking for more inclusions

**Comment by kepano** [comment]
As mentioned in #526 I don't plan to add more options. I recommend using snippets for this.
