### ISSUE TITLE
Cannot hide property row lines on mobile

### ISSUE THREAD

**Issue by greetclammy** [kepano/obsidian-minimal#799]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.7.18

### Describe the bug

I want to hide them to make it look consistent between desktop & mobile. Unfortunately, the toggle has no effect on mobile.
<br>

<img src="https://github.com/user-attachments/assets/10770fda-1515-4b02-9ecb-29fba5236924" width="250">
<img src="https://github.com/user-attachments/assets/8526475b-da01-4b99-99ae-1fd3f763087c" width="250">

### Debug info

SYSTEM INFO:
	Operating system: ios 18.1 (Apple iPhone14,5)
	Obsidian version: 1.7.4 (167)
	API version: v1.7.4
	Login status: not logged in
	Language: en
	Live preview: on
	Base theme: adapt to system
	Community theme: Minimal v7.7.18
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 37
	Plugins enabled: 2
		1: Minimal Theme Settings v8.1.1
		2: Style Settings v1.0.9

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Enable the toggle via Style Settings

**Comment by greetclammy** [comment]
Whether the toggle is ON or OFF, the property lines stay visible on mobile. The setting works correctly on desktop.

**Comment by greetclammy** [comment]
To hide property row lines as of v1.9.9:

```css
body.is-mobile .metadata-container {
    --metadata-divider-width: 0;
}
```

From [Discord](https://discord.com/channels/686053708261228577/702656734631821413/1406425966162608268).
