### ISSUE TITLE
Find field overlaps content in v4.2.1

### ISSUE THREAD

**Issue by quinncomendant** [kepano/obsidian-minimal#80]
When I invoke the find function (⌘F) it appears lower on the screen than usual, overlapping with the page content. This only happens in edit mode, not preview mode.

macOS 12.1
Obsidian v0.13.14
Minimal Theme v4.2.1 
Minimal Theme Settings v4.2.0.

Here's a screencast of the problem:

![Screen Recording 2021-12-23 at 14 00 43](https://user-images.githubusercontent.com/6884276/147295068-132a4a30-ad4d-493e-8bce-c07b90cd9475.gif)

BTW, I love the new focus mode. Nice!

**Comment by kepano** [comment]
I have noticed this too, it seems to be related to a change in a recent version of Obsidian. Shouldn't be too hard to fix.

**Comment by kepano** [comment]
Please try updating to the latest version. I believe this is fixed now!

**Comment by quinncomendant** [comment]
I'm already using the latest version of everything.

**Comment by kepano** [comment]
I just pushed an update, it doesn't have a new version number but if you click Update in Obsidian it should be fixed!

**Comment by quinncomendant** [comment]
Yep! It's fixed!
