### ISSUE TITLE
Incorrect Rendering In Latex/Mathjax

### ISSUE THREAD

**Issue by LynetteCullens** [kepano/obsidian-minimal#800]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.7.18

### Describe the bug

`##### $\mu$` renders incorrectly on PC and does not render at all on iOS.
Only happens from level 5 onward.
### Desktop: Example Using `##### $\left(\mu \Phi\right)$`
![image](https://github.com/user-attachments/assets/3cc3d2c5-fb1c-4d48-a02f-cb09e02de291)
![image](https://github.com/user-attachments/assets/0a92210f-e3c8-4a90-90bd-fac93f6ac69c)

### iPad: Example
![IMG_0019](https://github.com/user-attachments/assets/c726ba6b-75e2-45dc-90d6-09c35e44ea27)

### Debug info

```
SYSTEM INFO:
	Obsidian version: v1.7.4
	Installer version: v1.5.3
	Operating system: Windows 10 Home 10.0.19045
	Login status: logged in
	Language: en
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: Minimal v7.7.18
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 0
	Plugins enabled: 0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
```

**Comment by kepano** [comment]
It likely depends on your font and style settings and whether small caps are supported. You can turn off small caps in the H5 settings in Style Settings.

**Comment by LynetteCullens** [comment]
> It likely depends on your font and style settings and whether small caps are supported. You can turn off small caps in the H5 settings in Style Settings.

That worked perfectly. Thank you. I forgot to say that.
