### ISSUE TITLE
Animation speed setting for stacked tabs

### ISSUE THREAD

**Issue by greetclammy** [kepano/obsidian-minimal#805]
**Is your feature request related to a problem? Please describe.**
The animation when switching between stacked tabs feels too slow, making quick tab switching feel sluggish. While there's an animation speed setting in "Minimal Advanced Settings", it doesn't affect the stacked tabs switching animation. There currently doesn't seem to be a way to adjust this specific animation speed or disable it.

**Describe the solution you'd like**
Add a setting to control the speed of stacked tabs animation, or at least a toggle to disable the animation entirely.

**Related requests**
- [Faster ways to cycle through tab stack and tabs, and search tabs - Feature requests - Obsidian Forum](https://forum.obsidian.md/t/faster-ways-to-cycle-through-tab-stack-and-tabs-and-search-tabs/44945?u=peeragetalkers)
- [Stack Tabs: Disable/reduce scroll animation - Feature requests - Obsidian Forum](https://forum.obsidian.md/t/stack-tabs-disable-reduce-scroll-animation/45105?u=peeragetalkers)

**Comment by kepano** [comment]
The animation is defined by the browser engine and can't be changed sadly
