### ISSUE TITLE
Add Hotkey Support for All Custom Checkbox Types

### ISSUE THREAD

**Issue by greetclammy** [kepano/obsidian-minimal#808]
**Is your feature request related to a problem? Please describe.**
Currently, there's no way to quickly toggle between the various [custom checkbox types](https://minimal.guide/checklists) using keyboard shortcuts. Having to manually type the syntax e.g. `- [*]`, `- [f]`, `- [p]` slows down note-taking and reduces the utility of these helpful checkbox variations.

**Describe the solution you'd like**
Add the ability to configure hotkeys for all custom checkbox types. This would allow to quickly cycle through or directly set any checkbox type using keyboard shortcuts, similar to how the default checkbox can be toggled with `Cmd/Ctrl+L`.

**Comment by greetclammy** [comment]
Related: #724

**Comment by kepano** [comment]
Themes cannot control hotkeys. This would need to be done via a plugin.

**Comment by kepano** [comment]
It seems like something that should be implemented more genetically since many themes use this feature of Obsidian
