### ISSUE TITLE
Image grid doesn't work with the standard markdown syntax

### ISSUE THREAD

**Issue by Rubecks** [kepano/obsidian-minimal#81]
The addition of image grids on 4.2 is great. But it isn't working when you embed the images using the `![description](link)` syntax, only with the wikilinks format. So you can't make galleries with remote images or if you use plugins that converts links to make notes comply with the standard markdown language.

**Comment by kepano** [comment]
Unfortunately this is limitation of how Obsidian treats remote images. You can chime into this feature request, to try and nudge Obsidian devs to make this change:

https://forum.obsidian.md/t/wrap-remote-images-in-span-element-like-local-wikilink-images/29172

**Comment by kepano** [comment]
Can you try out 4.2.2? I may have a fix.

**Comment by Rubecks** [comment]
Nice! It works for remote images just fine, but if you link a local one, it doesn't.

And there's a bug, if you preview the grid, switch to the edit mode, change something, and change back to the preview, the images behave in a pretty weird way. Sometimes gaps appear, their height grow too much... But if you change to another file and back, or open it on another tab, it gets back to normal. It doesn't happen when using wikilinks with local images.

**Comment by kepano** [comment]
> Nice! It works for remote images just fine, but if you link a local one, it doesn't.

Interesting. Now this is another different combination of issues. This will require at minimum a change to Contextual Typography.

> And there's a bug, if you preview the grid, switch to the edit mode, change something, and change back to the preview, the images behave in a pretty weird way. Sometimes gaps appear, their height grow too much... But if you change to another file and back, or open it on another tab, it gets back to normal. It doesn't happen when using only wikilinks with local images.

I have seen both of these bugs too, but I do not know how to fix them. With the gaps, I have no idea what is causing this issue. For the height issue, it might be a Chromium bug — what is happening is that a new height is being calculated for the row based on the latest image you added. I have not thought of a solution yet.

**Comment by kepano** [comment]
This should now be fixed if you update to Contextual Typography 2.2.4

You will also need to restart Obsidian for the changes to take effect.
