### ISSUE TITLE
Minimal Helper Classes for the Elements of the Page.

### ISSUE THREAD

**Issue by zak-admin** [kepano/obsidian-minimal#812]
**Is your feature request related to a problem? Please describe.**
I would like to use Minimal Helper Classes for the elements of the page, instead of the whole page. For that purpose I tried [custom classes plugin](https://github.com/LilaRest/obsidian-custom-classes). But it did not work as I expected.. It works for the classes which I defined, but is not working for minimal helper classes... What can be done to make it work as I want it to..

**Describe the solution you'd like**
A way to use the helper classes for the element not for the entire page....

Also Check: https://github.com/LilaRest/obsidian-custom-classes/issues/21

**Comment by kepano** [comment]
Unfortunately this is not something themes can control.
