### ISSUE TITLE
Dataview full width for some queries despite settings (possibly related to "TASK")?

### ISSUE THREAD

**Issue by cansar** [kepano/obsidian-minimal#82]
I'm not sure why this might be happening, would welcome any suggestions on what to look for to provide better debugging information. I actually turned off all snippets and Minimal Theme Settings and Style Settings. I used TABLE on one page and it worked great (no other content) and did TASK on the same one and it breaks.
<img width="1749" alt="image" src="https://user-images.githubusercontent.com/92989/147314604-76457ee0-30ac-4d95-9c8b-8b107f90c824.png">

The query is:
```
TASK where !completed
```

**Comment by kepano** [comment]
Just released 4.2.3 that should fix this issue. Let me know if this works for you!

**Comment by cansar** [comment]
Wonderful, thank you! Fixed now.

I'm also seeing some issues with img-100 (and the setting) not working but I'll look into that tomorrow.

I really love this new feature.
