### ISSUE TITLE
100% pane width Images not working?

### ISSUE THREAD

**Issue by cansar** [kepano/obsidian-minimal#83]
I can't get 100% pane Width to work via either CSS or settings. I've tried setting it in both Minimal Theme Settings and Style Settings. I've also turned off each of those plugins to see if that helps.

This seems like a basic issue so maybe I'm doing something wrong? Dataview tables work great now. The screenshot here is in Live Preview but it looks the same in Reader mode.

<img width="2047" alt="image" src="https://user-images.githubusercontent.com/92989/147365178-9128e557-d7df-4ac2-b1b6-8d6164f54cf8.png">

**Comment by kepano** [comment]
I am not sure what I am looking at in the screenshot. Can you show what it looks like rendered?

Are you using the latest version of Contextual Typography?

Note that new layout features do not support Live Preview

**Comment by cansar** [comment]
I was using the global settings and updated plugins. However in the middle of creating a clearer example it started working all of a sudden (without any discernible change to the note). But most other notes still don't work. I haven't been able to figure out why unfortunately, I'm going to play around with this some more in real world usage and see what happens...

**Comment by kepano** [comment]
I have not seen the behavior you are describing... Other possibilities that I can think of:

- Interference from a snippet or plugin
- If you try to run both Minimal Settings and Style Settings at the same time you can run into conflicts

Also, you may want to quit and reopen Obsidian, sometimes that is needed to fully reset your plugins.

**Comment by cansar** [comment]
I just created a new vault with no plugins and all default settings except for Minimal as the theme, Light mode, and Source mode as the editor. I think the issue might be related to web links? Here is a minimal case that triggers it for me consistently:

<img width="2044" alt="image" src="https://user-images.githubusercontent.com/92989/147592876-99d14ea9-8f30-4406-8adb-63f3e8b14b25.png">

```
---
cssClasses: img-100
---

![](https://media.cntraveler.com/photos/59d3a805ddaded4e04772233/16:9/w_1280,c_limit/Rome_GettyImages-841851056.jpg)
```

I hope this helps/makes more sense!

**Comment by kepano** [comment]
Ah I see. Yes there is an open issue for this, see #81 

This is due to a limitation of the Contextual Typography plugin, seen here:
https://github.com/mgmeyers/obsidian-contextual-typography/issues/7

**Comment by kepano** [comment]
Note that remote images in Markdown format should now be working as of Minimal 4.2.2 — however for local images you need to use the Wikilinks syntax

**Comment by cansar** [comment]
This was very helpful context but the problem actually ended up being something else. Apparently there has to be a blank line between text and the image for it to work. I couldn't find anything about this being part of the spec and I'm not sure if it's an issue with Obsidian but I'll look into it some more later today. Here's a screenshot that illustrates it:

<img width="1993" alt="image" src="https://user-images.githubusercontent.com/92989/147595326-dd4bde07-f2b7-4cfc-96e1-6b168d0a659c.png">
