### ISSUE TITLE
The cursor does not appear on the left edge of the editor in Android 11.

### ISSUE THREAD

**Issue by farux** [kepano/obsidian-minimal#85]
The cursor does not appear on the left edge of the editor.
After applying the following snippet, the cursor is now displayed correctly.

`.is-mobile .ͼ1 .cm-line {
  padding:0 0 0 1px !important;
  }`

Xiaomi Redmi note 9s Miui12.5.1(Android11) Minimal Theme + Minimal Theme Settings Plugin

**Comment by kepano** [comment]
I was not able to reproduce this, but made a change in 4.2.5 that might help

**Comment by farux** [comment]
It's working.
Thank you!
