### ISSUE TITLE
Completed checkbox items do not align with unchecked items

### ISSUE THREAD

**Issue by jdudleyie** [kepano/obsidian-minimal#86]
In the latest version of Minimal Theme (4.2.4) with the latest public or insiders Obsidian build (latter is v0.13.16) the checked checkboxes do not align with unchecked ones.

![image](https://user-images.githubusercontent.com/3493601/147417884-7e30776c-66f4-4665-8da6-c88c3dce2bce.png)

**Comment by kepano** [comment]
This should be fixed in 4.2.5 thanks!
