### ISSUE TITLE
Relationship line doesn't show in live preview mode

### ISSUE THREAD

**Issue by SerotoninNone** [kepano/obsidian-minimal#87]
Hi kepano,

I just upgraded to the v0.13.14 of Obsidian and I have Minimal Theme 4.2.0. I find the relationship line doesn't show in the live preview mode and I haven't found places in Minimal Theme Settings where I can change it as I can do with relationship lines in editor and preview mode.

Do I miss something or It's just how it is currently designed?

Look forward to your reply.

SerotoninNone

**Comment by kepano** [comment]
Can you try upgrading to the latest version? This was fixed in Minimal 4.2.4

**Comment by SerotoninNone** [comment]
Hi kepano,



I upgraded and the problem is fixed! Thank you!

However, I encounter a new issue with blockquote in live preview mode.

Personally, when I write reading notes of a book, I look for a way to visually separate what I think from my summarization of what the author said. And currently, I use a blockquote that has a grey background color and a bolder border to achieve this visual separation. So I made a small change to the Minimal.css like this ⬇️ (although I know nothing about css...)

<img width="365" alt="image" src="https://user-images.githubusercontent.com/96717314/147531237-7eb49c0c-3aaa-4e9c-8f27-3d84b837e33e.png">

It has been working well for me, but after I upgraded, I find it seems no longer working in live preview mode (though it does work in reading view). 

I am wondering if there is a way to fix this, because I always work in editor view and almost never change to reading view.

Look forward to your reply.


SerotoninNone

**Comment by SerotoninNone** [comment]
Hi, kepano,



I think I figured it out! I changed this part of the MInimal.css ⬇️ 

<img width="592" alt="image" src="https://user-images.githubusercontent.com/96717314/147721554-14eb9175-34b6-4ca8-9f46-4f830c673cf6.png">

And I just want to say I really enjoy this theme and thank you so much for your work!



Best,

SerotoninNone
