### ISSUE TITLE
Image grid: how to get just that feature?

### ISSUE THREAD

**Issue by Nithilher** [kepano/obsidian-minimal#89]
I have a heavily customized personal theme for obsidian. However, I would like to use the image grid feature of your theme. However, just extracting the bit of css code from the section "Image Grid" in your obsidian.css does not seem to suffice. Is there an easy way to get it working with one's own theme?

**Comment by kepano** [comment]
See the forum thread on this topic
https://forum.obsidian.md/t/display-side-by-side-image-grid/9359/58

Contextual Typography plugin is necessary for the code to work though.

**Comment by Nithilher** [comment]
Strange, whatever I do, the images are always in one column beneath each other:

![[img1.png]] ![[img2.png]]

or

![[img1.png]]
![[img2.png]]

or

![[img1.png]]

![[img2.png]]

(with a blank line in between)
all yield the same result in preview mode. The first variant does show them side by side in editor mode, though. Contextual Typography plugin is loaded and enabled.
