### ISSUE TITLE
FR: Honor "Readable line length" option

### ISSUE THREAD

**Issue by eddyg** [kepano/obsidian-minimal#9]
I just found your theme and installed it today. So far, I like many things about it, so thank you!

One thing I've noticed is that the **Readable line length** option (in the **Editor** settings) always seems to be enabled. Regardless of how wide I make the window, it only uses a small (centered) part of the window when I have your **Minimal** theme selected.

It would be terrific if your theme honored the **Readable line length** setting.

Thanks for considering this!

**Comment by kepano** [comment]
This is fixed as of 2.5.11

**Comment by eddyg** [comment]
Fix confirmed. Thanks for quick response! 👍

**Comment by eddyg** [comment]
Hmm, one thing I just noticed:

The title of the note is still left-justified to the **Readable line length** width, which looks odd:

<img width="888" alt="ScreenShot 2021-05-13-12 17 09@2x" src="https://user-images.githubusercontent.com/3235109/118154549-2f74d280-b3e5-11eb-866d-d3fe212f6817.png">

**Comment by kepano** [comment]
Unfortunately this is a limitation of how Obsidian CSS classes are scoped. I can't change the position of the title dynamically based on the Obsidian setting. 

However, if you download the Minimal Theme Settings plugin you can change the **Line width** setting to a large number like 100 and that should fix it.

**Comment by eddyg** [comment]
Ah, gotcha. Thanks for the explanation.

Sometimes I want to toggle **Readable line length** on, so I used the inspector to find the title class and just added this snippet to my "custom CSS":

```css
.view-header-title-container {
    margin: 0;
}
```

My CSS knowledge is basic, but this seems to left-justify the title, which looks decent enough with both **Readable line length** off or on.

Thanks again for the responsiveness! 🎉
