### ISSUE TITLE
Mobile Link Text Color

### ISSUE THREAD

**Issue by npazo** [kepano/obsidian-minimal#91]
I was trying to figure out why the link text on mobile (i.e. `[this text](url)`) was the accent color but on desktop it is  `faint`. It appears that `.mod-cm5` only applies to the desktop version and causes the style to not apply on mobile. I would have submitted a PR but I am not sure what the correct change is, I have confirmed that removing `.mod-cm5` styles both mobile and desktop but I don't know if there are other impacts there or not.

https://github.com/kepano/obsidian-minimal/blob/e0d1611aa45c959b40ce7175e2e28aa2909d8ebb/obsidian.css#L3115

**Comment by kepano** [comment]
Ok, I am removing that line for now. It's in the latest commit. Thanks!

**Comment by npazo** [comment]
Ah, I should have just opened the PR, I made it too confusing. I think you just wanted to remove the parent class `.mod-cm5` not the entire line. Now it doesn't work right on Desktop or Mobile

**Comment by kepano** [comment]
I see, try again!

**Comment by npazo** [comment]
👍
