### ISSUE TITLE
App ribbon in focus mode

### ISSUE THREAD

**Issue by mnvwvnm** [kepano/obsidian-minimal#93]
Hi.

Just to report a detail about how app ribbon hides in focus mode: when closing sidebar, app ribbon disappears immediately (including the background) before file explorer, creating a weird effect.

1. before new setting

https://user-images.githubusercontent.com/22862501/147795061-7db238c3-1e6a-46de-8970-d0ac2bdb6c5f.mov

2. with new setting

https://user-images.githubusercontent.com/22862501/147795082-6af30bba-a135-4669-849e-c6e56b649f26.mov

(Congratulations for new settings. They jump as Christmas gifts) :)

**Comment by kepano** [comment]
This is fixed in 4.3.1

**Comment by mnvwvnm** [comment]
Great. Thank you.
