### ISSUE TITLE
possible to add folder icons to the file explorer view?

### ISSUE THREAD

**Issue by zeltak** [kepano/obsidian-minimal#96]
hi all and thx for the fantastic work on this great theme!

one thing that is really missing for me is folder icons in file explorer view. its hard for me to distinguish between folder and files that way (...im getting old i know.. :))

the excellent `California coast`

![image](https://user-images.githubusercontent.com/498410/147871486-15296c86-aa28-4733-bbc2-8911f730d725.png)

has excellent icons for folders and files.

Is that possible with the `minimal` theme? any suggestions highly appreciated!

best

Z

**Comment by kepano** [comment]
I don't have any plans to add this, but you may be able to create a snippet from the bits you like in California Coast!

**Comment by zeltak** [comment]
thx alot!

since i have zero coding skills, any tips or guides you can refer me on how to do so?

best

Z
