### ISSUE TITLE
Embedded Note Title not aligned in Reading View

### ISSUE THREAD

**Issue by oliverga** [kepano/obsidian-minimal#97]
Maybe more of an issue of the [Embedded Note Titles]( https://github.com/mgmeyers/obsidian-embedded-note-titles) plugin, but it only happens when using the Obsidian Minimal theme. The embedded title seems to be aligned to the left side of the window, not the to text. It is aligned properly in the editing view.

![Skærmbillede 2022-01-02 122034](https://user-images.githubusercontent.com/7099699/147874133-74069288-8b37-459b-b830-0ea414da902d.jpg)

**Comment by kepano** [comment]
I am not able to reproduce this. Which version of Obsidian, Minimal Theme and Embedded Note Titles are you using?

Do you have any other active snippets or plugins?

**Comment by OliverGA** [comment]
Minimal Theme v4.3.4, Embedded Note Titles v1.2.3.

It seems it has to do with [mgmeyer's](https://github.com/mgmeyers) other plugin [Contextual Typography](https://github.com/mgmeyers/obsidian-contextual-typography). If I unenable that and enable Embedded Note Titles, that seems to fix it. 

Using Contextual Typography v 2.2.4.

**Comment by kepano** [comment]
Thanks! Can you try Minimal 4.3.5 — I think this should be fixed now.

**Comment by oliverga** [comment]
It's fixed! Thank you, and thanks for the fantastic theme!
