### ISSUE TITLE
Incorrect PDF heading colors w/ dark theme

### ISSUE THREAD

**Issue by lilithium-hydride** [kepano/obsidian-minimal#98]
When exporting a PDF using the Minimal theme and Obsidian's dark mode, headings are styled with light colors, which does not occur after switching Obsidian to light mode. Normal text is styled correctly in both cases, though. See below, from a test document:

![image](https://user-images.githubusercontent.com/78992082/148008129-44e5d307-0883-4c4d-80c9-3cbbfa48d931.png)

![image](https://user-images.githubusercontent.com/78992082/148008176-3896d442-e239-466e-ae14-44cb075212a1.png)

Using `obsidian 0.13.14-1` and the latest .css from master (commit `bcfc6e6` as of writing).

**Comment by MavropaliasG** [comment]
Having the same problem, it also happens with italicized text

Obsidian 0.13.14 in Linux if that helps

**Comment by j-u-l-i-u-s** [comment]
+1 with the same issue, on MacOS. Would be great if this could be fixed. 

I tried to fix it via CSS snippets but didn’t manage. Can someone help me with a CSS quick fix please?

**Comment by kepano** [comment]
Unable to reproduce, please reopen if relevant
